### PR TITLE
[WIP] Fix `true_divide` with dtype argument (simple version)

### LINKED ISSUE #2059: Unexpected result in cupy.divide with dtype argument
Version: current master 202e4e8902e593b8c8ba487f8371e4b6a42e4660
```
>>> cupy.show_config()
CuPy Version          : 6.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9020
CUDA Driver Version   : 9020
CUDA Runtime Version  : 9020
cuDNN Build Version   : 7005
cuDNN Version         : 7005
NCCL Build Version    : 2104
NCCL Runtime Version  : (unknown)
```

#### Code
```py
import cupy
import numpy

a = cupy.array(500., dtype=numpy.float64)

c = cupy.divide(1., a)
print(c.dtype, c)

c = cupy.divide(1., a, dtype=numpy.float64)
print(c.dtype, c)
```
#### Result
```
float64 0.002
float64 -0.08333333333333333
```

### PR DESCRIPTION
**Pull request by okuta**
Fix #2059. rel #2076

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
@okuta Could you resolve conflicts?

**Comment by niboshi** [comment]
@asi1024 #2076 is being reviewed, instead of this one.

**Comment by niboshi** [comment]
@okuta As #2076 has been merged, can this PR be closed?

**Comment by okuta** [comment]
OK, Thanks!

**Pull request closed without merging**
