### PR TITLE
Fix integer `scatter_add` failure on Windows

### PR DESCRIPTION
**Pull request by asi1024**
https://ci.preferred.jp/cupy.experimental.win.cuda100/71661/

### CODE REVIEW

**Comment by asi1024** [comment]
Now I just added dtype combinations in scatter functions tests, but let me check that the tests fail here since I don't have a local Windows environment :bow:
Jenkins, test this please.

**Comment by asi1024** [comment]
Windows CI failed.
https://storage.googleapis.com/chainer-artifacts-pfn-public-ci/cupy-ci/71666/cupy_test_log.txt

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by leofang — APPROVED** [review]

**Comment by asi1024** [comment]
The CI failure is due to the difference of dtype behavior between Linux and Win32.
On Linux, `numpy.intc` is an alias of `numpy.int32`. However, on Win32, `numpy.dtype('i').type == numpy.intc` and it is not an alias of `numpy.int32`.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Now all tests have passed! PTAL!

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
