### PR TITLE
Warn non-tuple sequence for multidimensional indexing

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
TODO: Remove self-uses of `cupy_arr[list_idx]`.

Otherwise it causes regressions.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
> TODO: Remove self-uses of `cupy_arr[list_idx]`.

I'll push the commits here.  I was working on it in #4226.  There, the failing test is `tests.cupyx_tests.test_lapack.TestGels_param*` https://jenkins.preferred.jp/job/chainer/job/cupy_pr/2478/, which is irrelevant to non-tuple indexing.

**Comment by toslunar** [comment]
pushed 3c7837dde304589e999fda8c183558d2184ec4ed, be92edcfb1ed0b98488663dc0b7f20f574ebe602.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
