### PR TITLE
Add cuTENSOR to library download tool

### PR DESCRIPTION
**Pull request by leofang**
I am working on making cuTENSOR available on Conda-Forge (conda-forge/staged-recipes#13576), and I realized the same convenience can also be brought to here. Currently machine-readable links are only available on Linux variants (thanks to @kkraus14's help 👍).

### CODE REVIEW

**Comment by kkraus14** [comment]
> Currently machine-readable links are only available on Linux variants

Would you want Windows variants as well? I'm happy to push on the team for more uploads 😄

**Comment by leofang** [comment]
> > Currently machine-readable links are only available on Linux variants
> 
> Would you want Windows variants as well? I'm happy to push on the team for more uploads 😄

That would certainly be useful (at least we can offer it on Conda-Forge) 👍 Perhaps @kmaehashi can comment. (The team is working on improving Windows support.)

**Comment by kmaehashi** [comment]
Thanks @leofang, I didn't know these links are publicly accessible.
@kkraus14 Great, that would be really helpful!

**Comment by leofang** [comment]
> Thanks @leofang, I didn't know these links are publicly accessible.

Right, previously they were not made public (a login to Developer Program was required), but @kkraus14 did some magic 😁

**Comment by kkraus14** [comment]
@leofang Windows link: https://developer.download.nvidia.com/compute/cutensor/1.2.2/local_installers/libcutensor_1.2.2.exe

**Comment by kmaehashi** [comment]
Thank you! We can then use 7z command to extract the exe programmatically:

```
> 7z x libcutensor_1.2.2.exe
> tree /A /F libcutensor
...
C:\USERS\CHAINER\CUTENSOR\LIBCUTENSOR
\---libcutensor
    |   libcutensor.nvi
    |   license.pdf
    |
    +---include
    |   |   cutensor.h
    |   |
    |   \---cutensor
    |           types.h
    |
    \---lib
        +---10.1
        |       cutensor.dll
        |       cutensor.lib
        |       cutensor_static.lib
        |
        +---10.2
        |       cutensor.dll
        |       cutensor.lib
        |       cutensor_static.lib
        |
        \---11
                cutensor.dll
                cutensor.lib
                cutensor_static.lib
```

**Comment by leofang** [comment]
Thanks, @kkraus14!

> We can then use 7z command to extract the exe programmatically

@kmaehashi Do we want to add an extra dependency like `py7zr` for Windows, or would you prefer to bundle it in the wheel?

**Comment by kmaehashi** [comment]
`py7zr` cannot be used to extract EXE-formatted 7z file.

https://py7zr.readthedocs.io/en/latest/user_guide.html?highlight=sfx#user-guide
> py7zr does not support self-extracting archive, aka. SFX file, and only support plain 7z archive file.

and AFAIK there's no command-line option to just extract the files from EXE without installation. (c.f. [Extracting and Inspecting the Files Manually](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#install-cuda-software))
@kkraus14 Correct me if I'm wrong.

So, how about this? (I think it's ok to merge this PR without Windows support and do this later)

* If 7z command is unavailable, instruct users to install [7z command](https://www.7-zip.org/), OR manually run the cuTENSOR installer EXE
* Preload from any of `~/.cupy` or the default installation path of cuTENSOR installer (`C:\Program Files\NVIDIA cuTENSOR\v1.2\lib\11.0\cutensor.dll`) on Windows

**Comment by kkraus14** [comment]
I'm not familiar with the packaging format of the cuTensor Windows package so I'm not sure what will or won't work unfortunately.

**Comment by leofang** [comment]
I see, I wasn't aware of such limitations...

> So, how about this? (I think it's ok to merge this PR without Windows support and do this later)
> 
> * If 7z command is unavailable, instruct users to install [7z command](https://www.7-zip.org/), OR manually run the cuTENSOR installer EXE
> * Preload from any of `~/.cupy` or the default installation path of cuTENSOR installer (`C:\Program Files\NVIDIA cuTENSOR\v1.2\lib\11.0\cutensor.dll`) on Windows

Either way is fine for me, @kmaehashi, I have no preference on this. Let me know how you would like to proceed 🙂

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM, let's do the Windows support separately.

**Pull request merged**
