### PR TITLE
Added the implementation of method "alen"

### PR DESCRIPTION
**Pull request by ameyachawla99**
Hi , I am Ameya Chawla currently pursuing my B.Tech in Computer Science and Engineering .
I read about your organization in GSOC 2021 and looking forward to work with your organization .

Added the implementation of method "alen"
as mentioned in the comparison document
https://docs.cupy.dev/en/stable/reference/comparison.html

### CODE REVIEW

**Comment by leofang** [comment]
Unfortunately it's marked deprecated in NumPy and I doubt the core team would add it 😅 https://github.com/numpy/numpy/pull/14181 Maybe pick another function and give it a try? 🙂

**Comment by ameyachawla99** [comment]
@leofang 
Why i am also getting error in pretest flake 8 error Error: Process completed with exit code 1 ?

Please can you please guide me how to handle this error?

**Comment by leofang** [comment]
Formatting aside, the code you added would not work. Have you verified it locally?

Flake8 is a format checker that ensures the contributed code complies with PEP8 and our code style guides. If you scroll up the pretest output log, it gives you a set of reasons for which line the style is problematic.

Again, as I mentioned above I don't think `cupy.alen()` would be accepted due to its NumPy counterpart being deprecated. While it's still good for you to learn through this process, please do consider working on other missing functions.

**Comment by emcastillo** [comment]
Hi, thank you for your contribution!
unfortunately, as leofang noted above, `alen` is currently deprecated so we can't add it to CuPy right now.
I am sorry that I have to close this PR, but we will welcome another PR with a different non-deprecation function, and help you in the process.

**Comment by takagi** [comment]
If you are interested in participate in GSoC, the following is the general timeline:
https://summerofcode.withgoogle.com/how-it-works/

**Comment by takagi** [comment]
@ameyachawla99  If you are interested in participating in GSoC, the following is the general timeline:
https://summerofcode.withgoogle.com/how-it-works/

We can discuss your draft proposal so feel free to contact us about it!

**Pull request closed without merging**
