### PR TITLE
cupyx/signal: skip tests against older SciPy versions, adjust test tolerances

### PR DESCRIPTION
**Pull request by ev-br**
Older CUDA versions seem to have precision issues, had to make test tolerances *very* loose. So instead tighten tolerances, conditionally skip tests on older CUDA versions.

As suggested in https://github.com/cupy/cupy/pull/7591#issuecomment-1586561815

### CODE REVIEW

**Comment by takagi** [comment]
I found that some older SciPy returns different results from newer, so these failures may not be because of CUDA versions. For example, `TestIIRFilter::test_symmetry` passes with `atol=1e-5, rtol=1e-6` on `scipy==1.7`, but fails on `scipy==1.6`.

We test some combinations of CUDA versions and scipy (and other dependencies) versions as you can see in https://github.com/cupy/cupy/blob/main/.pfnci/coverage.rst. 
- cupy.linux.cuda113 -> scipy 1.6
- cupy.linux.cuda114 -> scipy 1.7
- cupy.linux.cuda115 -> scipy 1.8

**Comment by takagi** [comment]
Would you try requiring newer scipy as `@testing.numpy_cupy_allclose(scipy_name='scp>=1.8', ...)` instead of skipping older CUDA versions? Then, I run the full test again.

**Comment by ev-br** [comment]
Done!

**Comment by takagi** [comment]
Let me give it some fixes, and kick the full test again.

**Comment by takagi** [comment]
`pkg_resources` issue is to be resolved in #7653.

**Comment by takagi** [comment]
CI failures are not related to this PR.

**Comment by takagi** [comment]
Thanks, @ev-br! I slightly changed the title, and sorry for making your branch dirty.

**Comment by ev-br** [comment]
Thank you @takagi!

**Pull request merged**
