### PR TITLE
Add semicolons to the reduction kernel template

### PR DESCRIPTION
**Pull request by gwtnb**
Add semicolons to the reduction kernel template

### CODE REVIEW

**Comment by niboshi** [comment]
Just curious, but why do we need semicolons?

**Comment by gwtnb** [comment]
When opening a generated file, emacs fails to indent correctly without semicolons.

**Comment by niboshi** [comment]
I see, thanks

**Comment by gwtnb** [comment]
Of course, not only for emacs but for coding style.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
