### PR TITLE
20200316

### PR DESCRIPTION
**Pull request by Fokatu**
Sorry. Wrong operation

### CODE REVIEW

**Comment by leofang** [comment]
@Fokatu Just curious, you closed it because it didn't work (I'd be curious why), or you didn't have time to polish it?

**Comment by Fokatu** [comment]
@leofang,  it works for me. But I am not familiar with github, I don't know how to contribute. The above is a wrong operation.

**Comment by leofang** [comment]
Thanks @Fokatu! If you could paste your scripts here for how you confirmed it's working, I could find some time to take over. I think it's in good shape, just needs tests, docs, and perhaps small style fixes.

**Comment by Fokatu** [comment]
it is great if you could add it to the main repository.

here is a small example
`import cupy as cp

write_surf_str = r"""
extern "C"
{
    // Surface memory 
    __global__ void write_surf(cudaSurfaceObject_t surf, 
    	int width, int height)
    {
    	int w = blockIdx.x * blockDim.x + threadIdx.x;
    	int h = blockIdx.y * blockDim.y + threadIdx.y;
    
    	if (w < width && h < height)
    	{
    		float value = h * width + w;
    		surf2Dwrite(value, surf, w * 4, h);
    	}
    }
}
"""

def create_texture(width, height):
    format_desc = cp.cuda.texture.ChannelFormatDescriptor(32, 0, 0, 0,
                                                          cp.cuda.runtime.cudaChannelFormatKindFloat)  # always float32 format
    cudaArraySurfaceLoadStore = 2
    d_array = cp.cuda.texture.CUDAarray(format_desc, width, height, flags=cudaArraySurfaceLoadStore)
    data = cp.zeros((height,width), dtype=cp.float32)
    d_array.copy_from(data)

    res_desc = cp.cuda.texture.ResourceDescriptor(
        restype=cp.cuda.runtime.cudaResourceTypeArray,
        cuArr=d_array
    )

    surf_obj = cp.cuda.texture.SurfaceObject(res_desc)

    return surf_obj, d_array

write_surf = cp.RawKernel(write_surf_str, "write_surf")

width = 4
height = 4
img_surf, img_array = create_texture(width, height)

img_data = cp.zeros((4,4), dtype=cp.float32)
img_array.copy_from(img_data)


img_array.copy_to(img_data)
print("\nbefore write:\n", img_data)

grid_dim = (1, 1)
block_dim = (4, 4)
write_surf(grid_dim, block_dim, (img_surf, 4, 4))
img_array.copy_to(img_data)
print("\nafter write:\n", img_data)
`

the output is as follows:
`before write:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

after write:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]`

**Comment by leofang** [comment]
Thank you, @Fokatu! I can reproduce.

```python
import cupy as cp


write_surf_str = r"""
extern "C"
{
__global__ void write_surf(cudaSurfaceObject_t surf, int width, int height)
{
int w = blockIdx.x * blockDim.x + threadIdx.x;
int h = blockIdx.y * blockDim.y + threadIdx.y;

    if (w < width && h < height)
    {
        float value = h * width + w;
        surf2Dwrite(value, surf, w * 4, h);
    }
}
}
"""

def create_texture(width, height):
    format_desc = cp.cuda.texture.ChannelFormatDescriptor(32, 0, 0, 0,
        cp.cuda.runtime.cudaChannelFormatKindFloat) # always float32 format
    cudaArraySurfaceLoadStore = 2
    d_array = cp.cuda.texture.CUDAarray(format_desc, width, height, flags=cudaArraySurfaceLoadStore)
    data = cp.zeros((height,width), dtype=cp.float32)
    d_array.copy_from(data)

    res_desc = cp.cuda.texture.ResourceDescriptor(
        restype=cp.cuda.runtime.cudaResourceTypeArray,
        cuArr=d_array
    )

    surf_obj = cp.cuda.texture.SurfaceObject(res_desc)

    return surf_obj, d_array

write_surf = cp.RawKernel(write_surf_str, "write_surf")

width = 4
height = 4
img_surf, img_array = create_texture(width, height)

img_data = cp.zeros((4,4), dtype=cp.float32)
img_array.copy_from(img_data)

img_array.copy_to(img_data)
print("\nbefore write:\n", img_data)

grid_dim = (1, 1)
block_dim = (4, 4)
write_surf(grid_dim, block_dim, (img_surf, 4, 4))
img_array.copy_to(img_data)
print("\nafter write:\n", img_data)
```

**Pull request closed without merging**
