### PR TITLE
Support Python 3.11

### PR DESCRIPTION
**Pull request by takagi**
#7142

### CODE REVIEW

**Comment by kmaehashi** [comment]
Dependents:
* NumPy/SciPy already have py311 wheels on PyPI
* MPI4py: tracked in https://github.com/mpi4py/mpi4py/issues/273. Maybe use Python 3.10 for `multi` tests until this gets fixed?
* fastrlock: v0.8.1 supports Python 3.11. Let's wait for them to be uploaded on PyPI: https://github.com/scoder/fastrlock/releases/tag/v0.8.1

**Comment by leofang** [comment]
For mpi4py, if you run cythonize and build from source, it should work, see https://github.com/conda-forge/mpi4py-feedstock/pull/58/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR16.

For cuda-python, will ask internally.

**Comment by leofang** [comment]
> For mpi4py, if you run cythonize and build from source, it should work, see https://github.com/conda-forge/mpi4py-feedstock/pull/58/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR16.

btw mpi4py 3.1.4 was just released

**Review by kmaehashi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
Python 3.11 unittest has some DeprecationWarning. I'm going to fix the tests shortly.

**Comment by kmaehashi** [comment]
The skipped test (586861ecd0ee477cccf576773a5817311747751e) should be fixed in #7178, which is targeted for the December release.

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
