### PR TITLE
Remove custom tempdir context manager

### PR DESCRIPTION
**Pull request by niboshi**
Part of #2994

### CODE REVIEW

**Comment by leofang** [comment]
Thanks, @niboshi. Any chance you could also remove this part since PY3 has native support?
https://github.com/cupy/cupy/blob/27e64d24394f06df57d146443ec8a8311599bee3/cupy/cuda/compiler.py#L106-L117

**Comment by niboshi** [comment]
@leofang I didn't notice it. Thank you!

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
AppVeyor failed on `%CMD_IN_ENV% python setup.py build install -vvvv`.  Contrary to the traceback, the essential cause was that `build_and_run` in `install/build.py` raised
```
[WinError 145] The directory is not empty: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpbft8evjm'
```
, which didn't immediately stop the installation because it was downgraded to a warning by `check_cudnn_version`.

https://bugs.python.org/issue26660 may be relevant.

**Comment by niboshi** [comment]
PTAL

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
