### PR TITLE
ENH: add `cupyx.scipy.signal.minimum_phase`

### PR DESCRIPTION
**Pull request by ev-br**
cross-ref https://github.com/cupy/cupy/issues/7403

<s>This PR is on top of gh-7537 to minimize git conflicts  going forward.</s>

### CODE REVIEW

**Review by takagi — DISMISSED** [review]
LGTM!

**Comment by ev-br** [comment]
Rebased on main.

**Comment by takagi** [comment]
I'll kick the CI once #7653 is merged.

**Review by takagi — APPROVED** [review]
LGTM! The CI failures are not related to this. I filed #7665.

**Pull request merged**
