### PR TITLE
Rename submodules under `cupy.linalg` package

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR renames the submodules under `cupy.linalg` to indicate that they are CuPy's private submodules and not intended to be used by users.

### CODE REVIEW

**Comment by emcastillo** [comment]
Probably blocked by #3234?

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
