### PR TITLE
Reorganize import in device.pyx

### PR DESCRIPTION
**Pull request by okuta**
This PR is related to #2053 .

### CODE REVIEW

**Comment by hvy** [comment]
@kmaehashi could you take a look at this one as well?

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Comment by kmaehashi** [comment]
Will backport after #2053 has backported.

**Comment by kmaehashi** [comment]
This PR has been backported in #2121 along with backport for #2053.

**Pull request merged**
