### PR TITLE
Add `cupy.who`

### PR DESCRIPTION
**Pull request by emcastillo**
Take over #3224

Added test and minor fixes in the code.

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
Would you add `misc.rst` for the reference?

**Comment by emcastillo** [comment]
There was no misc.rst so I added it

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI pass.

**Comment by emcastillo** [comment]
We are in code freeze!

**Comment by takagi** [comment]
Oops, I removed the label.

**Comment by emcastillo** [comment]
I just fixed the doctest, can you rerun the CI please 😇

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
I didnt pushed it right, let me retrigger

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
```
15:47:31 Failed example:
15:47:31     cupy.who()
15:47:31 Expected:
15:47:31     Name            Shape            Bytes            Type
15:47:31     ===========================================================
15:47:31     <BLANKLINE>
15:47:31     a               10               80               int64
15:47:31     b               20               160              float64
15:47:31     <BLANKLINE>
15:47:31     Upper bound on total bytes  =       240
15:47:31 Got:
15:47:31     Name            Shape            Bytes            Type
15:47:31     ===========================================================
15:47:31     <BLANKLINE>
15:47:31     b               20               160              float64
15:47:31     a               10               80               int64
15:47:31     <BLANKLINE>
15:47:31     Upper bound on total bytes  =       240
```

Since the order is not deterministic, I think is better to remove the doctest ....

**Comment by emcastillo** [comment]
I have to change the code to make the print order deterministic.
probably some `sorted(dict.keys())` should be enough

**Comment by emcastillo** [comment]
Jenkins, test this please

(Sorted the keys to have deterministic output)

**Comment by takagi** [comment]
LGTM! I'll merge this after release.

**Pull request merged**
