### PR TITLE
Support `allow_pickle` in `cupy.load` and `cupy.save`

### LINKED ISSUE #2289: `TestNpz.test_dump` test failure
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/161/TEST=cupy-py3,label=mn1-p100/console

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #2289

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
When backporting, change the default behavior of `allow_pickle` to `True` in `cupy.load`.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
