### PR TITLE
Fix typecast from complex to bool in JIT

### PR DESCRIPTION
**Pull request by asi1024**
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/2972/TEST=cupy-py36,label=mn1-p100/testReport/junit/tests.cupy_tests.functional_tests.test_vectorize/TestVectorizeExprs/test_vectorize_typecast/

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
