### PR TITLE
Add `may_share_memory`

### PR DESCRIPTION
**Pull request by asi1024**
Part of #2407.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins test this please

**Comment by emcastillo** [comment]
[Jenkins test failed](https://jenkins.preferred.jp/job/chainer/job/cupy_pr/297/TEST=cupy-py35,label=mn1-p100/testReport/junit/tests.cupy_tests.misc_tests.test_memory_ranges/TestMayShareMemory/test_combination/) 😞

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
One jenkins issue on [`cupy-example`](https://jenkins.preferred.jp/job/chainer/job/cupy_pr/325/TEST=cupy-example,label=mn1-p100/console)
```
13:25:23   File "/home/user/.local/lib/python2.7/site-packages/cupy/__init__.py", line 609, in <module>
13:25:23     from cupy.misc import may_share_memory  # NOQA
13:25:23 ImportError: No module named misc
```

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
CI unrelated

**Pull request merged**
