### PR TITLE
Fix `polyfit` tests tolerance

### PR DESCRIPTION
**Pull request by emcastillo**
In the CuPy combination tests, when using Numpy 1.19.2 and CUDA 9.2 polyfit fails when weights are set to other than `None`. Because of a e-16 difference in one result.
```
actual     = array([3.21811551e+00, 8.02329466e-01, 2.14338135e-16])
atol       = 0
desired    = array([3.21811551, 0.80232947, 0.        ])
```
https://jenkins.preferred.jp/job/chainer/job/chainer-test_pr/220/

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
LGTM.

**Comment by asi1024** [comment]
`polyfit` is not supported in v8.

**Pull request merged**
