### PR TITLE
Add a lingering doc page for `fromDlpack()`

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of #5488. I noticed that both the docstrings of `cp.from_dlpack()` and `cp.ndarray.toDlpack()` have a mention of the old `cp.fromDlpack()`, so perhaps before its full removal we should still keep its docstring rendered (but not indexed)?

### CODE REVIEW

**Comment by leofang** [comment]
The rendered page is here: 
https://cupy--5509.org.readthedocs.build/en/5509/reference/generated/cupy.fromDlpack.html

**Comment by kmaehashi** [comment]
How about naming the file `_deprecated.rst` instead of `_dlpack.rst` so that we can use it in similar cases in future and also make the role of the file explicit?

**Comment by leofang** [comment]
Sounds good, done in d267241.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Merging as docs build are fine. Thanks!

**Pull request merged**
