### PR TITLE
ensure the input to the CUFFT Plan1D class is C contiguous

### LINKED ISSUE #1394: Document behavior of memory pools
Context: https://github.com/chainer/chainer/issues/4911

### LINKED ISSUE #1934: incorrect FFT results for Fortran-order arrays?
* Conditions (from `python -c 'import cupy; cupy.show_config()'`)

Tested in two environments with different CuPy versions:
```bash
CuPy Version          : 4.4.1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9010
CUDA Driver Version   : 9010
CUDA Runtime Version  : 9010
cuDNN Build Version   : 7102
cuDNN Version         : 7102
NCCL Build Version    : 2115
```
and (this CuPy is built from the latest master branch)
```
CuPy Version          : 6.0.0b1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9010
CUDA Driver Version   : 9010
CUDA Runtime Version  : 9010
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
```
* Code to reproduce
```python
import numpy as np
import cupy as cp

AXES=[(0,), (1,), (2,), (0,1), (1,2), (0,2), (0,1,2)]
a_np = np.random.random((3,4,5))+1j*np.random.random((3,4,5))

print("In C order:")
a_np = np.ascontiguousarray(a_np)
a_cp = cp.asarray(a_np)
a_cp = cp.ascontiguousarray(a_cp)
assert np.allclose(cp.asnumpy(a_cp), a_np)
for axes in AXES:
    result_np = np.fft.fftn(a_np, axes=axes)
    result_cp = cp.fft.fftn(a_cp, axes=axes)
    print(axes, ":", np.allclose(cp.asnumpy(result_cp), result_np))

print("\nIn F order:")
a_np = np.asfortranarray(a_np)
a_cp = cp.asarray(a_np)
a_cp = cp.asfortranarray(a_cp)
assert np.allclose(cp.asnumpy(a_cp), a_np)
for axes in AXES:
    result_np = np.fft.fftn(a_np, axes=axes)
    result_cp = cp.fft.fftn(a_cp, axes=axes)
    print(axes, ":", np.allclose(cp.asnumpy(result_cp), result_np))
```
* Error messages, stack traces, or logs

The outputs from both environments are identical:
```bash
In C order:
(0,) : True
(1,) : True
(2,) : True
(0, 1) : True
(1, 2) : True
(0, 2) : True
(0, 1, 2) : True

In F order:
(0,) : False
(1,) : True
(2,) : False
(0, 1) : True
(1, 2) : False
(0, 2) : False
(0, 1, 2) : True
```
But it's expected to be `True` for all of the axes choices. It seems to me the bug is not introduced by the recent changes in adding support for cuFFT plans (#1669, #1745, #1746) but by something much older. For now I have not yet tracked down the problem, will update here if I find it. I hope I didn't do something stupid in the test...

Thanks.

### PR DESCRIPTION
**Pull request by grlee77**
Plan1D requires C contiguous data, but `_exec_fft` did not always ensure this. Specifically if the array was F-contiguous and the last axis was transformed, no copy was made, leading to an incorrect output.

closes #1934

@leofang, can you run your test cases using this small patch and verify that this fixes it for you?

### CODE REVIEW

**Comment by leofang** [comment]
@grlee77 Are you referring to #1934? No, I still got the same output :( I even rebuilt a fresh cupy this afternoon...

**Comment by leofang** [comment]
@grlee77 I take my reply above back. I had a buggy NumPy build, and after updating my NumPy, I can confirm this patch works!

**Comment by asi1024** [comment]
Thank you for the PR. LGTM!

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure is irrelevant to this PR.

**Pull request merged**
