### PR TITLE
[WIP] An attempt on adding median for CuPy

### PR DESCRIPTION
**Pull request by andy6975**

### CODE REVIEW

**Comment by andy6975** [comment]
Kindly review it and let me know what changes are to be made. It's not complete yet but a try. Also, it's mainly inspired by the code of np.median

**Comment by grlee77** [comment]
Thanks for working on this @andy6975. It will be nice to have median support in CuPy!

To start with, I would move the file to `cupy/statistics` instead of `cupy/math`. I think `median` fits well alongside the existing `mean`, `std` and `var`.

I would then add a new file for tests under `tests/cupy_tests/statics_tests/test_median.py`  (apparently there is a spelling error in the "statistics_tests" folder name, but that can be addressed in a different PR).  It will probably be easiest to just adapt existing tests for a related method like the class `TestAverage` from the existing `test_meanvar.py` file.

I think once you have tests that pass for you locally we can go into finer details of the implementation. Also, note that unlike some other projects, the automated CI here only tests against automated code style rules. A core member of CuPy will trigger the full tests suite later on.

**Comment by andy6975** [comment]
Thanks @grlee77 for replying back. The code is not complete and may not pass all the tests. Like for example, it doesn't work for non-contigous arrays, yet. But I will work on it if given a green flag to continue working on this. Thanks!

**Comment by grlee77** [comment]
>  But I will work on it if given a green flag to continue working on this. Thanks!

It is not up to me, but I am pretty sure there is interest in adding this function to CuPy. As one example, I recently wanted to use it in a PR updating `cupy.pad` (the `median` case is disabled there at the moment).

**Comment by asi1024** [comment]
@andy6975 Is this PR ready to review?

**Comment by asi1024** [comment]
@andy6975 Can I close this PR?

**Pull request closed without merging**
