### PR TITLE
Use MSVC 14.0 with CUDA 11.2

### PR DESCRIPTION
**Pull request by emcastillo**
Should fix : https://github.com/cupy/cupy-release-tools/pull/66

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Comment by kmaehashi** [comment]
I'll merge after Windows test pass.

**Pull request merged**
