### PR TITLE
Monitor `*array_api*` by `flake8`/`autopep8`

### PR DESCRIPTION
**Pull request by EarlMilktea**
### Description of changes

- Remove blanket exclude rules
- Fix linter warnings

### CODE REVIEW

**Comment by leofang** [comment]
Hi Earl, sorry the communication was not ideal. We meant to nuke the `array_api` module anytime from now (https://github.com/cupy/cupy/issues/8470#issuecomment-2311516454). If if it were not the plan, this module was maintained by pushing patches from `numpy.array_api` so that we can retain (most of) the commit history and authorship. Applying any linter on this module would make the patching harder. In any case I would suggest to not touch this module.

**Comment by EarlMilktea** [comment]
@leofang I see. Then let me close this PR☺️

**Comment by EarlMilktea** [comment]
@leofang By the way, then how can I contribute to the code here (PR to numpy?)

**Comment by leofang** [comment]
As mentioned NumPy 2 removes the entire `numpy.array_api` module and points people to either `array_api_compat` or `array_api_strict` packages. If you have time to help it'd be great if you can do the same thing for CuPy and
1. remove `cupy.array_api`
2. remove all of its tests
3. update the docs

see the discussion in #8470 or ask any question you might have! 😉

**Pull request closed without merging**
