### PR TITLE
Add `__cupy_get_ndarray__` dunder method to transform objects to arrays'

### PR DESCRIPTION
**Pull request by emcastillo**
Alternative to #6413

in HIP `__cuda_array_interface__` is not well defined, so it causes some functionality that relies on it such as polynomial API to fail where it shouldn't because it is being used as a hack to transform a regular object into a cupy ndarray in a really convoluted way.
We add a method to transform objects into ndarrays explicitly, avoiding the obscurity of the previous approach.

This PR fixes

```
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArithmetic::test_poly1d_arithmetic[_param_8_{func=<lambda>, type_l='ndarray', type_r='poly1d'}]
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArithmetic::test_poly1d_arithmetic[_param_20_{func=<lambda>, type_l='ndarray', type_r='poly1d'}]
cupy_tests/lib_tests/test_polynomial.py::TestPoly1dPolynomialArithmetic::test_poly1d_arithmetic[_param_32_{func=<lambda>, type_l='ndarray', type_r='poly1d'}]
```

### CODE REVIEW

**Review by leofang — COMMENTED** [review]
I like it a lot more! Only nitpick: can we check `__dlpack__` before `__cuda_array_interface__`?

**Comment by kmaehashi** [comment]
This will allow things like `cupy.sum(torch_tensor)` and wondering this is against the DLPack design that requires users to explicitly use `from_dlpack`.

**Comment by emcastillo** [comment]
changed the pr to not use dlpack and add a cupy specific private protocol to achieve the same.

**Review by kmaehashi — APPROVED** [review]
LGTM!

**Pull request merged**
