### PR TITLE
Support compile-time constants in CuPy JIT

### PR DESCRIPTION
**Pull request by asi1024**
This PR supports compile-time constants in CuPy JIT. This enhancement simplifies generated code by evaluating some numerical expressions in transpile time and enables us to use Python objects of any type, even if it is a non-numerical object, in compile-time.

### CODE REVIEW

**Comment by emcastillo** [comment]
This is to evaluate numerical expresions in transpile time?
Cool!

**Comment by asi1024** [comment]
Yes, this enhancement can shrink the given code by evaluating numerical expressions in transpile time.

**Comment by asi1024** [comment]
PTAL.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
