### PR TITLE
Add `cupy.shape`

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by leofang** [comment]
Interesting. Didn't know this wasn't implemented. Would this allow `__array_function__` to take effect, so that `numpy.shape(cupy_array)` works?

**Comment by toslunar** [comment]
> Would this allow `__array_function__` to take effect, so that `numpy.shape(cupy_array)` works?

Yes.
https://github.com/cupy/cupy/blob/766dfd04703da1d9a971d1124951c24b91bfbc33/cupy/core/core.pyx#L1351-L1367

**Comment by leofang** [comment]
Thanks, @toslunar! I was a bit confused by the logic of `__array_function__` there; looks like if a name is in the `cupy` module, the dispatch will happen?

**Comment by takagi** [comment]
LGTM! Waiting for auto-merge.

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
