### PR TITLE
Copy inputs in ufunc if they share the same memory with outputs

### LINKED ISSUE #2407: Incorrect behavior of in-place operation between ndarrays share same memory space
Incorrect behavior of in-place operation between ndarrays which
- share same memory space and
- have different strides.

Test code:
```py
import numpy
import cupy

for xp in (numpy, cupy):
    x = xp.arange(10000).reshape(100, 100)
    x += x.T
    print(xp.__name__, ':', x.sum())  # Expected: 99990000 = 10000 * (10000 - 1)
```
Output:
```py
numpy : 99990000
cupy : 100026222
```

### PR DESCRIPTION
**Pull request by asi1024**
Fix #2407.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
#2475 is a workaround for one of the two errors in cupy-py35's `test_texture.py` (although the error shouldn't have happened), but the other `CUDARuntimeError` in `tests/cupy_tests/random_tests/test_generator.py` still happens, see the Jenkins report for #2475: https://jenkins.preferred.jp/job/chainer/job/cupy_pr/366/. Jenkins should be fixed.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins error seems to be related

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
still errored  😭

**Pull request merged**
