### PR TITLE
Do not let Python 2 users build CuPy v7+

### LINKED ISSUE #2763: CUPY 7.0 fails with Python 2.7
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
 - Python version 2.7.15+
  - CuPy version 7.0.0
  - Ubuntu 18.04
  - CUDA version NA
  - cuDNN/NCCL version (if applicable) NA
* Code to reproduce
```
Run python, issue `import cupy`.
```
* Error messages, stack traces, or logs
```
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cupy/__init__.py", line 47, in <module>
    import cupyx as _cupyx
  File "/usr/local/lib/python2.7/dist-packages/cupyx/__init__.py", line 11, in <module>
    from cupyx._ufunc_config import errstate  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/cupyx/_ufunc_config.py", line 17
    def errstate(*, divide=None, over=None, under=None, invalid=None, linalg=None):
                  ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by leofang**
Close #2763. 

cc: @JanuszL

### CODE REVIEW

**Comment by kmaehashi** [comment]
Could you use `python_requires='>=3.5.0'`?  (https://github.com/chainer/chainer/issues/7936) Then pip prints error message on unsupported Python:

```
cupy requires Python '>=3.5.0' but the running Python is 2.7.14
```

**Comment by leofang** [comment]
Sounds good, thanks @kmaehashi.

**Comment by leofang** [comment]
@kmaehashi Travis still tests PY34...Should I lower the requirement a bit?

**Comment by jakirkham** [comment]
Thanks for doing this @leofang! 😄

**Comment by jakirkham** [comment]
> @kmaehashi Travis still tests PY34...Should I lower the requirement a bit?

If so, we might want to [add Python 3.4 to the trove classifiers]( https://github.com/cupy/cupy/blob/b232b863b765b984d10af159a8540f112ae4caac/setup.py#L142-L143 ).

**Comment by leofang** [comment]
> If so, we might want to [add Python 3.4 to the trove classifiers](https://github.com/cupy/cupy/blob/b232b863b765b984d10af159a8540f112ae4caac/setup.py#L142-L143).

and also the installation guide.

**Comment by kmaehashi** [comment]
pfnCI, test this please.
(Let's ignore travis failure in 3.4.)

**Comment by leofang** [comment]
@kmaehashi Looks like this passed the CI?

**Comment by leofang** [comment]
I removed the Python 2 warning in d9775d7 since it won't even build for PY2.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
