### PR TITLE
Fix `matmul` docstring

### LINKED ISSUE #5170: Wrong documentation for matmul
Hi,

The documentation for the [matmul](https://docs.cupy.dev/en/v9.0.0/reference/generated/cupy.matmul.html) function is broken since v9.

It should read "Returns the matrix product for two arrays..." like in [v8](https://docs.cupy.dev/en/v8.6.0/reference/generated/cupy.matmul.html), but instead it shows the documentation for the[ _GUFunc class](https://github.com/cupy/cupy/blob/4469fae998df33c72ff40ef954cb08b8f0004b18/cupy/_core/_gufuncs.py#L143).

I assume the docs generation script messed up because matmul is created [using this class](https://github.com/cupy/cupy/blob/4469fae998df33c72ff40ef954cb08b8f0004b18/cupy/linalg/_product.py#L12). 

Cheers.

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #5170 

https://cupy--5174.org.readthedocs.build/en/5174/reference/generated/cupy.matmul.html

### CODE REVIEW

**Comment by takagi** [comment]
The documentation still seems to break:
- Begin with "_matmul(ndarray a, ndarray b, ndarray out=None) -> ndarray"
- Args part

Would you check them?

**Comment by emcastillo** [comment]
Yeah! got it on my pending list! :)

**Comment by emcastillo** [comment]
The docstring is fixed, but the header should be rewritten :(

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
The description begins with

> matmul(ndarray a, ndarray b, ndarray out=None) -> ndarray

Is this intended?

Also, "Args:" part looks broken to be a line.

> a (cupy.ndarray): The left argument. b (cupy.ndarray): The right argument. out (cupy.ndarray): Output array.

**Comment by emcastillo** [comment]
PTAL!

**Review by takagi — APPROVED** [review]

**Comment by takagi** [comment]
Will be merged after code-freeze cleared.

**Pull request merged**
