### PR TITLE
Support `subtract.at`, `bitwise_and.at`, `bitwise_or.at`, `bitwise_xor.at`

### PR DESCRIPTION
**Pull request by asi1024**
Part of https://github.com/cupy/cupy/issues/7082.

~Blocked by https://github.com/cupy/cupy/pull/7077.~

### CODE REVIEW

**Review by emcastillo — DISMISSED** [review]
Sorry! I mixed this with #7077

**Comment by emcastillo** [comment]
```
20:19:25 FAILED cupy_tests/core_tests/test_ufunc_methods.py::TestUfuncAtAtomicOps::test_at_add_duplicate_indices
20:19:25 FAILED cupy_tests/core_tests/test_ufunc_methods.py::TestUfuncAtAtomicOps::test_at_bitwise_and
20:19:25 FAILED cupy_tests/core_tests/test_ufunc_methods.py::TestUfuncAtAtomicOps::test_at_bitwise_or
20:19:25 FAILED cupy_tests/core_tests/test_ufunc_methods.py::TestUfuncAtAtomicOps::test_at_bitwise_xor
```
I think that ROCm had some issues with atomics

**Comment by asi1024** [comment]
@emcastillo All tests have passed!

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
