### PR TITLE
Fix handle types to `intptr_t`

### PR DESCRIPTION
**Pull request by leofang**
Fix https://github.com/cupy/cupy/pull/3719#discussion_r466540976. For some reason this was overlooked when we unified the returned type...

### CODE REVIEW

**Comment by leofang** [comment]
This can wait after #3719 is merged.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@kmaehashi PTAL.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
