### PR TITLE
Fix ndarray initialization bug

### PR DESCRIPTION
**Pull request by okuta**
Do not use `shape`.

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
https://github.com/cupy/cupy/pull/1907/files#diff-bebe923819e806ae22e9923de58e954cR141
`s` is correct.

**Comment by okuta** [comment]
> Please add a testcase for it.

OK, I will.

**Comment by okuta** [comment]
I added.

**Comment by toslunar** [comment]
The Jenkins failure seems unrelated to the PR.

**Pull request merged**
