### PR TITLE
Rename arg of `isscalar`

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
It's possible that
```python
from numpy import isscalar  # NOQA
```
is sufficient.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
As the current `cupy.isscalar` definition was introduced at #355 replacing with

```Python
from numpy import isscalar  # NOQA
```

for some reason, I suppose leaving the definition would be fine.

**Comment by takagi** [comment]
LGTM! Waiting for CI finish.

**Comment by niboshi** [comment]
This is nocompat, right?

**Comment by takagi** [comment]
Ah... yes.

**Pull request merged**
