### PR TITLE
Revert `_get_arch`

### PR DESCRIPTION
**Pull request by takagi**
This PR partially reverts the change made in https://github.com/cupy/cupy/pull/4558, where `_get_arch` was simplified.

`_get_arch` was originally for the case that nvrtc supported only lower compute capability than nvcc, but at the same time, it also worked for the situation that the compute capability that the CUDA Toolkit version supported was lower than the GPU did.

The situation may have to be always an error as, for example, one should not expect to run Ampere on CUDA 10.x, but we keep working user's environment here. (Actually, we have to build CUDA 9.0 wheels on Tesla T4 (CC = 7.5))

### CODE REVIEW

**Comment by kmaehashi** [comment]
LGTM!
pfnCI, test this please.

**Comment by leofang** [comment]
Thanks @takagi.

**Comment by leofang** [comment]
@toslunar @kmaehashi The failing tests are also frequently seen when testing #4628 (thus I suspect it might have something to do with #4684):
```
tests.cupy_tests.random_tests.test_generator.TestInterval.test_goodness_of_fit
tests.cupy_tests.random_tests.test_generator.TestChoiceChi.test_goodness_of_fit
tests.cupy_tests.random_tests.test_generator.TestChoiceChi.test_goodness_of_fit_2
tests.cupy_tests.random_tests.test_sample.TestRandint2.test_goodness_of_fit
tests.cupy_tests.random_tests.test_sample.TestRandint2.test_goodness_of_fit_2
tests.cupy_tests.random_tests.test_sample.TestRandomIntegers2.test_goodness_of_fit
tests.cupy_tests.random_tests.test_sample.TestRandomIntegers2.test_goodness_of_fit_2
```
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/3058/

**Comment by kmaehashi** [comment]
Let me merge this as 
As for the test failures, we're discussing reverting batched SVD PR to isolate the issue. (as the next release date is close)

**Comment by leofang** [comment]
> As for the test failures, we're discussing reverting batched SVD PR to isolate the issue. (as the next release date is close)

@kmaehashi All failures are from the  `test_svd_rank<N>_loop` tests. Perhaps it's easier to just disable this call path https://github.com/cupy/cupy/blob/1976a612043e63d149b9ed08e622220f54ed7f3d/cupy/linalg/_decomposition.py#L398-L402
and also those tests?

**Pull request merged**
