### PR TITLE
Support CUDA 12.2

### PR DESCRIPTION
**Pull request by kmaehashi**
Part of #7674

Also removes fp16 headers for CUDA versions no longer supported.

### CODE REVIEW

**Comment by takagi** [comment]
Flaky:
```
FAILED cupy_tests/math_tests/test_misc.py::TestConvolve::test_convolve_large_non_contiguous[same]
FAILED cupy_tests/math_tests/test_misc.py::TestConvolve::test_convolve_large_non_contiguous[full]
```

May still have a bug with CUDA 12.2's cusolver:
```
FAILED cupyx_tests/scipy_tests/sparse_tests/test_linalg.py::TestLOBPCG::test_maxit_None
```

**Comment by kmaehashi** [comment]
Tests passed!

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
