### PR TITLE
Suppress nvcc warning

### LINKED ISSUE #6943: Suppress compilation warnings from `complex.h`
Ex:
```
    /home/leof/dev/cupy_cuda114/cupy/_core/include/cupy/complex/complex.h(94): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

    /home/leof/dev/cupy_cuda114/cupy/_core/include/cupy/complex/complex.h(94): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

    /home/leof/dev/cupy_cuda114/cupy/_core/include/cupy/complex/complex.h(101): warning: __host__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

    /home/leof/dev/cupy_cuda114/cupy/_core/include/cupy/complex/complex.h(101): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration
```
The parallel build experiment (#6941) made it more noisy. I am pretty sure I introduced these warnings in a prior PR, and mistakenly thought it'd be fixed by a future nvcc 😞 Let's just make the annotation properly done...

Please assign this task to me, thanks!

### PR DESCRIPTION
**Pull request by leofang**
Close #6943.

### CODE REVIEW

**Comment by leofang** [comment]
Confirmed fixed in the CI build logs too (try searching `__device__` or `__host__`). The CI failures seem irrelevant and known.

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
@leofang LGTM. Thanks!

**Comment by leofang** [comment]
@kmaehashi @asi1024 Perhaps this code-fix PR can be backported?

**Pull request merged**
