### PR TITLE
[backport] Fix complex type checks in `_correlate_or_convolve`

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #2923

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
I have seen this test fail in other benchmarks, seem to be flaky

**Comment by niboshi** [comment]
It should be fixed by #2913.

**Comment by emcastillo** [comment]
Right, I didn't remember the exact error

**Comment by niboshi** [comment]
#2913 has been merged.

**Comment by emcastillo** [comment]
Thanks!
Jenkins, test this please

**Pull request merged**
