### PR TITLE
Windows: Fix cuTENSOR tests

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of #4776. It's currently not tested on the Windows CI yet, but will cause errors when we enable it.

### CODE REVIEW

**Comment by asi1024** [comment]
Merged master branch to reflect #4803.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM!

**Review by asi1024 — APPROVED** [review]

**Comment by leofang** [comment]
Thanks!

**Pull request merged**
