### PR TITLE
[backport] Fix `argmin`/`argmax` `dtype` argument

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #2872

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Can we retest this? I couldnt reproduce the failure locally

**Comment by emcastillo** [comment]
Merge after #2912

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request closed without merging**
