### PR TITLE
Assert that all the pointers are in the same device in `concatenate`

### LINKED ISSUE #3283: Concatenating arrays from different devices results in a CUDARuntimeError
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : CUBLASError('CUBLAS_STATUS_NOT_INITIALIZED')
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2506
NCCL Runtime Version  : 2506
```

* Code to reproduce
``` python
import cupy
print(cupy.__version__)

arrs = []
rng = cupy.random.RandomState(1994)

for i in range(100):
    cupy.cuda.runtime.setDevice(i % 2)
    a = rng.randn(1000, 100)
    arrs.append(a)


cat = cupy.concatenate(arrs, axis=0)
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "with-cupy.py", line 14, in <module>
    cat = cupy.concatenate(arrs, axis=0)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/cupy/manipulation/join.py", line 54, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/_routines_manipulation.pyx", line 577, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 623, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 649, in cupy.core._routines_manipulation._concatenate
  File "cupy/core/_routines_manipulation.pyx", line 770, in cupy.core._routines_manipulation._concatenate_single_kernel
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1243, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1264, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1042, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1062, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 764, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 761, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 1011, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 499, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 500, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 99, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 296, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

I'm using cupy with `dask` on multiple GPUs.  If the operation is not supported, a more friendly error message for further debugging would be appreciated. ;-)

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #3283

Concatenate creates an array of pointers, but the device here is not verified so it can fail
with hard to understand errors.

TODO: Add test

### CODE REVIEW

**Comment by takagi** [comment]
Calling `cupy.concatenate()` raises the similar error without the change in this PR:
```Python
>>> import cupy
>>> from cupy import cuda
>>> with cuda.Device(0):
...     a = cupy.empty((2, 3, 4))
...
>>> with cuda.Device(1):
...     b = cupy.empty((2, 3, 4))
...
>>> cupy.concatenate((a, b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ext-mtakagi/cupy/cupy/manipulation/join.py", line 57, in concatenate
    return core.concatenate_method(tup, axis, out)
  File "cupy/core/_routines_manipulation.pyx", line 535, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 595, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 632, in cupy.core._routines_manipulation._concatenate
  File "cupy/core/_kernel.pyx", line 1006, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 116, in cupy.core._kernel._preprocess_args
  File "cupy/core/_kernel.pyx", line 86, in cupy.core._kernel._check_array_device_id
ValueError: Array device must be same as the current device: array device = 1 while current = 0```

**Comment by takagi** [comment]
50 devices in #3283?

**Comment by leofang** [comment]
I think it's 2. It took modulo 2, not divided by 2 😂

**Comment by takagi** [comment]
😂

**Comment by takagi** [comment]
Just it depends on the code path.

**Comment by takagi** [comment]
@emcastillo  I've wrote the test for this PR, and would you add it in `cupy/tests/cupy_tests/manipulation_tests/test_join.py` with `from copy import cuda`?

```Python
@testing.multi_gpu(2)
def test_concatenate_large_different_devices(self):
    arrs = []
    for i in range(10):
        with cuda.Device(i % 2):
            arrs.append(cupy.empty((2, 3, 4)))
    with pytest.raises(ValueError):
        cupy.concatenate(arrs)
```

**Comment by emcastillo** [comment]
@takagi please, push it to my branch so you can get authorship in the commit 😊

**Comment by takagi** [comment]
Okay, then would you give me permission to push?

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for auto-merge.

**Comment by trivialfis** [comment]
Thanks!

**Pull request merged**
