### PR TITLE
Hide private names in `cupyx.scipy.sparse`

### PR DESCRIPTION
**Pull request by takagi**
Part of https://github.com/cupy/cupy/issues/6252.

### CODE REVIEW

**Review by kmaehashi — DISMISSED** [review]

**Comment by kmaehashi** [comment]
Could you take a look at test failures? :pray:

**Comment by takagi** [comment]
@kmaehashi Would you see what's going wrong on Jenkins?

**Comment by kmaehashi** [comment]
Test failures are irrelevant, so let's merge this one.

```
16:46:01 FAILED cupyx_tests/scipy_tests/special_tests/test_beta.py::TestBeta::test_beta_specific_vals
16:46:01 FAILED cupyx_tests/scipy_tests/special_tests/test_beta.py::TestBeta::test_betaln_specific_vals
16:46:01 FAILED cupyx_tests/scipy_tests/special_tests/test_gammainc.py::TestGammainc::test_roundtrip
```

**Comment by takagi** [comment]
Thanks!

**Pull request merged**
