### PR TITLE
JIT: Use C++14

### PR DESCRIPTION
**Pull request by asi1024**
https://github.com/cupy/cupy/pull/6668#discussion_r854845340

### CODE REVIEW

**Comment by emcastillo** [comment]
cuda110 tests are broken since the cooperative groups stuff

**Review by emcastillo — DISMISSED** [review]

**Comment by asi1024** [comment]
This fix will not work on CentOS 7.

**Comment by asi1024** [comment]
> This fix will not work on CentOS 7.

NVRTC can compile C++14 code, so we can apply this PR.

**Review by emcastillo — APPROVED** [review]
lgtm

**Comment by emcastillo** [comment]
```
0:10:27 Looking for cache files under /home/jenkins-external-slave/.cupy-pfnci/.cupy/kernel_cache...
20:10:30 Traceback (most recent call last):
20:10:30   File ".pfnci/trim_cupy_kernel_cache.py", line 85, in <module>
20:10:30     main()
20:10:30   File ".pfnci/trim_cupy_kernel_cache.py", line 43, in main
20:10:30     stat = os.lstat(f)
20:10:30 FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins-external-slave/.cupy-pfnci/.cupy/kernel_cache/2751f477ec32e01f296254dae20ae0ef802d08e7.hsaco'
```
Seems like jenkins failure is unrelated

**Pull request merged**
