### PR TITLE
CI: Fix unquoted specifiers

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes the issue that `cuda-head` test did not install pre-releases correctly (`=0a0` file was created...).

### CODE REVIEW

**Review by toslunar — COMMENTED** [review]
How about `shlex.join`?

**Comment by kmaehashi** [comment]
> How about `shlex.join`?

Thanks, good suggestion :)

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
I'll kick the CI later.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
