### PR TITLE
Support cuTENSOR 1.4.0

### PR DESCRIPTION
**Pull request by takagi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Several tests failed with `CUTENSOR_STATUS_INTERNAL_ERROR`. Can you take a look on this? @takagi

**Comment by leofang** [comment]
I can reproduce it locally:
```python
>>> a = cp.asarray([1.], dtype=cp.float64)
>>> a.max()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 915, in cupy._core.core.ndarray.max
    cpdef ndarray max(self, axis=None, out=None, keepdims=False):
  File "cupy/_core/core.pyx", line 923, in cupy._core.core.ndarray.max
    return _statistics._ndarray_max(self, axis, out, None, keepdims)
  File "cupy/_core/_routines_statistics.pyx", line 38, in cupy._core._routines_statistics._ndarray_max
    result = cutensor._try_reduction_routine(
  File "cupy/cutensor.pyx", line 799, in cupy.cutensor._try_reduction_routine
    _reduction_impl(
  File "cupy/cutensor.pyx", line 716, in cupy.cutensor._reduction_impl
    cutensor.reduction(
  File "cupy_backends/cuda/libs/cutensor.pyx", line 817, in cupy_backends.cuda.libs.cutensor.reduction
    check_status(status)
  File "cupy_backends/cuda/libs/cutensor.pyx", line 242, in cupy_backends.cuda.libs.cutensor.check_status
    raise CuTensorError(status)
cupy_backends.cuda.libs.cutensor.CuTensorError: CUTENSOR_STATUS_INTERNAL_ERROR
```
Will look into it later this week.

**Comment by leofang** [comment]
btw CUDA 10.2/11.2 tests passed? Do they use different setups for cuTENSOR?

**Comment by leofang** [comment]
I can also reproduce the failure with a C code. Filed nvbugs 3486461 for further investigation.

**Comment by kmaehashi** [comment]
> I can also reproduce the failure with a C code. Filed nvbugs 3486461 for further investigation.

Thanks, Leo!

> btw CUDA 10.2/11.2 tests passed? Do they use different setups for cuTENSOR?

Yes, we are designing the test matrix to cover all supported software versions.

https://github.com/cupy/cupy/blob/485257874104e3efc5e71778afbff8cb0ef27fb9/.pfnci/matrix.yaml#L89
https://github.com/cupy/cupy/blob/master/.pfnci/coverage.md

**Comment by leofang** [comment]
I see, so for CUDA 10.2 no cuTENSOR is installed, and CUDA 11.2 has cuTENSOR 1.4 installed but not used (`CUPY_ACCELERATORS` unset).

**Comment by leofang** [comment]
@kmaehashi @takagi We have identified the root cause and fixed the bug for the next release. In the meanwhile, I think there's a simple workaround. Would you like me to send a patch so as to unblock this PR?

**Comment by kmaehashi** [comment]
@leofang Thanks! That would be helpful if the fixed version is not going to be out soon 😃

**Comment by leofang** [comment]
See https://github.com/takagi/cupy/pull/3.

**Comment by kmaehashi** [comment]
Yes. Could you regenerate @takagi?

**Comment by kmaehashi** [comment]
Thanks, head test failure unrelated to this PR.

**Pull request merged**
