### PR TITLE
Fix `csr_matrix._get_intXslice` for step < 0 case

### PR DESCRIPTION
**Pull request by asi1024**
Blocked by #3948 and #3955.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
Rebased.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
Reproduced the test failure locally with SciPy 1.4.1.

**Comment by emcastillo** [comment]
Segfault?

**Comment by emcastillo** [comment]
Segfault?

**Comment by asi1024** [comment]
@emcastillo #3955 will resolve these test failures.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
