### PR TITLE
Avoid monkeypatching distutils

### LINKED ISSUE #5619: error: Microsoft Visual C++ 14.2 or greater is required
In case building CuPy 9.3 on Windows with Visual Studio 2019 and CUDA SDK 11.4 (and probably other versions) fails with `error: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools ...`, this patch worked for me on Python 3.7-10:

```diff
diff --git a/cupy_setup_build.py b/cupy_setup_build.py
index b363c1026..0d77f34aa 100644
--- a/cupy_setup_build.py
+++ b/cupy_setup_build.py
@@ -2,7 +2,7 @@ import argparse
 import copy
 from distutils import ccompiler
 from distutils import errors
-from distutils import msvccompiler
+from distutils import _msvccompiler as msvccompiler
 from distutils import sysconfig
 from distutils import unixccompiler
 import os
```

### PR DESCRIPTION
**Pull request by kmaehashi**
Part of #4983. Avoid monkeypatching distutils when building CuPy, and also avoid `import numpy.distutils`.

This is needed to remove the setuptools version restriction on Windows (reverts #6260).
This also closes #5619.

ref #5476

### CODE REVIEW

**Comment by kmaehashi** [comment]
Will fix flake8 and mypy after seeing the GPU CI results 😄

**Comment by emcastillo** [comment]
seems like it didn't work :(

**Comment by kmaehashi** [comment]
Let's merge this PR targetting the February release as this is relatively a large change.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
