### PR TITLE
[backport] Bug: Fix `coosort`

### PR DESCRIPTION
**Pull request by takagi**
Backport of #2410

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by hvy** [comment]
Thanks, LGTM! I'll merge this PR soon after the release.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
