### PR TITLE
 Support 'f' and 'c' in order

### PR DESCRIPTION
**Pull request by okuta**
NumPy supports small character.

### CODE REVIEW

**Comment by kmaehashi** [comment]
The followings must be fixed as well:

unravel_index
csc_matrix.toarray
csr_matrix.toarray

**Comment by kmaehashi** [comment]
I think it's acceptable to fix above 3 functions in another PR.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
> I think it's acceptable to fix above 3 functions in another PR.

Yes, I will fix in another PR.

**Comment by kmaehashi** [comment]
Jenkins test error is not related to this PR.
LGTM!

**Pull request merged**
