### PR TITLE
Improve cupyx.scipy.sparse int x int indexing

### PR DESCRIPTION
**Pull request by asi1024**
Blocked by #3975 
- `master`
```
- name = major_slice, major = 30, minor = 30, format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:  347.650 us   +/-62.985 (min:  338.049 / max: 3612.037) us     GPU-0:  353.839 us   +/-63.345 (min:  344.064 / max: 3636.224) us
```
- this PR
```
- name = major_slice, major = 30, minor = 30, format = csr, density = 0.5, dtype = float32, n_rows = 15000, n_cols = 15000
cupy.sparse         :    CPU:  109.048 us   +/-39.150 (min:  105.948 / max: 3626.384) us     GPU-0:  114.418 us   +/-39.267 (min:  110.592 / max: 3641.344) us
```

### CODE REVIEW

**Comment by toslunar** [comment]
Please merge (or rebase to) `master` in order to show the appropriate diff of the PR (`git diff master...intxint`).

**Comment by asi1024** [comment]
@toslunar Rebased.

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
