### PR TITLE
Slight code improvements for the CUB reduction kernel

### PR DESCRIPTION
**Pull request by leofang**
Related to #4484, #4485. Tons of thanks to @emcastillo who figured out that the last segment size is corrupted in HIP due to the difference of its memory model from CUDA's.

**UPDATE:** This PR mainly does two things:
1. Instead of modifying the kernel argument directly, we copy it to a register and modify the local copy.
2. Sync threads only on HIP.

### CODE REVIEW

**Comment by emcastillo** [comment]
Is this ready? seems to be so

**Comment by leofang** [comment]
I prefer #4485 to go in first, so that I can resolve a possible conflict here.

**Comment by leofang** [comment]
> I prefer #4485 to go in first, so that I can resolve a possible conflict here.

@emcastillo I resolved the conflict. PTAL.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
