### PR TITLE
Update cupy-wheel for v11

### PR DESCRIPTION
**Pull request by kmaehashi**
* Update package list
* Fix issue in #6688 (pip caches cupy-wheel) by using build number override technique described in https://discuss.python.org/t/wheel-caching-and-non-deterministic-builds/7687

### CODE REVIEW

**Comment by kmaehashi** [comment]
Test failure is irrelevant.

**Comment by leofang** [comment]
Yeah I also saw the same errors in #6871...

**Review by emcastillo — APPROVED** [review]
LGTM!

**Pull request merged**
