### PR TITLE
Remove stubs for APIs dropped in CUDA 10.1 Update 2

### PR DESCRIPTION
**Pull request by kmaehashi**
Follow-up for #2573

### CODE REVIEW

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by jakirkham** [comment]
Thanks all! 😀

**Pull request merged**
