### PR TITLE
Support ncclSend/ncclRecv from NCCL 2.7

### PR DESCRIPTION
**Pull request by leofang**

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Currently the test is skipped in the CI. To test this, chainer-test should have NCCL 2.7+ installed.

**Comment by leofang** [comment]
cc: @jakirkham

**Comment by takagi** [comment]
I'll kick the CI after https://github.com/chainer/chainer-test/pull/589 is merged.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
The test was run in `cupy-py35` and passed.

**Comment by takagi** [comment]
LGTM!

**Comment by leofang** [comment]
Thank you!

**Pull request merged**
