### PR TITLE
Add divmod function to cupy namespace

### PR DESCRIPTION
**Pull request by okuta**
This PR fix this [error.](https://gist.github.com/okuta/fb26f7e8dc30020bb4d9735304fb0d06)

### CODE REVIEW

**Comment by beam2d** [comment]
I tried this patch but the error still occurs. The error does not occur after writing `cupy.divmod = cupy.core.divmod`, so we have to put the symbol to `cupy` instead of fixing the argument of `create_ufunc`.

**Comment by beam2d** [comment]
Looks good.
Jenkins, test this please.

**Comment by beam2d** [comment]
It looks NumPy <1.13 does not have divmod.

**Comment by okuta** [comment]
@beam2d I fixed test.

**Comment by beam2d** [comment]
Thanks, LGTM

**Comment by toslunar** [comment]
It seems the PR added `cupy.divmod`.  Is this still an enhancement and OK to be backported?

**Comment by okuta** [comment]
OK, I changed label.

**Comment by okuta** [comment]
I want backport this PR to support latest fusion function.

**Pull request merged**
