### PR TITLE
Fix `cupy.repeat` error message about `repeats` argument type

### LINKED ISSUE #2221: Error message from `cupy.repeat` is misleading
Version: current master cbd9c30db2eff89f8d102684085779d75a7e6f5f
See also: https://stackoverflow.com/questions/56344478/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

```python
import cupy as cp

arr = cp.array([5, 1, 4], 'float32')
rep = cp.array([3, 2], 'int32')
ret = cp.repeat(arr, rep)
```
```
Traceback (most recent call last):
  File "/home/niboshi/t/a.py", line 5, in <module>
    ret = cp.repeat(arr, rep)
  File "/data2/work/w/repos/cupy/cupy/manipulation/tiling.py", line 69, in repeat
    return a.repeat(repeats, axis)
  File "cupy/core/core.pyx", line 593, in cupy.core.core.ndarray.repeat
  File "cupy/core/core.pyx", line 601, in cupy.core.core.ndarray.repeat
  File "cupy/core/_routines_manipulation.pyx", line 276, in cupy.core._routines_manipulation._ndarray_repeat
  File "cupy/core/_routines_manipulation.pyx", line 506, in cupy.core._routines_manipulation._repeat
  File "cupy/core/core.pyx", line 906, in cupy.core.core.ndarray.__nonzero__
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The error message could be improved.
As seemingly this issue is *repeated* (#1918), we might include the reason behind prohibiting `cupy.ndarray` in the error message.

### Some more detail

It seems that [this condition](https://github.com/cupy/cupy/blob/v7.0.0a1/cupy/core/_routines_manipulation.pyx#L503) is satisfied for `cupy.ndarray` and the following `if repeats < 0:` is evaluated.

`numpy.issubdtype(repeats, numpy.integer)` surprisingly returns `True`.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #2221

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM!

By the way, I'm not sure what the rhs of the `or` operator intends. Do you think we can remove it?

https://github.com/cupy/cupy/pull/2400/files#diff-22ceaeb1c1db287ae5c69ce6f45e63a7R507
```Python
    if (isinstance(repeats, int) or
            (hasattr(repeats, 'dtype') and
             numpy.issubdtype(repeats, numpy.integer))):
 ```

**Comment by niboshi** [comment]
@takagi I guess it's required to handle something like `numpy.int32(3)`.

**Comment by takagi** [comment]
I got it!

**Comment by takagi** [comment]
@kmaehashi I take it over.

**Pull request merged**
