### PR TITLE
Rename `cupy.core` submodule to `cupy._core`

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR renames `cupy.core` submodule to `cupy._core` to indicate it is CuPy's private submodule and not intended to be used by users.

### CODE REVIEW

**Comment by asi1024** [comment]
@takagi This PR conflict with many on-going PRs each other. I will start reviewing after all v8 release blockers are resolved.

**Comment by asi1024** [comment]
@takagi Could you resolve conflicts?

**Comment by kmaehashi** [comment]
Discussed internally: we will be delaying this rename to v9 rc release because many PRs will start to conflict when this got merged.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
Ignote the error above. This is because I added a label to run release note generator.

**Pull request merged**
