### PR TITLE
Getitem for major dimension

### PR DESCRIPTION
**Pull request by unnonouno**
I implemented __getitem__ for major dimension of compressed matrixes.
Please merge #240 first.
related to #36

### CODE REVIEW

**Comment by takagi** [comment]
LGTM!

**Comment by unnonouno** [comment]
I fixed behavior of getitem for slices with negative values.

**Comment by takagi** [comment]
Please resolve the conflicts.

**Comment by unnonouno** [comment]
I rebased master.

**Comment by takagi** [comment]
I will merge this after CI passes.

**Pull request merged**
