### PR TITLE
Docs: ufunc methods

### PR DESCRIPTION
**Pull request by kmaehashi**
Part of #7082

cc/ @asi1024

### CODE REVIEW

**Comment by asi1024** [comment]
`ufunc.outer` and `ufunc.at` is already documented.
https://cupy--7077.org.readthedocs.build/en/7077/reference/generated/cupy.ufunc.html

**Comment by kmaehashi** [comment]
This page intends to follow the strcutrue of numpy's docs:
https://numpy.org/doc/stable/reference/ufuncs.html#methods
and also list ufuncs supported for each method. 😄

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
Canceled CIs as it's too congested, continue merging as this is docs only pr and got approved

**Pull request merged**
