### PR TITLE
Update `cupy.array_api` (cont'd)

### PR DESCRIPTION
**Pull request by leofang**
Applied patches from upstream:
- numpy/numpy#21666
- numpy/numpy#21084

### CODE REVIEW

**Comment by leofang** [comment]
Notes:
1. After this PR we'll be in sync with upstream.
2. To backport this PR, https://github.com/cupy/cupy/pull/6904 needs to be merged first.

**Comment by asi1024** [comment]
LGTM. Thanks!

**Review by asi1024 — APPROVED** [review]

**Comment by leofang** [comment]
@asi1024 I think this PR should be backported 🙂

**Pull request merged**
