### PR TITLE
Change minimum Cython version

### PR DESCRIPTION
**Pull request by okuta**
Ctyhon version 0.26.0 was released. We should use latest Cython.
https://github.com/cython/cython/blob/master/CHANGES.rst

### CODE REVIEW

**Comment by unnonouno** [comment]
It changes requirements. Do we need to backport it?

**Comment by okuta** [comment]
This change only affects developers.
In this case, what do you think is good?

**Comment by niboshi** [comment]
Doesn't it affect users who install cupy via pip?

**Comment by okuta** [comment]
Yes, we use cpp file that is generated from Cython file.
However, if you are worried it is possible to not backport

**Comment by sonots** [comment]
0.26.1 is released on 2017-08-29. https://github.com/cython/cython/blob/master/CHANGES.rst#0261-2017-08-29

**Comment by niboshi** [comment]
Unless it solves any critical problem, requirements should no be tightened in minor stable releases.
It would break environments of someone with no privilege of cython installation.

**Comment by okuta** [comment]
OK.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
