### PR TITLE
[WIP] Allow external memory pools

### PR DESCRIPTION
**Pull request by hvy**
Required by Chainer (https://github.com/chainer/chainer/pull/5821) to share memory pools between CuPy and ChainerX.

### CODE REVIEW

**Comment by hvy** [comment]
Thanks for the suggestion but wouldn't that affect the performance of the current memory pool?

**Comment by hvy** [comment]
Mostly these casts https://github.com/cupy/cupy/pull/1883/files#diff-0cb5dfa3212da5a58c698548f2df2f68R1084 🤔

**Comment by niboshi** [comment]
Do you mean the cast itself? Or method call after the cast?
I'm not 100% sure without measurement, but I don't think they would introduce great degradation.

**Comment by hvy** [comment]
The call to malloc is affected. But I should probably measure it anyhow. The generated code differs quite a bit.

**Comment by hvy** [comment]
screen shot 2018-12-12 at 18 17 51

**Comment by niboshi** [comment]
That's weird. How is `malloc` defined in `BaseSingleDeviceMemoryPool`?

**Comment by hvy** [comment]
Ah it was empty actually. I'm trying to implement the hierarchy you suggested.

**Comment by hvy** [comment]
Closed in favor of https://github.com/cupy/cupy/pull/1904.

**Pull request closed without merging**
