### PR TITLE
Add FFT functions

### PR DESCRIPTION
**Pull request by not522**
I'm implementing FFT functions using cuFFT library.

### CODE REVIEW

**Comment by bkvogel** [comment]
Thank you for working on this. It will be nice to have FFT support.

**Comment by okuta** [comment]
jenkins, test this plsae.

**Comment by bkvogel** [comment]
jenkins, test this please.

**Comment by bkvogel** [comment]
It seems that I cannot run the CuPy examples using this PR. For example, `cupy\examples\gemm\sgemm.py` fails with:
ImportError: cannot import name 'fft'

**Comment by not522** [comment]
I fixed ImportError and other bugs.
All checks have passed.

**Comment by bkvogel** [comment]
jenkins, test this please.

**Comment by bkvogel** [comment]
LGTM!

**Pull request merged**
