### PR TITLE
Inherit environment variable and detect cl.exe automatically

### PR DESCRIPTION
**Pull request by kmaehashi**
* NVCC refers to several environment variables, so it should be inherited from the environment.
* On Windows, it's better to append path to the compiler to allow using nvcc backend without frustration.

See comments in the code for details.

### CODE REVIEW

**Comment by leofang** [comment]
LGTM. Do I understand it correctly that if `cl.exe` is not found, we rely on the fact that an error would be raised when `nvcc` is invoked?

**Comment by kmaehashi** [comment]
Yes, in that case users will see `nvcc fatal   : Cannot find compiler 'cl.exe' in PATH` error, as far as I tested. But I'm not 100% sure because it's not precisely documented how NVCC locates the compiler on Windows...

**Review by leofang — APPROVED** [review]

**Comment by kmaehashi** [comment]
(For later reference) When `TMP`/`TEMP` is not set, `nvcc.exe` dies with exit status 2, without any messages at all.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
memorandum (for future reference): when `TMP`/`TEMP` is not set, nvcc.exe dies with exit status 2 without any output.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
