### PR TITLE
Simplify nogil

### PR DESCRIPTION
**Pull request by okuta**
`cdef extern` receives additional configuration.

### CODE REVIEW

**Comment by gwtnb** [comment]
Please resolve conflicts.

**Comment by gwtnb** [comment]
Could you paste a link to a document about the feature? I found [one](https://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/version/Doc/Manual/external.html) but it is for Pyrex.

**Comment by okuta** [comment]
Cython uses this feature.
https://github.com/cython/cython/blob/master/Cython/Includes/libc/string.pxd#L10

**Comment by rezoo** [comment]
Could I merge this PR after resolving the conflicts? It simplifies the code, but several PRs follow the old ``nogil`` style.

**Comment by okuta** [comment]
@rezoo I fixed.

**Pull request merged**
