### PR TITLE
use `time.process_time` instead of `time.clock`

### LINKED ISSUE #3059: time.clock was removed in Python 3.8
https://github.com/python/cpython/pull/13270 . Given that the project is Python 3 only it will be better to use the alternatives. There is https://github.com/cupy/cupy/issues/2599 for Python 3.8 but not sure why it didn't error out.

https://github.com/cupy/cupy/blob/8d923719ced31fdff4a42702d395ec87a7e98045/cupy/random/generator.py#L681

### PR DESCRIPTION
**Pull request by rushabh-v**
closes #3059

### CODE REVIEW

**Comment by niboshi** [comment]
`time.process_time` is local to the curren process. I think it's not appropriate for a seed.
How about `time.time`?

**Comment by rushabh-v** [comment]
can you take a look back, please @niboshi ?

**Comment by niboshi** [comment]
Thanks, looks good to me.

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
