### PR TITLE
Refactoring cupy/cuda/cudnn

### PR DESCRIPTION
**Pull request by okuta**
This PR adds some memorable things.

### CODE REVIEW

**Comment by niboshi** [comment]
Why did you rewrite `ConvolutionFwdPreference` to `int`, for instance?

**Comment by okuta** [comment]
To avoid compile error.
If we use `ConvolutionFwdPreference`, each pyx file needs to include `cupy_cudnn.h`.
It design is not suitable.

**Comment by niboshi** [comment]
>each pyx file needs to include `cupy_cudnn.h`.

Do you mean `cimport`ing `pxd` files?
Is it not possible to declare in a `pxd` file and `cimport`ing it from `pyx` files?

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
