### PR TITLE
Readd `ndarray` type to `y`

### PR DESCRIPTION
**Pull request by jakirkham**
Closes https://github.com/cupy/cupy/issues/3092
Closes https://github.com/cupy/cupy/issues/3110

cc @leofang

### CODE REVIEW

**Comment by leofang** [comment]
I think you can add that this PR closes #3092 and #3110.

**Comment by leofang** [comment]
This PR  is tested locally btw.

**Comment by jakirkham** [comment]
Ah ok. So this worked for you? 🙂

**Comment by leofang** [comment]
Yes!

**Comment by jakirkham** [comment]
Thanks Leo!

Yeah I'm also a bit fuzzy on why this helps, but that doesn't mean much (given I'm not as familiar with the codebase as all of you 🙂).

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@jakirkham This is the very same error that I made multiple times in the past! The offending line is 
```python
y_ptr = <void *>y.data.ptr
``` 
If `y` is a Python object (since `cdef` was removed; can be confirmed by inspecting the generated cpp file; Cython is to be blamed -- it should deduce `y`'s type!), then this cast is just giving us a pointer to the Python object `y.data.ptr`, not the actual pointer to the data.

Refs: 
1. https://github.com/cupy/cupy/pull/2455#discussion_r325234488
2. https://github.com/cupy/cupy/blob/43c3c21e1fea5f0fc8a449aa97f10227c8ae6f91/cupy/cuda/texture.pyx#L328-L329

**Comment by jakirkham** [comment]
Thanks @emcastillo! 😀 Sorry for the silly typo (autocomplete 😞)

That makes sense! Thanks for the clarification Leo! 😀

**Pull request merged**
