### PR TITLE
Windows: Fix histogram test failures

### PR DESCRIPTION
**Pull request by leofang**

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Fixed all tests in `test_histogram.py`! (Failures: 986 -> 956)

**Comment by leofang** [comment]
This is ready. Failed tests do not seem related.

**Comment by toslunar** [comment]
label: `cat:bug`

This PR fixes the main code, while #4776 fixes the test code.

**Review by toslunar — APPROVED** [review]

**Pull request merged**
