### PR TITLE
Fix: Add missing output dtype check for direct correlate/convolve 

### LINKED ISSUE #5989: cupyx.scipy.signal.convolve2d yields a JitifyException: Runtime compilation
### Description

The following snipet of code produces a Jitify Exception at Runtime compilation: 

```py
from cupyx.scipy import signal
from scipy import misc
import cupy as cp

ascent = misc.ascent()
scharr = cp.array([[ -3-3j, 0-10j,  +3 -3j],
                   [-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
ascentcp = cp.array(ascent)
grad = signal.convolve2d(ascentcp, scharr, boundary='symm', mode='same')
```

-----------------------------------

The error info I have collected follows: 

```
---------------------------------------------------
--- JIT compile log for /tmp/tmpv46hshqr/48d1e6d813e89a765e8f8cac84ee6955_2.cubin.cu ---
---------------------------------------------------
cupy/complex/complex.h(94): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

cupy/complex/complex.h(101): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

type_traits(1): warning: extra text after expected end of preprocessing directive

type_traits(2): warning: white space is required between the macro name "_JITIFY_INCLUDE_GUARD_C" and its replacement text

/tmp/tmpv46hshqr/48d1e6d813e89a765e8f8cac84ee6955_2.cubin.cu(24): error: no suitable conversion function from "W" to "Y" exists
          detected during instantiation of "std::enable_if<<expression>, B>::type cast<B,A>(A) [with B=Y, A=W]" 
(81): here

1 error detected in the compilation of "/tmp/tmpv46hshqr/48d1e6d813e89a765e8f8cac84ee6955_2.cubin.cu".

---------------------------------------------------
JITIFY compilation error: Runtime compilation failed
-----
Name: /tmp/tmpv46hshqr/48d1e6d813e89a765e8f8cac84ee6955_2.cubin.cu
Options: --std=c++11 -DCUPY_USE_JITIFY -I/home/admpy/Scripting/anaconda3/lib/python3.8/site-packages/cupy/_core/include -I/home/admpy/Scripting/anaconda3/lib/python3.8/site-packages/cupy/_core/include/cupy/_cuda/cuda-11.2 -I/usr/local/cuda-11.2/include -ftz=true --device-debug --generate-line-info
CUDA source:
01 #include <cupy/complex.cuh>
02 #include <cupy/carray.cuh>
03 #include <cupy/atomics.cuh>
04 
05     typedef complex<double> W;
06 typedef long long X;
07 typedef long long Y;
08 
09 
10 // workaround for HIP: line begins with #include
11 #include <type_traits>  // let Jitify handle this
12 #include <cupy/math_constants.h>
13 
14 // Implements a casting function to make it compatible with scipy
15 // Use like cast<to_type>(value)
16 template<> struct std::is_floating_point<float16> : std::true_type {};
17 template<> struct std::is_signed<float16> : std::true_type {};
18 template<class T> struct std::is_signed<complex<T>> : std::is_signed<T> {};
19 
20 template <class B, class A>
21 __device__ __forceinline__
22 typename std::enable_if<(!std::is_floating_point<A>::value
23                          || std::is_signed<B>::value), B>::type
24 cast(A a) { return (B)a; }
25 
26 template <class B, class A>
27 __device__ __forceinline__
28 typename std::enable_if<(std::is_floating_point<A>::value
29                          && (!std::is_signed<B>::value)), B>::type
30 cast(A a) { return (a >= 0) ? (B)a : -(B)(-a); }
31 
32 template <class T>
33 __device__ __forceinline__ bool nonzero(T x) { return x != static_cast<T>(0); }
34 
35     extern "C" __global__ void cupyx_scipy_ndimage_correlate_2d_reflect_w3_3(const CArray<long long, 2, 1, 1> x, const CArray<complex<double>, 2, 0, 1> w, CArray<long long, 2, 1, 1> _raw_y, CIndexer<2> _ind) {
36       ;
37       CUPY_FOR(i, _ind.size()) {
38         _ind.set(i);
39         Y &y = _raw_y[_ind.get()];
40 
41     int xsize_0=x.shape()[0], ysize_0 = _raw_y.shape()[0], xstride_0=x.strides()[0];
42 int xsize_1=x.shape()[1], ysize_1 = _raw_y.shape()[1], xstride_1=x.strides()[1];
43     int _i = i;
44 int ind_1 = _i % ysize_1 - 1; _i /= ysize_1;
45 int ind_0 = _i - 1;
46     // don't use a CArray for indexing (faster to deal with indexing ourselves)
47     const unsigned char* data = (const unsigned char*)&x[0];
48     int iws = 0;
49     W sum = (W)0;
50 
51     for (int iw_0 = 0; iw_0 < 3; iw_0++)
52     {
53         int ix_0 = ind_0 + iw_0;
54 
55         if (ix_0 < 0) {
56             ix_0 = - 1 -ix_0;
57         }
58         ix_0 %= xsize_0 * 2;
59         ix_0 = min(ix_0, 2 * xsize_0 - 1 - ix_0);
60         ix_0 *= xstride_0;
61 
62 
63     for (int iw_1 = 0; iw_1 < 3; iw_1++)
64     {
65         int ix_1 = ind_1 + iw_1;
66 
67         if (ix_1 < 0) {
68             ix_1 = - 1 -ix_1;
69         }
70         ix_1 %= xsize_1 * 2;
71         ix_1 = min(ix_1, 2 * xsize_1 - 1 - ix_1);
72         ix_1 *= xstride_1;
73 
74         // inner-most loop
75         W wval = w[iws];
76 if (nonzero(wval)) {
77             sum += cast<W>((*(X*)&data[ix_0 + ix_1])) * wval;
78         }
79         iws++;
80     }}
81     y = cast<Y>(sum);
82     ;
83       }
84       ;
85     }
86 
-----
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in _jitify_prep(source, options, cu_path)
    245     try:
--> 246         name, options, headers, include_names = jitify(
    247             source, options, _jitify_header_source_map)

cupy/cuda/jitify.pyx in cupy.cuda.jitify.jitify()

cupy/cuda/jitify.pyx in cupy.cuda.jitify.jitify()

RuntimeError: Runtime compilation failed

During handling of the above exception, another exception occurred:

JitifyException                           Traceback (most recent call last)
<ipython-input-37-0806ad4d1efe> in <module>
----> 1 grad = signal.convolve2d(ascentcp, scharr, boundary='symm', mode='same')

~/Scripting/anaconda3/lib/python3.8/site-packages/cupyx/scipy/signal/signaltools.py in convolve2d(in1, in2, mode, boundary, fillvalue)
    343     .. seealso:: :func:`scipy.signal.convolve2d`
    344     """
--> 345     return _correlate2d(in1, in2, mode, boundary, fillvalue, True)
    346 
    347 

~/Scripting/anaconda3/lib/python3.8/site-packages/cupyx/scipy/signal/signaltools.py in _correlate2d(in1, in2, mode, boundary, fillvalue, convolution)
    409     if quick_out is not None:
    410         return quick_out
--> 411     return _st_core._direct_correlate(in1, in2, mode, in1.dtype, convolution,
    412                                       boundary, fillvalue, not convolution)
    413 

~/Scripting/anaconda3/lib/python3.8/site-packages/cupyx/scipy/signal/_signaltools_core.py in _direct_correlate(in1, in2, mode, output, convolution, boundary, fillvalue, shift)
     73     in2 = _reverse(in2) if convolution else in2.conj()
     74     if not swapped_inputs or convolution:
---> 75         kernel(in1, in2, output)
     76     elif output.dtype.kind != 'c':
     77         # Avoids one array copy

cupy/_core/_kernel.pyx in cupy._core._kernel.ElementwiseKernel.__call__()

cupy/_core/_kernel.pyx in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel()

cupy/_util.pyx in cupy._util.memoize.decorator.ret()

cupy/_core/_kernel.pyx in cupy._core._kernel._get_elementwise_kernel()

cupy/_core/_kernel.pyx in cupy._core._kernel._get_simple_elementwise_kernel()

cupy/_core/core.pyx in cupy._core.core.compile_with_cache()

~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, jitify)
    458             name_expressions, log_stream, cache_in_memory)
    459     else:
--> 460         return _compile_with_cache_cuda(
    461             source, options, arch, cache_dir, extra_source, backend,
    462             enable_cooperative_groups, name_expressions, log_stream,

~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory, jitify)
    536     if backend == 'nvrtc':
    537         cu_name = '' if cache_in_memory else name + '.cu'
--> 538         ptx, mapping = compile_using_nvrtc(
    539             source, options, arch, cu_name, name_expressions,
    540             log_stream, cache_in_memory, jitify)

~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_using_nvrtc(source, options, arch, filename, name_expressions, log_stream, cache_in_memory, jitify)
    296                 cu_file.write(source)
    297 
--> 298             return _compile(source, options, cu_path,
    299                             name_expressions, log_stream, jitify)
    300     else:

~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile(source, options, cu_path, name_expressions, log_stream, jitify)
    265 
    266         if jitify:
--> 267             options, headers, include_names = _jitify_prep(
    268                 source, options, cu_path)
    269         else:

~/Scripting/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py in _jitify_prep(source, options, cu_path)
    252         if dump:
    253             cex.dump(sys.stderr)
--> 254         raise JitifyException(str(cex))
    255     assert name == cu_path
    256 

JitifyException: Runtime compilation failed
------------------------------------------------------------------------------------------
```

To produce this error report I had the following environment variables.  %env in python: 

```
 'CUPY_CUDA_COMPILE_WITH_DEBUG': '1',
 'CUPY_DUMP_CUDA_SOURCE_ON_ERROR': '1',
 'CUPY_CACHE_SAVE_CUDA_SOURCE': '1',
```

   Thank you for reading. 

### To Reproduce

```py
from cupyx.scipy import signal
from scipy import misc
import cupy as cp

ascent = misc.ascent()
scharr = cp.array([[ -3-3j, 0-10j,  +3 -3j],
                   [-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
ascentcp = cp.array(ascent)
grad = signal.convolve2d(ascentcp, scharr, boundary='symm', mode='same')
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

my cupy config settings: 

```
{40}>> cp.show_config()
OS                           : Linux-4.18.0-240.22.1.el8_3.x86_64-x86_64-with-glibc2.10
Python Version               : 3.8.5
CuPy Version                 : 9.5.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.5
SciPy Version                : 1.6.2
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.23
CUDA Root                    : /usr/local/cuda-11.2
nvcc PATH                    : /usr/local/cuda-11.2/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11020
cuBLAS Version               : (available)
cuFFT Version                : 10400
cuRAND Version               : 10203
cuSOLVER Version             : (11, 0, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8201
cuDNN Version                : 8201
NCCL Build Version           : 21003
NCCL Runtime Version         : 21104
cuTENSOR Version             : 10303
cuSPARSELt Build Version     : 100
Device 0 Name                : GeForce RTX 2060 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

--------------------------------------

### Additional Information

To produce this error report I had the following environment variables.  %env in python: 

```
 'CUPY_CUDA_COMPILE_WITH_DEBUG': '1',
 'CUPY_DUMP_CUDA_SOURCE_ON_ERROR': '1',
 'CUPY_CACHE_SAVE_CUDA_SOURCE': '1',
 ```

  regarding the installation I did it with the following command : 

```
    {43}>> %hist -g conda-forge
...
182/413: !bin/conda install -c nvidia -c rapidsai -c conda-forge cupy cudatoolkit=11.2 cudnn cutensor nccl
```

  I am a newby on CUDA. I have been learning and using Cupy for some time now. I was going through cupyx.scipy modules and functions when I came across this issue. I would love to have enough knowledge to have a go myself at fixing this issue, but I don't even know where to start even though I know Python and a bit of C++. That "Jitify" looks intimidating to me as  I don't know anything about it.
   Any guidance / tutorials would be appreciated. This is my 1st issue found and reported.
  
   I hope you find all the information needed.  Thank you for reading.

### LINKED ISSUE #6047: cupyx.scipy.signal.convolve2d: integer overflow when using mixed dtypes
### Description

CuPy's `convolve2d` behaves differently from SciPy's `convolve2d` when using two arrays with different dtypes. When using integers with different precision, CuPy's `convolve2d` leads to integer overflow.

#### SciPy's behaviour

If the precisions of the convolved integer arrays are different, the higest precision is used to prevent integer overflow.

```py
# scipy's convolve2d
import numpy as np
from scipy.signal import convolve2d
a = np.array([[257]], dtype="uint64")
b = np.array([[1]], dtype="uint8")
result = convolve2d(a, b, mode="same")
print(result, result.dtype)
# [[257]] uint64 : expected result
```

#### CuPy's behaviour

If the precisions of the convolved integer arrays are different, the calculation is limited by the lowest precision and integer overflow occurs. The dtype of the resulting array is that of the first array passed to `convolve2d`, but the overflow occurs before: the error is present even when the first array has the higher precision.

```py
# cupy's convolve2d
import cupy as cp
from cupyx.scipy.signal import convolve2d
a = cp.asarray(a) # defined above
b = cp.asarray(b)
result = convolve2d(a, b, mode="same")
print(result, result.dtype)
# [[1]] uint64 : correct dtype, but uint8 integer overflow
# reversed convolution
result = convolve2d(b, a, mode="same")
print(result, result.dtype)
# [[1]] uint8 : wrong dtype and uint8 integer overflow
```

#### Expected behaviour

The expected behaviour is SciPy's behaviour: when convolving arrays of mixed dtypes, the calculations should be performed on the highest-precision dtype.

### To Reproduce

```py
# scipy's convolve2d
import numpy as np
from scipy.signal import convolve2d
a = np.array([[257]], dtype="uint64")
b = np.array([[1]], dtype="uint8")
result = convolve2d(a, b, mode="same")
print(result, result.dtype)
# [[257]] uint64 : expected result

# cupy's convolve2d
import cupy as cp
from cupyx.scipy.signal import convolve2d
a = cp.asarray(a)
b = cp.asarray(b)
result = convolve2d(a, b, mode="same")
print(result, result.dtype)
# [[1]] uint64 : correct dtype, but uint8 integer overflow
# reversed convolution
result = convolve2d(b, a, mode="same")
print(result, result.dtype)
# [[1]] uint8 : wrong dtype and uint8 integer overflow
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Windows-10-10.0.19041-SP0
Python Version               : 3.7.4
CuPy Version                 : 9.5.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.2
SciPy Version                : 1.7.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.13
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc.EXE
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11020
cuBLAS Version               : (available)
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : GeForce MX150
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leofang**
Close #5989. Close #6047.

### CODE REVIEW

**Comment by leofang** [comment]
@kmaehashi You might want to prioritize this PR now that it fixes two bugs...😅

**Comment by leofang** [comment]
Looks like #6047 is only partially fixed by this PR. Investigating...

**Comment by leofang** [comment]
> Looks like #6047 is only partially fixed by this PR. Investigating...

Discussed with @emcastillo and worked around in 4f84dba.

**Review by emcastillo — COMMENTED** [review]
Can we add tests that reproduce the original PR behavior?
thanks!

**Comment by leofang** [comment]
Sorry, Emilio, didn't have time to add tests, let me revisit this later this week 😅

**Pull request merged**
