### PR TITLE
Add sosfilt to cupyx.scipy.signal 

### PR DESCRIPTION
**Pull request by andfoy**
See https://github.com/cupy/cupy/issues/7403

This implementation will contemplate the performance against the following baselines:

1. N sequential calls to `lfilter`, where each one of them computes each second order section.
3. N calls to convolve1d  to compute the FIR part and a extension of the `apply_iir` kernel to chained second order sections (the kernel would compute the IIR part from the FIR output in a chained fashion).
4. A generalization of `apply_iir` where the function would compute both FIR and IIR sections sequentially one after another with custom kernels for both parts.

If the third option improves the performance, then it would be possible to think about improving `lfilter` this route.

### CODE REVIEW

**Comment by andfoy** [comment]
## Baseline: N-calls to sosfilt

The performance exceeds CPU, however, the gains are below `lfilter` https://github.com/cupy/cupy/pull/7522#issuecomment-1512248298

<details>
<summary>Benchmark script</summary>

```python
from itertools import product

import cupy as cp
import numpy as np
from cupy import testing
from cupyx.profiler import benchmark

from cupyx.scipy.signal import lfilter
from scipy.signal import sosfilt

from tqdm import tqdm


def sosfilt_gpu(sos, x):
    n_sections = sos.shape[0]
    out = x
    for i in range(n_sections):
        b = sos[i, :3]
        a = sos[i, 3:]
        out = lfilter(b, a, out)
    return out


input_sizes = [5, 10, 100, 1000, 5000, 10000, 50000, 100000, 200000, 500000,
               700000, 1_000_000, 2_000_000, 10_000_000]
modules = [(cp, sosfilt_gpu, 'CuPy'), (np, sosfilt, 'SciPy')]
kwargs = [('sections', [1, 2, 4, 6, 10])]
# kwargs = [('extrapolate', [True])]
kwargs = list(product(*[list(product([x[0]], x[1])) for x in kwargs]))
measurement = {}


def gather_time(prof):
    cpu_time = prof.cpu_times.mean() * 1000
    gpu_time = prof.gpu_times.mean() * 1000
    return max(cpu_time, gpu_time)


def input_creation(xp, fn, size, sections=1, **kwargs):
    size = size[0]
    signs = xp.tile(xp.asarray([1, -1], dtype=xp.float32),
                    int(2 * np.ceil(size / 4)))
    x = xp.arange(3, size + 3, dtype=xp.float32) * signs[:size]
    sos = testing.shaped_random((sections, 6), xp, dtype=xp.float32, scale=0.2)
    sos[:, 3] = 1
    return fn, (sos, x)


def closure(fn, sig):
    return fn(*sig)


for kwarg_comb in kwargs:
    kwarg_measurement = measurement.get(kwarg_comb, {})
    measurement[kwarg_comb] = kwarg_measurement
    kwarg_comb = dict(kwarg_comb)
    for size in tqdm(input_sizes):
        size_measurement = kwarg_measurement.get(size, {})
        kwarg_measurement[size] = size_measurement
        for xp, cls, _id in modules:
            b, x = input_creation(xp, cls, (size,), **kwarg_comb)
            prof = benchmark(closure, (b, x), n_repeat=100)
            size_measurement[_id] = gather_time(prof)


lines = []
for kwarg_comb in kwargs:
    kwarg_line = ', '.join([f'{x}={y}' for x, y in kwarg_comb])
    lines.append(f'### `{kwarg_line}`\n')
    lines.append('| Size | CuPy (ms) | SciPy (ms) | Speedup |')
    lines.append('|:----:|:---------:|:----------:|:-------:|')
    kwarg_measurement = measurement[kwarg_comb]
    for size in input_sizes:
        comp = f'{size}'
        size_measurement = kwarg_measurement[size]
        times = []
        for _, _, _id in modules:
            time = size_measurement[_id]
            times.append(time)
            time_info = f'{time:3f}'
            comp = f'{comp} | {time_info}'
        speedup = times[1] / times[0]
        comp = f'{comp} | {speedup:3f}'
        lines.append(f'| {comp} |')
    lines.append('\n')


print('\n'.join(lines))

```

</details>

### `sections=1`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.613755 | 0.046468 | 0.075711 |
| 10 | 0.620122 | 0.046223 | 0.074539 |
| 100 | 0.617342 | 0.046645 | 0.075558 |
| 1000 | 0.640009 | 0.052966 | 0.082758 |
| 5000 | 0.634863 | 0.076890 | 0.121113 |
| 10000 | 0.638840 | 0.107466 | 0.168220 |
| 50000 | 0.675243 | 0.365712 | 0.541600 |
| 100000 | 0.751063 | 0.651487 | 0.867420 |
| 200000 | 0.823949 | 1.280575 | 1.554192 |
| 500000 | 1.138552 | 3.122153 | 2.742215 |
| 700000 | 1.172018 | 4.337553 | 3.700928 |
| 1000000 | 1.424714 | 6.169439 | 4.330299 |
| 2000000 | 2.061368 | 12.237209 | 5.936450 |
| 10000000 | 8.833731 | 65.695496 | 7.436892 |


### `sections=2`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 1.065471 | 0.044531 | 0.041794 |
| 10 | 1.036196 | 0.044476 | 0.042922 |
| 100 | 1.050123 | 0.045676 | 0.043496 |
| 1000 | 1.062751 | 0.051676 | 0.048625 |
| 5000 | 1.087722 | 0.083210 | 0.076499 |
| 10000 | 1.084115 | 0.107135 | 0.098822 |
| 50000 | 1.122207 | 0.349261 | 0.311227 |
| 100000 | 1.164118 | 0.651050 | 0.559264 |
| 200000 | 1.251127 | 1.284136 | 1.026384 |
| 500000 | 1.689196 | 3.138663 | 1.858082 |
| 700000 | 1.664792 | 4.364201 | 2.621469 |
| 1000000 | 2.125529 | 6.195132 | 2.914630 |
| 2000000 | 3.766088 | 12.280270 | 3.260750 |
| 10000000 | 17.685374 | 68.228049 | 3.857880 |


### `sections=4`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 1.935750 | 0.044777 | 0.023132 |
| 10 | 1.974398 | 0.047271 | 0.023942 |
| 100 | 1.901800 | 0.045955 | 0.024164 |
| 1000 | 1.907960 | 0.053572 | 0.028078 |
| 5000 | 1.986670 | 0.085149 | 0.042860 |
| 10000 | 1.983019 | 0.123278 | 0.062167 |
| 50000 | 2.048754 | 0.489008 | 0.238686 |
| 100000 | 2.226545 | 0.961143 | 0.431675 |
| 200000 | 2.106406 | 1.617995 | 0.768130 |
| 500000 | 2.454835 | 3.931815 | 1.601661 |
| 700000 | 3.121466 | 5.552204 | 1.778717 |
| 1000000 | 4.219894 | 8.113491 | 1.922677 |
| 2000000 | 8.533369 | 16.264552 | 1.905994 |
| 10000000 | 38.543931 | 87.759898 | 2.276880 |


### `sections=6`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 2.870826 | 0.045845 | 0.015969 |
| 10 | 2.901599 | 0.046496 | 0.016024 |
| 100 | 2.870399 | 0.047094 | 0.016407 |
| 1000 | 2.890838 | 0.058419 | 0.020208 |
| 5000 | 3.020943 | 0.106296 | 0.035186 |
| 10000 | 3.034364 | 0.165602 | 0.054576 |
| 50000 | 3.058810 | 0.633834 | 0.207216 |
| 100000 | 3.047574 | 1.336216 | 0.438452 |
| 200000 | 3.099589 | 2.425581 | 0.782549 |
| 500000 | 3.604059 | 5.983788 | 1.660292 |
| 700000 | 4.627693 | 9.306127 | 2.010964 |
| 1000000 | 7.540762 | 11.869955 | 1.574106 |
| 2000000 | 11.435028 | 23.679072 | 2.070749 |
| 10000000 | 54.193005 | 122.996925 | 2.269609 |


### `sections=10`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 4.690346 | 0.045992 | 0.009806 |
| 10 | 4.684124 | 0.045213 | 0.009652 |
| 100 | 4.673375 | 0.047721 | 0.010211 |
| 1000 | 4.780533 | 0.068116 | 0.014249 |
| 5000 | 4.938676 | 0.154203 | 0.031224 |
| 10000 | 4.919248 | 0.260260 | 0.052906 |
| 50000 | 4.935578 | 1.112485 | 0.225401 |
| 100000 | 4.960301 | 2.169453 | 0.437363 |
| 200000 | 5.017229 | 4.325484 | 0.862126 |
| 500000 | 5.872927 | 10.707101 | 1.823128 |
| 700000 | 7.614751 | 14.957175 | 1.964237 |
| 1000000 | 10.304004 | 21.336567 | 2.070706 |
| 2000000 | 19.115013 | 42.520007 | 2.224430 |
| 10000000 | 91.075582 | 217.807334 | 2.391501 |

**Comment by andfoy** [comment]
## Baseline: N calls to `convolve1d` + `apply_iir_sos`

If the IIR computation is moved to a sequence of chained calls over a single copy, then the runtime performance improves at least by 1.5x w.r.t https://github.com/cupy/cupy/pull/7528#issuecomment-1518440099

<details>
<summary>Benchmark script</summary>

```python
from itertools import product

import cupy as cp
import numpy as np
from cupy import testing
from cupyx.profiler import benchmark

from cupyx.scipy.signal import sosfilt as sosfilt_gpu
from scipy.signal import sosfilt as sosfilt_cpu

from tqdm import tqdm


input_sizes = [5, 10, 100, 1000, 5000, 10000, 50000, 100000, 200000, 500000,
               700000, 1_000_000, 2_000_000, 10_000_000]
modules = [(cp, sosfilt_gpu, 'CuPy'), (np, sosfilt_cpu, 'SciPy')]
kwargs = [('sections', [1, 2, 4, 6, 10])]
# kwargs = [('extrapolate', [True])]
kwargs = list(product(*[list(product([x[0]], x[1])) for x in kwargs]))
measurement = {}


def gather_time(prof):
    cpu_time = prof.cpu_times.mean() * 1000
    gpu_time = prof.gpu_times.mean() * 1000
    return max(cpu_time, gpu_time)


def input_creation(xp, fn, size, sections=1, **kwargs):
    size = size[0]
    signs = xp.tile(xp.asarray([1, -1], dtype=xp.float32),
                    int(2 * np.ceil(size / 4)))
    x = xp.arange(3, size + 3, dtype=xp.float32) * signs[:size]
    sos = testing.shaped_random((sections, 6), xp, dtype=xp.float32, scale=0.2)
    sos[:, 3] = 1
    return fn, (sos, x)


def closure(fn, sig):
    return fn(*sig)


for kwarg_comb in kwargs:
    kwarg_measurement = measurement.get(kwarg_comb, {})
    measurement[kwarg_comb] = kwarg_measurement
    kwarg_comb = dict(kwarg_comb)
    for size in tqdm(input_sizes):
        size_measurement = kwarg_measurement.get(size, {})
        kwarg_measurement[size] = size_measurement
        for xp, cls, _id in modules:
            b, x = input_creation(xp, cls, (size,), **kwarg_comb)
            prof = benchmark(closure, (b, x), n_repeat=100)
            size_measurement[_id] = gather_time(prof)


lines = []
for kwarg_comb in kwargs:
    kwarg_line = ', '.join([f'{x}={y}' for x, y in kwarg_comb])
    lines.append(f'### `{kwarg_line}`\n')
    lines.append('| Size | CuPy (ms) | SciPy (ms) | Speedup |')
    lines.append('|:----:|:---------:|:----------:|:-------:|')
    kwarg_measurement = measurement[kwarg_comb]
    for size in input_sizes:
        comp = f'{size}'
        size_measurement = kwarg_measurement[size]
        times = []
        for _, _, _id in modules:
            time = size_measurement[_id]
            times.append(time)
            time_info = f'{time:3f}'
            comp = f'{comp} | {time_info}'
        speedup = times[1] / times[0]
        comp = f'{comp} | {speedup:3f}'
        lines.append(f'| {comp} |')
    lines.append('\n')


print('\n'.join(lines))

```

</details>

### `sections=1`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.311368 | 0.045333 | 0.145594 |
| 10 | 0.282300 | 0.045242 | 0.160263 |
| 100 | 0.278241 | 0.045471 | 0.163425 |
| 1000 | 0.281128 | 0.051562 | 0.183412 |
| 5000 | 0.342120 | 0.085108 | 0.248767 |
| 10000 | 0.328567 | 0.106078 | 0.322850 |
| 50000 | 0.344969 | 0.356782 | 1.034245 |
| 100000 | 0.374732 | 0.676821 | 1.806145 |
| 200000 | 0.473316 | 1.272387 | 2.688243 |
| 500000 | 0.690786 | 3.107291 | 4.498194 |
| 700000 | 0.861683 | 4.335956 | 5.031960 |
| 1000000 | 1.150433 | 6.161273 | 5.355611 |
| 2000000 | 2.250222 | 12.236341 | 5.437836 |
| 10000000 | 8.028845 | 65.478584 | 8.155417 |


### `sections=2`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.400924 | 0.043962 | 0.109652 |
| 10 | 0.364117 | 0.043895 | 0.120552 |
| 100 | 0.383391 | 0.044259 | 0.115441 |
| 1000 | 0.376700 | 0.050756 | 0.134740 |
| 5000 | 0.462769 | 0.075383 | 0.162896 |
| 10000 | 0.476769 | 0.106018 | 0.222367 |
| 50000 | 0.466864 | 0.348748 | 0.747002 |
| 100000 | 0.564069 | 0.649556 | 1.151553 |
| 200000 | 0.690871 | 1.293010 | 1.871564 |
| 500000 | 1.182515 | 3.123621 | 2.641507 |
| 700000 | 1.134116 | 4.341579 | 3.828160 |
| 1000000 | 1.544677 | 6.175659 | 3.998025 |
| 2000000 | 3.151248 | 12.246761 | 3.886320 |
| 10000000 | 14.812347 | 65.774131 | 4.440494 |


### `sections=4`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.572274 | 0.043598 | 0.076184 |
| 10 | 0.538310 | 0.043867 | 0.081490 |
| 100 | 0.557416 | 0.044972 | 0.080680 |
| 1000 | 0.555996 | 0.052081 | 0.093672 |
| 5000 | 0.724999 | 0.082959 | 0.114427 |
| 10000 | 0.713476 | 0.122348 | 0.171481 |
| 50000 | 0.738369 | 0.433150 | 0.586632 |
| 100000 | 0.893869 | 0.814678 | 0.911406 |
| 200000 | 1.194260 | 1.614218 | 1.351647 |
| 500000 | 1.951754 | 3.954132 | 2.025938 |
| 700000 | 2.073467 | 5.505706 | 2.655314 |
| 1000000 | 2.985464 | 7.799427 | 2.612467 |
| 2000000 | 5.736192 | 15.570588 | 2.714447 |
| 10000000 | 28.527579 | 82.324444 | 2.885784 |


### `sections=6`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.721990 | 0.044035 | 0.060991 |
| 10 | 0.713864 | 0.044254 | 0.061992 |
| 100 | 0.730902 | 0.045070 | 0.061663 |
| 1000 | 0.740987 | 0.056064 | 0.075662 |
| 5000 | 0.986647 | 0.101764 | 0.103141 |
| 10000 | 0.966458 | 0.159737 | 0.165281 |
| 50000 | 1.012628 | 0.613710 | 0.606057 |
| 100000 | 1.231387 | 1.180093 | 0.958345 |
| 200000 | 1.656013 | 2.343440 | 1.415110 |
| 500000 | 2.502631 | 5.772539 | 2.306588 |
| 700000 | 3.084735 | 8.061419 | 2.613326 |
| 1000000 | 4.296123 | 11.461397 | 2.667847 |
| 2000000 | 8.506464 | 22.852972 | 2.686542 |
| 10000000 | 42.336378 | 118.526999 | 2.799649 |


### `sections=10`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 1.070869 | 0.044075 | 0.041158 |
| 10 | 1.072351 | 0.044257 | 0.041271 |
| 100 | 1.068708 | 0.046331 | 0.043352 |
| 1000 | 1.116726 | 0.065716 | 0.058847 |
| 5000 | 1.478086 | 0.151246 | 0.102325 |
| 10000 | 1.469926 | 0.257050 | 0.174873 |
| 50000 | 1.533305 | 1.105679 | 0.721108 |
| 100000 | 1.888201 | 2.163436 | 1.145766 |
| 200000 | 2.544839 | 4.287434 | 1.684757 |
| 500000 | 4.063693 | 10.677338 | 2.627496 |
| 700000 | 5.032404 | 14.923838 | 2.965549 |
| 1000000 | 7.138145 | 21.287578 | 2.982228 |
| 2000000 | 14.084321 | 42.392421 | 3.009902 |
| 10000000 | 69.964918 | 216.701016 | 3.097281 |

**Comment by andfoy** [comment]
This is a refinement of https://github.com/cupy/cupy/pull/7528#issuecomment-1526651192, where an additional copy is removed, thus improving the performance by at least 1x.

### `sections=1`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.278973 | 0.044522 | 0.159592 |
| 10 | 0.262923 | 0.052144 | 0.198323 |
| 100 | 0.290228 | 0.044606 | 0.153694 |
| 1000 | 0.270645 | 0.050876 | 0.187981 |
| 5000 | 0.314630 | 0.095861 | 0.304677 |
| 10000 | 0.315201 | 0.105647 | 0.335172 |
| 50000 | 0.310386 | 0.347667 | 1.120110 |
| 100000 | 0.373265 | 0.661077 | 1.771066 |
| 200000 | 0.432452 | 1.276550 | 2.951892 |
| 500000 | 0.815245 | 3.106994 | 3.811114 |
| 700000 | 0.839405 | 4.328272 | 5.156358 |
| 1000000 | 1.104483 | 6.166424 | 5.583085 |
| 2000000 | 2.154315 | 12.346971 | 5.731276 |
| 10000000 | 7.070148 | 65.867541 | 9.316289 |


### `sections=2`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.426475 | 0.052455 | 0.122996 |
| 10 | 0.342770 | 0.043584 | 0.127153 |
| 100 | 0.361476 | 0.044295 | 0.122539 |
| 1000 | 0.357182 | 0.050660 | 0.141833 |
| 5000 | 0.441830 | 0.075851 | 0.171675 |
| 10000 | 0.458602 | 0.113514 | 0.247522 |
| 50000 | 0.449796 | 0.347472 | 0.772510 |
| 100000 | 0.549610 | 0.648735 | 1.180355 |
| 200000 | 0.708212 | 1.281150 | 1.808992 |
| 500000 | 1.199334 | 3.127185 | 2.607435 |
| 700000 | 1.483469 | 4.442335 | 2.994558 |
| 1000000 | 1.389007 | 6.194143 | 4.459404 |
| 2000000 | 2.739551 | 12.343107 | 4.505522 |
| 10000000 | 13.428260 | 66.193946 | 4.929451 |


### `sections=4`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.560729 | 0.043205 | 0.077052 |
| 10 | 0.519587 | 0.043548 | 0.083813 |
| 100 | 0.543391 | 0.044384 | 0.081680 |
| 1000 | 0.545468 | 0.052048 | 0.095419 |
| 5000 | 0.727178 | 0.083629 | 0.115005 |
| 10000 | 0.698169 | 0.121570 | 0.174127 |
| 50000 | 0.743518 | 0.430142 | 0.578523 |
| 100000 | 0.898874 | 0.814492 | 0.906125 |
| 200000 | 1.183848 | 1.612642 | 1.362204 |
| 500000 | 1.982284 | 3.958613 | 1.996996 |
| 700000 | 1.946901 | 5.514063 | 2.832226 |
| 1000000 | 2.676215 | 7.962544 | 2.975300 |
| 2000000 | 5.242254 | 15.629235 | 2.981396 |
| 10000000 | 26.319673 | 82.667579 | 3.140904 |


### `sections=6`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.734330 | 0.043825 | 0.059681 |
| 10 | 0.695503 | 0.043821 | 0.063007 |
| 100 | 0.717577 | 0.044901 | 0.062574 |
| 1000 | 0.733202 | 0.055845 | 0.076166 |
| 5000 | 0.979926 | 0.102652 | 0.104755 |
| 10000 | 1.064975 | 0.158492 | 0.148823 |
| 50000 | 0.998484 | 0.612805 | 0.613736 |
| 100000 | 1.238979 | 1.160156 | 0.936381 |
| 200000 | 1.697436 | 2.334486 | 1.375301 |
| 500000 | 2.208302 | 5.774117 | 2.614732 |
| 700000 | 2.957419 | 8.038037 | 2.717923 |
| 1000000 | 3.964853 | 11.560470 | 2.915737 |
| 2000000 | 7.884513 | 22.953585 | 2.911224 |
| 10000000 | 39.281512 | 119.170078 | 3.033745 |


### `sections=10`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 1.076492 | 0.043748 | 0.040640 |
| 10 | 1.165084 | 0.043792 | 0.037587 |
| 100 | 1.070924 | 0.045959 | 0.042915 |
| 1000 | 1.103144 | 0.065803 | 0.059650 |
| 5000 | 1.493642 | 0.151385 | 0.101353 |
| 10000 | 1.469469 | 0.252776 | 0.172019 |
| 50000 | 1.512211 | 1.104334 | 0.730278 |
| 100000 | 1.902534 | 2.162060 | 1.136411 |
| 200000 | 2.606488 | 4.330219 | 1.661323 |
| 500000 | 3.616084 | 10.686919 | 2.955384 |
| 700000 | 4.664653 | 14.923515 | 3.199276 |
| 1000000 | 6.601497 | 21.340109 | 3.232617 |
| 2000000 | 13.295121 | 42.702925 | 3.211925 |
| 10000000 | 65.298195 | 217.897612 | 3.336962 |

**Comment by andfoy** [comment]
## Baseline: Move FIR part to its own kernel + `apply_iir_sos`

If the FIR part is moved to a separate kernel that gets call N times + a sequence of chained IIR calls, the performance improves when compared against https://github.com/cupy/cupy/pull/7528#issuecomment-1531841782. As this baseline has a better performance, it will be the final implementation for this PR

### `sections=1`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.170389 | 0.044727 | 0.262501 |
| 10 | 0.169208 | 0.047014 | 0.277846 |
| 100 | 0.192341 | 0.044978 | 0.233843 |
| 1000 | 0.195692 | 0.050870 | 0.259952 |
| 5000 | 0.216771 | 0.075523 | 0.348401 |
| 10000 | 0.209244 | 0.133468 | 0.637861 |
| 50000 | 0.225093 | 0.354239 | 1.573742 |
| 100000 | 0.257784 | 0.668677 | 2.593940 |
| 200000 | 0.348252 | 1.276932 | 3.666696 |
| 500000 | 0.638395 | 3.166065 | 4.959414 |
| 700000 | 0.835493 | 4.408228 | 5.276199 |
| 1000000 | 1.020653 | 6.281173 | 6.154074 |
| 2000000 | 1.477582 | 12.266964 | 8.302052 |
| 10000000 | 6.935073 | 67.293195 | 9.703315 |


### `sections=2`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.200730 | 0.042268 | 0.210572 |
| 10 | 0.219881 | 0.043234 | 0.196622 |
| 100 | 0.195048 | 0.043664 | 0.223862 |
| 1000 | 0.200497 | 0.049770 | 0.248233 |
| 5000 | 0.278174 | 0.094069 | 0.338165 |
| 10000 | 0.279589 | 0.117232 | 0.419303 |
| 50000 | 0.287119 | 0.346787 | 1.207813 |
| 100000 | 0.368062 | 0.990369 | 2.690767 |
| 200000 | 0.558698 | 1.291190 | 2.311070 |
| 500000 | 1.133764 | 3.122468 | 2.754071 |
| 700000 | 1.063892 | 4.379839 | 4.116806 |
| 1000000 | 1.404220 | 6.185336 | 4.404820 |
| 2000000 | 2.751146 | 12.813310 | 4.657445 |
| 10000000 | 13.385394 | 66.609809 | 4.976305 |


### `sections=4`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.270837 | 0.050533 | 0.186580 |
| 10 | 0.250309 | 0.043171 | 0.172472 |
| 100 | 0.244953 | 0.044049 | 0.179828 |
| 1000 | 0.256536 | 0.062437 | 0.243384 |
| 5000 | 0.394746 | 0.082858 | 0.209902 |
| 10000 | 0.389985 | 0.121542 | 0.311658 |
| 50000 | 0.437553 | 0.430161 | 0.983107 |
| 100000 | 0.582747 | 0.813922 | 1.396700 |
| 200000 | 0.867492 | 1.591187 | 1.834237 |
| 500000 | 1.793600 | 4.005476 | 2.233205 |
| 700000 | 1.923982 | 5.514607 | 2.866246 |
| 1000000 | 2.771033 | 7.840812 | 2.829563 |
| 2000000 | 5.324764 | 15.631729 | 2.935666 |
| 10000000 | 26.325522 | 82.591003 | 3.137298 |


### `sections=6`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.297529 | 0.072821 | 0.244753 |
| 10 | 0.296886 | 0.043029 | 0.144934 |
| 100 | 0.288726 | 0.044144 | 0.152893 |
| 1000 | 0.311220 | 0.055238 | 0.177489 |
| 5000 | 0.508876 | 0.101683 | 0.199819 |
| 10000 | 0.512517 | 0.158646 | 0.309542 |
| 50000 | 0.571860 | 0.612795 | 1.071581 |
| 100000 | 0.758603 | 1.187687 | 1.565625 |
| 200000 | 1.217810 | 2.342357 | 1.923417 |
| 500000 | 2.044067 | 5.776625 | 2.826045 |
| 700000 | 2.841137 | 8.046500 | 2.832140 |
| 1000000 | 4.025964 | 11.487570 | 2.853372 |
| 2000000 | 7.867505 | 22.867414 | 2.906565 |
| 10000000 | 39.354475 | 119.153025 | 3.027687 |


### `sections=10`

| Size | CuPy (ms) | SciPy (ms) | Speedup |
|:----:|:---------:|:----------:|:-------:|
| 5 | 0.426592 | 0.051399 | 0.120488 |
| 10 | 0.380786 | 0.043236 | 0.113544 |
| 100 | 0.411907 | 0.045215 | 0.109771 |
| 1000 | 0.415419 | 0.065337 | 0.157281 |
| 5000 | 0.770338 | 0.150608 | 0.195509 |
| 10000 | 0.741645 | 0.256332 | 0.345626 |
| 50000 | 0.818326 | 1.114783 | 1.362273 |
| 100000 | 0.977224 | 2.200256 | 2.251537 |
| 200000 | 1.500158 | 4.343576 | 2.895413 |
| 500000 | 3.412556 | 10.736098 | 3.146058 |
| 700000 | 4.694688 | 14.877430 | 3.168992 |
| 1000000 | 6.588034 | 21.357774 | 3.241904 |
| 2000000 | 13.313125 | 42.618586 | 3.201246 |
| 10000000 | 65.239440 | 217.407982 | 3.332462 |

**Comment by andfoy** [comment]
Not related, the ReadTheDocs issue is caused by https://github.com/readthedocs/readthedocs.org/issues/10290

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
I'll merge this soon after the healthy CIs finish.

**Comment by takagi** [comment]
Thanks, @andfoy!

**Pull request merged**
