### PR TITLE
Add CI for CUDA 12.0

### PR DESCRIPTION
**Pull request by kmaehashi**
cuda120 tests:
* https://ci.preferred.jp/cupy.linux.cuda120/120643/
* https://ci.preferred.jp/cupy.linux.cuda120.multi/120644/
* https://ci.preferred.jp/cupy.win.cuda120/120645/

### CODE REVIEW

**Comment by kmaehashi** [comment]
cuDNN for CUDA 12 is not available yet (cuDNN for CUDA 11 didn't run on 12). Maybe we will ship the initial `cupy-cuda12x` package with cuDNN disabled.

**Comment by takagi** [comment]
Seems cupyx.linalg.invh does not raise in this test:
https://github.com/cupy/cupy/blob/e352abb89d098c12f1e9965427d0530e8ab4d3b0/tests/cupyx_tests/linalg_tests/test_solve.py#L57

**Comment by takagi** [comment]
Test failures other than invh:
```
05:12:18.298485 STDOUT 1594] | FAILED install_tests/test_build.py::TestCheckVersion::test_check_cudnn_version
05:12:18.298538 STDOUT 1594] | FAILED install_tests/test_universal_pkg/test_setup.py::test_get_cuda_version
```

**Comment by kmaehashi** [comment]
/pass

and:

* https://ci.preferred.jp/cupy.linux.cuda120/120843/
* https://ci.preferred.jp/cupy.win.cuda120/120844/

**Comment by kmaehashi** [comment]
Test passed, I think it's ok to merge

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
