### PR TITLE
Fix #1021

### LINKED ISSUE #1021: When `input_num` is given and the function returns values, it fails
```
@cupy.fuse(input_num=0)
def f(x):
    return x

a = cupy.array([1], 'f')
print(f(a))
```
This code causes an error even with #1020.
```
  File "cupy/core/elementwise.pxi", line 550, in cupy.core.core.ElementwiseKernel.__call__
    raise TypeError('Wrong number of arguments for %s' % self.name)
TypeError: Wrong number of arguments for f
```
In this code, the argument `x` is treated as output variable for the ElementwiseKernel which `fuse` created. And because this function returns a variable, it has another output variable. So the kernel has two output variables. To call ElementwiseKernel, a user need to give no output variable or all output variables, but in this code the user give only one variable `a`.

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks for the PR!
Could you please briefly describe what was wrong and how it was fixed?
Also, is it possible to add test case for this case?

**Comment by okuta** [comment]
@asi1024 Cloud you add test?

**Comment by asi1024** [comment]
Some bugs still exist.  I will fix it as soon as possible.

**Comment by asi1024** [comment]
I made another PR #1167. This PR removes `input_num` from the feature and resolves this problem.

**Pull request closed without merging**
