### PR TITLE
More support `__cuda_array_interface__`

### PR DESCRIPTION
**Pull request by okuta**
ElementwiseKernel and ReductionKernel accept `__cuda_array_interface__` array by this PR.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
I fixed.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
