### PR TITLE
Fix fusion tests for HIP

### PR DESCRIPTION
**Pull request by emcastillo**
Merge after #4485 
changes are those of commit https://github.com/cupy/cupy/commit/21fc6c83805d9d62ef721f080d93b9ead29025a1

### CODE REVIEW

**Review by leofang — CHANGES_REQUESTED** [review]
Could you revert the changes in these files?
- `cupy_backends/hip/cupy_hip.h`
- `tests/cupy_tests/core_tests/fusion_tests/test_example.py`

**Comment by emcastillo** [comment]
Sorry, I can't see what is wrong with `tests/cupy_tests/core_tests/fusion_tests/test_example.py`
The test needs to be skipped

**Comment by leofang** [comment]
> Sorry, I can't see what is wrong with `tests/cupy_tests/core_tests/fusion_tests/test_example.py`
> The test needs to be skipped

Why? I thought you already made fusion work?

**Comment by emcastillo** [comment]
HIP does not support cooperative groups for doing inter-block barriers, so in some fusion cases it will fail.
The example relies precisely on that :(

**Comment by leofang** [comment]
Ohhh OK. I missed that, thanks. So do we want to raise in fusion when cooperative group is required?

**Comment by emcastillo** [comment]
That's what we do!
https://github.com/cupy/cupy/blob/master/cupy/cuda/compiler.py#L414

**Comment by leofang** [comment]
...Right...I really should get some more sleep 😧😵🥱

**Comment by emcastillo** [comment]
I think that just showing some random cuda related API message is not helpful at all for end users, so we have to catch it in the fusion side and raise a more friendly user related error.

**Comment by leofang** [comment]
@emcastillo Could you merge or rebase with master?

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
LGTM!

**Pull request merged**
