### PR TITLE
Use `intptr_t` for cuSOLVER  handles

### LINKED ISSUE #2716: Use `intptr_t` instead of `size_t ` for handle types
Related: #1913

Handles are pointers. `intptr_t` should be used as a representative type.

* [ ] cublas
* [ ] cusolver  #2718
* [ ] cusparse
* [ ] cudnn

### PR DESCRIPTION
**Pull request by niboshi**
A part of #2716

Other types should be fixed, too (like `stream` and `devInfo`), but this PR only fixes handles.

### CODE REVIEW

**Comment by niboshi** [comment]
I think it's rather better to define the following way:
```py
ctypedef void* cusolverDnHandle_t 'cusolverDnHandle_t`
ctypedef void* cusolverSpHandle_t 'cusolverSpHandle_t`

ctypedef intptr_t DnHandle
ctypedef intptr_t SpHandle
```
That way,
* No confusion between C and Python types. Previously, `Handle` looked like a Python type (due to naming convention), but was actually a C type.
* Python types have distinct names for the two types of handles. Previously a single type `size_t` (or `intptr_t`) represented both types in Python code.

**Comment by leofang** [comment]
Let me chip in one quick thought: the proposed C types look fine, but it could be possible that without lifting the 79 characters/line limit, you might end up with a whole bunch of line breaking...

**Comment by anaruse** [comment]
I would suggest to split a file `cusolver.pyx` into two files, `cusolverdn.pyx` for cuSolverDn and `cusolversp.pyx` for cuSolverSp.  cuSolverDn and cuSolverSp are essentially different libraries and handles for cuSolverDn and cuSolverSp are never used together. This change might cause some compatibility breakage, but maintenance will be easier.

**Comment by kmaehashi** [comment]
Offline discussions regarding @niboshi's new `ctypedef` proposal:
The proposal itself looks good, but we concluded that this is not worth the cost because (1) lots of fixes across entire `cupy.cuda.*` (like `cupy.cuda.driver.{Stream,Device,...}`, `cupy.cuda.cublas.{DiagType, ...}`) is needed to keep consistency, (2) readability will decrease (although we can improve it by fixing indentation at the same time), (3) they are not user-facing API so it is relatively low-priority refactoring.

Offline discussions regarding @anaruse's proposal:
We decided to continue with one file because (1) We have some Dn/Sp common API like `cusolverGetProperty`, (2) one mapping to one shared library (`libcusolver.so`) seems straight-forward, (3) it is a thin wrapper there's not much problem even if the file is large.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
