### PR TITLE
Use `platform.machine()` instead of `platform.processor()`

### PR DESCRIPTION
**Pull request by kmaehashi**
See #8654. Follows-up #8655.

### CODE REVIEW

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
Yeah I think this is the right move. On Windows (+miniforge) `platform.processor()` does not even do what we think it should do. 
截圖 2024-10-10 下午4 06 55
(Sorry for posting a screenshot; I can't copy/paste text from this VM.)

**Review by jakirkham — APPROVED** [review]
Thanks Kenichi! 🙏

Agree this is a good idea 🙂

**Comment by jakirkham** [comment]
Side note: Looks like the same Windows build that we have seen issues with also ran into issues here

**Comment by jakirkham** [comment]
Hmm...actually the failure here looks legitimate. Though don't think it is related to this change (unless I'm missing something)

```python
=========================== short test summary info ===========================
FAILED cupyx_tests\scipy_tests\interpolate_tests\test_bspline.py::TestBSpline::test_bspline_derivative_jumps[_param_0_{c=[-1, 2, 0, -1], extrapolate=True}] - AssertionError:	
Not equal to tolerance rtol=1e-07, atol=0	
	
x and y nan location mismatch:	
 x: array([-1.206633,  0.363639, -0.413208,       nan])	
 y: array([-1.206633,  0.363639, -0.413208,  0.      ])	
= 1 failed, 101393 passed, 9227 skipped, 677 deselected, 2025 xfailed, 2609 warnings in 3674.17s (1:01:14) =	
------------------------------------------------------------------------------------------
```

**Comment by kmaehashi** [comment]
It's a known flaky one (#7240), so I believe it's unrelated to this PR.

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
