### PR TITLE
Implement environment check to validate NVRTC configuration errors

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR implements warnings to check CUDA configuration errors on user's host.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
Please check travis result.

**Comment by kmaehashi** [comment]
It seems that NVRTC in CUDA 11.1 now `dlopen`s `libnvrtc-builtins.so.11.1` instead of `libnvrtc-builtins.so`, so this kind of mismatch (which this PR intends to detect) won't happen anymore.

**Pull request closed without merging**
