### PR TITLE
Xfail some tests under ROCm/HIP

### PR DESCRIPTION
**Pull request by takagi**
Rel #4132, #4484.

Tests fail on rocm-ci-report but I cannot reproduce them on my local.

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Question: What's the `(ROCm ver, GPU arch)` that you used to test? I feel some bugs only appear on certain combinations, but can't say for certain...

**Comment by takagi** [comment]
```>>> import cupy
>>> cupy.show_config()
OS                      : Linux-5.4.0-58-generic-x86_64-with-glibc2.27
CuPy Version            : 9.0.0b3
NumPy Version           : 1.20.1
SciPy Version           : 1.6.1
Cython Build Version    : 0.29.21
Cython Runtime Version  : 0.29.22
CUDA Root               : /opt/rocm
CUDA Build Version      : 400
CUDA Driver Version     : 321200
CUDA Runtime Version    : 3212
cuBLAS Version          : 23200
cuFFT Version           : 10008966
cuRAND Version          : 201006
cuSOLVER Version        : (3, 10, 0)
cuSPARSE Version        : 21950
NVRTC Version           : (9, 0)
Thrust Version          : 100908
CUB Build Version       : 201005
Jitify Build Version    : None
cuDNN Build Version     : None
cuDNN Version           : None
NCCL Build Version      : 2708
NCCL Runtime Version    : 2708
cuTENSOR Version        : None
Device 0 Name           : Vega 20
Device 0 Arch           : gfx906
Device 1 Name           : Vega 20
Device 1 Arch           : gfx906
Device 2 Name           : Vega 20
Device 2 Arch           : gfx906
Device 3 Name           : Vega 20
Device 3 Arch           : gfx906
Device 4 Name           : Vega 20
Device 4 Arch           : gfx906
Device 5 Name           : Vega 20
Device 5 Arch           : gfx906
Device 6 Name           : Vega 20
Device 6 Arch           : gfx906
Device 7 Name           : Vega 20
Device 7 Arch           : gfx906
```

**Comment by takagi** [comment]
> I cannot reproduce them on my local.

MI100 reproduces it. MI50 doesn't.

**Comment by leofang** [comment]
> > I cannot reproduce them on my local.
> 
> MI100 reproduces it. MI50 doesn't.

Pardon my language, but I think MI100 is fxxked up...See also https://github.com/cupy/cupy/pull/4653#issuecomment-778724972.

**Pull request merged**
