### PR TITLE
Add a few driver/runtime/nvrtc API wrappers

### PR DESCRIPTION
**Pull request by leofang**
- `cudaMallocFromPoolAsync`
- `cudaMemPoolCreate`
- `cudaMemPoolDestroy`
- `cuCtxGetDevice`
- `cuStreamGetCtx`  
- `nvrtcGetNVVM`

### CODE REVIEW

**Comment by leofang** [comment]
Is it OK to backport this PR to v10? I am thinking some of them are useful in our tests but the v11 release is too late for us.

**Comment by kmaehashi** [comment]
> Is it OK to backport this PR to v10? I am thinking some of them are useful in our tests but the v11 release is too late for us.

I think it's OK to backport this one :)

**Comment by leofang** [comment]
Is the Jenkins error related to this PR? I can't see.

**Comment by emcastillo** [comment]
```
11:59:19 E   AttributeError: module 'cupy_backends.cuda.api.runtime' has no attribute 'cudaDevAttrMemoryPoolsSupported'
11:59:19         __module__ = 'cupy_tests.cuda_tests.test_runtime'
11:59:19         __qualname__ = 'TestMemPool'
```

**Comment by leofang** [comment]
It's strange... Is the error coming from the HIP backend? I thought we hard-coded it...
```python
>>> import cupy as cp
>>> cp.cuda.runtime.cudaDevAttrMemoryPoolsSupported
115
```

**Comment by emcastillo** [comment]
In ROCm

```
>>> cupy.cuda.runtime.cudaDevAttrMemoryPoolsSupported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cupy_backends.cuda.api.runtime' has no attribute 'cudaDevAttrMemoryPoolsSupported'
```

Will fix

**Comment by emcastillo** [comment]
Sent a fix #6621

**Comment by leofang** [comment]
Ah, good catch, thx Emilio!

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
