### PR TITLE
[WIP] Support TensorComprehensions

### PR DESCRIPTION
**Pull request by mitmul**
Please merge #1176 first.
This PR adds some features to support [TensorComprehensions](https://github.com/facebookresearch/TensorComprehensions) in CuPy. This PR includes

- [x] DLPack conversion 
- [x] `define` method of `ExecutionEngine`
- [x] `compile` method of `ExecutionEngine`
- [x] `run` method of `ExecutionEngine`
- [ ] add `autotune` method

## Usage

```python
import cupy as cp

lang = """
def matmul1(float(M,N) A, float(N,K) B) -> (output) {
  output(i, j) +=! A(i, kk) * B(kk, j)
}
"""

mat1 = cp.random.randn(3, 4).astype(cp.float32)
mat2 = cp.random.randn(4, 5).astype(cp.float32)
inputs = [mat1, mat2]

matmul_tc = cp.TCKernel(lang, 'matmul1', inputs)

outputs = matmul_tc(mat1, mat2)

print(outputs)

print(mat1.dot(mat2))
```

Output:
```
[array([[-1.6109701 , -0.8591884 ,  1.9276512 ,  1.173499  ,  0.52361923],
       [ 0.09751272,  0.60291064,  0.650693  ,  0.55805117, -0.00793068],
       [ 1.2433641 ,  1.3963815 , -1.5949605 , -2.0097587 , -1.1013638 ]],
      dtype=float32)]
[[-1.6109701  -0.8591884   1.9276514   1.1734991   0.52361923]
 [ 0.09751274  0.60291064  0.65069306  0.55805117 -0.00793068]
 [ 1.243364    1.3963815  -1.5949605  -2.009759   -1.1013638 ]]
```

It seems to be working correctly.

I'd like to discuss the interface after I finished wrapping all necessary methods in TC.

### CODE REVIEW

**Comment by prigoyal** [comment]
great work. this sounds wonderful @mitmul :) I was wondering if you are planning to submodule TC codebase or subtree it or some other approach? My recommendation would be to go with submodule so that in future, when TC adds new features like AMD support, then you can simply update the submodule and use it. :)

**Comment by mitmul** [comment]
Ah, just calling `protoc mapping_options.proto --cpp_out=include_dir` seems to resolve the problem of missing `mapping_options.pb.h`. So now I think using submodule sounds quite reasonable.

**Comment by prigoyal** [comment]
thanks @mitmul , btw, if you have any feedback on how we can improve the codebase, your feedback is warmly welcomed :)

**Comment by mitmul** [comment]
I made another PR only for some basic features: #1176 
This PR turned to try implementing `autotune` method based on #1176.

**Comment by nicolasvasilache** [comment]
Hi @mitmul,

this is very exciting to us that you are considering TC + cupy, I was pondering a similar solution myself. I would just like to attract your attention to the fact that the ExecutionEngine is going away soon as we revamp the internals of TC to make it more portable. 

It will still be easy to implement such an ExecutionEngine abstraction if needed but we have been working on decoupling, compilation in a more functional-style API, execution and storage classes. This refactoring ends up simplifying implementation (esp at the autotuner concurrency level), extensibility and portability.

Please take a look [here](https://github.com/facebookresearch/TensorComprehensions/issues/307). I am maintaining a work in progress refactoring PR that implements all these proposed changes in a personal branch. I can point you to it if it is of interest but this is still in flight and subject to change.

Please let me know if you'd like to discuss and feel free to comment on the API RFCs which questions, comments or concerns.

I am looking forward to playing with cupy + TC, thank you for this!

**Comment by mitmul** [comment]
@nicolasvasilache Hi, thank you for commenting on this PR. I'd like to re-start working on this by thinking how to wrap the autotune feature from scratch, because TC code base seems largely changed. When do you plan the release of next version of TC? Or, could you tell me the stable commit in the current master branch of TC?

**Comment by nicolasvasilache** [comment]
Hello @mitmul,

First a little disclaimer, I am not involved with FB anymore and as such I am not working on TC.

The current TC master supports pytorch 0.4.0 and dependencies are precompiled and served through conda. This was essentially a transition towards the pytorch 1.0 build system. Note however that TC is not yet compatible with pytorch 0.4.1+ so there will be work needed to support that if someone wants it.

The features and APIs of TC are stabilized and build from source but we did not get package shipping with the new API. The best way to build from source (assuming pytorch 0.4.0 is enough) is to follow the build instructions and also look at our docker image.

Building support for other frameworks should be quite straightforward. 
It should just be a matter of porting this [API](https://github.com/facebookresearch/TensorComprehensions/blob/master/tensor_comprehensions/pybinds/tclib.cc) to your tensor type, be mindful of the latencies converting tensors to/from DLPack though.

**Comment by asi1024** [comment]
Closing the PR as it has been WIP for a long time.
Please reopen if you want to continue.

**Pull request closed without merging**
