### PR TITLE
add batched cholesky solver

### PR DESCRIPTION
**Pull request by dmargala**
This PR adds a public function `cupyx.linalg.cholesky_solve` (#4237) that computes the solution to a system of linear equations A * X = B for symmetric/Hermitian positive-definite matrices. Similar to the LAPACK xPOSV routines, it performs factorization and then uses the factored form to solve the system of equations. This PR is mostly a refactor of `cupyx.linalg.invh`, which is implemented as the special case A * X = I. 

There is related work in #4172 to implement `cupyx.scipy.linalg.cho_factor` and `cupyx.scipy.linalg.cho_solve` which are wrappers for the non-batched cholesky factorization step (xPOTRF) and cholesky solve step (xPOTRS) and match the scipy api. 

It might make more sense to separate the factorization and solution steps here too but since this was mostly just a refactor of `cupyx.linalg.invh`, I didn't want to change too much.

### CODE REVIEW

**Comment by anaruse** [comment]
Thanks for the PR to generalize `cupyx.linalg.invh` to cholesky solver.

It's a bit annoying that there is no function in `numpy.linalg` or `scipy.linalg` that corresponds to the cholesky solver, but since it it the LAPACK posv equivalent, I thinks it is better to put it in `cupyx.lapack` as `posv`.

For reference, there are `gesv` and `gels` in `cupyx.lapack` now.

**Comment by dmargala** [comment]
Thanks for the suggestion, I moved the cholesky solver to `cupyx.linalg.posv`.

It looks like `scipy.linalg.solve(..., assume_a='pos', ...)` calls `posv` here: https://github.com/scipy/scipy/blob/v1.5.4/scipy/linalg/basic.py#L243

In general though, it doesn't seem like the scipy api supports batch inputs which is really what I am trying to accomplish here.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
