### PR TITLE
[backport] Add `take_along_axis`

### PR DESCRIPTION
**Pull request by takagi**
Backport of #2314

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
Just I missed making this backport when I merged the original one.

**Comment by asi1024** [comment]
Should PR #2314 be backported? #2314 only adds a new feature and does not fix any bug.

**Comment by takagi** [comment]
I'm a bit confused if features should be backported or not by [this comment](https://github.com/cupy/cupy/pull/2325#issuecomment-516034899)

As you say, features are basically not backported:
- [features not labeled to-be-backport](https://github.com/cupy/cupy/pulls?q=is%3Apr+is%3Aclosed+label%3Acat%3Afeature+-label%3Ato-be-backported+
)
- [features labeled to-be-backport](https://github.com/cupy/cupy/pulls?q=is%3Apr+is%3Aclosed+label%3Acat%3Afeature+label%3Ato-be-backported
)

Let me close this PR.

**Pull request closed without merging**
