### PR TITLE
add `cupy.random.logistic`

### PR DESCRIPTION
**Pull request by YoshikawaMasashi**

### CODE REVIEW

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
You are right...
```
>>> cupy.isfinite(cupy.random.logistic(size=10**7, dtype=cupy.float32)).all()
array(True)
```


I think the output is not finite In [the other approachs in wikipedia](https://en.wikipedia.org/wiki/Logistic_distribution#Related_distributions).

The output of gumbel is not finite.
```
>>> cupy.isfinite(cupy.random.gumbel(size=10**7, dtype=cupy.float32)).all()
array(False)
```
And, the output of standard_exponential could be 0.

**Comment by YoshikawaMasashi** [comment]
I implemented finite sampling using rejection sampling.
```
>>> cupy.isfinite(cupy.random.logistic(size=10**8, dtype=cupy.float32)).all()
array(True)
```

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
