### PR TITLE
Rest of version check fix for new ROCm version definition

### PR DESCRIPTION
**Pull request by takagi**
Succeeding #5657. Rel #5592, especially https://github.com/cupy/cupy/issues/5592#issuecomment-900813721.

This PR fixes version checks for the new ROCM version definition. I looked up all the lines to fix by:
```
$ find . -name '*.py' -or -name '*.pyx' | xargs grep 'runtimeGetVersion\|driverGetVersion\|get_build_version' -n`
```

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Let me retest with LLVM_PATH fix.
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Some cuBLAS tests are still failing, and it now crashes (maybe around `getPTX`)...

```
10:59:54 cupy_tests/cuda_tests/test_compiler.py sFatal Python error: Segmentation fault
10:59:54 
10:59:54 Current thread 0x00007fc8d4617740 (most recent call first):
10:59:54   File "/tmp/.local/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 665 in compile
10:59:54   File "/tmp/.local/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 282 in _compile
```

**Comment by takagi** [comment]
Seems both `hiprtcGetCodeSize` and `hiprtcGetCode` can cause segfault...

**Comment by takagi** [comment]
> Seems both hiprtcGetCodeSize and hiprtcGetCode can cause segfault...

Pure HIP C++ code that calls hiprtc does not reproduce the segfalut, so CuPy may have something.

**Comment by takagi** [comment]
Looks like the debug log (`AMD_LOG_LEVEL=4`) says the segfault is caused in `hiprtcGetCodeSize ` before it returns, but I'm not sure what brings it.
```
$ AMD_LOG_LEVEL=4 python -m pytest tests/cupy_tests/cuda_tests/test_compiler.py -s
...
:3:hip_rtc.cpp              :212 : 1367995802275 us: [7feeb976d600] hiprtcCreateProgram ( 0x7ffcb6605a20, , /tmp/tmp3yh3eq3j/kern.cu, 0, char array:<null>, char array:<null> )
:3:hip_rtc.cpp              :237 : 1367995802287 us: [7feeb976d600] hiprtcCreateProgram: Returned HIPRTC_SUCCESS
:3:hip_rtc.cpp              :244 : 1367995802297 us: [7feeb976d600] hiprtcCompileProgram ( 0x55b83b155e50, 0, char array:<null> )
:3:hip_rtc.cpp              :271 : 1367995802307 us: [7feeb976d600] hiprtcCompileProgram: Returned HIPRTC_SUCCESS
:3:hip_rtc.cpp              :359 : 1367995802320 us: [7feeb976d600] hiprtcGetCodeSize ( 0x55b83b155e50, 0x7ffcb6605c38 )
Fatal Python error: Segmentation fault
...
```

I guess the following is the definition of `hiprtcGetCodeSize` (its latest one, and not necessarily the same as that of ROCm 4.3).
https://github.com/ROCm-Developer-Tools/hipamd/blob/6a21816f5dd993443c105e9f158c9f96da31b5c6/src/hip_rtc.cpp#L399

**Comment by takagi** [comment]
I found it is just because a CUDA-specific test unexpectedly runs.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
