### PR TITLE
add Box-Cox transformations to cupyx.scipy.special

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds `boxcox`, `boxcox1p`, `inv_boxcox` and `inv_boxcox1p` to `cupyx.scipy.special`. It is based on top of #6300. Only the changes in commit e5e5aa4 are new to this PR.

cc @IvanYashchuk 

The `boxcox` function is the "one-parameter Box-Cox transformation" described [here](https://en.wikipedia.org/wiki/Power_transform#Box%E2%80%93Cox_transformation)

### CODE REVIEW

**Review by emcastillo — DISMISSED** [review]
LGTM!!! Thanks!!

**Comment by emcastillo** [comment]
seems like `cupyx_tests.scipy_tests.special_tests.test_ufunc_dispatch` is broken in all configs

**Comment by grlee77** [comment]
> seems like cupyx_tests.scipy_tests.special_tests.test_ufunc_dispatch is broken in all configs

Okay, I will take a look. I hadn't tested since that dispatch PR was merged.

**Comment by grlee77** [comment]
Okay, the failures due to `ndtr` and `ndtri` should be fixed now. Please test again

e616646 fixes the float32 dispatching as well as bugs in the `test_statistics.py` tests that were causing some functions to not be tested or to only be tested with float64 dtype

**Review by emcastillo — APPROVED** [review]
Thanks!!

**Pull request merged**
