### PR TITLE
Show type of error in `numpy_cupy_*` decorators

### PR DESCRIPTION
**Pull request by toslunar**
`str(exc)` does not contain the type of the exception `exc`.

```
>>> print(TypeError('foo'))
foo
>>> print(repr(TypeError('foo')))
TypeError('foo')
>>> list(traceback.TracebackException.from_exception(TypeError('foo')).format_exception_only())
['TypeError: foo\n']
```

### CODE REVIEW

**Comment by toslunar** [comment]
Please review #4442 first.

**Comment by toslunar** [comment]
example

```diff
--- before
+++ after
@@ -1,34 +1,37 @@
 ============================= test session starts ==============================
 platform linux -- Python 3.9.1, pytest-4.1.1, py-1.10.0, pluggy-0.13.1
 rootdir: ..., inifile: setup.cfg
 collected 1 item

 test_tmp.py F                                                            [100%]

 =================================== FAILURES ===================================
 _________________________________ TestA.test_a _________________________________

-self = <test_tmp.TestA object at 0x7f7c033ec580>
+self = <test_tmp.TestA object at 0x7f9e416bea90>
 xp = <module 'cupy' from '.../cupy/__init__.py'>

     @testing.numpy_cupy_array_equal(accept_error=True)
     def test_a(self, xp):
 >       return xp.array(xp.__name__[4], xp.float32)
 E       AssertionError: Different types of errors occurred
 E
 E       cupy
+E       Traceback (most recent call last):
 E         File ".../cupy/testing/helper.py", line 47, in _call_func
 E           result = impl(self, *args, **kw)
 E         File ".../tests/test_tmp.py", line 16, in test_a
 E           return xp.array(xp.__name__[4], xp.float32)
-E       string index out of range
+E       IndexError: string index out of range
+E
 E
 E       numpy
+E       Traceback (most recent call last):
 E         File ".../cupy/testing/helper.py", line 47, in _call_func
 E           result = impl(self, *args, **kw)
 E         File ".../tests/test_tmp.py", line 16, in test_a
 E           return xp.array(xp.__name__[4], xp.float32)
-E       could not convert string to float: 'y'
+E       ValueError: could not convert string to float: 'y'

 test_tmp.py:16: AssertionError
-=========================== 1 failed in 0.50 seconds ===========================
+=========================== 1 failed in 0.45 seconds ===========================
```

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
