### PR TITLE
Avoid __init__ function call overhead in memory allocation

### PR DESCRIPTION
**Pull request by okuta**
The memory allocation is core part in CuPy. So, I want to speed up it.

### CODE REVIEW

**Comment by okuta** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Can you show the improvement?

**Comment by asi1024** [comment]
@okuta I didn't know that such kinds of fixes are effective for performance improvement. Thanks. (Note: [Fast instantiation](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#fast-instantiation))
How about defining `__cinit__` method?

**Comment by okuta** [comment]
In my understanding,[ `__cinit__` is special method.](https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#initialisation-methods-cinit-and-init)
> The __cinit__() method is where you should perform basic C-level initialisation of the object, including allocation of any C data structures that your object will own

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
