### PR TITLE
Add timeout to Windows CI

### PR DESCRIPTION
**Pull request by kmaehashi**
Currently Windows CIs for branch tests take more than the hard limit (10 hours) set in `.pfnci/config.pbtxt`.
This is preventing the kernel cache to grow and taking 8 hours for each pull request tests.

This PR intends to add soft timeout to Windows CI to grow kernel cache incrementally.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Timeout triggered as expected.

https://ci.preferred.jp/cupy.win.cuda122/143204/
> WARNING: Command timed out: python -m pytest -rfEX -m "not slow" .

**Comment by kmaehashi** [comment]
Confirmed test times out after 5 hours.

**Review by emcastillo — APPROVED** [review]
LGTM!!! Thanks!!!

**Pull request merged**
