### PR TITLE
Add more K-S tests

### PR DESCRIPTION
**Pull request by toslunar**
Merge #1677 first.

ref. #1300

### CODE REVIEW

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure (`tests.chainer_tests.links_tests.normalization_tests.test_batch_renormalization.BatchRenormalizationTest_param_13.test_forward_multi_gpu`) is unrelated to the PR.

**Pull request merged**
