### PR TITLE
CI: Implement Docker caching for CuPy release workflow

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

This PR implements Docker caching for CuPy release workflow.

Relevant Docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache

### Before caching ([Logs](https://github.com/cupy/cupy/runs/5343897816?check_suite_focus=true))

image

#### After caching ([Logs](https://github.com/cupy/cupy/runs/5343946966?check_suite_focus=true))

image

### CODE REVIEW

**Comment by kmaehashi** [comment]
Hi @HarshCasper, thanks for the PR!
I'm wondering if caching is needed here because (1) this workflow only runs when making a release (i.e. once a month) and (2) the base CUDA Docker images are updated frequently and we would like to use the latest one every time when making a release, so it is unlikely to hit the cache.

**Comment by kmaehashi** [comment]
Let me close this as I think caching is not needed for the above reasons. Thanks anyways! 😃

**Comment by HarshCasper** [comment]
@kmaehashi No worries! I believe this would have been helpful in the case of PRs as well. I will find something else to work on. Thanks!

**Comment by kmaehashi** [comment]
> I believe this would have been helpful in the case of PRs as well.

Actually, the workflow runs in PRs as well but only for PRs modifying `docker/**` and `.github/workflows/docker.yml`, which is almost not happening except for the release.

**Pull request closed without merging**
