### PR TITLE
Improve version embedding

### PR DESCRIPTION
**Pull request by okuta**
Current CuPy requires installed state.
This fix relaxing limitation of environment. For example, [Pyinstaller.](http://www.pyinstaller.org/)

### CODE REVIEW

**Comment by niboshi** [comment]
How about `imp.load_source`? Isn't it safer?

**Comment by niboshi** [comment]
Also, I think it's better to use `os.path.join` instead of hardcoded slash as a path separator.

**Comment by okuta** [comment]
OK, I will fix.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
