### PR TITLE
Update installation guide

### LINKED ISSUE #2177: Installation Guide Update re:"We now provide wheels of development releases for Windows."
In the referenced issue, it looks like binary wheels are now provided for Windows.
Would it be ok to put this information on the installation page?
https://docs-cupy.chainer.org/en/stable/install.html

I am struggling to get cupy going on Windows and this might have helped save me lots of time. 

Thank you!

We now provide wheels of development releases for Windows.
Try `pip install cupy-cuda92` etc. as in the installation docs.

_Originally posted by @kmaehashi in https://github.com/cupy/cupy/issues/914#issuecomment-405825989_

### PR DESCRIPTION
**Pull request by kmaehashi**
Blocked by: https://github.com/chainer/chainer-test/pull/510

* Support Ubuntu 18.04
* Drop Ubuntu 14.04
* Add notes for Windows (closes #2177 and #2178)

### CODE REVIEW

**Comment by toslunar** [comment]
chainer/chainer-test#510 is merged.

**Comment by hvy** [comment]
Thanks for the heads up. I'll check this PR.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Test failures are not related to this PR.

**Comment by hvy** [comment]
LGTM!

**Pull request merged**
