### PR TITLE
JIT: Fix `BuiltinFunc` not to inherit `Expr` class

### PR DESCRIPTION
**Pull request by asi1024**
Cosmetic changes.

### CODE REVIEW

**Comment by leofang** [comment]
Q: With this change, is there any semantics change for `Expr` or `BuiltinFunc`?

**Comment by asi1024** [comment]
`BuiltinFunc` will be handled as `Constnant`, not `Expr` after this PR, but it is just an internal change. There is no need to modify the definition of each builtin-function.

**Comment by asi1024** [comment]
I have totally forgotten that a `Constant` class object of `Function` needs to have CUDA variables whose values are not determined at compile time unless `BuiltinFunc` inherits Expr. Please let me withdraw this pull request...

**Pull request closed without merging**
