### PR TITLE
[backport] Fix byte buffer handling to support PyPy

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #3225

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
@kmaehashi seems like the test passed without doing anything 😂

**Comment by leofang** [comment]
What happened 😂

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
