### PR TITLE
Make random.get_random_state() thread-safe

### LINKED ISSUE #77: get_random_state() is not thread-safe
In the code below, the seed should be set to 10 no matter what order these threads are executed.

**Code**:
```
import threading
import random
import cupy

SEED = 10

def func_seed():
    cupy.random.seed(SEED)

def func_get_random_state():
    cupy.random.get_random_state()

def test():
    procs = [
        threading.Thread(target=func_seed),
        threading.Thread(target=func_get_random_state),
        threading.Thread(target=func_get_random_state),
        threading.Thread(target=func_get_random_state),
        threading.Thread(target=func_get_random_state),
        threading.Thread(target=func_get_random_state),
        threading.Thread(target=func_get_random_state),
    ]
    random.shuffle(procs)

    for p in procs:
        p.start()
        #p.join()  # this hides the problem

    for p in procs:
        p.join()

    actual = cupy.random.uniform()

    cupy.random.seed(SEED)
    expected = cupy.random.uniform()

    print("Expected: {}".format(expected))
    print("Actual  : {}".format(actual))

test()
```

**Result**:
```
Expected: 0.6320792449063122
Actual  : 0.41662013290707867
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #77

### CODE REVIEW

**Comment by okuta** [comment]
How about using thread local storage for random state?

**Comment by niboshi** [comment]
You mean `_random_states`? Then, there would be independent random states per thread for a single device. Each device should have single random state regardless of threads.

**Comment by niboshi** [comment]
I updated with a lock-free method which I intend to utilize GIL.
Do you think it is robust?

**Comment by okuta** [comment]
OK, I understood. This code is robust.
LGTM!

**Pull request merged**
