### PR TITLE
CI: use CUDA docker images for CUDA Python CI

### PR DESCRIPTION
**Pull request by kmaehashi**
This avoids using hand-crafted Dockerfile for CUDA Python CI for maintainability.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/cupy.linux.cuda11x-cuda-python/91288/

**Comment by kmaehashi** [comment]
Testing: https://ci.preferred.jp/cupy.linux.cuda11x-cuda-python/91330/

**Comment by kmaehashi** [comment]
Test passed.

**Review by emcastillo — APPROVED** [review]
LGTM!

**Comment by kmaehashi** [comment]
I'll make a backport pr

**Pull request merged**
