### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by hvy**
Fixed documentation of matmul. More specifically, removed `out` from the list or arguments and added a return variable.

### CODE REVIEW

**Comment by okuta** [comment]
Thank you for your PR.

This is not document problem. Current matmul implementation is incomplete.
Cloud you add `out=None` argument?
```python
cpdef ndarray matmul(ndarray a, ndarray b, ndarray out=None):
    if out is not None:
        raise NotImplementedError('Can not specify `out`')
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html

**Comment by hvy** [comment]
Thank you for the review. I see that this is not a matter of documentation. Added a third `out` argument (a placeholder for now) which raises an exception in case it is not `None`.

**Comment by okuta** [comment]
Thanks!

jenkins, test this please.

**Comment by okuta** [comment]
Thanks!

jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
