### PR TITLE
Bump Cython version requirement for Python 3.9

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Blocked by https://github.com/chainer/chainer-test/pull/637

**Comment by takagi** [comment]
Now the blocker is merged!

**Comment by takagi** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
