### PR TITLE
Increase test coverage for Generalized Universal Functions

### PR DESCRIPTION
**Pull request by emcastillo**
~Depends on #5260~

Adds tests for axes, type, signatures, and out features of gufuncs.

### CODE REVIEW

**Comment by emcastillo** [comment]
rebased! ptal

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Changed the label as this includes bug fix.

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
