### PR TITLE
CI: Migrate ROCm build test from FlexCI to GitHub Actions (using ROCm docker image)

### PR DESCRIPTION
**Pull request by kmaehashi**
https://github.com/cupy/cupy/pull/6026/files#r744235981

### CODE REVIEW

**Comment by emcastillo** [comment]
This one is much smaller and seems easier to maintain.
AMD repos tend to change address and keys requiring periodic changes.

**Comment by kmaehashi** [comment]
> This one is much smaller and seems easier to maintain.

:+1:

**Comment by emcastillo** [comment]
jenkins failures unrelated

**Comment by emcastillo** [comment]
Merging! thanks!!

**Pull request merged**
