### PR TITLE
Check kernel name when a kernel is made

### LINKED ISSUE #518: No validation for kernel name
Although `ElementwiseKernel`'s `name` argument is directly used as a function name in generated CUDA code, there are no validation process to raise an exception when invalid characters are used in `name`.
That causes CUDA compile error, which is a bit difficult to debug.

### PR DESCRIPTION
**Pull request by unnonouno**
fix #518

### CODE REVIEW

**Comment by unnonouno** [comment]
I think it is better to add more validation.

**Comment by niboshi** [comment]
How about `is_valid_kernel_name` instead? It would be more useful.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by niboshi** [comment]
How about some more test cases:
* Empty `''`
* Something starting with a digit, succeeded by some valid characters
* Something including symbols (printable symbol, `'\n'`, space, tab, etc)

**Comment by unnonouno** [comment]
I added more tests.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
