### PR TITLE
Define `ndarray.__iter__`

### LINKED ISSUE #1432: Raise TypeError: iteration over a 0-d array
`tuple` and `list` should raise on 0-d inputs. 
```
>>> tuple(numpy.array(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iteration over a 0-d array
>>> tuple(cupy.array(3))
()
```

```
>>> list(numpy.array(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iteration over a 0-d array
>>> list(cupy.array(3))
[]
```

Issue #1427 is probably due to this.

`len` is correct:
```
>>> len(numpy.array(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: len() of unsized object
>>> len(cupy.array(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1503, in cupy.core.core.ndarray.__len__
    raise TypeError('len() of unsized object')
TypeError: len() of unsized object
```

### PR DESCRIPTION
**Pull request by toslunar**
If `__iter__` is undefined, `__getitem__` is used.  This is wrong if the array is 0-dim.

Close #1432.

### CODE REVIEW

**Comment by okuta** [comment]
Cloud you add test?

**Comment by toslunar** [comment]
Added.  Is it a correct place?
I also added tests of `ndarray.__len__` because it seemed there wasn't.

**Comment by okuta** [comment]
`tests/cupy_tests/core_tests` is prefer. Please move it.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
