### PR TITLE
Fix matrix multiplication when matrixes have duplicated entries

### PR DESCRIPTION
**Pull request by unnonouno**
When a sparse matrix has duplicated entries, matrix multiplication does not work correctly.
merge #833 first

### CODE REVIEW

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
The test was failed.

**Comment by unnonouno** [comment]
I found that we don't need to call `sum_duplicates` in `eliminate_zeros`.

**Comment by okuta** [comment]
The test was failed.

**Comment by unnonouno** [comment]
I split the PR. Check #998 first.

**Comment by okuta** [comment]
I merged #998.

**Comment by unnonouno** [comment]
updated

**Comment by okuta** [comment]
Thanks

**Comment by okuta** [comment]
The test was failed. Please check test result?

**Comment by unnonouno** [comment]
Because CUDA <8 does not have an API for this method, i convert a compressed matrix to coo format, eliminate zeros on coo, and convert it to the original format. But matrix conversion method calls `sum_duplicates`. It cannot keep number of non-zeros. With the latest CUDA, it does not happen. So i skipped the test to check nnz.

**Comment by okuta** [comment]
OK.

**Comment by okuta** [comment]
The test is failed.

**Comment by unnonouno** [comment]
Oh, sorry. I need to use skipIs, not skipUnless.

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
@unnonouno  Do you want to backport this PR?
This PR based on #998 and it is not backported.

**Pull request merged**
