### PR TITLE
Fix bad source hyperlinks

### LINKED ISSUE #1834: Bad `cupy.all` source hyperlink
The [source] hyperlink in `cupy.all` links to the wrong destination.

https://docs-cupy.chainer.org/en/latest/reference/generated/cupy.all.html

### PR DESCRIPTION
**Pull request by asi1024**
Fixes #1834.

### CODE REVIEW

**Comment by asi1024** [comment]
jenkins, test, this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
I can't backport this PR automatically.

**Pull request merged**
