### PR TITLE
Make einsum accept subscripts in numpy int

### LINKED ISSUE #6495: einsum indices don't allow np.int
### Description

If calling `cupy.einsum` with something that contains something integer-like as list entries, like `np.int`, I get the error

```
File "/home/ssemper/.local/lib/python3.7/site-packages/cupy/linalg/_einsum.py", line 62, in _parse_int_subscript
'each subscript must be either an integer or an ellipsis',
```

whereas the same code is executing just fine with `numpy.einsum`. In my case specifically it was `numpy.int64`.

### To Reproduce

```py
# cupy.einsum(cupy.random.randn(4,3), np.arange(2), cupy.random.randn(3,5), np.arange(1,3), [0,2])
```

### Installation

_No response_

### Environment

```
[ssemper@maurice scripts]$ intelpython3 -c 'import cupy; cupy.show_config()'
OS                           : Linux-5.10.100-2-MANJARO-x86_64-with-arch-Manjaro-Linux
Python Version               : 3.7.9
CuPy Version                 : 10.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.2+intel.0
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.21
CUDA Root                    : /opt/cuda
nvcc PATH                    : /opt/cuda/bin/nvcc
CUDA Build Version           : 11050
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101301
CUB Build Version            : 101301
Jitify Build Version         : 60e9e72
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3090
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by toslunar**
Follow numpy/numpy#16080 to resolve #6495.

### CODE REVIEW

**Review by emcastillo — DISMISSED** [review]
LGTM!

**Review by emcastillo — APPROVED** [review]
Thanks!

**Comment by toslunar** [comment]
I'll backport this because 
> NumPy/SciPy-compatible API in CuPy v10 is based on NumPy 1.21 and SciPy 1.7

https://docs.cupy.dev/en/stable/install.html#python-dependencies

**Pull request merged**
