### PR TITLE
Rename my_sum to my_add in docs

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by toslunar** [comment]
Why do you keep the name `sum_kernel`?

**Comment by kmaehashi** [comment]
Fixed, just overlooked it.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure (`TestConvolutionND_param_16.test_backward_gpu_nobias`) is irrelevant to the PR.

**Pull request merged**
