### PR TITLE
[backport] Support sparse pointwise maximum and minimum

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #3860

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
@emcastillo Could you rebase this PR to the current v8?

**Comment by asi1024** [comment]
Sorry, #3959 should be backported firstly...

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Needs #3964

**Comment by emcastillo** [comment]
rebased

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
