### PR TITLE
Avoid using `pip install -e` on Windows CI for performance

### PR DESCRIPTION
**Pull request by kmaehashi**
Depends on ~#4969~

See https://github.com/cupy/cupy/pull/4963#issuecomment-805927327

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
```

00:09:37.883078 STDOUT 2644] | C:\Development\Python\Python37\lib\importlib\__init__.py:127: in import_module |  
-- | -- | --
00:09:37.883078 STDOUT 2644] | return _bootstrap._gcd_import(name[level:], package, level) |  
00:09:37.883078 STDOUT 2644] | ..\install\build.py:10: in <module> |  
00:09:37.883078 STDOUT 2644] | from install import utils |  
00:09:37.883078 STDOUT 2644] | E   ModuleNotFoundError: No module named 'install' |  
00:09:37.883078 STDOUT 2644] | =========================== short test summary info ========


```

**Comment by emcastillo** [comment]
https://github.com/cupy/cupy/blob/master/install/build.py#L10

maybe this is related?

**Comment by leofang** [comment]
Doesn't look like the CI runtime is reduced?

**Comment by kmaehashi** [comment]
I've manually pushed kernel cache.

**Comment by kmaehashi** [comment]
I've rebased to the latest master and measured time with Emilio's cache hit ratio statistics.

The first run took 6h3m: https://ci.preferred.jp/cupy.experimental.win.cuda100/72192/148338

```
06:03:01.924304 STDOUT 3584] | Compile Cache hits 13873 |
06:03:01.924304 STDOUT 3584] | Compile Cache misses 58479 |
06:03:01.924304 STDOUT 3584] | Compile Cache hit ratio 0.19
```

The second run took 1h47m: https://ci.preferred.jp/cupy.experimental.win.cuda100/72192/148339

```
01:47:15.600036 STDOUT 3704] | Compile Cache hits 72282 |
01:47:15.600036 STDOUT 3704] | Compile Cache misses 188 |
01:47:15.600036 STDOUT 3704] | Compile Cache hit ratio 1.00
```

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Test finished in 1h14m!

**Comment by kmaehashi** [comment]
Jenkins failure seems irrelevant.

**Comment by leofang** [comment]
Awesome!

**Pull request merged**
