### PR TITLE
[backport] Support CUDA 11.0

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #3405 + #3578 + #3183 (those all are needed to build on CUDA 11.0 so cannot be separated)

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by kmaehashi** [comment]
depends on https://github.com/cupy/cupy/pull/3721

**Comment by pentschev** [comment]
@kmaehashi we need #3183 and #3578 for this to branch to build. I realize the latter is already listed in https://github.com/cupy/cupy/issues/3406 , but #3183 isn't. I guess we should backport those first, there should be no major issues with those.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
> @kmaehashi we need #3183 and #3578 for this to branch to build. I realize the latter is already listed in #3406 , but #3183 isn't. I guess we should backport those first, there should be no major issues with those.

Thank you! I've included #3578 to this PR.

**Comment by pentschev** [comment]
Thanks @kmaehashi , FWIW, I don't think the build will succeed before merging https://github.com/cupy/cupy/pull/3760 .

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Merge after merging https://github.com/chainer/chainer-test/pull/593 and rerunning test on CUDA 11.0

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Sent PRs to fix issues above:
https://github.com/cupy/cupy/pull/3699 
https://github.com/chainer/chainer-test/pull/597

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
