### PR TITLE
[backport] Fix `cupy.array` from nested list of zero-dim ndarray

### PR DESCRIPTION
**Pull request by asi1024**
Backport of #4569

### CODE REVIEW

**Comment by asi1024** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
pip 21 released 3 days ago breaks with python 3.5 because of F-string.

**Comment by kmaehashi** [comment]
Fixing the test condition: https://github.com/chainer/chainer-test/pull/631

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
