### PR TITLE
Implemented RangeStart and RangeEnd

### PR DESCRIPTION
**Pull request by unnonouno**
I implemented RangeStart and RangeEnd that shows range in nvvp.
See https://github.com/chainer/chainer/pull/2496

### CODE REVIEW

**Comment by okuta** [comment]
LGTM except document and calling test.

**Comment by okuta** [comment]
Do you have a plan of document and test?

**Comment by unnonouno** [comment]
In my opinion, this is a thin wrapper for nvtx API. We need to provide higher level API to users.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
