### PR TITLE
Fix files not closed

### LINKED ISSUE #4546: Python 3.8 warning in Windows
```
Traceback (most recent call last):
  File "C:\Development\Python\Python38\lib\site-packages\cupy\_environment.py", line 265, in get_preload_config
    _preload_config = json.load(open(config_path))
ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Development\\Python\\Python38\\lib\\site-packages\\cupy\\.data\\_wheel.json' mode='r' encoding='cp1252'>
```

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #4546

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI pass.

**Comment by kmaehashi** [comment]
I think the test failure is unrelated and fixed in #4648

**Comment by toslunar** [comment]
pfnCI, test this please.

**Pull request merged**
