### PR TITLE
Fix ROCm build error

### PR DESCRIPTION
**Pull request by kmaehashi**
Ref #2560, #2531

Test: https://ci.preferred.jp/cupy.py3.amd/41455/

### CODE REVIEW

**Comment by leofang** [comment]
Oops, sorry I overlooked...

**Comment by kmaehashi** [comment]
Can be merged after confirming this test succeeds: https://ci.preferred.jp/cupy.py3.amd/41936/

@leofang No worries, I should have added AMD tests to CIs. (ongoing: #2408)

**Comment by Crissman** [comment]
imosCI, test this please.

**Comment by kmaehashi** [comment]
> Can be merged after confirming this test succeeds: https://ci.preferred.jp/cupy.py3.amd/41936/

The test has passed. Now waiting for Jenkins...

**Comment by leofang** [comment]
Just curious, how many kinds of CIs do you have? I've seen Jenkins, pfnCI, and now imosCI 😲

**Comment by kmaehashi** [comment]
> Just curious, how many kinds of CIs do you have? I've seen Jenkins, pfnCI, and now imosCI 😲

Currently we are going to migrate from Jenkins to FlexCI. (For historical reasons... (1) FlexCI is also called pfnCI/imosCI but they are the same thing (2) `pfnCI_test_this_please` also triggers Jenkins 🤣)

**Pull request merged**
