### PR TITLE
Refactor cuTENSOR handle initialization

### PR DESCRIPTION
**Pull request by niboshi**
This is yet another version mentioned here (described as version 4): https://github.com/cupy/cupy/pull/2764#discussion_r354683947

### CODE REVIEW

**Comment by niboshi** [comment]
Needs #2771 first.

**Comment by kmaehashi** [comment]
Blocked by https://github.com/cupy/cupy/pull/3037

**Comment by emcastillo** [comment]
#3037 was merged :)

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
