### PR TITLE
Fix `TestStream` cleanup

### PR DESCRIPTION
**Pull request by emcastillo**
This seems to be why the copy multigpu error is happening in the CI https://github.com/cupy/cupy/issues/4673.

In these tests, ptds is left as the default stream for the rest of the CI execution, and when the array is copied back, `asarray` ignores the ptds set https://github.com/cupy/cupy/pull/5004, and just starts copying to host before the multidevice copy is over.

If we are right, https://github.com/cupy/cupy/pull/5040 will print 2 in the current stream being used once that test fails.

#5004 fixes the root cause of the error, but this PR is needed to set the CI environment correctly.

### CODE REVIEW

**Comment by leofang** [comment]
@emcastillo If #4337 had been merged this wouldn't have been a bug that keeps haunting us. Just saying 😂

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
@cupy/code-owners Failed to backport automatically.

----

```
fPR #5042 is not merged
```

**Comment by kmaehashi** [comment]
Let me test bot mode (https://github.com/cupy/backport/pull/27) of backport tool in this PR 🙇🏼 :

**Pull request merged**
