### PR TITLE
Fix multi-device copyto

### PR DESCRIPTION
**Pull request by niboshi**
Fixes https://github.com/chainer/chainer/issues/2911

### CODE REVIEW

**Comment by niboshi** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
test this please

**Comment by okuta** [comment]
How about prohibiting copying between devices when `where` is specified?

**Comment by niboshi** [comment]
Ah, yes, I didn't notice the documentation. I will fix.

**Comment by okuta** [comment]
OK, Please.

**Comment by niboshi** [comment]
Fixed.

**Pull request merged**
