### PR TITLE
Checks return types in `testing.numpy_cupy_*`

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Seems like there are functions that returns two numpy arrays instead of one cupy and one numpy array

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Pull request merged**
