### PR TITLE
Generate signature for ufunc documentation

### LINKED ISSUE #357: Generate correct documentation for ufuncs
Parameter list and description of the return value are missing.

CuPy (v1.0.2): https://docs-cupy.chainer.org/en/v1.0.2/reference/generated/cupy.add.html
NumPy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.add.html

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes part of #357.
Depends on ~#6126~.

### CODE REVIEW

**Comment by asi1024** [comment]
https://cupy--6137.org.readthedocs.build/en/6137/reference/generated/cupy.add.html#cupy-add

**Comment by kmaehashi** [comment]
Closed & reopened to rekick GitHub Actions 😄

**Comment by kmaehashi** [comment]
@asi1024 The last commit fixes the Sphinx warning. The problem was that `sin(x, /, out=None, *, casting='same_kind', dtype=None)` being an invalid reST. NumPy seems to handle this problem with [numpydoc](https://github.com/numpy/numpydoc/blob/4cfcfa6339e169572f29807a0d43c2b7b7080ece/numpydoc/docscrape.py#L465-L468) but since we don't have a similar layer I just fixed docstring generator to escape.

If it's ok for you please proceed to merge after test pass.

/test

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
