### PR TITLE
Fix cupy.copyto ignore where argument when src is scalar

### LINKED ISSUE #872: cupy.copyto behaves differently from numpy.copyto when src is a python scalar
Code:
```python
import numpy
import cupy

def copyto_check(xp):
    x = xp.zeros(3, dtype=numpy.float32)
    # replace first and third items with 1.0
    xp.copyto(x, 1.0, where=xp.asarray([True, False, True]))
    print(x)

print('numpy', numpy.__version__)
copyto_check(numpy)
print('cupy', cupy.__version__)
copyto_check(cupy)
```
Output:
```
numpy 1.14.0
[1. 0. 1.]
cupy 2.2.0
[1. 1. 1.]
```

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes #872

### CODE REVIEW

**Comment by niboshi** [comment]
Could you add more test cases?
(i.e. complex and numpy scalars)

**Comment by kmaehashi** [comment]
Thanks, I added the complex test case.
Currently `cupy.copyto` does not support NumPy scalar as a source, so I think it should be a separate PR if we need to support it.

**Comment by niboshi** [comment]
OK.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
