### PR TITLE
Add mquantiles and scoreatpercentile to cupyx.scipy.stats

### PR DESCRIPTION
**Pull request by andfoy**
This is required by `find_peaks_cwt` as part of #7403

### CODE REVIEW

**Comment by ev-br** [comment]
As an API design question: do we want to expose these  as public functions given that there's likely no chance to support masked arrays, or keep them private helpers for cupyx.scipy.signal functions that need them?

**Comment by takagi** [comment]
Very sorry that I left this so long...

> As an API design question: do we want to expose these as public functions given that there's likely no chance to support masked arrays, or keep them private helpers for cupyx.scipy.signal functions that need them?

Please keep them as private helpers this time as CuPy does not have masked arrays and can not have the same API as SciPy counterparts.

**Comment by andfoy** [comment]
Thanks for your feedback @takagi, I'm closing this one then

**Comment by takagi** [comment]
Thanks!

**Pull request closed without merging**
