### PR TITLE
Import modules locally in `cupyx/_runtime.py`

### PR DESCRIPTION
**Pull request by kmaehashi**
Preparation for #5677

### CODE REVIEW

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by emcastillo** [comment]
Error from 



```
+ python3 -c 'import cupy; cupy.show_config(_full=True)' |  
00:21:38.847882 STDOUT 2406] | Traceback (most recent call last): |  
00:21:38.847891 STDOUT 2406] | File "<string>", line 1, in <module> |  
00:21:38.847898 STDOUT 2406] | File "/root/.local/lib/python3.8/site-packages/cupy/__init__.py", line 880, in show_config |  
00:21:38.847906 STDOUT 2406] | _sys.stdout.write(str(_cupyx.get_runtime_info(full=_full))) |  
00:21:38.847907 STDOUT 2406] | File "/root/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 308, in get_runtime_info |  
00:21:38.847910 STDOUT 2406] | return _RuntimeInfo(full=full) |  
00:21:38.847915 STDOUT 2406] | File "/root/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 112, in __init__ |  
00:21:38.847916 STDOUT 2406] | self.cuda_build_version += f' (CUDA Python: {cuda.__version__})' |  
00:21:38.847919 STDOUT 2406] | TypeError: unsupported operand type(s) for +=: 'int' and 'str' |  
00:21:39.134622 STDOUT 2406]
```

**Comment by kmaehashi** [comment]
Thanks! Fixed.

**Review by toslunar — APPROVED** [review]

**Comment by emcastillo** [comment]
Agreed with @kmaehashi to merge 
https://github.com/cupy/cupy/pull/5677

instead since it contains the same fixes.

Thanks for review and testing!

**Pull request closed without merging**
