### PR TITLE
[backport] Separate code and path arguments in `RawModule`

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #2784

Was not cleanly cherry-picked

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Fixes in #2774 are mixed.
Please rebase on it after it will be mreged.

**Comment by niboshi** [comment]
#2774 is merged. Could you rebase?

**Comment by emcastillo** [comment]
PTAL

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
