### PR TITLE
Ignore error when peer access is already enabled 

### PR DESCRIPTION
**Pull request by leofang**
Cherry-pick from #2644. This PR fixes the error when peer access is enabled by some external libraries (cuFFT in the case of #2644). The `CUDARuntimeError` should be silently ignored in this case.

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM
Jenkins, test this please

**Comment by niboshi** [comment]
As #2899 has just been merged, could you resolve conflict?

**Comment by leofang** [comment]
@niboshi Done, PTAL 🙂

**Comment by niboshi** [comment]
Thanks!
Jenkins, test this please

**Pull request merged**
