### PR TITLE
Use special variable in map_expr in cupy.ReductionKernel

### PR DESCRIPTION
**Pull request by knorth55**
we can use special variable `a` in `post_map_expr` but not in `map_expr`.
I add arg `use_special_variable_in_map_expr` to use special variable `a` in `map_expr`.

EDIT:
arg name: `use_special_variable_in_map_expr` is quite long.
if you have any suggestion, please let me know.

### CODE REVIEW

**Comment by asi1024** [comment]
Is this PR purely for consistency with `post_map_expr` or does it allow expressing reduction kernels that we could not before?

**Comment by knorth55** [comment]
Current `pre_map_expr` doesn't allow something like `T val =input0 + input1; if (val > input2) { a = val } else {a = input2}` because it evaluates as `a = ${pre_map_expr}`

**Comment by asi1024** [comment]
We'll discuss the flag that you suggested and get back to you.  The concern is the usability, that the user needs to pass it explicitly.

**Comment by asi1024** [comment]
By the way, You can implement the above example as follows:
```python
import cupy

my_premap = '''
template <typename T>
__device__ T my_premap(T input0, T input1, T input2) {
  T out;
  T val = input0 + input1;
  if (val > input2) { out = val; } else { out = input2; }
  return out;
}
'''

my_func = cupy.ReductionKernel(
    'T x0, T x1, T x2',
    'T y',
    'my_premap(x0, x1, x2)',
    'a + b',
    'y = a',
    '0',
    preamble=my_premap
)

a = cupy.array([1, 2, 3, 4, 5])
b = cupy.array([6, 7, 8, 9, 10])
c = cupy.array([10, 10, 10, 10, 10])

result = my_func(a, b, c)

print(result)  # 59 (= 10 + 10 + 11 + 13 + 15)
```

**Comment by knorth55** [comment]
Any updates?

**Comment by asi1024** [comment]
We discussed this feature and concluded that the interface is not so easy to understand for users.
- It is not straight-forward to switch the behavior with a flag.
- It does not increase the expressiveness as stated above.
- Additionally, it may be dangerous because the `PRE_MAP(a)` can read uninitialized variable `a`.

I'm sorry but we don't want to accept this feature.

**Comment by knorth55** [comment]
> I'm sorry but we don't want to accept this feature

It is very sad that you just dismiss it.

> - It is not straight-forward to switch the behavior with a flag.
> - It does not increase the expressiveness as stated above.
> - Additionally, it may be dangerous because the PRE_MAP(a) can read uninitialized variable a

First and third comment can be avoidable.
So the second comment is the problem, and I don't see the reason why you dismiss it.
Expressiveness is not a problem (because you can express whatever you want by writing raw CUDA code) , but the easiness to use and understand is the point.
Anyway, for the improvement, I want to think about other ways to approach this problem.

There are mainly two points:

- `map_expr` interface is difficult to write complex kernel
- `map_expr` and `post_map_expr` are different interface

> - `map_expr` interface is difficult to write complex kernel

So, CuPy team recommend to use template kernel described above for complex `map_expr`.
It is OK for me because I got another suggestion from you, but is there any good idea for other users to use complex `map_expr` easily?
I think of writing about this tip in documentation.

> - `map_expr` and `post_map_expr` are different interface

Another point is that `map_expr`, `post_map_expr` interface are different, which makes difficult to understand.
Flag is to keep backward compatibility, so I can remove it and make it to same interface.

**Comment by asi1024** [comment]
> It is OK for me because I got another suggestion from you, but is there any good idea for other users to use complex `map_expr` easily?

Currently, we support `cupy.fuse` experimentally to write such kernels easily.  We will write it in documentation soon.
```py
import cupy

 @cupy.fuse()
 def my_func(x0, x1, x2):
     val = x0 + x1
     out = cupy.where(val > x2, val, x2)
     return cupy.sum(out)

 a = cupy.array([1, 2, 3, 4, 5])
 b = cupy.array([6, 7, 8, 9, 10])
 c = cupy.array([10, 10, 10, 10, 10])

 result = my_func(a, b, c)

 print(result)  # 59 (= 10 + 10 + 11 + 13 + 15)
```

**Pull request closed without merging**
