### PR TITLE
add NdBSpline based interpolation methods to RGI

### PR DESCRIPTION
**Pull request by ev-br**
Add a constructor for N-dimensional b-splines from data, which is new in SciPy 1.13.0. 

The user API matches that of SciPy 1.13.0:
- the constructor is exposed via the RegularGridInterpolator only
- there is a slight backwards compat change: RGI(..., method="cubic") now goes through the NdBSpline. Previous behavior is available via `RGI(..., method="cubic_legacy")`
- the new way is parametrically slower for construction of an interpolator (previously: essentially zero work; currently: construct and solve a large sparse linear system)
- the new way is parametrically faster for evaluations: previously the evaluation went through a python loop over the data points, and for each data point a loop over the dimensions; the new way delegates to NdBSpline, which has a GPU kernel for evaluations.
- new methods can compute the derivatives.

cross-ref https://github.com/cupy/cupy/issues/7186

### CODE REVIEW

**Comment by ev-br** [comment]
This PR now includes Edgar's fixes for NdBSpline.design_matrix (thanks!) and is passing all tests locally.

**Comment by takagi** [comment]
Would you add `make_ndbspl` on scipy_interpolate.rst?

**Comment by ev-br** [comment]
> Would you add make_ndbspl on scipy_interpolate.rst?

It's private in SciPy, so this would go beyond the scipy 1.13.0 API at least. Yes/no?

**Comment by takagi** [comment]
> It's private in SciPy, so this would go beyond the scipy 1.13.0 API at least. Yes/no?

Thanks, we don't need it on the current document.

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
