### PR TITLE
Fix SciPy dependency leak

### LINKED ISSUE #6931: Failure importing `cupyx.scipy.linalg` in CuPy 11 without `scipy` installed
### Description

In CuPy 11.0.0, `import cupyx.scipy.linalg` fails if `scipy` isn't installed. This was not the case for CuPy 10.6.0.

This is not a major problem, but I wanted to confirm, is the new behavior intended or is it a bug?

For context, this has come up in the context of some Dask tests that depend on `cupyx.scipy.linalg` that used to import and successfully complete in CuPy 10.6.0 even without `scipy` being installed.

### To Reproduce

CuPy 10.6.0 _without_ `scipy` succeeds:

```py
In [1]: import cupy

In [2]: cupy.__version__
Out[2]: '10.6.0'

In [3]: import cupyx.scipy.linalg

In [4]: import scipy
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 import scipy

ModuleNotFoundError: No module named 'scipy'
```

CuPy 11.0.0 _without_ `scipy` fails:

```python
In [1]: import cupy

In [2]: cupy.__version__
Out[2]: '11.0.0'

In [3]: import cupyx.scipy.linalg
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 import cupyx.scipy.linalg

File /datasets/pentschev/miniconda3/envs/rn-220729/lib/python3.8/site-packages/cupyx/scipy/linalg/__init__.py:2, in <module>
      1 # flake8: NOQA
----> 2 from cupyx.scipy.linalg._special_matrices import (
      3     tri, tril, triu, toeplitz, circulant, hankel,
      4     hadamard, leslie, kron, block_diag, companion,
      5     helmert, hilbert, dft,
      6     fiedler, fiedler_companion, convolution_matrix
      7 )
      8 from cupyx.scipy.linalg._solve_triangular import solve_triangular  # NOQA
      9 from cupyx.scipy.linalg._decomp_lu import lu, lu_factor, lu_solve  # NOQA

File /datasets/pentschev/miniconda3/envs/rn-220729/lib/python3.8/site-packages/cupyx/scipy/linalg/_special_matrices.py:4, in <module>
      2 import cupy
      3 from cupy import _core
----> 4 from cupyx.scipy.linalg import _uarray
      7 @_uarray.implements('tri')
      8 def tri(N, M=None, k=0, dtype=None):
      9     """ Construct (``N``, ``M``) matrix filled with ones at and below the
     10     ``k``-th diagonal. The matrix has ``A[i,j] == 1`` for ``i <= j + k``.
     11
   (...)
     24     .. seealso:: :func:`scipy.linalg.tri`
     25     """

File /datasets/pentschev/miniconda3/envs/rn-220729/lib/python3.8/site-packages/cupyx/scipy/linalg/_uarray.py:73, in <module>
     71 for func_name in _cp_linalg_functions:
     72     cp_func = getattr(_cp_linalg, func_name)
---> 73     scipy_func = getattr(_scipy_linalg, func_name)
     74     _implemented[scipy_func] = cp_func

AttributeError: 'NoneType' object has no attribute 'eigh'

In [4]: import scipy
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 import scipy

ModuleNotFoundError: No module named 'scipy'

In [5]:
```

CuPy 11.0.0 _with_ `scipy` succeeds:

```python
In [1]: import cupy

In [2]: cupy.__version__
Out[2]: '11.0.0'

In [3]: import cupyx.scipy.linalg

In [4]: import scipy

In [5]:
```

### Installation

_No response_

### Environment

CuPy 10.6.0:

```
OS                           : Linux-4.15.0-189-generic-x86_64-with-glibc2.10
Python Version               : 3.8.13
CuPy Version                 : 10.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.6
SciPy Version                : None
Cython Build Version         : 0.29.30
Cython Runtime Version       : 0.29.30
CUDA Root                    : /datasets/pentschev/miniconda3/envs/rn-220728
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 87d8ccd
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:06:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:07:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:0A:00.0
Device 3 Name                : Tesla V100-SXM2-32GB
Device 3 Compute Capability  : 70
Device 3 PCI Bus ID          : 0000:0B:00.0
Device 4 Name                : Tesla V100-SXM2-32GB
Device 4 Compute Capability  : 70
Device 4 PCI Bus ID          : 0000:85:00.0
Device 5 Name                : Tesla V100-SXM2-32GB
Device 5 Compute Capability  : 70
Device 5 PCI Bus ID          : 0000:86:00.0
Device 6 Name                : Tesla V100-SXM2-32GB
Device 6 Compute Capability  : 70
Device 6 PCI Bus ID          : 0000:89:00.0
Device 7 Name                : Tesla V100-SXM2-32GB
Device 7 Compute Capability  : 70
Device 7 PCI Bus ID          : 0000:8A:00.0
```

CuPy 11.0.0:

```
OS                           : Linux-4.15.0-189-generic-x86_64-with-glibc2.10
Python Version               : 3.8.13
CuPy Version                 : 11.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.6
SciPy Version                : None
Cython Build Version         : 0.29.30
Cython Runtime Version       : 0.29.31
CUDA Root                    : /datasets/pentschev/miniconda3/envs/rn-220729
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10207
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 3c4a4ba
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:06:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:07:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:0A:00.0
Device 3 Name                : Tesla V100-SXM2-32GB
Device 3 Compute Capability  : 70
Device 3 PCI Bus ID          : 0000:0B:00.0
Device 4 Name                : Tesla V100-SXM2-32GB
Device 4 Compute Capability  : 70
Device 4 PCI Bus ID          : 0000:85:00.0
Device 5 Name                : Tesla V100-SXM2-32GB
Device 5 Compute Capability  : 70
Device 5 PCI Bus ID          : 0000:86:00.0
Device 6 Name                : Tesla V100-SXM2-32GB
Device 6 Compute Capability  : 70
Device 6 PCI Bus ID          : 0000:89:00.0
Device 7 Name                : Tesla V100-SXM2-32GB
Device 7 Compute Capability  : 70
Device 7 PCI Bus ID          : 0000:8A:00.0
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kmaehashi**
`scipy=null` test configuration was not working as SciPy was indireclty installed via Optuna.

Closes #6931

### CODE REVIEW

**Comment by kmaehashi** [comment]
Confirmed `SciPy Version                : None` in `cupy.linux.cuda111`.

/test mini

**Comment by asi1024** [comment]
@kmaehashi Could you check the CI failure of cuda111?

**Comment by kmaehashi** [comment]
This is the known one (#6816), the I think it's ok as test collection succeeds.

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
