### PR TITLE
Set CUPY_CI environment variable in Travis CI and AppVeyor

### PR DESCRIPTION
**Pull request by niboshi**
Follow up #2979

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I guess it is ok not to backport it?

**Comment by niboshi** [comment]
Let's backport it.

**Pull request merged**
