### PR TITLE
Alias NumPy error classes

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by kmaehashi** [comment]
:+1: Let's expose other exception/warning classes as well.

```
>>> mod = numpy
>>> [x for x in [getattr(mod, x) for x in dir(mod)] if inspect.isclass(x) and issubclass(x, BaseException)]
[<class 'numpy.AxisError'>, <class 'numpy.ComplexWarning'>, <class 'numpy.ModuleDeprecationWarning'>, <class 'numpy.RankWarning'>, <class 'numpy.TooHardError'>, <class 'numpy.VisibleDeprecationWarning'>]
```

**Comment by toslunar** [comment]
Is it OK to test `cupy.AxisError is numpy.AxisError`?  To reserve possible future changes like adding cusolver devinfo to `cupy.linalg.LinAlgError`, I suppose we don't promise more than `issubclass(cupy.AxisError, numpy.AxisError)`.

**Comment by kmaehashi** [comment]
> To reserve possible future changes like adding cusolver devinfo to `cupy.linalg.LinAlgError`, I suppose we don't promise more than `issubclass(cupy.AxisError, numpy.AxisError)`.

Good point! I agree only testing `issubclass(cupy.AxisError, numpy.AxisError)`.

**Review by kmaehashi — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
