### PR TITLE
Add `special.{i0e, i1e}`

### PR DESCRIPTION
**Pull request by khushi-411**
Hi,
The PR adds `cupyx.special.{i0e, i1e}` special functions in cupy. Looking forward to your viewpoints. Thanks!

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, @takagi!
Thanks for merging this PR! :)

**Comment by khushi-411** [comment]
I think the failure is irrelevant to the PR. Your opinions, please :) Thanks!
```
=========================== short test summary info =========================== |  
-- | --
02:01:19.682270 STDOUT 4016] | FAILED cupy_tests\cuda_tests\test_memory_hook.py::TestMemoryHook::test_hook |  
02:01:19.682270 STDOUT 4016] | = 1 failed, 97674 passed, 4497 skipped, 683 deselected, 107 xfailed, 1774 warnings in 6683.34s (1:51:23) = |  
02:01:19.684222 STDOUT 4016] | Uploading test results... | 6.6s
02:01:26.318005 STDOUT 4016] | Build Log: https://storage.googleapis.com/chainer-artifacts-pfn-public-ci/cupy-ci/97756/cupy_build_log.txt |  
02:01:26.321791 STDOUT 4016] | Test Log: https://storage.googleapis.com/chainer-artifacts-pfn-public-ci/cupy-ci/97756/cupy_test_log.txt |  
02:01:26.596349 STDERR 4016] | Test failed with status 1 |  
02:01:26.596349 STDERR 4016] | At C:\Windows\TEMP\flexci\run-00199068\work\src\.pfnci\windows\test.ps1:134 |  
02:01:26.596349 STDERR 4016] | char:9 |  
02:01:26.596349 STDERR 4016] | +         throw "Test failed with status $test_retval" |  
02:01:26.596349 STDERR 4016] | +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ |  
02:01:26.596349 STDERR 4016] | + CategoryInfo          : OperationStopped: (Test failed with status 1:Str |  
02:01:26.596349 STDERR 4016] | ing) [], RuntimeException |  
02:01:26.596349 STDERR 4016] | + FullyQualifiedErrorId : Test failed with status 1
```

**Comment by takagi** [comment]
Yeah, your change should not be responsible for the failure. Let me kick CI again.

**Review by takagi — APPROVED** [review]
LGTM, thanks!

**Comment by takagi** [comment]
Rel #6324.

**Pull request merged**
