### PR TITLE
Fix test skip issue

### PR DESCRIPTION
**Pull request by kmaehashi**
Follow-up #5791

I failed to test #5791 correctly... I confirmed this PR correctly skips on CUDA 10.2.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
Let me merge this as `cupy.linux.cuda114` is already confirmed at https://ci.preferred.jp/cupy.linux.cuda114/79852/

**Pull request merged**
