### PR TITLE
Use `.imag = 0` at hipFFT workaround

### PR DESCRIPTION
**Pull request by toslunar**
Nitpick at #3896.

### CODE REVIEW

**Comment by leofang** [comment]
Hi @toslunar Thanks for the code fix, but unfortunately there is a reason I didn't do this. For real arrays (either NumPy or CuPy) we can't overwrite their imaginary components:
```python
>>> import cupy as cp
>>> a = cp.arange(33, dtype=cp.float32)
>>> a.imag = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1143, in cupy.core.core.ndarray.imag.__set__
    _math._ndarray_imag_setter(self, value)
  File "cupy/core/_routines_math.pyx", line 83, in cupy.core._routines_math._ndarray_imag_setter
    raise TypeError('cupy.ndarray does not have imaginary part to set')
TypeError: cupy.ndarray does not have imaginary part to set
>>> 
>>> import numpy as np
>>> a = np.arange(33, dtype=cp.float32)
>>> a.imag = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: array does not have imaginary part to set
```
And when we arrive here there's no guarantee that the input would be complex. Perhaps you could add a comment instead?

**Comment by toslunar** [comment]
After `a = _convert_dtype(a, value_type)` with `value_type='C2R'` (or `'C2C'`), we have complex `a.dtype`.  Then, its `imag` attribute is writable.
```
>>> a = np.arange(3, dtype=np.complex64)
>>> a.imag = 1
>>> a
array([0.+1.j, 1.+1.j, 2.+1.j], dtype=complex64)
```

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Let me test this on my AMD build later today.

**Review by leofang — APPROVED** [review]
Thank you for your explanation, @toslunar! You're absolutely right. I don't know what I was thinking 😅 Good catch! All FFT tests passed locally on a Radeon VII +  ROCm 3.5.0.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
