### PR TITLE
Fix document about fusion functions

### PR DESCRIPTION
**Pull request by okuta**
Some document of function are blank. Please see [this](https://docs-cupy.chainer.org/en/v2/reference/generated/cupy.copy.html)

This PR fixes this problem.

### CODE REVIEW

**Comment by niboshi** [comment]
* `logic.truth.all` and `logic.truth.any` do not have docstring. Can you write them?
* `ufunc`s still generate no documentation. I think [this line](https://github.com/okuta/cupy/blob/23f8dabaa809ed58b86d52c516d598a450f3d157/cupy/core/fusion.py#L682) should be `cupy_op.__doc__`.

**Comment by okuta** [comment]
OK, I will create other PRs.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
