### PR TITLE
Switch from `.A` attribute to `.todense()` method

### PR DESCRIPTION
**Pull request by jakirkham**
The sparse matrix `.A` attribute is deprecated in SciPy (and [removed in 1.14.0]( https://docs.scipy.org/doc/scipy-1.14.1/release/1.14.0-notes.html#expired-deprecations )) and is sometimes used with NumPy & SciPy in the tests. So swap it out for the `.todense()` method, which is not deprecated. The behavior and results should be the same. This just avoids deprecation warnings or errors from SciPy.

xref: https://github.com/scipy/scipy/pull/14822
xref: https://github.com/scipy/scipy/pull/20499

### CODE REVIEW

**Comment by jakirkham** [comment]
Noticed some other code uses `toarray()` ( for example: https://github.com/cupy/cupy/pull/8508 )

Happy to switch to that if preferred

**Comment by kmaehashi** [comment]
Thanks John! `toarray` sounds better as CuPy does not have `cp.matrix`.

**Comment by jakirkham** [comment]
Thanks Kenichi! 🙏

Sounds good. Included the change.

**Review by kmaehashi — APPROVED** [review]
Thanks, LGTM!

**Comment by jakirkham** [comment]
Thanks Kenichi! 🙏

**Pull request merged**
