### PR TITLE
Array and array wrap

### LINKED ISSUE #589: __array__ and __array_wrap__
A question about the Numpy array interface. `cupy.ndarray` implements `__array__`, but  it doesn't work since `np.asarray(cupy_array)` raises an exception:
```
ValueError: object __array__ method not producing an array
```
So unless you have other plans for this method, it should be changed to return a Numpy array.

Do you want a PR? I'd also like to have the `__array_wrap_` method, so I'd implement that one as well.

### PR DESCRIPTION
**Pull request by kohr-h**
Closes #589

### CODE REVIEW

**Comment by hvy** [comment]
Removed my assignment as this PR should be addressed alongside/post #589 .

**Comment by kmaehashi** [comment]
Related: https://github.com/rapidsai/cudf/issues/4552

**Comment by asi1024** [comment]
@kohr-h Sorry for our late response.
We don’t want implicit conversions to NumPy arrays as the default behavior, because it often causes silent bugs and performance degradations.

**Comment by asi1024** [comment]
We decided not to allow implicit conversion to NumPy arrays in #3421.

**Comment by kohr-h** [comment]
Better late than never :wink: 
Reasonable choice, thanks for the explanation!

**Pull request closed without merging**
