### PR TITLE
Remove dtype option which is introduced in v1.11

### PR DESCRIPTION
**Pull request by unnonouno**
`dtype` option for `randint` method is supported since v1.11. We need to support v1.10.

### CODE REVIEW

**Comment by niboshi** [comment]
It has been introduced to fix some problem in #413.
If `dtype` is removed, I think another fix is needed.

@okuta How do you think?

**Comment by unnonouno** [comment]
What happens?

**Comment by niboshi** [comment]
Well, my guess is that in Windows, `np.int` is int32 by default, so `0xffffffff` is not representable.
I think changing to `0x7fffffff` should fix the problem.

**Comment by unnonouno** [comment]
I think it's enough.

**Comment by okuta** [comment]
How about fixing tests? Please see #413.

**Comment by unnonouno** [comment]
If `0x7fffffff` solves the problem, it is better.

**Comment by unnonouno** [comment]
I fixed max random value and stopped skipping tests.

**Comment by niboshi** [comment]
LGTM!

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
