### PR TITLE
Add basic CUDA 11.5 support

### PR DESCRIPTION
**Pull request by leofang**
Part of #5929. There is no new arch added to this CUDA release.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks! Running test: https://ci.preferred.jp/cupy.linux.cuda115/83347/

**Comment by leofang** [comment]
@kmaehashi Pending the discussion in #5992.

**Comment by kmaehashi** [comment]
Seems CUDA 11.5 docker image is not available yet 😓  https://hub.docker.com/r/nvidia/cuda
Manually copied Dockerfiles from container-images repo. 

Running test: https://ci.preferred.jp/cupy.linux.cuda115/83361/

**Comment by leofang** [comment]
> Pending the discussion in #5992.

**UPDATE**: We choose either this PR or #5993.

**Comment by kmaehashi** [comment]
Closing as #5993 merged.

**Pull request closed without merging**
