### PR TITLE
Revert "Support batched SVD"

### PR DESCRIPTION
**Pull request by emcastillo**
Reverts cupy/cupy#4628

Lets check CIs if we revert this

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Can I do one little experiment here? I wanna remove skip

**Comment by emcastillo** [comment]
Release is next week, and there is national holiday next tuesday, so we think it might be better to merge this pr first and address the concerns in a new one 😁

**Comment by leofang** [comment]
Right, nvm. The changes I wanna test cannot be done in the revert PR. Let's get this in asap and I'll try them in another PR.

**Comment by leofang** [comment]
Connection failure in a few CIs. Restarting...

Jenkins, test this please

**Comment by leofang** [comment]
Is the CI dead? Progress got aborted...

Jenkins, test this please

**Comment by leofang** [comment]
Looks like simple timeouts.

Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Looks like the CI is not accepting jobs?

**Comment by leofang** [comment]
btw it'd be great if the SVD fix https://github.com/cupy/cupy/pull/4690 could be tested on daily shuffle.

**Comment by emcastillo** [comment]
Let's favour #4690 over this

**Pull request closed without merging**
