### PR TITLE
Enable new random api in ROCm 4.3

### LINKED ISSUE #5892: Support new random API in ROCm
### Description

Seems that the blocker for implementing this feature was already addressed in 
https://github.com/ROCm-Developer-Tools/HIP/issues/2186

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #5892

### CODE REVIEW

**Comment by emcastillo** [comment]
PTAL!
Tests passed locally :)

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
This should work now for all rocm versions.

4.0, and 4.2 does not support some of the required templating and indirection functionalities, so the API only works with  >+ 4.3 :(

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by kmaehashi** [comment]
Sorry for the delay :bow:
Let me kick the Jenkins again.

pfnCI, run Jenkins please.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Confirmed generator API tests run in ROCm 4.3!

**Pull request merged**
