### PR TITLE
Treat sphinx warnings as errors

### PR DESCRIPTION
**Pull request by niboshi**
Port from Chainer: https://github.com/chainer/chainer/pull/3069

### CODE REVIEW

**Comment by unnonouno** [comment]
It causes a warning for `ReductionKernel.__call__`. Maybe it is because this method uses `**kwargs` and `*args` in Cython. We can ignore this warnings. Do you have an idea?

**Comment by niboshi** [comment]
We can't ignore this warning, because it generates incorrect documentation (empty arguments).
I made a fix in #455, so please merge it.

**Comment by unnonouno** [comment]
Oh, i see.

**Comment by niboshi** [comment]
We need #355 (or other way) to avoid warnings originating from NumPy documentation.

**Comment by unnonouno** [comment]
Can you merge the master?

**Comment by niboshi** [comment]
Rebased.

**Comment by niboshi** [comment]
Please merge #483. It will fix doctest warning.

**Comment by okuta** [comment]
I merged #483

**Comment by niboshi** [comment]
Also #484 may be needed.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
I got this error:
```
WARNING: [autosummary] failed to import u'cupy.cuda.memory_hooks.DebugPrintHook': no module named cupy.cuda.memory_hooks.DebugPrintHook
```

**Comment by niboshi** [comment]
Ah, yes, I made a fix for that (#483), but it resulted in a strange import error...
So I reverted it (#486)...

**Comment by niboshi** [comment]
The above problem has been solved in #502 and I rebased.
(Hopefully) this PR is ready for merge.

**Comment by niboshi** [comment]
bump

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
