### PR TITLE
Add cupy.nan

### LINKED ISSUE #307: cupy.nan is non-existent
Although `numpy.nan` exists, `cupy.nan` does not.

### PR DESCRIPTION
**Pull request by delta2323**
Fix #307 

This PR add `cupy.nan` which is identical to `numpy.nan`.

### CODE REVIEW

**Comment by niboshi** [comment]
I think an alias to `numpy.nan` is not appropriate. For example, `cupy.isnan(cupy.nan)` will not work.
Perhaps we have to define 1-sized `ndarray` or CUDA-backed scalar? (maybe related to #144).
But in that case, in which device that memory should be allocated is a potential problem...

(By the way, we also want `cupy.inf`).

**Comment by delta2323** [comment]
I tried several patterns and it seems to work except the difference mentioned in #144.

```
In [18]: cupy.isnan(cupy.full((10,), cupy.nan))
Out[18]: array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [19]: cupy.isnan(cupy.nan)
Out[19]: array(True, dtype=bool)

In [20]: cupy.isnan(numpy.nan)
Out[20]: array(True, dtype=bool)

In [21]: numpy.isnan(cupy.nan)
Out[21]: True
```

**Comment by niboshi** [comment]
Oops, `cupy.isnan(numpy.nan)` failed in my environment, but it does not reproduce.
Maybe the working tree at that moment was broken? I'm sorry.

**Comment by delta2323** [comment]
I discussed the matter with @okuta and concluded that we need to discuss its specification in #307. So I close this PR for the time being.

**Comment by kaish114** [comment]
`cupy.isnan` **implementation** has been done or not??

**Pull request closed without merging**
