### PR TITLE
Package the tests

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the tests are included in `sdist`s.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
I think -- I may be wrong -- @jakirkham is working on conda-forge/staged-recipes#9959 and he needs to include the tests in the Conda recipe.

**Comment by jakirkham** [comment]
That's right. We would like to download the `sdist` from PyPI and have the tests already included there. As Leo says, this will help with the Conda package.

**Comment by kmaehashi** [comment]
Thanks for the followup! I'll proceed to merge after the release.

**Comment by jakirkham** [comment]
Should we do before so they are included in the release? 😉 Though no pressure. 🙂

**Comment by kmaehashi** [comment]
@jakirkham Actually we're preparing wheels two days before the release, sorry that I couldn't include this in the release today.

**Comment by jakirkham** [comment]
> Actually we're preparing wheels/sdists two days before the release, sorry that I couldn't include this in the release today.

No worries at all. Just figured I'd ask.

Looking forward to the release! 😄

**Pull request merged**
