### PR TITLE
Add parallel build feature

### PR DESCRIPTION
**Pull request by emcastillo**
Use the `CUPY_NUM_BUILD_JOBS` to control the number of modules being built in parallel.

This PR enables the parallel compilation of thrust and cub, which are the modules that takes most of the time.
When building for all the compute archs, the master branch buiold time is 18 minutes, with this PR it becomes 9 minutes.
Moreover, if we limit to a single compute capability with something like `CUPY_NVCC_GENERATE_CODE=arch=compute_62,code=sm_62` , we get a build time of 3 minutes, which is enough for the majority of the users.

Currently, the default is 4 processes because as long as we ensure that there are two threads, cub and thrust will be built independently.

Cub and Thrust are a single .cu file that is built for all the compute archs, and this is what takes the majority of the compile time. Unfortunately this process can't be parallelized unless we run `nvcc ... --dryrun` and run these commands in a different thread by ourselves.

Credit goes to this SO post:
https://stackoverflow.com/questions/11013851/speeding-up-build-process-with-distutils

### CODE REVIEW

**Comment by emcastillo** [comment]
BTW, `pip install -e . --global-option="build_ext" --global-option="-j4"` achieves the same 😄

**Comment by kmaehashi** [comment]
Setting `self.parallel = True` in `custom_build_ext` instance seems enough?
https://github.com/pypa/setuptools/blob/400b71c9b932893ab97dd6368ae7bfb822064a87/setuptools/_distutils/command/build_ext.py#L454

**Comment by kmaehashi** [comment]
This closes #1961

**Comment by emcastillo** [comment]
fixed to use self.parallel

**Comment by leofang** [comment]
> Setting `self.parallel = True` in `custom_build_ext` instance seems enough?

So neat! Why isn't this undocumented?!

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM!

**Comment by kmaehashi** [comment]
@emcastillo Could you add `CUPY_NUM_BUILD_JOBS` to docs?

**Comment by kmaehashi** [comment]
Currently, instability is discovered in some environments. See #4344 for details.

**Pull request merged**
