### PR TITLE
[backport] Support 0-sized arrays for `linalg.qr`

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #2586

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Sorry, I mistook and merged it by accident 😥

**Comment by toslunar** [comment]
LGTM.  No worries, @emcastillo.

**Comment by emcastillo** [comment]
thanks!!
🙇

**Pull request merged**
