### PR TITLE
Add `CUDA_VERSION` define for Cython compilation

### PR DESCRIPTION
**Pull request by emcastillo**
Probably this is not the best place to do this but I have 0 knowledge of the building/compilation system.
Would love some feedback on where to set this option.

The main reason for this is to allow compile-time conditionals such as `IF CUDA_VERSION` in the *pyx *pxd files to avoid compilation errors within different CUDA versions when accessing struct fields and so.

BTW, `compile_time_env` is not documented in `cythonize` args so this is also scary, but there is no other way to set this. https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#cythonize-arguments

### CODE REVIEW

**Comment by leofang** [comment]
`compile_time_env` was once added in https://github.com/cupy/cupy/pull/3534/commits/6479c0e03faadbb0d2893c2a2648a55120ea0bc5 but got removed later.

**Comment by leofang** [comment]
I also need `compile_time_env` for #3892. There, cuFFT and hipFFT have different types for the plan handle...(`int` vs `struct*`, wtf).

**Comment by kmaehashi** [comment]
Resolved conflict.
pfnCI, test this please.

**Comment by emcastillo** [comment]
Seems like AMD CI needs an additional package 😅

```



2020-09-29 11:19:27.452921 STDOUT 2085] | compile_time_env['CUDA_VERSION'] = build.get_cuda_version() |  
2020-09-29 11:19:27.452924 STDOUT 2085] | File "/tmp/flexci/run-00130544/tmp/pip-13jpwmr6-build/install/build.py", line 321, in get_cuda_version |  
2020-09-29 11:19:27.452929 STDOUT 2085] | raise RuntimeError(msg) |  
2020-09-29 11:19:27.452966 STDOUT 2085] | RuntimeError: check_cuda_version() must be called first. |  
2020-09-29 11:19:27.452967 STDOUT 2085] | Error in sys.excepthook: |  
2020-09-29 11:19:27.452971 STDOUT 2085] | Traceback (most recent call last): |  
2020-09-29 11:19:27.452996 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook |  
2020-09-29 11:19:27.452998 STDOUT 2085] | from apport.fileutils import likely_packaged, get_recent_crashes |  
2020-09-29 11:19:27.453001 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module> |  
2020-09-29 11:19:27.453031 STDOUT 2085] | from apport.report import Report |  
2020-09-29 11:19:27.453033 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module> |  
2020-09-29 11:19:27.453036 STDOUT 2085] | import apport.fileutils |  
2020-09-29 11:19:27.453060 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module> |  
2020-09-29 11:19:27.453062 STDOUT 2085] | from apport.packaging_impl import impl as packaging |  
2020-09-29 11:19:27.453065 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module> |  
2020-09-29 11:19:27.453111 STDOUT 2085] | import apt |  
2020-09-29 11:19:27.453113 STDOUT 2085] | File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module> |  
2020-09-29 11:19:27.453131 STDOUT 2085] | import apt_pkg |  
2020-09-29 11:19:27.453133 STDOUT 2085] | ModuleNotFoundError: No module named 'apt_pkg' |  
2020-09-29 11:19:27.453159 STDOUT 2085]


```

**Comment by leofang** [comment]
No, it's just that you need to call `check_cuda_version()` before calling `get_cuda_version()`.

**Comment by emcastillo** [comment]
I will fix the if to avoid calling get cuda version if we are using hip

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
