### PR TITLE
Address KeyErrors from importlib_metadata

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes: https://github.com/cupy/cupy/issues/8440

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks @hmaarrfk! This PR itself looks fine and I'm happy to merge, but curious why this happens, because CuPy uses `importlib.metadata` and not `importlib_metadata` (which is from the PyPI package). Is there a platform doing `importlib.metadata = importlib_metadata` somewhere?

**Review by kmaehashi — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Hmmm. I understand that difference but all I can tell is that downgrading importlib_metadata helped resolve things for me.

I can investigate more but I feel like it is related to leftover files after a package is uninstalled. Which is really hard to simulate.

**Comment by kmaehashi** [comment]
Thanks @hmaarrfk, let's merge as anyways it's needed for Python 3.14 according to https://github.com/python/importlib_metadata/issues/497 😄

**Pull request merged**
