### PR TITLE
Support fusion feature of copyto method

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure is unrelated to the PR.

**Comment by toslunar** [comment]
I asked @asi1024 to debug the following:
```python
def f(x):
    y = cupy.mod(x, numpy.pi)
    cupy.copyto(y, 0, where=x < numpy.pi)
    return y

x = cupy.arange(10)
f(x)
"""
array([0.        , 0.        , 0.        , 0.        , 0.85840735,
       1.85840735, 2.85840735, 0.71681469, 1.71681469, 2.71681469])
"""

f = cupy.fuse()(f)
f(x)
"""
array([0., 0., 0., 0., 0., 1., 2., 0., 1., 2.])
"""
```

**Comment by okuta** [comment]
How about using this?
```
cupy.copyto(y, y.dtype.type(0), where=x < numpy.pi)
```
or

```
cupy.copyto(y, 0.0, where=x < numpy.pi)
```

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
