### PR TITLE
BUG: Fix the .T attribute in the `array_api` namespace

### PR DESCRIPTION
**Pull request by thomasjpfan**
Stay in sync with NumPy here: https://github.com/numpy/numpy/commit/eb865fa4683bca9a9d7c840f8addd30e39b62f5b

Ports https://github.com/numpy/numpy/pull/20499 to `cupy.array_api`

CC @asmeurer

### CODE REVIEW

**Comment by leofang** [comment]
Thanks, @thomasjpfan! Could you help port the full patch from https://github.com/numpy/numpy/pull/20499? The test should go to `tests/cupy_tests/array_api_tests/test_array_object.py`.

**Review by leofang — APPROVED** [review]
LGTM, thanks Thomas!

**Review by toslunar — APPROVED** [review]

**Comment by toslunar** [comment]
The `docs/readthedocs.org:cupy` failure is irrelevant to the PR.

**Pull request merged**
