### PR TITLE
Support setuptools 74.0.0 or later

### LINKED ISSUE #8568: CuPy fails with setuptools 74.0.0
setuptools v74.0 (specifically https://github.com/pypa/setuptools/pull/4600) removed `setuptools.msvc` module, which has been there for 8 years. Currently, CuPy depends on the module for both build-time and runtime:

* build-time: https://github.com/cupy/cupy/blob/69a2137ec7577adb03407ed3e8db373ee2118b4c/install/cupy_builder/_compiler.py#L265-L266
* runtime (Windows only): https://github.com/cupy/cupy/blob/69a2137ec7577adb03407ed3e8db373ee2118b4c/cupy/cuda/compiler.py#L102

Until the problem is resolved, we will pin the setuptools version in the CI. (#8567)

### Workarounds (for users)

* Windows users seeing `Failed to auto-detect cl.exe path` warning: Do one of the following workarounds:
    1. Downgrade setuptools to v73.x or earlier
    2. Upgrade setuptools to v74.1.0 or later, and do `import setuptools.msvc` along with `import cupy`
    3. Manually add `cl.exe` directory (e.g., `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\`) to `PATH`
* Linux/Windows users experiencing `ModuleNotFoundError: No module named 'setuptools.msvc'` error when building CuPy from source: This problems happens with setuptools v74.0.0 only. Try upgrading setuptools to v74.1.0 or later (or downgrade setuptools to v73.x or earlier).

Both problems will be fixed in the future release (#8583).

### Additional Context

It seems scikit-build is also affected by this change: https://github.com/pypa/setuptools/issues/4608, https://github.com/scikit-build/scikit-build/issues/1114

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #8568. Follows-up #8574. Reverts #8567.

edit: This PR adopts recent setuptools changes, specifically v74.0.0 (which [removed](https://github.com/pypa/setuptools/pull/4600) `setuptools.msvc`) and v74.1.0+ (which [reverted](https://github.com/pypa/setuptools/pull/4626) `setuptools.msvc` but requires explicit module import instead of `import setuptools`).

<details>
<summary>Original description</summary>

On Windows platform with setuptools 74+, it will now take 2-3 seconds to find `cl.exe`. This overhead happens only once per process, and only when the use of `nvcc` is requested.

`setuptools.msvc` (which we rely on for years and is now removed) was able to discover `cl.exe` very quickly as it directly reads the Windows registry. The new approach introduced in this PR (which only uses the public/documented setuptools API) retrives the compiler path through `vcvarsall.bat`, which incurs subprocess invocation.
</detail>

### CODE REVIEW

**Comment by kmaehashi** [comment]
Oops, I just noticed `setuptools.msvc` removal has been reverted...

https://github.com/pypa/setuptools/pull/4626

**Comment by kmaehashi** [comment]
/test mini

This one is review ready!

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
