### PR TITLE
`scipy.linalg.{tri/tril/triu}` are deprecated in SciPy 1.11.0

### PR DESCRIPTION
**Pull request by asi1024**
Part of https://github.com/cupy/cupy/issues/7664.

https://scipy.github.io/devdocs/release/1.11.0-notes.html#deprecated-features

### CODE REVIEW

**Comment by takagi** [comment]
`to-be-backport` is for test code only.

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by asi1024** [comment]
https://ci.preferred.jp/cupy.linux.cuda-head/144697/

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
{tri/tril/triu} test failures are gone in the head test.

**Pull request merged**
