### PR TITLE
Add CUDA 10.2 support

### PR DESCRIPTION
**Pull request by ksangeek**
I was working to build `cupy` for `linux-ppc64le` with cudatoolkit `10.2` and got these kind of errors with multiple tests when running certain tests -
```python
______________________________ TestNdarrayDeepCopy_param_2.test_deepcopy ______________________________

self = <cupy.testing.parameterized.TestNdarrayDeepCopy_param_2 testMethod=test_deepcopy>

    def test_deepcopy(self):
        arr = core.ndarray(self.shape)
>       arr2 = copy.deepcopy(arr)

core_tests/test_ndarray.py:140:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../conda3/envs/cupy_py36/lib/python3.6/copy.py:161: in deepcopy
y = copier(memo)
cupy/core/core.pyx:1084: in cupy.core.core.ndarray.__deepcopy__
???
cupy/core/core.pyx:1085: in cupy.core.core.ndarray.__deepcopy__
???
cupy/core/core.pyx:419: in cupy.core.core.ndarray.copy
???
cupy/core/core.pyx:389: in cupy.core.core.ndarray.astype
???
cupy/core/_kernel.pyx:864: in cupy.core._kernel.ufunc.__call__
???
cupy/core/_kernel.pyx:876: in cupy.core._kernel.ufunc._get_ufunc_kernel
???
cupy/core/_kernel.pyx:638: in cupy.core._kernel._get_ufunc_kernel
???
cupy/core/_kernel.pyx:60: in cupy.core._kernel._get_simple_elementwise_kernel
???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: Parameterized test failed.
E
E   Base test method: TestNdarrayDeepCopy.test_deepcopy
E   Test parameters:
E     shape: (1,)
E
E   RuntimeError: Failed to auto-detect CUDA root directory. Please specify `CUDA_PATH` environment variable if you are using CUDA v9.0, v9.1 or versions not yet supported by CuPy.

cupy/core/carray.pxi:153: AssertionError
```

That is when I realized that some changes are required to make that work.
I took PR https://github.com/cupy/cupy/pull/2117/files from @kmaehashi where CUDA 10.1 support was added as a reference and made changes for CUDA 10.2.

With these changes, I am no longer getting the earlier seen error to detect CUDA.
It would be really helpful if someone can guide on any other changes required to make this work complete. Thank you.

### CODE REVIEW

**Comment by ksangeek** [comment]
Hi @kmaehashi
1. After looking into the code a bit more today, the issue I reported without this patch is for the case when `cudatoolkit 10.2` is installed as a conda package. If I have `cudatookit 10.2` installed on the host I don't see this issue.

2. To verify this patch on an x86 machine, I compared the `tests/cupy_tests` results with `cupy 6.6.0` from conda-forge (https://anaconda.org/conda-forge/cupy) and the one I built with this patch for `cuda 10.2`. Here is the summary of pytest results -

    a. `cupy 6.6.0` from conda-forge and `cudatoolkit 10.1.243` conda package -
    ```
    ==== 1 failed, 14548 passed, 64 skipped, 51 warnings in 1880.15s (0:31:20) =====
     ```

    b. `cupy 6.6.0` with this patch and `cudatoolkit 10.2.89` conda package -

    ```
    ==== 19 failed, 14530 passed, 64 skipped, 48 warnings in 1875.91s (0:31:15) ====
    ```
    I see 18 additional test case failures with this patched conda package. All the new failures are in `tests/cupy_tests/fft_tests/test_fft.py`.

3. Here is the list of failed tests in `test_fft.py` -
```python
fft_tests/test_fft.py::TestFft2_param_1::test_fft2 dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestFft2_param_1::test_ifft2 dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestFftn_param_1::test_fftn dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestFftn_param_1::test_ifftn dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestFftn_param_8::test_fftn dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestFftn_param_8::test_ifftn dtype is <class 'numpy.float64'>
enable_nd is True
FAILED
fft_tests/test_fft.py::TestRfft2_param_1::test_irfft2 dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfft2_param_1::test_rfft2 dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_1::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_1::test_rfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_7::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_8::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_8::test_rfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_9::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_10::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_11::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_13::test_irfftn dtype is <class 'numpy.float64'>
FAILED
fft_tests/test_fft.py::TestRfftn_param_15::test_irfftn dtype is <class 'numpy.float64'>
FAILED
```

Attaching the detailed test logs -
[cupy_tests_only_with_cuda_10.2_patch_numpy_1.17_results_x86.txt](https://github.com/cupy/cupy/files/4049545/cupy_tests_only_with_cuda_10.2_patch_numpy_1.17_results_x86.txt)


Please let me know your opinion on these test results. Thank you!

**Comment by kmaehashi** [comment]
Sorry for the delayed response. There are two reasons why test fail:

* CuPy tests may fail if MKL-backed NumPy due as it behaves slightly different than usual NumPy. https://github.com/cupy/cupy/issues/2467
* There's a bug in CUDA 10.1 Update 2 and 10.2, which was fixed in https://github.com/cupy/cupy/pull/2922

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by ksangeek** [comment]
> Sorry for the delayed response. There are two reasons why test fail:
> 
> * CuPy tests may fail if MKL-backed NumPy due as it behaves slightly different than usual NumPy. #2467
> * There's a bug in CUDA 10.1 Update 2 and 10.2; workaround was added in #2922

Thanks @kmaehashi for providing the pointers.

**Comment by leofang** [comment]
@kmaehashi Did the CI test this PR against CUDA 10.2?

**Comment by leofang** [comment]
The backport PR is #3218.

**Comment by kmaehashi** [comment]
Added `backport` label to #3218 to avoid further bot comments. Sorry for the noise.

**Pull request merged**
