### PR TITLE
Add special functions from the CUDA Math API

### PR DESCRIPTION
**Pull request by grlee77**
This is a small PR adding simple ufunc wrappers for a handful of other CUDA Math API functions that overlap with functions in `cupyx.scipy.special`.

One question:

- For sinc: `scipy.special.sinc` **is** `numpy.sinc`. This function promotes any integer dtype to double while the implementation here does not. For example, for `cupy.sinc` as used here, providing `cp.int8` input will result in a `cp.float16` array being returned. Should we make a wrapper that promotes any ints to `cp.float64` for consistency with SciPy?

### CODE REVIEW

**Comment by grlee77** [comment]
I guess the since question is not specific to the special namespace. In general it is `cupy.sinc` that behaves differently from `numpy.sinc` in regards to integer type promotions.

**Comment by grlee77** [comment]
Please test again (the prior failure in `test_yn` should now be fixed).

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
LGTM! Thanks!

**Pull request merged**
