### PR TITLE
[backport] Fix cuSPARSE module build failure with CUDA 10.1 on Windows

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix cusparse versioning bug (manual backport of #4419)

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
