### PR TITLE
Introduce cupyx namespace

### PR DESCRIPTION
**Pull request by kmaehashi**
As discussed in https://github.com/cupy/cupy/pull/846, we introduce `cupyx` namespace to implement features specific to CuPy.

Note that although there are some other CuPy-specific entities like `ElementwiseKernel` under `cupy` namespace, they are kept as is, as it is less likely to conflict with future versions of NumPy.

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM, but should we deprecate `cupy.scatter_add` (by making it raise `DeprecationWarning`)?

**Comment by niboshi** [comment]
Also, I think it's better to mention other CuPy-specific identities which reside in `cupy` namespace.
That can be another PR, though.

**Comment by kmaehashi** [comment]
> LGTM, but should we deprecate cupy.scatter_add (by making it raise DeprecationWarning)?

I agree, fixed the code to emit the warning.

> Also, I think it's better to mention other CuPy-specific identities which reside in cupy namespace.

As CuPy is expected to behave as a drop-in replacement of NumPy, I personally feel that most users are not interested in that list. I'd like to rather prepare the reverse, i.e., what is missing in CuPy (https://github.com/cupy/cupy/issues/685).  Let's discuss this in another issue if needed, anyway.

**Comment by okuta** [comment]
When will this PR merge?

**Comment by kmaehashi** [comment]
Rebased to the latest master.

**Comment by niboshi** [comment]
Please fix test failures.

**Comment by kmaehashi** [comment]
Fixed doctest.
Chainer test failures should be fixed after merging https://github.com/chainer/chainer/pull/4363.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
