### PR TITLE
[WIP] Add Dependabot configuration to auto-update docs dependencies

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by leofang** [comment]
FYI: NumPy folks are considering to remove dependabot 
https://github.com/numpy/numpy/issues/18977
Maybe we should see what they find...

**Comment by kmaehashi** [comment]
Dependabot is disabled by default in forks. But once you opt-in with your fork, there's no way to disable it 😓 
https://github.com/twbs/bootstrap/discussions/31385

**Comment by leofang** [comment]
https://github.com/dependabot/dependabot-core/issues/2198

**Comment by kmaehashi** [comment]
Ok I struggled a bit but couldn't turn dependabot off in forks. Let's wait until the bug is fixed...

**Pull request closed without merging**
