### PR TITLE
Fix shaped_random for complex number

### PR DESCRIPTION
**Pull request by not522**
The original implementation of shaped_random always generates real number even if `dtype` indicates complex number.

### CODE REVIEW

**Comment by unnonouno** [comment]
It seems good. Can you write a test for this method? It is ok only to check dtype and shape of return values.

**Comment by not522** [comment]
I added test for `shaped_random`. It checks shape, dtype, value range, and the behavior for `numpy.bool_`.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
LGTM

**Pull request merged**
