### PR TITLE
Support NumPy 1.16

### LINKED ISSUE #1879: Support NumPy 1.16

### PR DESCRIPTION
**Pull request by okuta**
Close #1879

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
I removed unused import.

**Comment by okuta** [comment]
I fixed.
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure (`TestModifiedXLogX_param_0.test_backward_gpu`) is unrelated to the PR.

**Pull request merged**
