### PR TITLE
[backport] Add NumPy 1.18 to installation guide

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #3005

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
I think it's not necessary to backport this fix?

**Comment by kmaehashi** [comment]
> I think it's not necessary to backport this fix?

Support for newer versions of dependency should be backported (e.g. https://github.com/cupy/cupy/pull/2880), as well as the docs.

**Comment by niboshi** [comment]
It seems not all the  fixes were backported.
#2991

**Comment by niboshi** [comment]
I'll merge this for the following reason:

The fixes in #2991 not yet backported are fixes to change CuPy interfaces to match NumPy 1.18.
They are not fixes for using CuPy along with NumPy 1.18.
They are not necessarily required for claiming "NumPy 1.18 support".

**Pull request merged**
