### PR TITLE
Rename CHAINER_SEED

### PR DESCRIPTION
**Pull request by niboshi**
I think this environment variable should be renamed.

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
Many projects use ``CHAINER_SEED``.
https://github.com/search?p=1&q=CHAINER_SEED&type=Code&utf8=%E2%9C%93

We need fixing Chainer or writing migration document.
Are you planning to send the PR to Chainer project.

**Comment by niboshi** [comment]
I don't have any plan yet.
Actually, I think we need to reconsider random seeding in Chainer.

(Related issue: https://github.com/pfnet/chainer/issues/2679)

Maybe we should not merge this PR until we fix the overall strategy.

**Comment by gwtnb** [comment]
How about check `CHAINER_SEED` when `CUPY_SEED` is not set? Chainer v2 will be released soon, so we should not change the behavior of `CHAINER_SEED`.

**Comment by niboshi** [comment]
@gwtnb Fixed. Could you review?

**Comment by gwtnb** [comment]
LGTM

**Pull request merged**
