### PR TITLE
Use async memcpy in `ndarray.copy`

### LINKED ISSUE #4988: asarray Ignores the Current Stream
Right now, when copying from one GPU to another, cupy.asarray (and ndarray.copy) execute on the default stream even if some other stream is currently in use. This is because cudaMemcpy always runs on the default stream. This can cause synchronization issues if the next operation on the current stream executes on the copied data. This shows up in a larger app I'm helping with, but we haven't yet found a small example that shows the bad synchronization. I suspect that the fix is to change https://github.com/cupy/cupy/blob/23f0b72e6b9e8c8daf34548ac6649dd164da1c45/cupy/_core/core.pyx#L518 to use copy_from_device_async, but I'm not sure if there would be other undesirable consequences from that approach. Now that we've identified the problem, we can work around this by calling copy_from_device_async directly, but this is a major pitfall for multi-device users. What would be a sane way to fix this? A big thanks to @nicelhc13 for pinning down what was happening on our end.

### PR DESCRIPTION
**Pull request by takagi**
Fix #4988.

This PR fixes `ndarray.copy` to use async memcpy so that it respects the current stream.

I'll try to supply an appropriate testing code.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @pentschev @leofang (for awareness)

**Comment by takagi** [comment]
This PR is ready for review. Would you take a look?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
The test is neat!

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
