### PR TITLE
limit arch to the maximum value allowed in each NVRTC version

### LINKED ISSUE #1048: cupy.cuda.compiler.CompileException: nvrtc: error
Hello,
I met a problem about cuda when I running the code.
I had correctly installed cuda but it does not work.
when I run,
>>>python3 pose_detector1.py posenet models/coco_posenet.npz --img data/person.png -g 0

The error shows:

Loading PoseNet...
Inference scale: 1.5...
NVRTC compilation error: nvrtc: error: invalid value for --gpu-architecture (-arch)

-----
Name: 
Options: -I/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/core/include -ftz=true -arch=compute_61
CUDA source:
1 
-----
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/cuda/compiler.py", line 229, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pose_detector1.py", line 509, in <module>
    person_pose_array = pose_detector(img)
  File "pose_detector1.py", line 435, in __call__
    h1s, h2s = self.model(x_data)
  File "/home/suiishii/Chainer_Realtime_Multi-Person_Pose_Estimation/models/CocoPoseNet.py", line 136, in __call__
    h = F.relu(self.conv1_1(x))
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_2d.py", line 153, in forward_gpu
    x = cuda.cupy.ascontiguousarray(x)
  File "/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/creation/from_data.py", line 92, in ascontiguousarray
    return core.ascontiguousarray(a, dtype)
  File "cupy/core/core.pyx", line 2131, in cupy.core.core.ascontiguousarray
  File "cupy/core/core.pyx", line 2142, in cupy.core.core.ascontiguousarray
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python3.5/dist-packages/cupy-4.0.0b2-py3.5-linux-x86_64.egg/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

Here shows the information of cuda:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 33%   44C    P8    11W / 200W |   1313MiB /  8114MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1260      G   /usr/lib/xorg/Xorg                            47MiB |
|    0      2922      G   /usr/lib/xorg/Xorg                           295MiB |
|    0      3552      G   compiz                                       140MiB |
|    0      3916      G   fcitx-qimpanel                                 8MiB |
|    0     13646      G   ...-token=6178575BADBB10006C9A8F872A29596F   159MiB |
|    0     22760      C   python3                                      109MiB |
|    0     22903      C   python3                                      109MiB |
|    0     23080      C   python3                                      109MiB |
|    0     27219      C   python3                                      109MiB |
|    0     27329      C   python3                                      109MiB |
+-----------------------------------------------------------------------------+

I checked all the information of cuda, but I did not find some problem
Please help me to solve this issue.
Thank you！

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes #1048.
See also: http://docs.nvidia.com/cuda/nvrtc/index.html#group__options

### CODE REVIEW

**Comment by kmaehashi** [comment]
@anaruse Is it by design that `nvcc` supports `compute_61` but NVRTC does not accept `compute_61` on CUDA 8 or earlier? Are there any workarounds? (this question is not urgent, but would like to include this fix in the next release)

**Comment by anaruse** [comment]
`compute_61` is not supported by NVRTC in CUDA 8. You should select one out of the followings for NVRTC of CUDA 8.

- compute_20
- compute_30
- compute_35
- compute_50
- compute_52
- compute_53

**Comment by kmaehashi** [comment]
Thank you for clarification!

**Comment by kmaehashi** [comment]
Fixed CI failure. According to the API reference, NVRTC on CUDA 8.0 does not allow `compute_60` and  `compute_61` as input, but actually it can be compiled...

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
