### PR TITLE
Fix incorrect cast in element-wise op for float array and complex scalar

### LINKED ISSUE #1698: Complex scalar is not correctly casted
```
>>> cupy.arange(3, dtype='e') + 1j
array([0.+1.j, 1.+1.j, 2.+1.j])
>>> numpy.arange(3, dtype='e') + 1j
array([0.+1.j, 1.+1.j, 2.+1.j], dtype=complex64)
```

No problem with floats:
```
>>> cupy.arange(3, dtype='e') + 1e30
array([1.e+30, 1.e+30, 1.e+30], dtype=float32)
>>> cupy.arange(3, dtype='e') + 1e100
array([1.e+100, 1.e+100, 1.e+100])
```

### PR DESCRIPTION
**Pull request by asi1024**
Fix #1698.
Close #1640.

~Merge #1799 first.~

### CODE REVIEW

**Comment by toslunar** [comment]
`fusion.py` also has `_kind_score`.  Does it have the same role?

**Comment by asi1024** [comment]
I found another bug about casting from float to complex in `fuse`, so the test won't be passed now.
I'll fix it and send another PR.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure is unrelated to the PR.

**Pull request merged**
