### PR TITLE
[backport] Rename submodules under `cupy.testing` package

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3868

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
I also made `cupy.testing` change for v8 on behalf of @toslunar that merged #3868. I want to ask someone for reviewing and merging this.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Review by toslunar — APPROVED** [review]
Thanks a lot for backporting it.  LGTM

**Comment by takagi** [comment]
Thanks!

**Pull request merged**
