### PR TITLE
Add nan_to_num

### LINKED ISSUE #1391: Implement nan_to_num
🙏 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.nan_to_num.html

### PR DESCRIPTION
**Pull request by gwtnb**
Fix #1391.

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
```
___________________________ TestMisc.test_nan_to_num ___________________________

self = <cupy_tests.math_tests.test_misc.TestMisc testMethod=test_nan_to_num>

    def test_nan_to_num(self):
>       self.check_unary('nan_to_num')

self       = <cupy_tests.math_tests.test_misc.TestMisc testMethod=test_nan_to_num>

tests/cupy_tests/math_tests/test_misc.py:192: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cupy/testing/helper.py:574: in test_func
    impl(self, *args, **kw)
cupy/testing/helper.py:117: in test_func
    accept_error=accept_error)
cupy/testing/helper.py:50: in _check_cupy_numpy_error
    self.fail('Only numpy raises error\n\n' + numpy_tb)
E   AssertionError: Only numpy raises error
E   
E   Traceback (most recent call last):
E     File "/work/cupy/cupy/testing/helper.py", line 27, in _call_func
E       result = impl(self, *args, **kw)
E     File "/work/cupy/tests/cupy_tests/math_tests/test_misc.py", line 18, in check_unary
E       return getattr(xp, name)(a)
E     File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 377, in nan_to_num
E       maxf, minf = _getmaxmin(y.dtype.type)
E     File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 309, in _getmaxmin
E       f = getlimits.finfo(t)
E     File "/usr/local/lib/python3.5/dist-packages/numpy/core/getlimits.py", line 109, in __new__
E       raise ValueError("data type %r not inexact" % (dtype))
E   ValueError: data type <class 'numpy.bool_'> not inexact```
Cloud you fix this?

**Comment by gwtnb** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
