### PR TITLE
Fix indexing 0-dim array with boolean mask

### PR DESCRIPTION
**Pull request by niboshi**
Fixes a part of #503.

This allows boolean mask on a 0-dim array:
```
a = cupy.ones(())
a[a != 0]
```

### CODE REVIEW

**Comment by takagi** [comment]
Would you check the CI failure?

**Comment by niboshi** [comment]
Thank you, I fixed the mistake.

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
LGTM, I will merge this after I will check the CI passing.

**Pull request merged**
