### PR TITLE
Add `__init__.py` to allow importing test packages

### LINKED ISSUE #3384: fallback mode test fails
On master:
```bash
$ pytest tests/cupyx_tests/fallback_mode_tests/test_notifications.py
========================================================================= test session starts =========================================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.12.0
rootdir: /home/leofang/cupy, inifile: setup.cfg
collected 0 items / 1 error                                                                                                                                           

=============================================================================== ERRORS ================================================================================
____________________________________________ ERROR collecting tests/cupyx_tests/fallback_mode_tests/test_notifications.py _____________________________________________
ImportError while importing test module '/home/leofang/cupy/tests/cupyx_tests/fallback_mode_tests/test_notifications.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cupyx_tests/fallback_mode_tests/test_notifications.py:11: in <module>
    from tests.cupyx_tests.fallback_mode_tests import test_fallback as test_utils
E   ModuleNotFoundError: No module named 'tests.cupyx_tests'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 1 error in 0.31s ===========================================================================
```
I am guess it's related to the pytest version. It seems the CI works fine...

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes #3384

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Some `__init__.py` seems to be still lacking...

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
