### PR TITLE
[backport] Remove some xfails in sorting tests

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3167

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
This PR precedes #3286 and #3291 backports.

**Comment by takagi** [comment]
Let me look into the CI failure.

**Comment by takagi** [comment]
It's because CI uses numpy==1.9.4 and it raises while cupy doesn't.

**Comment by leofang** [comment]
If it's the case, I would suggest skipping the offending tests for older NumPy. I think starting v8.0.0a1 (?) the support of NumPy <v1.15 is dropped.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Thanks, but I suppose dropping older NumPy in v7 minor update is another issue and the failing CI `cupy-py35` is responsible to test the lowest NumPy version supported. Let me require newer NumPy for the specific tests.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
