### PR TITLE
Add `cupy.positive` in API Reference

### LINKED ISSUE #6017: Doc: `cupy.positive` needs to be added in API reference

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Fixes #6017 by updating the docs as discussed in the "issue conversations"

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks, could you move it to the same position as the NumPy's documentation (linked at the top of each RST file)?

**Comment by SauravMaheshkar** [comment]
I'm sorry could you elaborate more.

**Comment by toslunar** [comment]
Please check the NumPy links at the top of each files:
- [NumPy API Reference: Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)
- [NumPy API Reference: Universal functions (numpy.ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)

```rst
.. Hint:: `NumPy API Reference: Mathematical functions <https://numpy.org/doc/stable/reference/routines.math.html>`_
.. Hint:: `NumPy API Reference: Universal functions (numpy.ufunc) <https://numpy.org/doc/stable/reference/ufuncs.html>`_
```

**Comment by SauravMaheshkar** [comment]
Thanks for the clarity 👍. Corrected in 01c1ef8 and d450d9a

**Comment by kmaehashi** [comment]
Thanks, LGTM!

**Pull request merged**
