### PR TITLE
Fix find API interface

### PR DESCRIPTION
**Pull request by okuta**
Current find API interface is a little bit strange.

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM, but it alters the public interface. Should we mark this as non-compat?

**Comment by okuta** [comment]
These functions are not documented. It is very minor and, current implementation has some bug.

**Comment by okuta** [comment]
`feature` label is better.

**Comment by niboshi** [comment]
Yes, I know it's not documented.
But it's been a while since it was introduced, so I concern some advanced users can be using it.
Also I think this change is not crucial for its functionality. I mean if we are going to be conservative, it's easy to keep compatibility and still implement a feature that uses it in stable branch.

**Comment by okuta** [comment]
OK, I understand your concern.
Cloud you merge as no-compatibility PR.

**Comment by niboshi** [comment]
OK, I will not backport.
Btw, what is the bug you mentioned above?

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
