### PR TITLE
Update `array_api`

### PR DESCRIPTION
**Pull request by leofang**
Cherry-pick from upstream PRs:
- https://github.com/numpy/numpy/pull/22747
- https://github.com/numpy/numpy/pull/22365
- https://github.com/numpy/numpy/pull/21928

### CODE REVIEW

**Comment by leofang** [comment]
cc: @asmeurer @seberg

**Review by seberg — APPROVED** [review]

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
@leofang LGTM. Thanks!

**Comment by leofang** [comment]
Thanks @asi1024! btw can we backport this given it fixes two bugs? It's not urgent if it can't meet the code freeze this week 🙂

**Comment by asi1024** [comment]
@leofang Sure!

**Pull request merged**
