### PR TITLE
Fix ROCm build CI

### PR DESCRIPTION
**Pull request by kmaehashi**
ROCm build has not been tested properly.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
pfnCI, test this please

**Comment by leofang** [comment]
@kmaehashi cupy.py3.amd still fails, do you know why?

**Comment by kmaehashi** [comment]
@leofang I think the test now runs, if you have time could you merge my changes to #3786 and fix the error there as well?

**Comment by kmaehashi** [comment]
Test script is here: https://github.com/cupy/cupy/blob/6c70391f2ff066699552bdaf8edd87e9003080f6/.pfnci/script.sh#L64-L78

**Comment by leofang** [comment]
Thanks! Will do!

**Pull request closed without merging**
