### PR TITLE
Disable typecheck with NumPy v1 in CI

### PR DESCRIPTION
**Pull request by asi1024**
Part of https://github.com/cupy/cupy/issues/8306 and https://github.com/cupy/cupy/issues/8514.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Some tests looks still failing :eyes:

**Comment by asi1024** [comment]
To run tests with `numpy._set_promotion_state(‘weak’)` disabled in NumPy 1.x, we need to skip not only typecheck but also many tests related to OverflowError. We will close this pull request.

**Pull request closed without merging**
