### PR TITLE
Fix test_einsum

### PR DESCRIPTION
**Pull request by okuta**
CI is broken. This PR fix it.

### CODE REVIEW

**Comment by unnonouno** [comment]
Does it caused by overflow? If so, how about fixing shapes?

**Comment by okuta** [comment]
Yes, overflow causes problem.
I chaned shape.
https://github.com/cupy/cupy/pull/679/files#diff-54da0113d68135778489322716177c71R210

And, `skip_overflow` is `False` in most case. So, I did refactoring.

**Comment by ronekko** [comment]
Is this really caused by overflow?

For numpy.einsum with float16 inputs, if the subscripts indicate a reduction by '->' (for example of 'ij,i->', 'j' is reduced), then the sign of array may be broken.

The following code is a simple example that overflows must not be occured, but I got unexpected result.
In cupy, such strange behavior cannot be observed.

```python
import numpy as np

dtype = np.float16

a = np.arange(2 * 3, dtype=dtype).reshape(2, 3)
b = -np.arange(2, dtype=dtype)
subscripts = 'ij,i->'

x = np.sum(a * b[...,None])
y = np.einsum(subscripts, a, b)

print(x)  # -12.0
print(y)  # 12.0 (!?)

assert x == y  # assert fails
```

My envoronment is python3.6.1, numpy==1.13.3, wnidows10.
https://gist.github.com/ronekko/5074337b8b0464f8be52c7ae589b19ba

**Comment by unnonouno** [comment]
Maybe yes. float16 only has 11bit precision. That means, it cannot treat precisely numbers greater than 2048.
BTW, your code is another problem...

**Comment by unnonouno** [comment]
LGTM

**Comment by unnonouno** [comment]
@okuta v2 branch does not fails. We don't need to backport it.

**Comment by okuta** [comment]
OK

**Pull request merged**
