### PR TITLE
[backport] Add HIP symbol redefinitions

### PR DESCRIPTION
**Pull request by leofang**
Backport of #5362 by @leofang. The JIT part is removed in this PR as it's only applicable to the master branch.

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
It seems pfn-public-ci/cupy.linux.cuda114 didn't start at all...

Jenkins, test this please

**Comment by leofang** [comment]
Hmmm it still fails...For a strange reason: https://ci.preferred.jp/r/job/75124

/test

**Comment by kmaehashi** [comment]
GCP seems crowded today. Test VM may be preempted (killed) when there is high demand. The CI automatically retries to re-launch the VM, but that attempt seems also failed.

**Pull request merged**
