### PR TITLE
Use pytest-warnings to check deprecated warnings

### PR DESCRIPTION
**Pull request by unnonouno**
I added configuration for pytest-warnings to check DeprecationWarnings

### CODE REVIEW

**Comment by okuta** [comment]
Please reduce DeprecationWarnings

**Comment by unnonouno** [comment]
I fixed some tests
- support too small or too large index in `expand_dims` is deprecated
- boolean `subtract` is deprecated
- insufficient bits in `binary_repr` is deprecated

**Comment by okuta** [comment]
Please rebase or merge master for doc-test.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
