### PR TITLE
Use None instead of set() to improve memory allocation performance

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by sonots** [comment]
Thank you! LGTM!

**Comment by beam2d** [comment]
I give the background of this PR. This PR fixes the slow down issue of the current CuPy master; the main cause was heavy cache misses caused by linear search of the list of sets. This slow down was introduced by #382 that replaced the list of lists with a list of sets. The point is that Python `list` object is small while `set` object is large. Linearly searching `set` objects trigger increment/decrement of the reference counter of each `set` object which is far apart to each other due to large `set` object size (note that what is large is `set` object itself, not the region used for the hash table itself). It causes severe cache misses.

This PR replaces the default value of this list with `None`. It makes the situation better because most sets were not updated even once. Since all `None` objects are reused, now the linear search always increment/decrement the same ref count, thus much less cache misses.

**Comment by sonots** [comment]
perf stat -e instructions,cycles,L1-dcache-load-misses,LLC-load-misses,dTLB-load-misses python examples/imagenet/train_imagenet.py --arch resnet50 --batchsize 128 --epoch 1 --gpu 0 train.txt test.txt

Before:

```
   380,625,258,947      instructions              #    0.94  insns per cycle
   404,679,391,619      cycles
     7,645,880,085      L1-dcache-load-misses
     2,566,336,262      LLC-load-misses
       198,655,728      dTLB-load-misses

     101.093381407 seconds time elapsed
```

After:

```
   398,933,898,016      instructions              #    1.41  insns per cycle
   283,492,023,279      cycles
     7,727,211,322      L1-dcache-load-misses
       148,083,061      LLC-load-misses
        76,425,543      dTLB-load-misses

      59.625394260 seconds time elapsed
```

Great 🥇

**Comment by sonots** [comment]
LGTM!

**Comment by sonots** [comment]
I am not sure it is related to this commmit, but jenkins CI is failing.

**Comment by sonots** [comment]
jenkins, test this please

**Comment by sonots** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
