### PR TITLE
Define a few function's return types as `void`

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Actually a lot of functions could have this type in this file. Happy to type several in one go. Just let me know how we should handle these.

**Comment by kmaehashi** [comment]
> Actually a lot of functions could have this type in this file. Happy to type several in one go. Just let me know how we should handle these.

I think whichever is OK, but maybe doing it in one PR sounds better for both you and us as they conflict to each other.
Before adding type, please check the corresponding NumPy docs first, for example https://github.com/cupy/cupy/pull/2618 is invalid as `tolist` may return Python scalar. https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html

**Comment by jakirkham** [comment]
> > Actually a lot of functions could have this type in this file. Happy to type several in one go. Just let me know how we should handle these.
> 
> I think whichever is OK, but maybe doing it in one PR sounds better for both you and us as they conflict to each other.

Yep, makes sense. Let me pull them together then.

> Before adding type, please check the corresponding NumPy docs first, for example #2618 is invalid as `tolist` may return Python scalar. https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html

Good catch! Let's just close that out then.

**Comment by kmaehashi** [comment]
Could you resolve conflict?
Do you want to work with other return-type fixes in this PR, or are you going to create another one?

**Comment by jakirkham** [comment]
Fixed the conflicts.

Typed a few more functions that stood out to me. Can follow up with any other return types in another PR.

**Comment by kmaehashi** [comment]
LGTM!
pfnCI, test this please.

**Comment by leofang** [comment]
I could be wrong, but I don't think you can declare the C return types for `cdef`/`cpdef` functions that can raise...

**Comment by jakirkham** [comment]
I've not encountered any issue with this previously.

Was curious about this actually so tried a simple test case (see below). Seems to compile and run.

```cython
cpdef void func():
    raise Exception("Ack!")
```

That said, one does need to hold the GIL or acquire it if it was released. Though the Cython version I'm using seems to do this for you automatically, which is pretty cool. 😄

**Comment by leofang** [comment]
> I've not encountered any issue with this previously.
> 
> Was curious about this actually so tried a simple test case (see below). Seems to compile and run.
> 
> ```cython
> cpdef void func():
>     raise Exception("Ack!")
> ```

Try removing the `void` qualifier. You'll see that with `void` there's a line `Exception ignored in: ...` during the exception being raised, but without `void` it is gone. Not sure the exact mechanism here, but it seems the exception is suppressed (but then re-raised somewhere) with `void`. 

According to the error message, the test needs to capture the `ValueError` exception, but it was not raised, at least not when pytest was intercepting it.

**Comment by jakirkham** [comment]
Well I added `except *` to the function signature, which seems to have resolved the test issue.

**Comment by leofang** [comment]
Ah, ok. Didn't see that change while replying. I think `except *` should do the job:
https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values

**Comment by jakirkham** [comment]
No worries :)

**Comment by jakirkham** [comment]
Anything else needed here?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Thanks @leofang for the catch! Yes `except *` is needed in this case. However, use of `except *` has a performance disadvantage as it runs error check for every call.

As for `tofile` and `dump`, they may raise exception inside NumPy (e.g. file IO error). In additinon, `tofile` and `dump` are not called from other pyx (and will not likely to happen in future), so adding type has no merit. Could you revert these two?

**Comment by jakirkham** [comment]
Maybe we should just close this?

**Pull request closed without merging**
