### PR TITLE
Avoid using PyThread API

### LINKED ISSUE #1940: Avoid using PyThread TLS API
It's deprecated in favor of TSS ([PEP-539](https://www.python.org/dev/peps/pep-0539/)), and also it seems PyThread is considered as CPython's internal API, according to PEP-539.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #1940
Part of #2768

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
CI failure is unrelated, but is it safe to merge?

**Comment by niboshi** [comment]
>AttributeError: 'NoneType' object has no attribute 'ndim'

This one could be unrelated, but the test also suffers from timeout. That should not be ignored.

**Comment by emcastillo** [comment]
Timeout seems to be due to MPI not correctly closing the state

**Pull request merged**
