### PR TITLE
Support 64 bit extent `randint`

### LINKED ISSUE #2816: random.randint support for range larger than int32
[random.randint](https://github.com/cupy/cupy/blob/master/cupy/random/generator.py#L1122) doesn't support ranges larger than int32 apparently because [RandomState._interval](https://github.com/cupy/cupy/blob/f121d14f6d3d2f5b25a58f26d2f8bca40dd10812/cupy/random/generator.py#L631) doesn't. Is there a plan to support larger numbers such as int64 and uint64?

### PR DESCRIPTION
**Pull request by toslunar**
Fix #2816.

Compared to #2823, this PR keeps using 32-bit RNG.

### CODE REVIEW

**Comment by emcastillo** [comment]
I think this is the way to go.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Seems like some of the tests requires fixes 😭

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
I'd rather not regard the previous behavior as a bug because the error message is good.

**Pull request merged**
