### PR TITLE
[backport] Ignore warning caused by fastrlock

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #2488

### CODE REVIEW

**Comment by niboshi** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Seems like CI went wild, https://jenkins.preferred.jp/job/chainer/job/cupy_pr/399/

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
??

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
