### PR TITLE
remove intermediate aliases of cupy.sort

### PR DESCRIPTION
**Pull request by rushabh-v**
relates #2863

### CODE REVIEW

**Comment by emcastillo** [comment]
Hello, thanks for your contribution!
Instead of `sort` the issue is about prefixing `sorting` 😊

**Comment by rushabh-v** [comment]
>Instead of sort the issue is about prefixing sorting

Tell me if it requires any changes now.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
We are on code freeze now, the PR is fine but can't be merged yet.

**Comment by rushabh-v** [comment]
okay

**Pull request merged**
