### PR TITLE
enable complex tensors for cupy.matmul and cupy.einsum

### PR DESCRIPTION
**Pull request by hknerdgn**
Also changed tests to include complex arrays. Relates to issue #915.

### CODE REVIEW

**Comment by kmaehashi** [comment]
@cupy/core anyone know why it was commented out when it was first introduced in 
https://github.com/chainer/chainer/pull/1794?

**Comment by niboshi** [comment]
Just a guess, but at that time complex numbers were not supported (until #232).
I think it was meant to be uncommented when supported, but forgotten?

**Comment by hknerdgn** [comment]
Whatever the reason was back then, there is no reason now not to support it.

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by kmaehashi** [comment]
Please remove these comments.
https://github.com/hknerdgn/cupy/blob/1628544fc77dcc3b8fe9e8373809bf28330535d6/cupy/core/core.pyx#L3438-L3443

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
