### PR TITLE
Fix division by zero in mean/std/var functions for 0-length dimensions

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pentschev** [comment]
Please hold on to this, I'm checking it, but the behavior may differ from that of NumPy.

**Comment by pentschev** [comment]
NumPy reason for having NaNs for mean/std/var: https://github.com/numpy/numpy/issues/13582

**Comment by kmaehashi** [comment]
As discussed, let's return `nan` to align with the NumPy behavior and do not emit warnings as currently there's no policy of warnings/errors regarding div-by-zero. Let's leave that discussion to another issue.

**Comment by pentschev** [comment]
Agreed, I will work on that soon. Thanks @kmaehashi for the input.

**Comment by pentschev** [comment]
@kmaehashi the latest commits should now mimic the NumPy behavior.

**Comment by jakirkham** [comment]
@kmaehashi, would it be possible to get another review of this? 🙂

**Comment by pentschev** [comment]
As per our last meeting, I think this is good to merge. Could you take a last look at this @kmaehashi?

**Comment by pentschev** [comment]
I fixed the merge conflicts, so pinging here @kmaehashi whether we can merge this before spending too much time fixing future merge conflicts.

**Comment by kmaehashi** [comment]
Sorry for the delay.
pfnCI, test this please.

**Comment by kmaehashi** [comment]
@pentschev The fix seems a bit adhoc, how about this change? https://github.com/pentschev/cupy/pull/1

**Comment by pentschev** [comment]
No objections from me, I wasn't really sure what would be the preferred way here. That said, I merged your PR, if tests pass, I'm happy with this. :)

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by pentschev** [comment]
LGTM, thanks for the help with the PR @kmaehashi!

**Pull request merged**
