### PR TITLE
Refactor array testing decorators

### PR DESCRIPTION
**Pull request by niboshi**
Depends on #2820 
Refactor the common code to call cupy and cupy test implementation (`_call_func_numpy_cupy()`).

### CODE REVIEW

**Comment by emcastillo** [comment]
Let me take over this

**Comment by niboshi** [comment]
Rebased

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
CI errors are related

**Comment by niboshi** [comment]
Fixed.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
