### PR TITLE
CI: use separate project for multi-GPU tests

### PR DESCRIPTION
**Pull request by kmaehashi**
Recently we are hitting GPUs quota in FlexCI GCP and causing the delay in CI pipeline.

I'm thinking of separating multipe GPU tests to separate FlexCI project.
Currently unit tests use only one GPU except for few tests marked `multi_gpu`, but we are reserving 2 GPUs for whole time.
This should also reduce the total cost.

This PR depends on `multi_gpu` marker added in #6015.

### CODE REVIEW

**Comment by toslunar** [comment]
Besides #6098, `cupyx_tests/distributed_tests/test_store.py::TestTCPStore` is failing, but I've not reproduced it (by `CUDA_VISIBLE_DEVICES=0`).

**Comment by kmaehashi** [comment]
Tried to fix in #6114.
/test mini

**Comment by kmaehashi** [comment]
Test passed 😄

**Comment by kmaehashi** [comment]
Test failures are known ones @takagi is currently working on  so I think it's ok to merge this one.

**Pull request merged**
