### PR TITLE
[backport] Change sorting order of COO sparse matrix for cuSPARSE

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #3620

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by leofang** [comment]
SciPy version is too new for v7?

**Comment by emcastillo** [comment]
https://github.com/chainer/chainer-test/pull/590 should fix this

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
