### PR TITLE
Add requirements to build documentation on RTD

### PR DESCRIPTION
**Pull request by kmaehashi**
As we have a comparison table, we want to generate comparison table with the latest NumPy and SciPy, instead of the default version pre-installed by RTD.

Also related to: https://github.com/cupy/cupy/pull/1622#issuecomment-431334771

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
LGTM, waiting CI finish.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
I confirmed `numpy.quantile` (one of new feature in numpy-1.15) now appears in `latest`.

latest: https://docs-cupy.chainer.org/en/latest/reference/comparison.html
v5.0.0: https://docs-cupy.chainer.org/en/v5.0.0/reference/comparison.html

**Pull request merged**
