### PR TITLE
Add missing attrs

### PR DESCRIPTION
**Pull request by leofang**
Fix a likely merge error.

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
For record: this is a follow-up for https://github.com/cupy/cupy/pull/4556#pullrequestreview-597645023 and #4537

**Comment by leofang** [comment]
Failed tests are irrelevant and will be fixed in, e.g., #4743.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
