### PR TITLE
[backport] Fix `erfinv` & `erfcinv` in `cupyx.scipy.special`

### PR DESCRIPTION
**Pull request by asi1024**
Backport of #3159

### CODE REVIEW

**Comment by asi1024** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins errors are unrelated

**Comment by leofang** [comment]
Just curious, why this wasn't a bug for v7 until now? Has something changed?

**Comment by asi1024** [comment]
We added `optuna` to the requirements of Jenkins tests at https://github.com/chainer/chainer-test/pull/578 for the test of `cupyx.optimizing.optimize`, and `optuna` seems to require scipy package. So we fixed to install it only in v8 tests (https://github.com/chainer/chainer-test/pull/579).

**Comment by leofang** [comment]
Oh I see. So it sounds like with https://github.com/chainer/chainer-test/pull/579 you won't need this backport?

**Comment by asi1024** [comment]
Yes, we close this backport. Stable releases of CuPy will not follow API changes in NumPy/SciPy (excepts bug fixes) according to the [development policies](https://github.com/cupy/cupy/wiki/Development-policies).

**Pull request closed without merging**
