### PR TITLE
Fix mempool test skip condition

### PR DESCRIPTION
**Pull request by kmaehashi**
This is causing test collection error on JetPack.

## CUDA 10.2 on x86_64

```pycon
>>> from cupy.cuda import runtime
>>> runtime.deviceGetAttribute(runtime.cudaDevAttrMemoryPoolsSupported, 0)
1
```

## CUDA 10.2 on JetPack 4.6.2

```pycon
>>> from cupy.cuda import runtime
>>> runtime.deviceGetAttribute(runtime.cudaDevAttrMemoryPoolsSupported, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy_backends/cuda/api/runtime.pyx", line 181, in cupy_backends.cuda.api.runtime.deviceGetAttribute
    cpdef int deviceGetAttribute(int attrib, int device) except? -1:
  File "cupy_backends/cuda/api/runtime.pyx", line 184, in cupy_backends.cuda.api.runtime.deviceGetAttribute
    check_status(status)
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

### CODE REVIEW

**Review by leofang — APPROVED** [review]

**Comment by kmaehashi** [comment]
Hmm strange, this no longer reproduces on JetPack...

**Comment by kmaehashi** [comment]
Let me reopen if this issue happens again.

**Pull request closed without merging**
