### PR TITLE
Reduce `numpy.ndarray` creation in cuTENSOR operation preparation

### PR DESCRIPTION
**Pull request by asi1024**
This PR avoids creating `numpy.ndarray` for each operation.

TODO:
- [x] Fix documentations
- [x] Fix examples
- [x] Enhance test coverage

### CODE REVIEW

**Comment by anaruse** [comment]
I think it's good, but could you change the cuTensor examples in https://github.com/cupy/cupy/tree/master/examples/cutensor to also use `create_mode()`?

**Comment by asi1024** [comment]
I re-fixed to allow tuple of string as a `mode` for compatibility (addf884), but I'll change the examples because I want to recommend to create `Mode` for the CPU performance.

**Comment by asi1024** [comment]
@anaruse @kmaehashi Updated documentations and examples. PTAL.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
