### PR TITLE
Fix random docstring

### PR DESCRIPTION
**Pull request by takagi**
Fix docstrings of some Generator distributions.

### CODE REVIEW

**Comment by takagi** [comment]
Not draft for readthedocs preview.

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
Let me clean the commit log after being ready to merge.

**Comment by takagi** [comment]
I checked RTD preview to see the fix is okay. PTAL!

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by toslunar — APPROVED** [review]

**Comment by toslunar** [comment]
`standard_exponential` is in v9

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
will backport manually

**Pull request merged**
