### PR TITLE
add array_api.take function

### LINKED ISSUE #7425: Support for xp.take?
### Description

worth adding xp.take from array api standard:
https://data-apis.org/array-api/latest/API_specification/generated/array_api.take.html#array_api.take

I've landed a PR to numpy, I think implementation in cupy is the same?
https://github.com/numpy/numpy/pull/23284/files

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by arogozhnikov**
fix #7425 

Implementation is analogous to numpy: https://github.com/numpy/numpy/pull/23284

### CODE REVIEW

**Comment by arogozhnikov** [comment]
ping @kmaehashi

**Comment by kmaehashi** [comment]
Sorry for dropping the ball here :bow:
Could you add `test_indexing_functions.py` to `tests/cupy_tests/array_api_tests`?
LGTM otherwise!

**Comment by kmaehashi** [comment]
Thanks!
/test

**Review by kmaehashi — APPROVED** [review]

**Comment by arogozhnikov** [comment]
@kmaehashi all but one test passed. The one that failed does not seem to have any relation to my changes

**Comment by kmaehashi** [comment]
Right, this is tracked in #7468, merging. Thanks again!

**Pull request merged**
