### PR TITLE
Remove unneeded environment variable from ROCm install guide

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by leofang** [comment]
Is it because we set it here?
https://github.com/cupy/cupy/blob/0d103ab79708d620642d0aa13253b211ef219d51/cupy_setup_build.py#L597

**Comment by kmaehashi** [comment]
I guess the documentation was wrong from the start.
It seems there are no modules using `__HIP_PLATFORM_HCC__` as an environment variable. Moreover `export __HIP_PLATFORM_HCC__` (without value) does nothing.

**Comment by leofang** [comment]
Yeah I didn't notice it's not recommended to be set to 1, and indeed it's only needed by compilers (as a compile time flag) to select the code path.

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Change looks correct in the docs. Merge without jenkins

**Pull request merged**
