### PR TITLE
Implemented copy option of array conversion methods and wrote tests

### PR DESCRIPTION
**Pull request by unnonouno**
I implemented copy argument of array conversion methods. I also wrote unit tests for this option.

### CODE REVIEW

**Comment by takagi** [comment]
Please resolve the conflict.

**Comment by takagi** [comment]
jenkins test this please

**Comment by takagi** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
