### PR TITLE
Fix gitignore to exclude pyd files

### PR DESCRIPTION
**Pull request by kmaehashi**
pyd files are generated while building Windows DLL (Python modules).

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM, but how about moving to just below `*.pyo`?

**Comment by kmaehashi** [comment]
OK, I moved.

**Comment by niboshi** [comment]
Hmm, what's this error?

**Comment by kmaehashi** [comment]
Maybe becaue of new `hacking` released 2 hour ago ...
https://pypi.org/project/hacking/#history

**Comment by niboshi** [comment]
OK, it's not related anyway...

**Pull request merged**
