### PR TITLE
Improve readability of reduction kernel

### PR DESCRIPTION
**Pull request by sonots**
This PR only changes variable and function names to improve readability, and does not change any behaviors.

Concerns:  This requires JIT compilation again because texts of kernel codes are changed. Is it okay? (Personally thinking, I feel it is okay).

image

Changes:

* J_offset => reduce_block_offset
* j_offset => reduce_offset
* J_stride => reduce_block_size
* j_stride => reduce_stride
* i => i_out
* j => i_in
* J => i_reduce
* block_stride => out_block_size
* out_clp2_size => out_block_size
* clp2_count => reduce_block_size
* get_trans_args => get_permuted_args
* laxis => reduce_axis
* raxis => out_axis
* out_offset  =_tid % _out_block_size
* out_stride = gridDim.x * _out_block_size
* out_block_ num = (out_indexer.size + out_block_size - 1) // out_block_size

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by sonots** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
Cloud you split this PR?

**Comment by sonots** [comment]
Since this change introduces backward incompatibility to users, I separated changes in only python layter => https://github.com/cupy/cupy/pull/1580

Let me close this PR itself.

**Pull request closed without merging**
