### PR TITLE
Implement `make_interp_spline(..., bc_type="periodic")`

### PR DESCRIPTION
**Pull request by ev-br**
This is branched off gh-7195, will rebase after it is in. Relevant commits start from 64c80c417cc490f20e1c9e0bff22bb7552e200bf

### CODE REVIEW

**Comment by ev-br** [comment]
Rebased on master to pick up the recently merged make_interp_spline. This is now ready for review from my side.

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
Let me merge this as the CI failures on windows is not related to this. Thanks @ev-br!

**Pull request merged**
