### PR TITLE
Import `using_allocator` in `cupy.cuda`

### PR DESCRIPTION
**Pull request by jakirkham**
cc @emcastillo

### CODE REVIEW

**Comment by emcastillo** [comment]
depends on #2952

**Comment by niboshi** [comment]
Why does it depend on #2952?

**Comment by emcastillo** [comment]
They share a commit

**Comment by niboshi** [comment]
It seems they don't share a commit and I think we can merge this PR and discard the other one.

**Comment by emcastillo** [comment]
`Document `using_allocator` function` this commit is duplicated, although it has a different hash
I agree with closing #2952 and merging this one instead

**Comment by jakirkham** [comment]
PR ( https://github.com/cupy/cupy/pull/2952 ) could be backported to `v7`. This PR cannot be backported.

**Comment by niboshi** [comment]
>`Document using_allocator function` commit is duplicated in both, although it has a different hash.

And the content is different, too.

@jakirkham 
I think it's opposite: this PR can be backported and #2952 shouldn't.
`cupy.cuda.memory.using_allocator` is a "wrong" signature and users shouldn't use it.
Fortunately this signature is not documented yet. If it became documented in v7 (by backporting #2952) and this PR would be merged (to v8), v7 and v8 would be incompatible.

This PR breaks existing code that use `cupy.cuda.memory.using_allocator`, but we can't avoid that anyway. Maybe we can say it's their responsibility because it's not documented.

**Comment by jakirkham** [comment]
Ok happy to defer 🙂

**Comment by emcastillo** [comment]
I just got the flow of the two prs😅
sorry for the missunderstanding

**Comment by jakirkham** [comment]
No worries. Sorry for not being clearer.

**Comment by emcastillo** [comment]
Might be the sphinx error related to the function being a context manager?

**Comment by jakirkham** [comment]
It looks like Travis CI is using Python 3.5.6. Is that needed or can we update to a newer Python version?

**Comment by jakirkham** [comment]
My guess is using `contextmanager` in Cython results in something that Sphinx is unable to parse. This issue ( https://github.com/cython/cython/issues/1750 ) and [this blogpost]( https://opendreamkit.org/2017/06/09/CythonSphinx/ ) seem relevant here. What do we think about just moving the context manager into a pure Python file?

**Comment by emcastillo** [comment]
That approach should be fine.

**Comment by jakirkham** [comment]
Have pushed a few changes. These rewrite `using_allocator` to use only `get_allocator` and `set_allocator` (to make it possible to move the function). Then have pulled this code into `cupy.cuda`'s `__init__.py`. This seems to fix the Sphinx error. However as I've rewritten the function, it would be good to run this on Jenkins and also get a review. Please let me know what you think 🙂

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by jakirkham** [comment]
Had missed updating the tests. This seems to fix them except for one test that is checking for a `ValueError` to be raised by `set_allocator` when called within a `using_allocator` context. Will try to work out some changes to fix this.

**Comment by jakirkham** [comment]
Ok, simplified things a fair bit. Expect this should work better. Could use another run on Jenkins when you have a chance @emcastillo 🙂

**Comment by jakirkham** [comment]
Should add this worked for me locally as well. 😄

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by jakirkham** [comment]
The Jenkins status says the build failed, but if I look at the dashboard everything is passing. Am I missing something?

Screen Shot 2020-02-17 at 7 38 23 PM

**Comment by emcastillo** [comment]
Jenkins went nuts, lets try it again.
Jenkins, test this please.

**Comment by jakirkham** [comment]
No worries. Thanks for the help @emcastillo! 😄 Would also be interested to get your take on this approach 😉

**Pull request merged**
