### PR TITLE
[backport] Support all dtypes in every sorting function in `cupy.cuda.thrust`

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3286

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
Follows #3336, which is the backport of #2745 .

**Comment by leofang** [comment]
Did it fail because you need to backport #3167 first?

**Comment by emcastillo** [comment]
The reason to backport this pr is
https://github.com/cupy/cupy/pull/3291

**Comment by takagi** [comment]
Yes, we need #3167 to backport before #3286. Let me close this PR for now and make it again after #3345 will have been merged.

**Pull request closed without merging**
