### PR TITLE
Add `cupy.intersect1d` API

### PR DESCRIPTION
**Pull request by amanchhaparia**
Hi,
This PR aims to add `cupy.intersect1d` API mention in #6078. 

I had used `cupy.flatnonzero`, `unique` which have warning of '_may synchronize the device_'.
It would be great if someone provides suggestions to improvise it.

Thank You!

### CODE REVIEW

**Comment by khushi-411** [comment]
Hey, @amanchhaparia!
Will you please take a look at #6402? I'm already working on the same PR :)

Thanks!

**Comment by amanchhaparia** [comment]
> Hey, @amanchhaparia! Will you please take a look at #6402? I'm already working on the same PR :)
> 
> Thanks!

Yeah sure!
Actually I didn't noticed that since it was not updated on the tracker #6078

**Comment by asi1024** [comment]
Duplicate of https://github.com/cupy/cupy/pull/6402.

**Comment by kmaehashi** [comment]
Thank you for joining the review process in #6402, @amanchhaparia!

**Pull request closed without merging**
