### PR TITLE
import memory_hooks

### PR DESCRIPTION
**Pull request by niboshi**
Reopen #483. We need this to merge #442.

### CODE REVIEW

**Comment by niboshi** [comment]
I have no idea how to fix the import error in jenkins.

**Comment by okuta** [comment]
Please fix [setup.py](https://github.com/cupy/cupy/blob/888499b11367ba46a509523bc16578fd37c16baa/setup.py#L48).
`memory_hooks` does not belong to CuPy packge.

**Comment by niboshi** [comment]
Like this?
Adding `cupy.memory_hooks` resulted in `error: package directory 'cupy/memory_hooks' does not exist`.

**Comment by okuta** [comment]
Thanks, jenkins test was passed.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
