### PR TITLE
Use CUDA version to decide if it import cusolver or not

### PR DESCRIPTION
**Pull request by unnonouno**
When cusolver has a bug and cupy fails to import cusolver, the error is ignored and reports wrong error. It is better to check CUDA version.

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
@unnonouno Please check jenkins result.

**Comment by unnonouno** [comment]
Ah, ok. We cannot use runtime API on an environment without GPU. Do we have an API to check compile time version?

**Comment by okuta** [comment]
I agree your opinion.

**Comment by okuta** [comment]
How about embedding `CUDA_RUNTIME_VERSION` to `runtime` module or using `cudaGetDeviceCount` ?

**Comment by okuta** [comment]
Please check #954

**Comment by unnonouno** [comment]
#954 is reverted.

**Comment by kmaehashi** [comment]
Build time version is now embedded in `cupy.cuda.driver`. https://github.com/cupy/cupy/pull/937/files#diff-34a88f4729d17d511a33203cf596e3b8

**Comment by unnonouno** [comment]
Thank you!

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
