### PR TITLE
Assign a workpace to `ormqr` functions in `_solve`

### LINKED ISSUE #3323: v7.4.0 cupy/cuda/driver.pyx error line 118
Hi,

I'm working in conda envs with conda installs. Hit a snag upgrading from cupy 6.0.0 to 7.4.0 with rapidsai.

The MRE runs in cupy 6.0.0 and crashes in 7.4.0 with this error:

```
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 247, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
TypeError: 'NoneType' object is not callable
```

In Jupyter Notebook the MRE errors one line later:

```
CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

The complete stack trace is in the attached notebook along with additional system and device specs.

Great tool box, thanks.

Tom

---

[cupy740_crash_mre.ipynb.pdf](https://github.com/cupy/cupy/files/4602529/cupy740_crash_mre.ipynb.pdf)

```
# MRE
import numpy as np
import cupy as cp

MB = 1024**2
cp.cuda.Device(3).use()

free, total = cp.cuda.Device(3).mem_info
print(f"MB free {free / MB :.0f} total {total / MB :.0f}")

# ok on these ...
# n, p, g = 250, 5, 10
# n, p, g = 2500, 25, 1000

# errors on these
n, p, g = 25000, 250, 10000

yg = np.random.rand(n, g).astype("float32")
X = np.random.rand(n, p).astype("float32")


ygd = cp.asarray(yg)
Xd = cp.asarray(X)
print(f"MB matrices: {(ygd.nbytes + Xd.nbytes) / MB :.0f}")
assert ygd.nbytes + Xd.nbytes < free 

Qd, Rd = cp.linalg.qr(Xd)
bhatsd = cp.linalg.solve(Rd, Qd.T @ ygd)
yhatsd = Xd @ bhatsd  # jupyter gets past this line

# ed = yhatsd - ygd   # jupyter errors on this line
```

[sandbox]$ conda activate cupy
(cupy) [sandbox]$ python --version; python -c "import cupy; cupy.show_config()"; python cupy740_crash_mre.py
Python 3.7.7
CuPy Version          : 6.0.0
CUDA Root             : /usr/local/cuda-8.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7605
NCCL Build Version    : 1000
NCCL Runtime Version  : (unknown)
MB free 12039 total 12196
MB matrices: 978
(cupy) [sandbox]$ conda deactivate
[sandbox]$ conda activate rapidsai37
(rapidsai37) [sandbox]$ python --version; python -c "import cupy; cupy.show_config()"; python cupy740_crash_mre.py
Python 3.7.6
CuPy Version          : 7.4.0
CUDA Root             : /home/turbach/.conda/envs/rapidsai37
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507
MB free 12027 total 12196
MB matrices: 978
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 247, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
TypeError: 'NoneType' object is not callable
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 247, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
TypeError: 'NoneType' object is not callable
(rapidsai37) [sandbox]$

### PR DESCRIPTION
**Pull request by emcastillo**
Close #3323

`ormqr` functions were using the same workspace as `geqrf` which is different and causes a memory corruption.

### CODE REVIEW

**Comment by asi1024** [comment]
Could you add a test?

**Comment by emcastillo** [comment]
Let me think about how to test this ...
The error is not deterministic at all as it requires the arrays to be created using `cupy.asarray(np_array)` QR factorization to be done before the solve call and also to obtain the cublas handle before, otherwise, it does not fail. Omitting any of these steps doesn't create the failure  😥

@leofang any ideas?

**Comment by leofang** [comment]
No, I don't have good idea either. I am still puzzled that 
1. why would the error be triggered only when `cp.show_config()` was executed in the beginning of the #3323 script
2. why only 10.1/10.2 failed

Not sure if this is relevant: I took a quick look at the buffer size required by `ormqr`, and it seems to get roughly doubled in 10.1/10.2.

**Comment by emcastillo** [comment]
yes, probably that's the reason behind the error

**Comment by asi1024** [comment]
How about deleting `workspace` object after each workspace is used?

**Comment by emcastillo** [comment]
PTAL

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Looks good to merge the PR, but let me note that it may be intended that the workspace of `geqrf` is reused by `ormqr`.

The cuSOLVER doc of `ormqr` (https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-ormqr) says
>  The input parameter lwork is size of the working space, and it is returned by `geqrf_bufferSize()` or `ormqr_bufferSize()`.

and the example https://docs.nvidia.com/cuda/cusolver/index.html#qr_examples calls only `cusolverDnDgeqrf_bufferSize`.

**Comment by emcastillo** [comment]
Yes, maybe its a bug in cuda 10.1 or 10.2?
@anaruse can you help us with this? 😇

**Comment by leofang** [comment]
@toslunar this is interesting...When I checked the buffer sizes returned by `geqrf` and `ormqr`, the latter is always larger regardless of CUDA versions. But then I don't understand why it worked for 9.2/10.0...

**Comment by leofang** [comment]
It could be that a device synchronization needs to be done between `gegrf` and `ormqr`. At least it's what's done in the example.

**Comment by emcastillo** [comment]
@anaruse friendly ping

**Comment by anaruse** [comment]
Thanks for friendly ping ^^;
I'll look into this, so please wait for a while.

**Comment by anaruse** [comment]
I ran the repro script of https://github.com/cupy/cupy/issues/3323 with `cp.show_config()` in the beginning, but it did not raise any error.

```
CuPy Version          : 8.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 11000
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2506
NCCL Runtime Version  : 2506
MB free 32186 total 32508
MB matrices: 978
```

Please let me know what GPU was used when the issue occurred.
I used the GV100 for the test above.

**Comment by emcastillo** [comment]
We used V100 and G100, 
It is a memory corruption error so sometimes or depending of configurations it might not appear.

I think the main issue here is that 
`cusolver.geqrf_bufferSize` and `cusolver.unmqr_bufferSize` seems to return different buffersizes
```
geqrf buffersize  96768
ormqr buffersize  1323168
```

With the second being larger than the first, so if we use just the first one, we hit up a memory corruption in the GPU. However Nvidia docs says that only with geqrf size should be ok. So is it possible for this to be a bug in cuda or the Nvidia docs?

**Comment by leofang** [comment]
When testing it with Emilio I used 2080 Ti and reproduced.

**Comment by anaruse** [comment]
I understand the situation.
It looks to me that the problem is that the sample code [here](https://docs.nvidia.com/cuda/cusolver/index.html#ormqr-example1) does not use cusolverDn<t>ormqr_buffersize()...
I will check with the library team..

**Comment by leofang** [comment]
> CUDA Driver Version   : 11000

Why is your driver version so new @anaruse 🤣

**Comment by anaruse** [comment]
Please ignore that ^^

**Comment by anaruse** [comment]
It is a documentation bug.
Please use the helper function `cusolverDnDormqr_bufferSize()` to determine the size of workspace for the function `cusolverDnDormqr()`.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
