### PR TITLE
Remove `cupy.testing.NumpyError`

### PR DESCRIPTION
**Pull request by toslunar**
Use `numpy.errstate` instead.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Note: this pr requires numpy 1.17

**Comment by toslunar** [comment]
> Note: this pr requires numpy 1.17

`numpy.errstate` as a context manager is always available, while `@numpy.errstate(...)` (as a function decorator) is since NumPy 1.17.

**Comment by toslunar** [comment]
`NumpyError` is added by chainer/chainer#466.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
