### PR TITLE
Fix doc of `LinearOperator`

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
Should we fix the signature, too?
```diff
-    """Common interface for performing matrix vector products
+    """LinearOperator(shape, matvec, rmatvec=None, matmat=None, dtype=None, \
+rmatmat=None)
+
+    Common interface for performing matrix vector products
```

SciPy doc shows the signature of `__new__(*args, **kwargs)`

**Comment by toslunar** [comment]
https://cupy--4441.org.readthedocs.build/en/4441/reference/generated/cupyx.scipy.sparse.linalg.LinearOperator.html

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
