### PR TITLE
Add ChainerCV's tests to pfnCI

### PR DESCRIPTION
**Pull request by Hakuyume**
merge after #2144

### CODE REVIEW

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
pfnCI, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by Hakuyume** [comment]
jenkins, test this please

**Comment by kmaehashi** [comment]
#2144 has merged.

**Comment by niboshi** [comment]
Please resolve conflict.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
CI failure is unrelated.

**Pull request merged**
