### PR TITLE
[backport] Remove cuDNN overhead

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #512

### CODE REVIEW

**Comment by niboshi** [comment]
* A change to `get_compute_capability()` in `device.pyx` is dropped because it's not backported.
* A change to `TestCudnnDropout` in `test_cudnn.py` is dropped because it's not backported.

**Comment by okuta** [comment]
Please check travis CI result.

**Comment by okuta** [comment]
@niboshi Please check travis CI result

**Comment by niboshi** [comment]
* Dropped `cudnn.is_tensor_core_available`
* Dropped `cudnn.DropoutStates`

**Comment by niboshi** [comment]
I need to further check diff between `cudnn.py` and `cudnn.pyx`.

**Comment by niboshi** [comment]
* Dropped `warnings.warn` in `cudnn.create_dropout_states` and removed `import warnings`.

**Comment by niboshi** [comment]
I think it's done.

**Comment by okuta** [comment]
Please merge [this](https://github.com/chainer/chainer/pull/3999)

**Comment by niboshi** [comment]
#3999 has been merged.

**Comment by okuta** [comment]
jenkins, test this please

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
