### PR TITLE
[backport] Update document for cuDNN 8.1

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4643

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
https://github.com/cupy/cupy/pull/4699 should resolve the CI fail.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Merging as it's rendered correctly on RTD test.

**Pull request merged**
