### PR TITLE
Move `cupy.cudnn` `cupy.cusolver` `cupy.cutensor` `cupy.cusparse` to `cupyx`

### PR DESCRIPTION
**Pull request by emcastillo**
Close [#6011](https://github.com/cupy/cupy/issues/6011)

Should we keep aliases?

### CODE REVIEW

**Comment by asi1024** [comment]
@emcastillo Could you split the test fixes into another PR, to check this change keeps the conventional interface?

**Comment by emcastillo** [comment]
> Could you split the test fixes into another PR, to check this change keeps the conventional interface?

I feel the deprecation warning will make all the tests fails.

Should we have this PR without the warning & tests, and a follow-up one with the warning and the tests?

**Comment by asi1024** [comment]
@emcastillo I thought that we should separate this PR and run CIs for each PR to ensure that this change does not break the conventional APIs. However, Now I found that it is easy to confirm it by reviewing it, so no need to separate the PR!

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
