### PR TITLE
[backport] Test `numpy.VisibleDeprecationWarning`

### PR DESCRIPTION
**Pull request by takagi**
Backport of #4498

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Review by toslunar — APPROVED** [review]

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Pull request merged**
