### PR TITLE
Support list bins with histogram

### LINKED ISSUE #3334: Support list-like bins argument in histogram
As noted in https://github.com/cupy/cupy/issues/3322 , `cupy.histogram` currently expects the `bins` argument to be a cupy array, rather than an iterable sequence. It might be a nice addition to support Python lists as input.

The `numpy.histogram` argument accepts a generic sequence. Perhaps `cupy.histogram` could be enhanced to accept a list-like iterable which is then appropriately coerced (if need be) to a `cupy.array`, which is necessary for this segment of the code:

https://github.com/cupy/cupy/blob/76c6daca665890a9482d5ff66a49dbd484eb77b3/cupy/statistics/histogram.py#L211-L214

`_get_bin_edges` currently fails silently if a Python list is passed as `bins`. Support for a list-like iterable could perhaps be done in this function.

```python
import cupy as cp

arr = cp.random.randint(5,10,(10,10))
x, weights = cp.statistics.histogram._ravel_and_check_weights(arr, None)
cp.statistics.histogram._get_bin_edges(x, [5,6], None) # returns None
```

### PR DESCRIPTION
**Pull request by okuta**
Fix #3334

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI passes.

**Comment by leofang** [comment]
I think we need to modify this line
https://github.com/cupy/cupy/blob/56e97ee65f98e37e549fbc7424ea1333be981c00/cupy/statistics/histogram.py#L220
to `if isinstance(bins, cupy.ndarray) or numpy.ndim(bins) == 1:` (After #3060 is merged, we can simply do `if cupy.ndim(bins) == 1:`.

**Comment by okuta** [comment]
Thanks, I fixed.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Hi @okuta, sorry Line 220 that I referred to is new (from #3473) and you need to merge with master before fixing it 😅

**Comment by okuta** [comment]
OK, no problem! I will fix.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by leofang** [comment]
https://github.com/cupy/cupy/pull/3542#issuecomment-657106677 should fix it...Before calling the CUB routine we need to fix the type of `bin_edges`, as it's not guaranteed correct (see `_get_bin_edges`).

**Comment by okuta** [comment]
I sent #3617 .

**Comment by leofang** [comment]
@okuta I am lost...Why do we need #3617? We already support float16 in CUB histogram and it's covered by the tests.

**Comment by okuta** [comment]
In my environment, histogram test is failed with float16.
I use GeForce GTX Titan X (sm_52). 

```
% pytest tests/cupy_tests/statics_tests/test_histogram.py -s
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.6, pytest-4.1.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/okuta/env/chainer37/cupy, inifile: setup.cfg
collected 88 items

tests/cupy_tests/statics_tests/test_histogram.py .....................................................................................dtype is <class 'numpy.float16'>
F..

=================================================================================================== FAILURES ====================================================================================================
________________________________________________________________________________________ TestCubHistogram.test_histogram ________________________________________________________________________________________
cupy/testing/helper.py:659: in test_func
    impl(self, *args, **kw)
cupy/testing/helper.py:253: in test_func
    check_func(cupy_r, numpy_r)
cupy/testing/helper.py:488: in check_func
    array.assert_array_equal(x, y, err_msg, verbose, strides_check)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), y = array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), err_msg = '', verbose = True, strides_check = False

    def assert_array_equal(x, y, err_msg='', verbose=True, strides_check=False):
        """Raises an AssertionError if two array_like objects are not equal.

        Args:
             x(numpy.ndarray or cupy.ndarray): The actual object to check.
             y(numpy.ndarray or cupy.ndarray): The desired, expected object.
             strides_check(bool): If ``True``, consistency of strides is also
                 checked.
             err_msg(str): The error message to be printed in case of failure.
             verbose(bool): If ``True``, the conflicting values
                 are appended to the error message.

        .. seealso:: :func:`numpy.testing.assert_array_equal`
        """
        numpy.testing.assert_array_equal(
            cupy.asnumpy(x), cupy.asnumpy(y), err_msg=err_msg,
>           verbose=verbose)
E       AssertionError:
E       Arrays are not equal
E
E       Mismatched elements: 10 / 10 (100%)
E       Max absolute difference: 1
E       Max relative difference: 1.
E        x: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
E        y: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

cupy/testing/array.py:93: AssertionError
====================================================================================== 1 failed, 87 passed in 1.94 seconds ======================================================================================```

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
I don't understand why the CI attempts to build SciPy from source....Any insights, @kmaehashi?

**Comment by takagi** [comment]
Rel https://github.com/chainer/chainer-test/pull/604 .

**Comment by kmaehashi** [comment]
> I don't understand why the CI attempts to build SciPy from source....Any insights, @kmaehashi?

It was needed previously but no longer necessary. chainer-test PR above fixed to use wheels.

pfnCI, test this please.

**Comment by leofang** [comment]
Ah, I see. Thanks for explanation.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
