### PR TITLE
DOC: add missing functions to the API reference

### PR DESCRIPTION
**Pull request by grlee77**
Most of these were my oversight in recent morphology PRs. The rest I noticed due to missing links in the listings at: https://docs.cupy.dev/en/latest/reference/comparison.html

### CODE REVIEW

**Comment by toslunar** [comment]
Travis CI is failing with the message `/home/travis/build/cupy/cupy/cupy/_indexing/insert.py:docstring of cupy.diag_indices:22:Unexpected indentation.`.  I'll commit the fix to the docstring of `diag_index`.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
`<BLANKLINE>` is not removed from the HTML output.  This issue already exists in `cupy.who`.
https://docs.cupy.dev/en/stable/reference/generated/cupy.who.html

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
