### PR TITLE
Fix broadcasting error in cupy roll if shift argument is an array

### PR DESCRIPTION
**Pull request by awthomp**
Closes https://github.com/cupy/cupy/issues/4476

CuPy's roll function relies on Numpy's broadcasting function. This is all fine and good if the shift parameter is either a scalar or tuple, but if the shift parameter is an array, the user receives a cupy/numpy conversion error. Since CuPy's broadcast function doesn't yield an iterable object, we can't simply replace `numpy.broadcast` with `cupy.broadcast`.

I've submitted a PR to check if the shift argument is a `cupy.ndarray` object. If so, we migrate to the CPU and let `numpy.broadcast` do its thing with a numpy shift array.

The following code now works as expected:

```python
import cupy as cp
a = cp.arange(12).reshape(4,3)
shift = cp.array([1,2,3,4])
rolled = cp.roll(a, shift)
```

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Can I suggest adding a warning? That'll A) make it clear to users that it is *preferable* to pass a `numpy` array rather than a `cupy` one, and B) it'll serve as a reminder that this could be improved in the future.

**Comment by asi1024** [comment]
@awthomp Thank you for your PR!
We are considering another implementation that does not require device-to-host data transfer now (#4884). Do you have any concerns?

**Comment by awthomp** [comment]
Hey @asi1024. No concerns here! This PR was always meant to be a stop-gap, so I totally approve of a more efficient implementation.

**Comment by asi1024** [comment]
#4884 is merged!

**Pull request closed without merging**
