### PR TITLE
CI: Remove path length limitation on Windows CI image

### PR DESCRIPTION
**Pull request by kmaehashi**
https://github.com/cupy/cupy/pull/7851#issuecomment-1712702124

### CODE REVIEW

**Comment by kmaehashi** [comment]
Succeeded to create a long path file :tada:

```
    cmd /c "echo foo > C:\Windows\TEMP\flexci\run-00292523\work\src\build\lib.win-amd64-cpython-39\cupy\_core\include\cupy\cccl\libcudacxx\libcxx\test\std\experimental\memory\memory.polymorphic.allocator.class\memory.polymorphic.allocator.mem\construct_pair_const_lvalue_pair.pass.cpp"
```

**Review by leofang — APPROVED** [review]

**Comment by leofang** [comment]
Thanks for speedy fix, Kenichi-san!

**Review by emcastillo — APPROVED** [review]
LGTM!, never thought we need to mess with the registry 😅

**Comment by leofang** [comment]
This needs to be documented, as it impacts Windows users with all sources of installation (pip/conda/git), I'll handle it in #7851.

xref:
- https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation
- https://github.com/conda/conda/issues/7203

**Comment by kmaehashi** [comment]
As for #7851, can't we omit test files from installation? (maybe by adjusting [package_data](https://github.com/cupy/cupy/blob/6ccec449e9695168f89b3c5613b4ab532566a49a/setup.py#L73))

**Comment by leofang** [comment]
Hmmm, interesting, didn't notice it's in the test folder. I'll look into it. I suspect even manipulating path globs would hit the same issue.

**Pull request merged**
