### PR TITLE
Implement cuDNN batch normalization interface

### PR DESCRIPTION
**Pull request by okuta**
We want to provide simple cuDNN interface.

### CODE REVIEW

**Comment by takagi** [comment]
Would you resolve the conflict?

**Comment by okuta** [comment]
I resolved.

**Comment by takagi** [comment]
Would you check the CI failure on flake8.cython?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
