### PR TITLE
[backport] Fix split and array_split with indices overrun

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #2814

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Something weird happened with the PR,
I will fix it

**Comment by emcastillo** [comment]
Fixed

**Comment by takagi** [comment]
Looks still something wrong. Would you try the backport script with `--branch v7` option?

**Comment by emcastillo** [comment]
when a fix v6 then this one breaks ...

**Comment by takagi** [comment]
I got the situation.

**Comment by emcastillo** [comment]
Lets merge v6 first, then i will fix this

**Pull request closed without merging**
