### PR TITLE
Fix Windows CI test script to avoid caching kernel when in pull-request test

### PR DESCRIPTION
**Pull request by kmaehashi**
https://github.com/cupy/cupy/pull/4362#discussion_r572536881

This PR also fixes the issue that test script fails when all tests pass 😅

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
* `Uploading kernel cache` message not in the Windows test results.
* I think we don't have to retrigger Jenkins as this PR only changes FlexCI part.

**Pull request merged**
