### PR TITLE
Improve `Fusion.__call__`

### PR DESCRIPTION
**Pull request by asi1024**
~Merge #1835 first.~
~Merge #1856 first.~
~Merge #1888 first.~

Cythonized `fusion.py`.

fusion.py
```
[ 33.33%] ··· Running cupy.bench_fusion.Fusion.time_fusion_add_10_times
                     ok
[ 33.33%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     77.52μs
                  disabled    441.66μs
               ============= ==========

[ 66.67%] ··· Running cupy.bench_fusion.Fusion.time_fusion_loops
                     ok
[ 66.67%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     155.93μs
                  disabled    13.90ms
               ============= ==========

[100.00%] ··· Running cupy.bench_fusion.Fusion.time_fusion_lstm_grad_grad
                     ok
[100.00%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     577.69μs
                  disabled     4.47ms
               ============= ==========
```

fusion.pyx
```
[ 33.33%] ··· Running cupy.bench_fusion.Fusion.time_fusion_add_10_times                                                                                                            ok
[ 33.33%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     66.90μs
                  disabled    440.05μs
               ============= ==========

[ 66.67%] ··· Running cupy.bench_fusion.Fusion.time_fusion_loops                                                                                                                   ok
[ 66.67%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     148.16μs
                  disabled    13.92ms
               ============= ==========

[100.00%] ··· Running cupy.bench_fusion.Fusion.time_fusion_lstm_grad_grad                                                                                                          ok
[100.00%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     557.27μs
                  disabled     4.48ms
               ============= ==========
```

### CODE REVIEW

**Comment by okuta** [comment]
I want to merge this PR!

**Comment by okuta** [comment]
I merged #1888 .

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
