### PR TITLE
Clean up `internal.pyx` (`get_contiguous_strides`)

### PR DESCRIPTION
**Pull request by niboshi**
- Removed `get_contiguous_strides` because it's never used
- Renamed `set_contiguous_strides` -> `get_contiguous_strides_inplace`

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
@niboshi Could you check test failures?

**Comment by niboshi** [comment]
Hmm, instead of exposing this function back to Python, is it ok to test it indirectly via `ndarray.__init__()`?

**Comment by toslunar** [comment]
> Hmm, instead of exposing this function back to Python, is it ok to test it indirectly via `ndarray.__init__()`?

Sounds good!

**Comment by niboshi** [comment]
Sorry for delay. PTAL
(Btw, `itemsize=3` can't be tested so I removed it. I think it's ok if `itemsize=2` is tested.)

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
