### PR TITLE
Fix cupy.full and cupy.full_like to make unsafe casting

### LINKED ISSUE #6577: `cupy.full` makes casting in `safe` rule
### Description

Rel #6181.

As fixed in #6481, both `numpy.fill` and `cupy.fill` make casting in `safe` rule. However, `numpy.full` make casting in `unsafe` rule unlike `numpy.fill` does, and #6481 brought a bug that `cupy.full` works in `safe` rule as it is currently implemented using `cupy.fill`.

### To Reproduce

```py
>>> import numpy as np
>>> import cupy as cp
>>> np.full((), np.array(1, dtype=np.float64), dtype=np.int64)
array(1)
>>> cp.full((), cp.array(1, dtype=cp.float64), dtype=cp.int64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ext-mtakagi/cupy.cuda-11.6/cupy/_creation/basic.py", line 276, in full
    a.fill(fill_value)
  File "cupy/_core/core.pyx", line 665, in cupy._core.core.ndarray.fill
    cpdef fill(self, value):
  File "cupy/_core/core.pyx", line 679, in cupy._core.core.ndarray.fill
    raise TypeError(
TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
```

### Installation

Built from GitHub source

### Environment

```
# Paste the output here
```

### Additional Information

`numpy.fill` and `cupy.fill` make casting in `safe` rule:
```py
>>> import numpy as np
>>> import cupy as cp
>>> a = np.array(0, dtype=np.int64)
>>> a.fill(np.array(1, dtype=np.float64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
>>> a = cp.array(0, dtype=cp.int64)
>>> a = a.fill(cp.array(1, dtype=cp.float64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 665, in cupy._core.core.ndarray.fill
    cpdef fill(self, value):
  File "cupy/_core/core.pyx", line 679, in cupy._core.core.ndarray.fill
    raise TypeError(
TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe'
```

### PR DESCRIPTION
**Pull request by takagi**
Fix #6577. Merge #6584 first.

### CODE REVIEW

**Comment by asi1024** [comment]
Could you check the test failure?

**Comment by takagi** [comment]
I've added a following-up for #6584, which fixes `cupy.copyto` to take NumPy scalars as well.

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
