### PR TITLE
[backport] DOC: add missing functions to the API reference

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #4215

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Review by toslunar — CHANGES_REQUESTED** [review]
Some functions are v9-only.  Please check CI results.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by toslunar — APPROVED** [review]
Thanks!  LGTM

**Pull request merged**
