### PR TITLE
Fix import of `_get_axis`

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/cupy/cupy/issues/2971

### CODE REVIEW

**Comment by leofang** [comment]
Confirmed locally that this fixes #2971.

**Comment by jakirkham** [comment]
Thanks for checking Leo! Do you know what we need to do to get this running on CI?

**Comment by grlee77** [comment]
> Thanks for checking Leo! Do you know what we need to do to get this running on CI?

@leofang has already done work on this, but it still needs final review/merge.
#2584 makes it so CUB is enabled during the CI builds and #2598 adds new tests.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
This has been merged in v7 :s

**Comment by jakirkham** [comment]
Thanks!

Yeah I don't think so as things have moved around in `master` so this module exists there.

**Pull request merged**
