### PR TITLE
Replaced the links for NumPy docs as per issue #3418

### PR DESCRIPTION
**Pull request by Palash-Vishnani**
Replaced the old Scipy links by the new NumPy doc links, in almost all the files that needed this modification, as per issue #3418

### CODE REVIEW

**Comment by Palash-Vishnani** [comment]
@kmaehashi checkout this PR!

**Review by toslunar — COMMENTED** [review]
`git grep -n 'scipy\.org.*numpy'`
```
docs/source/reference/random.rst:57:   * `NumPy 1.16 Reference <https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.random.html>`_
```
How about `https://numpy.org/doc/1.16/reference/routines.random.html`?

**Comment by Palash-Vishnani** [comment]
@toslunar done.

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by Palash-Vishnani** [comment]
@toslunar @kmaehashi I think this PR is now ready for merging.

**Comment by kmaehashi** [comment]
LGTM, thanks @Palash-Vishnani and @toslunar!

**Pull request merged**
