### PR TITLE
Add ncclAvg and ncclBfloat16 for NCCL

### LINKED ISSUE #5529: NCCL 2.10: Support `ncclAvg` API

### PR DESCRIPTION
**Pull request by takagi**
Close #5529.

This PR adds `ncclAvg` operation introduced in NCCL 2.10.

### CODE REVIEW

**Comment by leofang** [comment]
For the completeness of 2.10 support, could you also add `ncclBfloat16`? CuPy doesn't use bf16 yet but it'd good to have it there.
https://github.com/NVIDIA/nccl/blob/7e515921295adaab72adf56ea71a0fafb0ecb5f3/src/nccl.h.in#L123

**Comment by takagi** [comment]
Okay, I'm going to do it!

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by leofang — APPROVED** [review]
LGTM! Thanks @takagi. Remember to change the PR title.

**Comment by leofang** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
