### PR TITLE
[backport] Fix `fill_diagonal`

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #3011

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
#3139 should be backported after this one

**Comment by takagi** [comment]
`cupy.core._carray` is not split from `cupy.core.core` in v7.

**Comment by emcastillo** [comment]
I will close this and manually backport #3139

**Pull request closed without merging**
