### PR TITLE
ndimage: add grid_mode option to zoom

### PR DESCRIPTION
**Pull request by grlee77**
blocked by #4400 (This PR builds on that one. Only the final "ENH: implement grid_mode parameter for zoom" commit here is new)

This PR implements zooming in a manner consistent with scikit-image's `resize` and OpenCV's `cv2.resize`. See further explanation in the corresponding SciPy PR scipy/scipy#13095 (to be released in SciPy 1.6).

Basically the issue relates to whether coordinate (0, 0) is at the center or corner of a pixel. In the kernel, this translates into computing coordinates via: 
`c = zoom * (in_coord + 0.5) - 0.5` (for grid_mode=True)
 vs.
`c = zoom * in_coord` (for grid_mode=False)

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
As well as #4400, would you mark `cupy.experimental` if `grid_mode` is supplied by the user. LGTM except for that.

**Comment by grlee77** [comment]
Thanks for reviewing @takagi, I have added the experimental marker here and in #4400

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
Thanks! I'll mrege this with following #4400 .

**Pull request merged**
