### PR TITLE
Remove batched QR solver's experimental mark

### PR DESCRIPTION
**Pull request by takagi**
Rel. #5583. Blocked by #6323.

Now that NumPy 1.22 is out, we can remove the experimental mark of `cupy.linalg.qr`.

### CODE REVIEW

**Comment by toslunar** [comment]
Maybe we can also work on https://github.com/cupy/cupy/blob/1ce389fb2145cee8dca1a0aa47d0c6636b1ec85e/tests/cupy_tests/linalg_tests/test_decomposition.py#L136-L137.

The methods `test_mode_rank3`, `test_mode_rank4` and the parameter `mode='raw'` require the condition `@testing.with_requires('numpy>=1.22')`.  For the last one, I'd use `pytest.param('raw', marks=testing.with_requires('numpy>=1.22'))` (but it assumes the undocumented fact: `testing.with_requires(...)` is PyTest marker when it is available).

**Comment by takagi** [comment]
Would you check if I got your point?

**Comment by toslunar** [comment]
> Would you check if I got your point?

Looks good.  To apply `pytest.mark.parametrize` to each test, receive the value by kwarg `test_*(self, mode)` (instead of `self.mode`) and maybe
```diff
-class TestQRDecomposition(unittest.TestCase):
+class TestQRDecomposition:
```

**Comment by takagi** [comment]
Thanks! And I've found that `_condition.repeat` is assuming the test class is of `unittest.TestCase`...

**Comment by takagi** [comment]
Can we leave `unittest.TestCase`-based test this time as we could implement `_condition.repeat` using pytest hooks, but it doesn't look much straightforward. Or any thought?
https://github.com/pytest-dev/pytest-rerunfailures/blob/master/pytest_rerunfailures.py#L467

**Comment by toslunar** [comment]
I'm sorry that I missed `_condition.repeat`.

It's fine to remove `repeat(3, 10)` because many matrices are tested (in rank-3 and 4 tests).  It's also OK to keep `unittest.TestCase` and `repeat(3, 10)` by fixing `check_mode` as
```python
if mode != 'raw' or numpy.lib.NumpyVersion(numpy.__version__) >= '1.22.0rc1':
    self._check_result(result_cpu, result_gpu)
```

**Comment by takagi** [comment]
Sure, PTAL again!

**Review by toslunar — CHANGES_REQUESTED** [review]
It seems the branch has a conflict and the auto-merged file will have `k = min(m, n)` twice.

```
% git fetch cupy pull/6327/merge
From github.com:cupy/cupy
 * branch                refs/pull/6327/merge -> FETCH_HEAD
% git diff --unified=5 FETCH_HEAD FETCH_HEAD^ FETCH_HEAD^2 $(git merge-base FETCH_HEAD^1 FETCH_HEAD^2)
```
```diff
diff --cc cupy/linalg/_decomposition.py
index 7b4cee164,a604592f1,09bde3fd1..52ffb28ab
--- a/cupy/linalg/_decomposition.py
+++ b/cupy/linalg/_decomposition.py
@@@@ -219,28 -219,28 -219,27 +219,29 @@@@ def cholesky(a)

   def _qr_batched(a, mode):
       batch_shape = a.shape[:-2]
       batch_size = internal.prod(batch_shape)
       m, n = a.shape[-2:]
 ++    k = min(m, n)

       # first handle any 0-size inputs
 --    if batch_size == 0 or m == 0 or n == 0:
 ++    if batch_size == 0 or k == 0:
           # support float32, float64, complex64, and complex128
           dtype, out_dtype = _util.linalg_common_type(a)

+ +        k = min(m, n)
           if mode == 'reduced':
  -            return (cupy.empty(batch_shape + (m, 0), out_dtype),
  -                    cupy.empty(batch_shape + (0, n), out_dtype))
  +            return (cupy.empty(batch_shape + (m, k), out_dtype),
  +                    cupy.empty(batch_shape + (k, n), out_dtype))
           elif mode == 'complete':
               q = _util.stacked_identity(batch_shape, m, out_dtype)
               return (q, cupy.empty(batch_shape + (m, n), out_dtype))
           elif mode == 'r':
  -            return cupy.empty(batch_shape + (0, n), out_dtype)
  +            return cupy.empty(batch_shape + (k, n), out_dtype)
           elif mode == 'raw':
               return (cupy.empty(batch_shape + (n, m), out_dtype),
  -                    cupy.empty(batch_shape + (0,), out_dtype))
  +                    cupy.empty(batch_shape + (k,), out_dtype))

       # ...then delegate real computation to cuSOLVER/rocSOLVER
       a = a.reshape(-1, *(a.shape[-2:]))
       out = _geqrf_orgqr_batched(a, mode)

```

**Comment by takagi** [comment]
Thanks!

**Review by toslunar — APPROVED** [review]
LGTM

**Pull request merged**
