### PR TITLE
[backport] Deterministic test

### PR DESCRIPTION
**Pull request by okuta**
This PR is backport of #82

### CODE REVIEW

**Comment by okuta** [comment]
This PR is miss.

**Comment by niboshi** [comment]
@okuta 
Don't we have to backport?
Stable branch should also be stabilized.

**Comment by okuta** [comment]
@niboshi 
This PR includes new features. What do you think about this point?

**Comment by niboshi** [comment]
@okuta 
I think stabilizing tests is more important.
The new features were simply needed to fix a "bug".

**Comment by okuta** [comment]
OK, I reopen this PR

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
Test is failing because of this:
```
./tests/cupy_tests/linalg_tests/test_decomposition.py:60:6: F821 undefined name 'condition'
```
Can you fix it?

**Comment by okuta** [comment]
Please merge #241 before this PR.

**Comment by niboshi** [comment]
Fix conflict please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
