### PR TITLE
ROCm: Fix bugs and test suites to make ROCm/HIP happy - Part 2

### PR DESCRIPTION
**Pull request by leofang**
~~Blocked by #3786.~~ ~~Details to follow.~~

**UPDATE**
- Add default complex<T> constructors: without them Clang would complain under C++11 mode (default for ROCm); this also brings us more in sync with upstream (Thrust)
- Fix Thrust support: we unified the type dispatcher (#3546) but forgot to include HIP's fp16 header and set it enabled, so the entire dispatcher was malfunctioning on ROCm...(oops!)
- Handle `HIP_VISIBLE_DEVICES` properly
- Fix segfault in `deviceGetAttribute()`
- Disable managed memory for ROCm/HIP: it's simply not supported
- Disable adding callbacks to default stream (https://github.com/ROCm-Developer-Tools/HIP/issues/2119)
- Fix `deviceGetByPCIBusId()`
- Fix a few other tests

### CODE REVIEW

**Comment by leofang** [comment]
#3893 can be investigated after this PR is in.

**Comment by leofang** [comment]
Blocked by #3988.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@emcastillo I updated the PR description. PTAL.

**Comment by leofang** [comment]
@emcastillo Friendly ping to make this backported in time 🙂

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
CI timed out, retrying...
Jenkins, test this please

**Comment by leofang** [comment]
Thanks!

**Pull request merged**
