### PR TITLE
Support dltensor with strides of NULL

### LINKED ISSUE #2095: [BUG] DLPack implementation doesn't handle nullptr for strides
According to DLPack spec if the strides attribute is NULL it indicates a dense tensor (https://github.com/dmlc/dlpack/blob/master/include/dlpack/dlpack.h#L142).

The current implementation in cupy will cause a segfault if `mem.dlm_tensor.dl_tensor.strides` is null as it will try to index into it (https://github.com/cupy/cupy/blob/v6.0.0b3/cupy/core/dlpack.pyx#L236).

### PR DESCRIPTION
**Pull request by crcrpar**
This PR resolves #2095.

### CODE REVIEW

**Comment by niboshi** [comment]
Can you fix the error?
You cannot declare cython types with `cdef` in this manner.

**Comment by crcrpar** [comment]
I think I fixed the error.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
