### PR TITLE
Adjust tolerance of `TestPolyArithmeticDiffTypes` under HIP/ROCm

### PR DESCRIPTION
**Pull request by takagi**
Rel #4132.

Tolerance in case HIP and `polymul`.

### CODE REVIEW

**Comment by leofang** [comment]
Part of https://github.com/cupy/cupy/issues/4484#issuecomment-767067322.

**Review by leofang — COMMENTED** [review]
Is it legit to access the class attribute in the decorator?
```python
@testing.numpy_cupy_allclose(
    rtol=1e-4 if (runtime.is_hip and self.fname == 'polymul') else 1e-5,
    accept_error=TypeError)
```

**Comment by takagi** [comment]
No, we don't have `self` there. I think no way to get `fname` without the parameterized class name.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
