### PR TITLE
Remove broken support for macOS

### PR DESCRIPTION
**Pull request by leofang**
It has been broken for quite some time (ex: https://github.com/cupy/cupy/issues/952#issuecomment-491635935), and CUDA has dropped support for Mac, so there's no reason to keep them around.

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Review by kmaehashi — APPROVED** [review]
LGTM!

**Comment by Photonico** [comment]
Hi,
My laptop is MBP2019.
Do you have a plan to support macOS?
If not, I will set it dual system.
Thx

**Comment by kmaehashi** [comment]
@Photonico Unfortunately, ROCm (nor CUDA) supports Mac.

**Pull request merged**
