### PR TITLE
Fixes a bunch of AMD issues

### PR DESCRIPTION
**Pull request by emcastillo**
Fixes Raw kernel tests and some issues with `__cuda_array_interface__`

### CODE REVIEW

**Comment by leofang** [comment]
What's wrong with the RawKernel tests? It went fine on my system 🤔

**Comment by emcastillo** [comment]
context_switch is multidevice, so probably they were skipped in your system.
They call hipcc with `-cubin` which is not supported.

**Comment by leofang** [comment]
Ah... right. Thanks for catching them 😅

**Comment by emcastillo** [comment]
@kmaehashi PTAL!

**Review by leofang — CHANGES_REQUESTED** [review]
Could you also skip the CUDA Array Interface tests in these files?
- tests/cupy_tests/creation_tests/test_from_data.py
- tests/cupy_tests/core_tests/test_ndarray_cuda_array_interface.py

**Comment by leofang** [comment]
Could you also add a skip to `tests/cupy_tests/core_tests/test_carray.py`? See https://github.com/cupy/cupy/issues/3833#issuecomment-754246631.

**Comment by emcastillo** [comment]
Those tests are already being skipped, I think 😄

**Comment by emcastillo** [comment]
Fixed a strange multi-device behavior

**Comment by leofang** [comment]
> Those tests are already being skipped, I think 😄

Right...sorry I had a dirty local build so I missed it 🤦🏻‍♂️

**Comment by leofang** [comment]
Jenkins, test this please

**Review by leofang — APPROVED** [review]
LGTM!

**Comment by leofang** [comment]
@emcastillo I resolved the conflict with master 😅

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM!

**Comment by leofang** [comment]
Thanks, @emcastillo @kmaehashi!

**Pull request merged**
