### PR TITLE
[backport] Support cuSparse generic API

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #3242

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by leofang** [comment]
#3081 changed the handle type from `size_t` to `intptr_t`.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Test failures are unrelated (fix in https://github.com/chainer/chainer-test/pull/594)

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Test passed!

**Pull request merged**
