### PR TITLE
implemented matrix power with tests

### LINKED ISSUE #1358: matrix power is missing from cupy.linalg.
There is a corresponding `numpy.linalg.matrix_power` in NumPy. Is there a reason why this has not made it into CuPy?

If it helps, I am willing to take a shot at this one, though I might need a bit of hand-holding as I've not much experience with Cython code.

### PR DESCRIPTION
**Pull request by ericmjl**
cc: @asi1024 and @kmaehashi, thank you for all the help put in so far. I am really sorry that I have had to redo this a few times.

To prep for this PR, I deleted my CuPy fork, re-forked CuPy, and applied the patch from the v2 PR (#1371) as a single commit. This PR closes #1358.

### CODE REVIEW

**Comment by ericmjl** [comment]
Not sure if this command works (coming from me), but I'll try it anyways.

Jenkins, test this please.

**Comment by kmaehashi** [comment]
Thank you for your work! LGTM.

Jenkins, test this please.
(sorry, this command only work for CuPy maintainers)

**Comment by kmaehashi** [comment]
Please merge https://github.com/ericmjl/cupy/pull/1 for CUDA 7.x support.

**Comment by ericmjl** [comment]
@kmaehashi @asi1024 thank you both for all the help! I will leave the PR in your hands now. Do let me know if there's something more I can do!

**Comment by kmaehashi** [comment]
@ericmjl Thanks! I'll merge after Jenkins test pass.

Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!
Thanks again for contribution!

**Comment by ericmjl** [comment]
Many thanks for your help, @kmaehashi @asi1024!

**Pull request merged**
