### PR TITLE
Disable jitify for cub & Bump CCCL

### PR DESCRIPTION
**Pull request by emcastillo**
Based on Leo's comment in https://github.com/cupy/cupy/issues/8209#issuecomment-2155784474
The CUB generic reduction routines are enabled by default and they use jitify, thus initializing the jitify cache.
Since CUB now fully supports NVRTC we can disable the jitify compilation and avoid the jitify initialization just for running CuPy regular routines.

This PR needs to bump cccl to allow cub to be compatible with nvrtc without using jitify.
I have used the latest commit available in cupy's cccl fork, which seems to include the msvc patch.
However, this patch was greatly changed in https://github.com/NVIDIA/cccl/pull/1420 and I am not sure if there is a regression or not, so let me kick all the CIs.

### CODE REVIEW

**Comment by emcastillo** [comment]
Strange, I can compile and run tests locally with cuda 12.4, I guess it may be the CI gcc version. I am running it with 11.4

**Comment by kmaehashi** [comment]
I've synced https://github.com/cupy/cccl main branch with upstream.

**Comment by emcastillo** [comment]
Thanks! I was able to reproduce the errors in my local env after doing a build from 0.

I will try with the current head, but probably will hit the thrust issues again. I am thinking on having a stable branch with the old cccl and the new nvrtc CUB if nothing else works.

Another quick solution while we harmonize everything would be to disable the CUB backed reduction by default. This will avoid the jitify initialization problem for the majority of users.

**Comment by emcastillo** [comment]
I merged this with #8221, fixed it for NVRTX & and bumped CCCL to the latest commit.

**Comment by leofang** [comment]
Lots of timeouts here, likely because the kernel cache is invalidated. We can tentatively bump the timeout limit as done previously in commit fd00150534c0aef3f803487c7a09262d31dcc124 and revert it once this PR is merged.

**Comment by kmaehashi** [comment]
It's ok to increase the timeout as Leo suggested. Besides that, there are errors reported (before the timeout) which are likely related to this PR, e.g.:

https://ci.preferred.jp/cupy.linux.cuda120/164308/
```
05:17:52.808601 STDOUT 1303]	FAILED cupy_tests/core_tests/test_raw.py::TestRawJitify_param_0_{jitify=False}::test_jitify1	
```

https://ci.preferred.jp/cupy.linux.cuda123/164314/
```
04:52:56.265113 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_0_{block=64, n=10}::test_grid_sync_rawkernel	
04:52:56.265117 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_0_{block=64, n=10}::test_grid_sync_rawmodule	
04:52:56.265124 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_1_{block=64, n=100}::test_grid_sync_rawkernel	
04:52:56.265126 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_1_{block=64, n=100}::test_grid_sync_rawmodule	
04:52:56.265129 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_2_{block=64, n=1000}::test_grid_sync_rawkernel	
04:52:56.265136 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_2_{block=64, n=1000}::test_grid_sync_rawmodule	
04:52:56.265138 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_3_{block=256, n=10}::test_grid_sync_rawkernel	
04:52:56.265154 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_3_{block=256, n=10}::test_grid_sync_rawmodule	
04:52:56.265175 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_4_{block=256, n=100}::test_grid_sync_rawkernel	
04:52:56.265177 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_4_{block=256, n=100}::test_grid_sync_rawmodule	
04:52:56.265180 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_5_{block=256, n=1000}::test_grid_sync_rawkernel	
04:52:56.265186 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawGridSync_param_5_{block=256, n=1000}::test_grid_sync_rawmodule	
04:52:56.292626 STDOUT 1298]	FAILED cupy_tests/core_tests/test_raw.py::TestRawJitify_param_0_{jitify=False}::test_jitify1	
```

**Comment by kmaehashi** [comment]
Btw I noticed timeouts are not happening in CUDA 12.3+ CIs. Maybe thanks to the compile time improvement mentioned in [CUDA 12.3 release notes](https://docs.nvidia.com/cuda/archive/12.3.0/cuda-toolkit-release-notes/index.html#cuda-compilers)? This is great 🎉

**Comment by leofang** [comment]
Discussed with Emilio, `test_jitify1` can be removed since the assumption (that Jitify must be run first) no longer holds. Will check other failures once either of us gets a chance

**Comment by leofang** [comment]
> Will check other failures once either of us gets a chance

The remaining of the failing tests are:
1. using nvcc,
2. including only `cooperative_groups.h` and nothing else
3. have the following bf16/fp16 conversion issues
```
/home/leof/miniforge3/envs/cupy_cuda125_dev/bin/../targets/x86_64-linux/include/cuda_bf16.h(4977): error: no instance of overloaded function "__half::__half" matches the specified type
  __half::__half(const __nv_bfloat16 f)
          ^

1 error detected in the compilation of "/tmp/tmpnoptin0u/4c03e54824ab5700c6f58a6b4b706396b4c17527.cu".
```
This happens because CuPy-bundled fp16 headers (added in CUDA 12.2) are incompatible with the latest bf16 headers (that somehow are loaded unconditionally by nvcc, despite that `cooperative_groups.h` and its dependencies do not include any bf16/fp16 headers.

@emcastillo @kmaehashi May I suggest a two-step approach? I'd really like to get this PR merged asap so that we have time to get it backported to v13.3.0 given its perf/UX improvement. So,
1. We skip the failing grid-sync tests for nvcc >12.2, and get this merged/backported
2. In a separate PR, we add fp16 headers from all CUDA 12.x minor releases (we did this in the old days). Given that the fp16/bf16 headers are rapidly evolved by the math libs team and they move in lock steps, but we can't redistribute bf16 headers, this is necessary.

In the near future, once we depend on nvmath-python, we rely on it to search for headers from pip wheels, conda packages, or system CTK (following [the logic done here](https://github.com/NVIDIA/nvmath-python/blob/7c485842d0f3300e03ec780056936503913910fe/nvmath/device/common_mathdx.py#L35-L90), which might later be refactored into cuda-python). Alternatively, we can also copy/paste the logic here, though I prefer to let us (NVIDIA) maintain this. In any case, once this is done then the bundled headers can again be removed, at the price of a few extra (small) NVIDIA wheels becoming a dependency.

**Comment by leofang** [comment]
@kmaehashi could you grant me write/maintainer access to the cupy/cccl fork? I have a minor fix to address https://github.com/NVIDIA/cccl/issues/2095.

**Comment by kmaehashi** [comment]
> @kmaehashi could you grant me write/maintainer access to the cupy/cccl fork? I have a minor fix to address [NVIDIA/cccl#2095](https://github.com/NVIDIA/cccl/issues/2095). See [cupy/cccl#1](https://github.com/cupy/cccl/pull/1).

Added write permission!

**Comment by leofang** [comment]
It seems the CI failures are in 3 categories
1. Early termination: CI just ended prematurely with the error "execution function exceeded the context's deadline"
2. Memory error: All tests passed normally, the kernel cache statistics was shown, but the CI returned an error "excessive memory usage is detected"
3. Actual test failures: Looking into this...

**Comment by leofang** [comment]
> 2\. In a separate PR, we add fp16 headers from all CUDA 12.x minor releases (we did this in the old days). Given that the fp16/bf16 headers are rapidly evolved by the math libs team and they move in lock steps, but we can't redistribute bf16 headers, this is necessary.

It seems we'll have to do this at least for CUDA 12.5... I can reproduce the `test_vectorize.py` failures from `pfn-public-ci/cupy.linux.cuda125` locally.

**Comment by miscco** [comment]
I tested locally and it should build with cccl main. 

I am not sure whether we need the thrust fix anymore

**Comment by leofang** [comment]
Discussed with @miscco to ensure we're on the same page. Here's what happened with this PR in the past two days:
- I found the NVRTC+Thrust issue, I reported it in https://github.com/NVIDIA/cccl/issues/2095
- I pushed a patch to CuPy's CCCL fork: https://github.com/cupy/cccl/pull/1
- @miscco fixed it in CCCL main the next day: https://github.com/NVIDIA/cccl/pull/2102
- I switched to CCCL main (commit 08e6a3c) to avoid patching myself, and hit the `thrust::less` issue (https://github.com/NVIDIA/cccl/issues/2109)
- I reverted back to use the fork (which is CCCL main as of 2 days ago + my NVRTC patch)

**Comment by leofang** [comment]
Things are looking good, will check back later today for the remaining running CIs. 

@kmaehashi I've eliminated the other two classes of errors and we're now left with the benign one:
> * Memory error: All tests passed normally, the kernel cache statistics was shown, but the CI returned an error "excessive memory usage is detected"

any advice for how to proceed here? Is the CI memory limit configurable on your side?

**Comment by leofang** [comment]
> Is the CI memory limit configurable on your side?

Ah it seems to be configurable in `.pfnci/config.pbtxt`, @kmaehashi is it ok that I bump it to 60 GB? Any bad consequences (such as increased fees)? 😛

**Comment by leofang** [comment]
> Things are looking good, will check back later today for the remaining running CIs.

Confirmed all tests passed 🎉 Now we just need to figure out a path forward for merging (due to the excessive memory error raised at the end of the CI runs).

**Comment by kmaehashi** [comment]
As all CIs have passed let's proceed to merge. If the excessive memory error happens in main branch as well let's consider increasing the size.

(But not sure why this started to happen... In our CI docker image is on the RAM disk, so the cause may be due to increase of the assets and/or real memory usage increase)

**Comment by jakirkham** [comment]
When building Docker images, do you squash layers? Or do you build everything in one layer? If not, that might be a way to cutdown on image size

**Comment by leofang** [comment]
> As all CIs have passed let's proceed to merge. If the excessive memory error happens in main branch as well let's consider increasing the size.
> 
> (But not sure why this started to happen... In our CI docker image is on the RAM disk, so the cause may be due to increase of the assets and/or real memory usage increase)

Note that the OOM errors only happened with Linux + CUDA 11.8 - 12.3; with CUDA 12.4 and above or any CUDA on Windows (that got run in the CI) does not have this issue. Therefore my thinking is it might be related to NVRTC and is something that can be improved in future CUDA. 

Also, I suspect we only need a temporary memory limit increase; once the kernels are cached I hope to see less OOM, though this part is harder to investigate properly yet quickly.

**Review by kmaehashi — APPROVED** [review]

**Comment by leofang** [comment]
Thanks to all, @emcastillo @miscco @kmaehashi!

**Pull request merged**
