### PR TITLE
Improving performance of `cupy.random.choice`

### PR DESCRIPTION
**Pull request by asi1024**
Fix https://github.com/cupy/cupy/issues/8477.

current master:

```
CPU:   528.909 us   +/-  8.817 (min:   513.830 / max:   556.690) us     GPU-0: 22175.946 us   +/- 21.370 (min: 22132.736 / max: 22215.679) us
```

This PR:

```
CPU:   542.260 us   +/- 226.564 (min:   510.556 / max:  2789.806) us     GPU-0:   548.843 us   +/- 227.403 (min:   517.088 / max:  2804.736) u
```

Reproducer:

```py
import cupy as cp
from cupyx.profiler import benchmark

def f():
    cp.random.choice(10000, size=10000, p=cp.ones(10000)/10000)

print(benchmark(f, (), n_repeat=20))
```

### CODE REVIEW

**Review by kmaehashi — APPROVED** [review]

**Comment by seberg** [comment]
This PR changes the stream of random numbers (noticed in a cuML doctest, I suspect that isn't a huge deal, once can set up the doctests to only run on newer cupy presumably).

I am not sure if CuPy has much of a policy around stream stability or if you may want to document the change.

Old stream:
```
In [5]: cp.random.RandomState(cp.uint32(10)).choice([0, 1], size=20, p=[0.5, 0.5])
Out[5]: array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0])
```
New stream:
```
In [2]: cp.random.RandomState(cp.uint32(10)).choice([0, 1], size=20, p=[0.5, 0.5])
Out[2]: array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1])
```

**Comment by jakirkham** [comment]
Curious what the result is if we drop `p` (given there is equal probability of either option)?

**Comment by kmaehashi** [comment]
Thanks for the catch! There's no explicit policy, but I think in general users would expect reproducibility between minor versions with fixed seeds, so I'll make a revert PR for v13 backport. cc/ @asi1024

**Comment by jakirkham** [comment]
Sounds good. Thanks all! 🙏

Given this code is more like NumPy (and it is more performant), think that is what we want longer term. We probably just need a little more time to understand the differences between the two

So reverting in v13 seems like the right approach

**Pull request merged**
