### PR TITLE
Remove code paths for unsupported Python versions

### PR DESCRIPTION
**Pull request by niboshi**
Part of #2994

### CODE REVIEW

**Comment by asi1024** [comment]
@niboshi Could you check flake8 failures?

**Comment by niboshi** [comment]
Force pushed.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Comment by kmaehashi** [comment]
Should this PR be backported?

**Comment by kmaehashi** [comment]
I made a backport to v7 as it looks safe.

**Pull request merged**
