### PR TITLE
[backport] Fix docs requirement

### PR DESCRIPTION
**Pull request by unnonouno**
#548

### CODE REVIEW

**Comment by niboshi** [comment]
LGTM!

**Comment by niboshi** [comment]
Jenkins needs a fix.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by niboshi** [comment]
jenkins test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
