### PR TITLE
Tests for NumPy alias functions

### PR DESCRIPTION
**Pull request by niboshi**
Related: #355 

Tests for NumPy functions.

### CODE REVIEW

**Comment by niboshi** [comment]
https://github.com/chainer/chainer-test/issues/303 needs to be fixed.

**Comment by okuta** [comment]
jenkins, test this please

**Comment by okuta** [comment]
Please rebase.

**Comment by niboshi** [comment]
Rebased.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please

**Comment by okuta** [comment]
I got error.
```
======================================================================
ERROR: test_values (test_base_n.TestBinaryReprValues_param_7)  parameter: {'args': (-3, 0)}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/cupy/cupy/testing/helper.py", line 1035, in test_values
    self.cupy_func(*self.args),
  File "/work/cupy/cupy/__init__.py", line 222, in binary_repr
    return numpy.binary_repr(num, width)
  File "/usr/local/lib/python3.4/dist-packages/numpy/core/numeric.py", line 2188, in binary_repr
    bin = ''.join([_lkup[ch] for ch in ostr[2:]])
  File "/usr/local/lib/python3.4/dist-packages/numpy/core/numeric.py", line 2188, in <listcomp>
    bin = ''.join([_lkup[ch] for ch in ostr[2:]])
KeyError: 'x'
```

**Comment by niboshi** [comment]
It seems this argument combination (-3, 0) is only supported from NumPy 1.12.0.
I commented out.

**Comment by okuta** [comment]
LGTM

**Pull request merged**
