### PR TITLE
Add user guide for streams & events

### PR DESCRIPTION
**Pull request by leofang**
Part of https://github.com/cupy/cupy/issues/4902#issuecomment-813205619.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks @leofang, great work!

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]
LGTM! 👍🏼

**Comment by leofang** [comment]
Thanks, @kmaehashi. I realized I forgot to document ExternalStream. I will send a separate PR.

**Pull request merged**
