### PR TITLE
Refactor cyclic imports

### PR DESCRIPTION
**Pull request by asi1024**
Moved the declaration of `_thread_local` to `_kernel.pyx`.

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
LGTM, will merge after CI finish!

**Comment by takagi** [comment]
The CI failure is not relevant to this PR.

**Comment by asi1024** [comment]
@takagi We don't need to backport this PR because `_kernel.pyx` in `v5` doesn't have this cyclic import.

**Comment by takagi** [comment]
Okay!

**Pull request merged**
