### PR TITLE
Support fallback allgorithm for spgemm

### LINKED ISSUE #7699: Use different cuSparse algorithm for SpGEMM
### Description

As noticed in issue #7044 the memory usage for SpGEMM can easily exceed the usage of GEMM on dense matrices.
The documentation of [CuSparse](https://docs.nvidia.com/cuda/cusparse/index.html#cusparsespgemm) specify that the memory usage is very high. As of CUDA 12.1.0 there are other options for the spgemm algorithm to lower the memory usage. Is it possible to fall back to `CUSPARSE_SPGEMM_ALG3` when `cusparseSpGEMM_workEstimation` fails with code 11? (`CUSPARSE_STATUS_INSUFFICIENT_RESOURCES`)
https://github.com/cupy/cupy/blob/3d80d9194530bdb02551f19f8119fa8b946c0e15/cupyx/cusparse.py#L2044

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lowener**
This PR closes #7699. It is adding support for SPGEMM ALG2 of cusparse that requires a much lower memory usage than the default, used only when the default algorithm would fail.

### CODE REVIEW

**Comment by leofang** [comment]
Q: Is there a way we can test the new code path? Maybe you can add a known problem size to the test suite?

**Comment by lowener** [comment]
I added a test to do `spgemm` on matrices (`100k x 50` - `50 x 100k`).
This problem size triggers the usage of the lower memory algorithm on my RTX 3070Ti (8GB) and on my Quadro RTX 8000 (48GB).
I disabled the element-wise comparison with scipy to not slow down the CI.

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
Let me kick the full test to check with older CTKs.

**Comment by takagi** [comment]
Would you check the result of static-checks and fix it?
https://github.com/cupy/cupy/actions/runs/8510603439/job/23642667154?pr=8252

**Comment by takagi** [comment]
record: https://ci.preferred.jp/p/dashboard_by_commit_id?commit_id=b0674103c5e9e63eaddfecbaaa096e94d53c1eb4

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
