### PR TITLE
Set `__module__` attr to parameterized class

### PR DESCRIPTION
**Pull request by toslunar**
Keep `__module__` attribute of the base test class (instead of `cupy.testing._bundle`) for a better message on fail.  In my opinion, `setattr(module, cls_name, cls)` justifies this.

<details><summary>Sample output</summary>

```
_______________________ TestA_param_0_{x=1, y=2}.test_a ________________________

self = <test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>, args = ()
kwargs = {}, s = <_io.StringIO object at 0x7f32104c30d0>, k = 'y', v = 2
err_class = <class 'AssertionError'>

    @functools.wraps(base_method)
    def new_method(self, *args, **kwargs):
        try:
>           return base_method(self, *args, **kwargs)

cupy/testing/parameterized.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = <test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>.x

tests/test_tmp.py:11: AssertionError

During handling of the above exception, another exception occurred:

self = <test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: Parameterized test failed.
E
E       Base test method: TestA.test_a
E       Test parameters:
E         x: 1
E         y: 2

tests/test_tmp.py:11: AssertionError
```

</details>

<details><summary>With #4211</summary>

before:
```
__________________________ TestA_param_0_{x=1}.test_a __________________________

self = <<cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>  parameter: {'x': 1}>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = <<cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>  parameter: {'x': 1}>.x

test_tmp.py:11: AssertionError
```

after:
```
_______________________ TestA_param_0_{x=1, y=2}.test_a ________________________

self = <<test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>  parameter: {'x': 1, 'y': 2}>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = <<test_tmp.TestA_param_0_{x=1, y=2} testMethod=test_a>  parameter: {'x': 1, 'y': 2}>.x

tests/test_tmp.py:11: AssertionError
```

</details>

### CODE REVIEW

**Comment by toslunar** [comment]
A difference between unittest and pytest is `__name__` of a test file, i.e. `__module__` of a test class:
- `python -m unittest tests/foo_tests/test_bar.py` -> `tests.foo_tests.test_bar`
- `pytest tests/foo_tests/test_bar.py` -> `test_bar`

This PR neglect the difference.  With pytest, paths (`foo_tests`) are available (only?) at `nodeid` (e.g. `tests/foo_tests/test_bar.py::TestA_param_0_{x=1}::test_b`).

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]
LGTM!

**Pull request merged**
