### PR TITLE
Do exact type comparison instead of `isinstance` for `numpy.dtype`

### PR DESCRIPTION
**Pull request by okuta**
This PR reduces ndarray initialization time.

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
Please check test failure:
```
21:47:26     @testing.for_orders('CFAK')
21:47:26     @testing.for_all_dtypes_combination(('src_dtype', 'dst_dtype'))
21:47:26     def test_astype_type(self, src_dtype, dst_dtype, order):
21:47:26         a = testing.shaped_arange((2, 3, 4), cupy, src_dtype)
21:47:26         b = astype_without_warning(a, dst_dtype, order=order)
21:47:26         a_cpu = testing.shaped_arange((2, 3, 4), numpy, src_dtype)
21:47:26         b_cpu = astype_without_warning(a_cpu, dst_dtype, order=order)
21:47:26 >       self.assertEqual(b.dtype.type, b_cpu.dtype.type)
21:47:26 E       AssertionError: <class 'numpy.uint64'> != <class 'numpy.uint64'>
```

**Comment by okuta** [comment]
Thanks, I will check it.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
