### PR TITLE
Reduce compile warnings

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by leofang** [comment]
Oh this is nice! Thanks @okuta for working on this. It's indeed hard when the debugging info for the build process is drown in a bunch of irrelevant warnings!

**Comment by toslunar** [comment]
Comparing as `int`s looks good to me.  I prefer it to comparing as unsigned ints, even though we can deduce both hand sides are non-negative with the *current* code.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
