### PR TITLE
Write note about environment variables

### PR DESCRIPTION
**Pull request by unnonouno**
I added notice about environment variables used in installation.
See #521

### CODE REVIEW

**Comment by niboshi** [comment]
Is it our script, or something that we can't modify?

**Comment by unnonouno** [comment]
It is used in `distutils`.

**Comment by niboshi** [comment]
Then, I think it's better to explicitly state that. One might think we're responsible and lazy.

**Comment by unnonouno** [comment]
I see.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
