### PR TITLE
[DO NOT MERGE] Monitor compile cache utilization

### PR DESCRIPTION
**Pull request by emcastillo**
Check if cache is being utilized in jenkins and windows CI

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
1. The cache hit in Windows is surprisingly low...I wonder why? Could it be the hash on Windows is not deterministic?
2. Jenkins reported failure, but the GitHub UI does not show a link. @kmaehashi maybe this also relates to the GitHub API fix?

**Comment by emcastillo** [comment]
Cache stats for windows,

```
Runtime Statistics
==================
Compile Cache hits 5002
Compile Cache misses 34942
Compile Cache hit ratio 0.13
```
I also suspect that the hashing in windows has something to do with this, or that we are unpacking the saved cache in the wrong folder.

**Comment by kmaehashi** [comment]
I checked a cache key. https://github.com/cupy/cupy/blob/v9.0.0b3/cupy/cuda/compiler.py#L479 and noticed that the key includes the full path to the CuPy's source tree. 


```
('70', ('-IC:\\Users\\chainer\\cupy\\cupy\\core\\include', '-IC:\\Users\\chainer\\cupy\\cupy\\core\\include\\cupy\\_cuda\\cuda-10.0', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\include', '-ftz=true'), (10, 0), 'nvrtc') b'//\n// Generated by NVIDIA NVVM Compiler\n//\n// Compiler Build ID: CL-24817639\n// Cuda compilation tools, release 10.0, V10.0.130\n// Based on LLVM 3.4svn\n//\n\n.version 6.3\n.target sm_70\n.address_size 64\n\n\n\n' #include <cupy/complex.cuh>
```

The problem is that FlexCI checkouts the git repo to a different path for every launch because it includes a execution ID, e.g., `C:\Windows\TEMP\flexci\run-00145123\work\src`.

**Comment by kmaehashi** [comment]
I think we can workaround this by pip installing it (ie avoid using `pip install -e`)

**Comment by kmaehashi** [comment]
Windows kernel cache issue is resolved via #4970. This helped a lot diagnosing the issue, thanks!

**Pull request closed without merging**
