### PR TITLE
[backport] Package tests in sdist

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #2563

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by jakirkham** [comment]
Thanks for doing this! 😄

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Sorry for the delay, LGTM.

**Pull request merged**
