### PR TITLE
Support `ignore_error` in kernel optimization

### PR DESCRIPTION
**Pull request by asi1024**
Address https://github.com/cupy/cupy/pull/3244#discussion_r435475481.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Is it possible to pass in `ignore_error` from `cupyx.optimizing.optimize`?

**Comment by leofang** [comment]
Would be nice if we could do this:
```python
with optimizing.optimize(key=None, ignore_error=(some_exception, )):
    # do something
```
which is not currently possible I think?

**Comment by asi1024** [comment]
It is possible to pass in `ignore_error` only from internal implementation.
In reduction case for example, it is passed from the following place:
https://github.com/cupy/cupy/blob/bedd67790e33812cdd3a4b4a8e0c841248e2cdaf/cupy/core/_reduction.pyx#L397-L404

**Comment by asi1024** [comment]
I think `ignore_error` parameters don't need to be exposed to the users in most situations.

**Comment by leofang** [comment]
Yeah that's [what I figured](https://github.com/cupy/cupy/pull/3244#issuecomment-641479088) 😇 Just wanna confirm with you I understand it correctly 🙏

**Pull request merged**
