### PR TITLE
Refactor ndimage_tests

### PR DESCRIPTION
**Pull request by toslunar**
Requires #4304.

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
I pushed a merge commit, but I'll do `git rebase master` and drop 61fe60fd479a684ff01c3f699b5d40f125c38044 (part of #4320).

**Review by grlee77 — APPROVED** [review]

**Comment by toslunar** [comment]
While the merge commits were manual, the rebase is clean and the force-push has no diff in files.

**Comment by toslunar** [comment]
Jenkins, test this please

**Pull request merged**
