### PR TITLE
Fix typos in `cupy.cuda.cufft`

### LINKED ISSUE #4009: Possible typo ("dype" instead of "dtype") in cufft.pyx
Hi!

I think I have stumbled upon a typo in cufft.pyx. The function cufft.PlanNd.check_output_array has several mentions of "ndarray.dype", which I strongly suspect was intended to be "dtype". Apologies if this has already been reported.

Here is a traceback:

File "cupy\cuda\cufft.pyx", line 845, in cupy.cuda.cufft.PlanNd.check_output_array
AttributeError: 'cupy.core.core.ndarray' object has no attribute 'dype'

And here is my CuPy version:

CuPy Version          : 8.0.0rc1
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
CUDA Build Version    : 11000
CUDA Driver Version   : 11000
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
cuTENSOR Version      : None

### PR DESCRIPTION
**Pull request by leofang**
Follow up of #3102. Close #4009. Thanks to @plamenivanov257 for reporting.

### CODE REVIEW

**Comment by leofang** [comment]
This PR should be backported.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Jenkins, test this please

**Pull request merged**
