### PR TITLE
Tentatively disable cuquantum intersphinx

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes docs build failure.

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
Sorry for the disturbance. It seems our website had issues in the past few days, I am out of office but I am told it should be back now, @kmaehashi would you kindly check when you get a chance?

**Comment by kmaehashi** [comment]
@leofang Thanks, but it seems `https://docs.nvidia.com/cuda/cuquantum/objects.inv` is still returning 403 error 😓

**Comment by leofang** [comment]
Sorry for the disruption, it should be fixed now 😓

**Pull request merged**
