### PR TITLE
Support compile-time constants in Fusion

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
Could you resolve conflict?

**Comment by asi1024** [comment]
Rebased.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
