### PR TITLE
Test `numpy.VisibleDeprecationWarning`

### PR DESCRIPTION
**Pull request by toslunar**
`numpy.VisibleDeprecationWarning` inherits `UserWarning`.

Merge #4226 first.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
**Fix ValueError testcases of `random.choice`** (c44474c7629351386aef47024866c0a38b0ed5b2)

The assertion in the previous test didn't work as intended.
Applying `cupy.asarray` to a ragged nested sequence results raises
`ValueError: Unsupported dtype object`, while `numpy.asarray` constructs
an object-array (with VisibleDeprecationWarning) in NumPy.

This commit replaces the testcases with pure `ndim` checks:
- `ValueError: a must be 1-dimensional`
- `ValueError: p must be 1-dimensional`

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI pass.

**Pull request merged**
