### PR TITLE
improve message during installation

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR tries to fix issue #669.

Currently many users are frequently trapped with installation issues.
I want to mitigate this situation by making messages more friendly.

By applying this PR, the following configuration summary is printed.

```
************************************************************
* CuPy Configuration Summary                               *
************************************************************

Build Environment:
  Include directories: ['/usr/local/cuda/include']   
  Library directories: ['/usr/local/cuda/lib64']
  nvcc command       : ['/usr/local/cuda/bin/nvcc']

Environment Variables:
  CFLAGS          : (none)
  LDFLAGS         : (none)
  LIBRARY_PATH    : /home/kenichi/.nccl/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib64:
  CUDA_PATH       : (none)
  NVCC            : (none)

Modules:
  cuda      : Yes (version 9.0.0)
  cudnn     : Yes (version 7.0.4)
  nccl      : Yes (version 2.1.2)
  cusolver  : Yes
  thrust    : Yes
************************************************************
```

When some of the module is unavailable,

```
************************************************************
* CuPy Configuration Summary                               *
************************************************************

Build Environment:
  Include directories: ['/usr/local/cuda/include']
  Library directories: ['/usr/local/cuda/lib64']
  nvcc command       : ['/usr/local/cuda/bin/nvcc']

Environment Variables:
  CFLAGS          : (none)
  LDFLAGS         : (none)
  LIBRARY_PATH    : /home/kenichi/.nccl/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib64:/home/kenichi/.cudnn/active/cuda/lib64:
  CUDA_PATH       : (none)
  NVCC            : (none)

Modules:
  cuda      : Yes (version 9.0.0)
  cudnn     : No (version 2.0.0)
    -> The library is installed but not supported.
  nccl      : No
    -> Cannot link libraries: ['nccl']
    -> Check your LDFLAGS environment variable.
  cusolver  : Yes
  thrust    : Yes

WARNING: Some modules could not be configured.
CuPy will be installed without these modules.
Please refer to the Installation Guide for details:
http://docs-cupy.chainer.org/en/stable/install.html
************************************************************
```

Full output example is as follows:

https://gist.github.com/kmaehashi/a944c9d1de181d1a398cd2e343eea38a

### CODE REVIEW

**Comment by sonots** [comment]
I may also want these environment variables to be printed, CUDA_PATH, and NVCC https://github.com/cupy/cupy/blob/e51b311608545870c1ee0bb70a48adcc60b5cbd2/docs/source/reference/environment.rst

**Comment by kmaehashi** [comment]
This PR is ready for review.
It would be nice if this PR can be merged before "cupy wheel support" PR.

**Comment by kmaehashi** [comment]
Via Jenkins (adhoc job), I confirmed that all compatible combinations of CUDA/cuDNN can be built.
I also manually tested that error is reported when some library is missing or unsatisfying version requirements.

**Comment by kmaehashi** [comment]
@okuta Thanks for review! Fixed accordingly.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
