### PR TITLE
Unify linux/windows randint with NumPy

### PR DESCRIPTION
**Pull request by emcastillo**
Alternative to #4802

### CODE REVIEW

**Comment by leofang** [comment]
Wow this works?!

**Comment by emcastillo** [comment]
I hope so

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by leofang — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Windows failure is fixed! I think this should be backported.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
