### PR TITLE
Add occupancy driver APIs

### PR DESCRIPTION
**Pull request by leofang**
***UPDATE***: Now only keeps the low-level API exposed, see https://github.com/cupy/cupy/pull/2424#issuecomment-525466669.

The following  APIs are added:
1. `cupy.cuda.driver.occupancyMaxActiveBlocksPerMultiprocessor()` (low-level/private API)
2. `cupy.cuda.driver.occupancyMaxPotentialBlockSize()` (low-level/private API)
3. ~~`cupy.RawKernel.calculate_theoretical_occupancy()` (as a high-level API for 1)~~
4. ~~`cupy.RawKernel.calculate_max_block_size()` (as a high-level API for 2)~~

I was looking into occupancy issues, and I thought it'd be nice for `RawKernel` users to be able to do the estimations in Python. I may have made mistakes in the implementation, and this might not be as useful as I thought, so based on the feedbacks I am fine with either making significant changes to or closing this PR. Thank you.

Design decisions:
- I wrapped the driver API instead of runtime API because it's not possible to pass `Function`/`CUFunction` pointers, which is all we have, to the latter (will get a `cudaErrorInvalidDeviceFunction` error), although I do think using runtime API for such a simple task is preferable.
- ~~I implemented simple, private checks (`_check_block_size()` and `_check_shmem_size()`) in `RawKernel` for basic input verification. While all positive integers are valid input for the driver API (say using an insanely huge `block_size=10000000`), getting `0` as output makes little sense to the users. But for simplicity perhaps we don't want those checks? I'm open to discussion.~~

~~Possible improvement:~~
- ~~Is it OK if we call `_check_shmem_size()` in `RawKernel.__call__()` to make the error message clearer, say in the situation of https://github.com/cupy/cupy/issues/2118#issuecomment-479546034? Is this considered not performant?~~

### CODE REVIEW

**Comment by emcastillo** [comment]
While I think it can be pretty useful to expose the occupancy related attributes through the API, I am not sure wether having a "calculate_occupancy" in the API is relevant enough. However I am not against it.

I am thinking that it would be cool to add a flag when launching a kernel for the first time to use this information to tune subsequent calls transparently. I am not sure if this makes enough sense

**Comment by leofang** [comment]
> While I think it can be pretty useful to expose the occupancy related attributes through the API, I am not sure wether having a "calculate_occupancy" in the API is relevant enough. However I am not against it.

I don't have strong opinion on the new `RawKernel` methods. This PR is more like kicking off a discussion and see where it can evolve to. 

But, it'd be nice to have the driver APIs added at least. Then, if we expose the underlying kernel through a readonly `RawKernel.ptr`, advanced users can call the driver APIs themselves. 

> I am thinking that it would be cool to add a flag when launching a kernel for the first time to use this information to tune subsequent calls transparently. I am not sure if this makes enough sense

Yes, this would be cool, but would require careful thought, as max occupancy doesn't necessarily guarantee max performance. There are other factors like memory coalescing that could also affect the speed.

**Comment by emcastillo** [comment]
> But, it'd be nice to have the driver APIs added at least. Then, if we expose the underlying kernel through a readonly RawKernel.ptr, advanced users can call the driver APIs themselves.

I agree with this, I also would like to have the cuda api exposed to some users. I am just wondering if its necessary to perform the occupancy calculations ourselves.

>Yes, this would be cool, but would require careful thought, as max occupancy doesn't necessarily guarantee max performance. There are other factors like memory coalescing that could also affect the speed.

Indeed, but mem coalescing is something that is implicit to the kernel itself, so is not magically tunable from the runtime system side. Maybe just for future reference, a kwarg `max_occupancy=True` to the `launch_kernel` method should suffice. I am not saying that we have to implement this.

**Comment by emcastillo** [comment]
Thanks for your hard work, sorry that you had to modify it.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Lets merge!

**Pull request merged**
