### PR TITLE
Setup random of Python library in testing/random

### PR DESCRIPTION
**Pull request by okuta**
rel #82

### CODE REVIEW

**Comment by niboshi** [comment]
Test has failed with a already-fixed-issue (https://github.com/chainer/chainer/pull/3627). Could you rebase?

**Comment by okuta** [comment]
I fixed.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
