### PR TITLE
add upgrade guide for v2 & v4

### LINKED ISSUE #878: Write upgrade guide
Let's write upgrade guide for CuPy.

c.f., https://github.com/chainer/chainer/pull/4151

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR adds upgrade guide for CuPy v2 and v4.
This fixes #878.

Remove v4 part when backporting.

### CODE REVIEW

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by delta2323** [comment]
I think it is better to note that CuPy v3 is skipped in the upgrade guide.

**Comment by kmaehashi** [comment]
@delta2323 Yes, that's covered here 😃 
https://github.com/cupy/cupy/pull/884/files#diff-9963560d58f6826ab7d096ab92c63712R16

**Comment by delta2323** [comment]
Oh, sorry. I overlooked it asI didn't check the generated documents. That looks to me.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by mitmul** [comment]
The test has succeeded. LGTM

**Pull request merged**
