### PR TITLE
Improve batched SVD

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of https://github.com/cupy/cupy/pull/4690#discussion_r579984220. Overwrites the intermediate array to reduce memory footprint, which seems to also perform faster.

### CODE REVIEW

**Comment by leofang** [comment]
Will experiment with a small pool of `(handle, stream)` and see if it improves performance or not.

**Comment by leofang** [comment]
> Will experiment with a small pool of `(handle, stream)` and see if it improves performance or not.

My preliminary conclusion is it does not help. In each `gesvd` call there are many small kernels launched and a few host-device transfers involved, so all these bring in non-negligible overheads that cannot be eliminated by simple stream parallelism. Only when cuSOLVER supports stream capture (#4567) would these be mitigated I am afraid...

**Comment by toslunar** [comment]
link to the issue (on non-batched SVD): #3327

**Comment by leofang** [comment]
Before this PR: 
```
svd                 :    CPU:967495.508 us   +/-387.404 (min:967270.049 / max:968551.172) us     GPU-0:967618.262 us   +/-388.642 (min:967400.391 / max:968675.598) us
```
after this PR:
```
svd                 :    CPU:957821.612 us   +/-3866.952 (min:953878.185 / max:962332.340) us     GPU-0:957949.573 us   +/-3870.807 (min:954001.221 / max:962460.022) us
```
input array: `cp.random.random((256, 64, 64))`

**Comment by leofang** [comment]
This is ready.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Review by toslunar — APPROVED** [review]

**Comment by leofang** [comment]
Thanks, @toslunar!

**Pull request merged**
