### PR TITLE
Add user guide for FFT

### LINKED ISSUE #5199: Normal behaviour or memory leak in fourier_shift?
While using the fourier shift I was observing the following behaviour and I cannot find a way to clear the residual memory.
As far as I see it, I am cleaning everything I have access to, right?
```
import cupy as cp
from cupyx.scipy.ndimage import fourier_shift as fourier_shift_g
mempool = cp.get_default_memory_pool()
for ii in range(2):
    print("Before:", mempool.used_bytes())
    a=cp.random.randn(1000,1000)
    print("After First:", mempool.used_bytes())
    a_ft=cp.fft.fftn(a)
    b=cp.fft.ifftn(fourier_shift_g(a_ft,[1,1]))
    print("After Shift:", mempool.used_bytes())
    del a
    del b
    del a_ft
    mempool.free_all_blocks()
    print("After Delete:", mempool.used_bytes())
print(cp.__version__)
```

```
Before: 0
After First: 8000000
After Shift: 56000000
After Delete: 16000000
Before: 16000000
After First: 24000000
After Shift: 56000000
After Delete: 16000000
9.0.0
```

```
OS                           : Windows-10-10.0.19041-SP0
CuPy Version                 : 9.0.0
NumPy Version                : 1.20.2
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA Build Version           : 11020
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11401
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1080 Ti
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:65:00.0
```

### PR DESCRIPTION
**Pull request by leofang**
Close #5199. Part of https://github.com/cupy/cupy/issues/4902#issuecomment-813205619.

### CODE REVIEW

**Comment by leofang** [comment]
This is ready for review! Though I probably missed the cutoff time...🤦 

Jenkins, test this please

**Comment by leofang** [comment]
btw this PR can be backported.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Review by takagi — APPROVED** [review]

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
