### PR TITLE
[v13] Missing backport for sparse_array.A removal

### PR DESCRIPTION
**Pull request by asi1024**
master: #8527
v13: #8552

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks! This is needed for SciPy 1.14.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Please proceed to merge after test pass.

**Comment by asi1024** [comment]
The CI failure on SciPy 1.7 is unrelated to this PR. (will be fixed by https://github.com/cupy/cupy/pull/8576.)

**Pull request merged**
