### PR TITLE
Improve caching in `ElementwiseKernel`

### PR DESCRIPTION
**Pull request by okuta**
Using local and global dictionary for fast lookup.

### CODE REVIEW

**Comment by okuta** [comment]
Jenkins, test this please

**Comment by okuta** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
@okuta Please check this PR: #2474

**Comment by okuta** [comment]
This PR also uses global dictionary to keep #2474.
https://github.com/cupy/cupy/pull/2688/files#diff-e2a721d3ce2742c7fd3e3e565742b7feR401

**Comment by niboshi** [comment]
OK, I didn't notice `@util.memoize`.
Please post a benchmark.

**Comment by okuta** [comment]
[benchmark code](https://gist.github.com/okuta/51b5f356ffbc7b8a69cc0ad6478ea221)

before
```
% python adam_elem2.py
adam     ,    1, 0.017272, 0.017270
adam     ,   10, 0.017024, 0.017023
```

after
```
% python adam_elem2.py
adam     ,    1, 0.015939, 0.015937
adam     ,   10, 0.015753, 0.015752
```

**Comment by niboshi** [comment]
What do the numbers mean? I can't see what `util` does.

**Comment by okuta** [comment]
This benchmark is for `_get_elementwise_kernel`. `util` pass has not passed.

**Comment by niboshi** [comment]
I wanted to ask the units of the numbers.

>`util` pass has not passed.

It looks each line is generated from within `util`. Am I missing anything?

Btw, I don't think it's that meaningful to measure `_get_elementwise_kernel` directly unless it's proven a hotspot.

**Comment by okuta** [comment]
Oh, I misunderstood. I used [this](https://github.com/okuta/cupy-bench/blob/master/util.py).
The unit is millisecond.

**Comment by niboshi** [comment]
So, the difference is just 65 ns?
Honestly I don't think it's worth complicating the code.

**Comment by okuta** [comment]
In my understanding 1085 ns?

**Comment by niboshi** [comment]
Sorry, I overlooked the numbers were averaged.
But I wonder how this fix could improve that much. It's contradictory to my previous benchmark in #2474.

**Comment by okuta** [comment]
Thanks. I tried cupy-pref.

before  ( 2e0515457848afb3cbd173b4d4f6b5dab53f24cc )
```
userkernel          :     8.064 us   +/- 0.245 (min:    7.801) us
```

after
```
userkernel          :     7.607 us   +/- 0.222 (min:    7.389) us
```

**Comment by toslunar** [comment]
kindly ping @niboshi

**Comment by niboshi** [comment]
Sorry for delay.
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
