### PR TITLE
Minor fixes to random kernels

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Merge #1681 first.

**Comment by YoshikawaMasashi** [comment]
Sorry for delay...
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
