### PR TITLE
[backport] Bump Cython version requirement for Python 3.9

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4706

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
CI unrelated

**Pull request merged**
