### PR TITLE
Detect repeated axis in reduction

### LINKED ISSUE #4486: `expand_dims` fails to check duplicated axes
```
>>> cupy.expand_dims(cupy.ones(7), axis=(0, -3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/cupy/_manipulation/dims.py", line 148, in expand_dims
    return _manipulation._expand_dims(a, axis)
  File "cupy/core/_routines_manipulation.pyx", line 223, in cupy.core._routines_manipulation._expand_dims
  File "cupy/core/_routines_manipulation.pyx", line 238, in cupy.core._routines_manipulation._expand_dims
  File "cupy/core/_routines_manipulation.pyx", line 317, in cupy.core._routines_manipulation._reshape
ValueError: cannot reshape array of size 7 into shape 49
```

### PR DESCRIPTION
**Pull request by toslunar**
Fix #4486.

### CODE REVIEW

**Review by takagi — APPROVED** [review]

**Comment by toslunar** [comment]
run jenkins please

**Comment by toslunar** [comment]
Updated the branch because it must have #6034 to run tests.

**Pull request merged**
