### PR TITLE
Move the NVTX module to `cupy_backends.cuda.libs`

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of #4919, #4920. 

This PR moves the `nvtx` module out of `cupy.cuda`, which makes better sense now that we put all CUDA modules that link to vendor libraries under `cuda_backends/cuda/{api, libs}`. The rest of CUDA modules in `cupy.cuda` are either CuPy-specific, or do not link to a particular CUDA component (ex: Thrust/CUB/Jitify are all header-only); the `cufft` module is the only exception due to the need of supporting FFT callbacks (#4853).

This also makes sense for rocTX, for which we already put the stub in `cupy_backends/hip/cupy_roctx.h` (#4088).

This PR does not break backward compatibility.

### CODE REVIEW

**Comment by leofang** [comment]
Not sure what caused this error: 
https://github.com/cupy/cupy/pull/4930/checks?check_run_id=2158104374#step:7:881

**Comment by leofang** [comment]
I took a closer look and still don't understand the error. Like `runtime`, `nvtx` is now also imported from `cupy_backends`, but Sphinx has no problem in documenting the functions from the `runtime` module.

**Comment by leofang** [comment]
> I took a closer look and still don't understand the error. Like `runtime`, `nvtx` is now also imported from `cupy_backends`, but Sphinx has no problem in documenting the functions from the `runtime` module.

Oh... I got it, there's a `cupy/cuda/runtime.py` just to make Sphinx happy...#3685

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Pull request merged**
