### PR TITLE
Windows: fix sparse matrix indexing type

### PR DESCRIPTION
**Pull request by leofang**
~~***DO NOT MERGE***~~ Another guess work...

### CODE REVIEW

**Comment by leofang** [comment]
I need to know we never get int64 on Linux either.

Jenkins, test this please

**Comment by leofang** [comment]
wtf the failures are gone (986 -> 1xx)?!

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@asi1024 I fixed it. Unlike on Linux, `np.intc != np.int32` on Windows.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
LGTM!

**Review by asi1024 — APPROVED** [review]

**Comment by leofang** [comment]
Thanks, @asi1024!

**Comment by leofang** [comment]
btw I think this should be backported.

**Pull request merged**
