### PR TITLE
Don't set FFT work area when gained work area size is zero

### PR DESCRIPTION
**Pull request by takagi**
(Replace #5309)

`hipfftMakePlan1d` can output zero for the work area size, and given a null pointer returned by the allocator that supplied zero for the size, `hipfftSetWorkArea` (internally calls `rocfft_execution_info_set_work_buffer`) returns `HIPFFT_INVALID_VALUE`.

This PR fixes `Plan1d` not to set the work area pointer if the computed work area size is zero. Also `PlanNd` has the same fix.

### CODE REVIEW

**Review by leofang — APPROVED** [review]
LGTM! Thanks for looking into this for me @takagi 😅 Got too many things on my plate this week...

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
Please wait to merge this change into the master before I check if hipFFT version in hipFFT repo also replicates this error. See https://github.com/cupy/cupy/issues/5314#issuecomment-854431141.

**Comment by takagi** [comment]
Let me close this PR as #5318 also solves #5309.

**Pull request closed without merging**
