### PR TITLE
Add FlexCI configurations

### PR DESCRIPTION
**Pull request by kmaehashi**
As a first step, employ the same test variation as Chainer.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Tests for this PR:
https://ci.preferred.jp/cupy.docker.py27and35.push/43529/
https://ci.preferred.jp/cupy.docker.py27and35.test/43530/
https://ci.preferred.jp/cupy.docker.py37.push/43531/
https://ci.preferred.jp/cupy.docker.py37.test/43532/
https://ci.preferred.jp/cupy.py37.gpu/43533/
https://ci.preferred.jp/cupy.py27and35.gpu/43534/

I'll enable webhook after this PR got merged.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
