### PR TITLE
Detect synchronization

### LINKED ISSUE #2808: Detection of device synchronization
Device synchronization is a source of performance degradation, but currently even some of CuPy functions implicitly (whether intentionally or not) do that (#2797).

It would be nice to have a mechanism to detect device synchronization.

### Proposal

Add a context manager within which any operation that synchronizes the device causes an error. The context manager sets a thread-local configuration variable.

```py
with cupyx.allow_synchronize(False):
    ... # operations that are not supposed to synchronize
```

In low-level CuPy code that cause synchronization like `ndarray.get`, insert `_declare_synchronize()` call as follows:

```py
cpdef _declare_synchronize():
    ... # Raise an error if within allow_synchronize(False).

cdef class ndarray:
    cpdef get(self, ...):
        _declare_synchronize()
       ...
```

### Application in unit tests

Given the above implemented, we could apply it in `testing.numpy_cupy_equal` for example. If the test code has expected device synchronization, the test implementation can enclose the code with `cupyx.allow_synchronize(True)` explicitly.

### Notes
* `ndarray.get` may copy asynchronously if certain conditions are met (if using a non-default stream and given an explicit `out` with pinned memory). If's difficult for the code to predict whether it's actually synchronous or not. Maybe it's safe to separate asynchronous behavior as another method like `ndarray.get_async`.

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #2808
Depends on #2818

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
@emcastillo  Please merge #2818 first.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
#2818 was merged

**Comment by niboshi** [comment]
Please merge #2818.

**Comment by emcastillo** [comment]
Rebase please :)

**Comment by niboshi** [comment]
PTAL.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
😂I guess that we have more synchronization than we expected

**Comment by niboshi** [comment]
Hmm, it's too many...
I think we should separate the change to test helpers as another PR.

**Comment by emcastillo** [comment]
I agree. At first, I thought that all of them were going to be fine so it was nice to do the checks all-together.

**Comment by niboshi** [comment]
Done (force-pushed).

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
Discussion to remove this feature ongoing in #2946

**Pull request merged**
