### PR TITLE
Doc: Add links to Anaconda, Gitter, StackOverflow

### LINKED ISSUE #3696: Document places for seeking for help and/or discussions
I think this is kinda follow-up of #3529? 
- Slack?
- Mailing list?
- GitHub issue tracker?
- any other channels I am not aware of? 🙂

### PR DESCRIPTION
**Pull request by leofang**
The Anaconda badge is copied from https://anaconda.org/conda-forge/cupy/badges.

Close #3696.

### CODE REVIEW

**Comment by jakirkham** [comment]
We also have `shields.io` based icons that we use in conda-forge that could be used here if preferred. Copied them from the README below

```markdown
Current release info
====================

| Name | Downloads | Version | Platforms |
| --- | --- | --- | --- |
| [![Conda Recipe](https://img.shields.io/badge/recipe-cupy-green.svg)](https://anaconda.org/conda-forge/cupy) | [![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/cupy.svg)](https://anaconda.org/conda-forge/cupy) | [![Conda Version](https://img.shields.io/conda/vn/conda-forge/cupy.svg)](https://anaconda.org/conda-forge/cupy) | [![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/cupy.svg)](https://anaconda.org/conda-forge/cupy) |
```

**Comment by leofang** [comment]
Oh nice, thanks @jakirkham. I like the "Conda Version" one better as it says "conda-forge". Will change to that.

**Comment by jakirkham** [comment]
Sounds good. Also thanks for working on this btw 🙂

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
Thanks, LGTM!

**Pull request merged**
