### PR TITLE
[WIP] Use fuse to improve norm 

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by asi1024** [comment]
How about using ReductionKernel?

**Comment by asi1024** [comment]
The current implementation creates kernels for each combination of `axis` and `keepdims`, but `cupy.ReductionKernel` does not.

**Comment by leofang** [comment]
I know very little about `@fuse()`, but I think if you provide a fast path using `create_reduction_func()`, #3244 should provide a very good performance.

**Comment by okuta** [comment]
Thanks!  #3244 is a better Implementation than this.

**Pull request closed without merging**
