### PR TITLE
TST/ENH: have the parameterize decorator generate descriptive ids

### PR DESCRIPTION
**Pull request by grlee77**
`pytest.mark.parametrize` generates descriptive IDs for the parameters provided.

This PR provides similar behavior for the `cupy.testing.parameterize` decorator. 

Prior to the present PR, this decorator justt enumerates the parameters as "_param_0", "_param_1", etc.
A concrete example:
```
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_0.test_cupy_array ✓                20% ██▏       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_1.test_cupy_array ✓                22% ██▎       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_2.test_cupy_array ✓                23% ██▍       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_3.test_cupy_array ✓                24% ██▌       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_4.test_cupy_array ✓                25% ██▌       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_5.test_cupy_array ✓                27% ██▋       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_6.test_cupy_array ✓                28% ██▊       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_7.test_cupy_array ✓                29% ██▉       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_8.test_cupy_array ✓                30% ███       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_9.test_cupy_array ✓                31% ███▎      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_10.test_cupy_array ✓               33% ███▍      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_11.test_cupy_array ✓               34% ███▍      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_12.test_cupy_array ✓               35% ███▌      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_13.test_cupy_array ✓               36% ███▋      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_14.test_cupy_array ✓               37% ███▊      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy_param_15.test_cupy_array ✓               39% ███▉      
```

after this PR, more decriptive ids are generated
```
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-0-numpy].test_cupy_array ✓          20% ██▏       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-0-cupy].test_cupy_array ✓           22% ██▎       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-1-numpy].test_cupy_array ✓          23% ██▍       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-1-cupy].test_cupy_array ✓           24% ██▌       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-2-numpy].test_cupy_array ✓          25% ██▌       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-2-cupy].test_cupy_array ✓           27% ██▋       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-3-numpy].test_cupy_array ✓          28% ██▊       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[True-3-cupy].test_cupy_array ✓           29% ██▉       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-0-numpy].test_cupy_array ✓         30% ███       
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-0-cupy].test_cupy_array ✓          31% ███▎      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-1-numpy].test_cupy_array ✓         33% ███▍      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-1-cupy].test_cupy_array ✓          34% ███▍      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-2-numpy].test_cupy_array ✓         35% ███▌      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-2-cupy].test_cupy_array ✓          36% ███▋      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-3-numpy].test_cupy_array ✓         37% ███▊      
tests/cupy_tests/creation_tests/test_from_data.py::TestArrayCopy[False-3-cupy].test_cupy_array ✓          39% ███▉      
```

I find this useful when testing to more quickly determine which cases are failing.

### CODE REVIEW

**Comment by grlee77** [comment]
In the final commit here, I removed a bunch of code that was supporting `bytes` objects, regex objects and non-ascii characters in strings. I was not sure any cases in CuPy would make use of these, but if they are of interest, we restore them.

**Comment by leofang** [comment]
Oh this is handy!

**Comment by kmaehashi** [comment]
Thank you for your work!
Actually we have a similar code to include parameters in test class names in Chainer. As cupy/testing is a fork of chainer/testing, I'd like to pull this feature from Chainer.
https://github.com/chainer/chainer/blob/959eb4866525bf7d2e90af5ef3ae628fbbf6ca56/chainer/testing/parameterized.py#L33-L101

**Comment by grlee77** [comment]
Okay, that should work too. Do you recommend I copy that code over in this PR then?

**Comment by grlee77** [comment]
For reference, I also made an upstream PR to pytest to allow the `__name__` attribute to be used on any object (rather than just functions or classes): pytest-dev/pytest#6152. That is useful for getting the names of "numpy" or "cupy" to show up in that name if modules are used as parameters.

**Comment by kmaehashi** [comment]
> Do you recommend I copy that code over in this PR then?

Yes, please. (Lot of changes has been made in Chainer repo since fork, so the region I quoted may not be sufficient)

> For reference, I also made an upstream PR to pytest to allow the __name__ attribute to be used on any object (rather than just functions or classes): pytest-dev/pytest#6152. That is useful for getting the names of "numpy" or "cupy" to show up in that name if modules are used as parameters.

Great!

**Comment by grlee77** [comment]
closing in favor of #2633

**Pull request closed without merging**
