### PR TITLE
Fix missing documents

### PR DESCRIPTION
**Pull request by not522**
Some functions are not documented. I add them to the document.

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
Please fix following error.
```
Warning, treated as error:
/home/user/.local/lib/python3.5/site-packages/cupy-4.0.0rc1-py3.5-linux-x86_64.egg/cupy/sparse/construct.py:docstring of cupy.sparse.rand:None: WARNING: more than one target found for cross-reference 'dtype': cupy.sparse.dia_matrix.dtype, cupy.sparse.csr_matrix.dtype, cupy.sparse.csc_matrix.dtype, cupy.sparse.coo_matrix.dtype, cupy.ndarray.dtype```

**Comment by not522** [comment]
OK, I fixed.

**Comment by okuta** [comment]
Thanks!

**Comment by okuta** [comment]
LGTM!

**Comment by okuta** [comment]
jenkins, test this please.

**Pull request merged**
