### PR TITLE
ROCm: Support rocFFT/hipFFT

### LINKED ISSUE #3892: ROCm: Support rocFFT
Currently we don't support the FFT library on ROCm, and attempting to do FFT would return a weird OOM error (presumably due to incorrect return code overflowing):
```python
>>> import cupy
>>>
>>> a = cupy.random.random(10)
>>> cupy.fft.fft(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leo/dev/cupy_rocm35/cupy/fft/fft.py", line 578, in fft
    return _fft(a, (n,), (axis,), norm, cupy.cuda.cufft.CUFFT_FORWARD)
  File "/home/leo/dev/cupy_rocm35/cupy/fft/fft.py", line 187, in _fft
    a = _fft_c2c(a, direction, norm, axes, overwrite_x, plan=plan)
  File "/home/leo/dev/cupy_rocm35/cupy/fft/fft.py", line 157, in _fft_c2c
    a = _exec_fft(a, direction, 'C2C', norm, axis, overwrite_x, plan=plan)
  File "/home/leo/dev/cupy_rocm35/cupy/fft/fft.py", line 114, in _exec_fft
    plan = cufft.Plan1d(out_size, fft_type, batch, devices=devices)
  File "cupy/cuda/cufft.pyx", line 277, in cupy.cuda.cufft.Plan1d.__init__
    self._single_gpu_get_plan(plan, nx, fft_type, batch)
  File "cupy/cuda/cufft.pyx", line 308, in cupy.cuda.cufft.Plan1d._single_gpu_get_plan
    work_area = memory.alloc(work_size)
  File "cupy/cuda/memory.pyx", line 569, in cupy.cuda.memory.alloc
    return get_allocator()(size)
  File "cupy/cuda/memory.pyx", line 1241, in cupy.cuda.memory.MemoryPool.malloc
    cpdef MemoryPointer malloc(self, size_t size):
  File "cupy/cuda/memory.pyx", line 1262, in cupy.cuda.memory.MemoryPool.malloc
    return mp.malloc(size)
  File "cupy/cuda/memory.pyx", line 930, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
    return self._malloc(rounded_size)
  File "cupy/cuda/memory.pyx", line 950, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
    mem = self._try_malloc(size)
  File "cupy/cuda/memory.pyx", line 1201, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
    raise OutOfMemoryError(
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 140,289,776,869,376 bytes (allocated so far: 1,024 bytes).
```
Note that while there's no package named hipFFT, it is actually there, bundled with rocFFT:
https://github.com/ROCmSoftwarePlatform/rocFFT/blob/master/library/include/hipfft.h

### PR DESCRIPTION
**Pull request by leofang**
~~Blocked by #3823.~~ Close #3892.

~~This builds and many tests pass, but some are failing.~~

***UPDATE***: major changes
- Support hipFFT
    - Split the code paths for `CUPY_USE_HIP` and `CUPY_NO_CUDA` for functions supported by HIP
    - Work around several (likely) bugs I found, in particular `PlanNd` cannot be used for C2R transforms (due to https://github.com/cupy/cupy/pull/3896#issuecomment-683797721); see the added comments for further detail.
- Cythonize `Plan1d` and `PlanNd`
    - this is necessary because in cuFFT the plan handle is an `int`, but in `hipFFT` it is a pointer to struct...Now we unify the code path by passing an `intptr_t` around
    - the code path splitting requires a compile time constant passed to Cython by setuptools
    - `__del__` is changed to `__dealloc__` (#3999)

### CODE REVIEW

**Comment by leofang** [comment]
Now the only failing tests are C2R!

**Comment by leofang** [comment]
Unless I made some stupid mistakes, I think hipFFT's C2R is not usable:
```python
>>> import numpy as np
>>> import cupy as cp
>>>
>>> # random complex input is NOT ok
>>> a = cp.random.random(10, dtype=cp.float32) + 1j*cp.random.random(10, dtype=cp.float32)
>>> a.dtype
dtype('complex64')
>>> a_np = cp.asnumpy(a)
>>> b = cp.fft.irfft(a)
>>> b_np = np.fft.irfft(a_np)
>>> b
array([ 0.48595607, -0.3194939 , -0.02252738,  0.11538664,  0.03148964,
       -0.11357258, -0.06430689,  0.08313904,  0.00260075, -0.00425398,
        0.09948202,  0.00063049, -0.01858845,  0.15512069,  0.03431274,
        0.24397987, -0.09207862,  0.44578272], dtype=float32)
>>> b_np
array([ 0.47939911, -0.35235256, -0.02908434,  0.08252793,  0.02493267,
       -0.14643128, -0.07086385,  0.05028037, -0.00395623, -0.03711266,
        0.09292506, -0.03222817, -0.02514544,  0.12226199,  0.02775578,
        0.21112119, -0.0986356 ,  0.41292404])
>>>
>>> # complex input with zero imaginary parts seems to be fine
>>> a = cp.arange(10, dtype=cp.complex64)
>>> a.dtype
dtype('complex64')
>>> a_np = cp.asnumpy(a)
>>> b = cp.fft.irfft(a)
>>> b_np = np.fft.irfft(a_np)
>>> b
array([ 4.5000000e+00, -1.8424132e+00, -1.6556847e-08, -2.2222222e-01,
        5.2981907e-08, -9.4671570e-02,  0.0000000e+00, -6.2915191e-02,
       -1.7586314e-09, -5.5555582e-02, -2.6490953e-08, -6.2915117e-02,
        0.0000000e+00, -9.4671644e-02,  1.8315477e-08, -2.2222222e-01,
       -2.6490953e-08, -1.8424134e+00], dtype=float32)
>>> b_np
array([ 4.5       , -1.84241319,  0.        , -0.22222222,  0.        ,
       -0.09467157,  0.        , -0.06291524,  0.        , -0.05555556,
        0.        , -0.06291524,  0.        , -0.09467157,  0.        ,
       -0.22222222,  0.        , -1.84241319])
>>> 
```

**Comment by leofang** [comment]
@emcastillo I figured it out. [cuFFT has this requirement](https://docs.nvidia.com/cuda/cufft/index.html#fft-types) for C2R, 
> Note: Complex-to-real (C2R) transforms accept complex-Hermitian input, which requires the 0th element (and the N/2-th input if N is even) to be real-valued, i.e. its imaginary part should be zero. Otherwise, the behavior of the transform is undefined.

However, it's taken care internally by cuFFT, so we never noticed it, whereas hipFFT's C2R puts the burden on the users to make sure of this:
```python
>>> import numpy as np
>>> import cupy as cp
>>>
>>> a = cp.random.random(10, dtype=cp.float32) + 1j*cp.random.random(10, dtype=cp.float32)
>>>
>>> # for hipFFT
>>> a[0].imag = 0
>>> a[-1].imag = 0
>>>
>>> a_np = cp.asnumpy(a)
>>> b = cp.fft.irfft(a)
>>> b_np = np.fft.irfft(a_np)
>>> b
array([ 0.5821325 , -0.25925124,  0.0324426 , -0.1120427 , -0.10557208,
        0.09456067,  0.12584956,  0.01406221,  0.05270479,  0.19236413,
       -0.07810728,  0.01756343, -0.05592638, -0.11704351,  0.16015655,
        0.06900278,  0.12585214,  0.23711425], dtype=float32)
>>> b_np
array([ 0.58213251, -0.25925126,  0.0324426 , -0.11204271, -0.10557209,
        0.09456068,  0.12584956,  0.01406221,  0.05270478,  0.19236414,
       -0.07810728,  0.0175634 , -0.05592637, -0.11704352,  0.16015654,
        0.06900281,  0.12585215,  0.23711428])
>>> cp.allclose(b, b_np)
array(True)
```
Most likely this remains true for multi-dimensional C2R (I'll check), but I think we should do this check for AMD users, which unfortunately requires synchronization.

**Comment by leofang** [comment]
All tests passed locally! Will update the PR description to document the necessary workarounds for hipFFT once #3823 is merged.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Looks like the CI is dead 😂

**Comment by leofang** [comment]
`cupy.py3.amd` is updated and it builds.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
using cufft alone is probably incurring in synchronization by itself so I think this is unavoidable but should not cause major performance issues.
Can you please rebase?

Thanks

**Comment by leofang** [comment]
Let me do it at once after #3823 and all of the module rename PRs go in 😅

**Comment by leofang** [comment]
Hi @emcastillo I merged with master and this PR is ready to review now.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Shown offline to @emcastillo: this is interesting...

GTX 2080 Ti:
```
C2C FFT (axis=2):
 fftn                :    CPU:  148.031 us   +/- 3.367 (min:  146.122 / max:  161.570) us     GPU-0: 4226.872 us   +/-17.463 (min: 4188.960 / max: 4251.040) us
C2C FFT (axis=1,2):
 fftn                :    CPU:  174.954 us   +/- 4.315 (min:  171.386 / max:  189.976) us     GPU-0: 8969.329 us   +/-31.234 (min: 8898.816 / max: 9037.856) us
C2C FFT (axis=0,1,2):
 fftn                :    CPU:  171.077 us   +/- 3.839 (min:  165.215 / max:  181.019) us     GPU-0:14937.326 us   +/-62.839 (min:14825.472 / max:15116.224) us
```

Radeon VII (enabled by this PR):
```
C2C FFT (axis=2):
 fftn                :    CPU:   20.327 us   +/- 3.520 (min:   16.674 / max:   26.898) us     GPU-0: 2836.795 us   +/-31.802 (min: 2750.468 / max: 2922.715) us
C2C FFT (axis=1,2):
 fftn                :    CPU:   42.046 us   +/- 1.835 (min:   38.792 / max:   48.750) us     GPU-0:10846.327 us   +/-24.716 (min:10778.332 / max:10901.215) us
C2C FFT (axis=0,1,2):
 fftn                :    CPU:   47.947 us   +/- 2.565 (min:   45.028 / max:   59.669) us     GPU-0:33255.901 us   +/-51.133 (min:33137.306 / max:33403.049) us
```

**Comment by leofang** [comment]
@emcastillo I added a short summary to the PR description.

**Comment by leofang** [comment]
Marked this PR as draft to investigate the implication of #3999.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Made the plan cache (#3730) work with this PR!

**Review by emcastillo — APPROVED** [review]
Amazing work as always!

**Pull request merged**
