### PR TITLE
Fix bugs in CUB

### LINKED ISSUE #2634: CUB-related test failures
* Conditions 
CuPy Version          : 7.0.0rc1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuDNN Build Version   : 7402
cuDNN Version         : 7402
NCCL Build Version    : None
NCCL Runtime Version  : None

* Code to reproduce
run pytest with / without CUB enabled

* Error messages, stack traces, or logs

The following test cases give me an error when running pytest with CUB_DISABALED=0, but pass with CUB_DISABLED=1. I haven't looked into specific cases, but based on the test names I would guess it is a combination of a few possible things:

1.) reduction in the presence of NaN values
2.) reduction of zero-sized arrays
3.) errors in some axis-specific reduction cases

```


 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:39 TestArrayReduction.test_max_nan
 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:51 TestArrayReduction.test_max_nan_imag
 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:45 TestArrayReduction.test_max_nan_real
 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:87 TestArrayReduction.test_min_nan
 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:99 TestArrayReduction.test_min_nan_imag
 - tests/cupy_tests/core_tests/test_ndarray_reduction.py:93 TestArrayReduction.test_min_nan_real
 - tests/cupy_tests/linalg_tests/test_einsum.py:279 TestEinSumUnaryOperation_param_20.test_einsum_unary
 - tests/cupy_tests/linalg_tests/test_einsum.py:297 TestEinSumUnaryOperation_param_20.test_einsum_unary_dtype
 - tests/cupy_tests/linalg_tests/test_einsum.py:279 TestEinSumUnaryOperation_param_49.test_einsum_unary
 - tests/cupy_tests/linalg_tests/test_einsum.py:297 TestEinSumUnaryOperation_param_49.test_einsum_unary_dtype
 - tests/cupy_tests/linalg_tests/test_einsum.py:279 TestEinSumUnaryOperation_param_136.test_einsum_unary
 - tests/cupy_tests/linalg_tests/test_einsum.py:297 TestEinSumUnaryOperation_param_136.test_einsum_unary_dtype
 - tests/cupy_tests/linalg_tests/test_einsum.py:289 TestEinSumUnaryOperation_param_136.test_einsum_unary_views
 - tests/cupy_tests/linalg_tests/test_norms.py:18 TestTrace.test_external_trace
 - tests/cupy_tests/linalg_tests/test_norms.py:12 TestTrace.test_trace
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_9.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_10.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_11.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_12.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_13.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:21 TestPadDefault_param_14.test_pad_default
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_9.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_10.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_11.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_12.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_13.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_14.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_15.test_pad
 - tests/cupy_tests/padding_tests/test_pad.py:133 TestPad_param_16.test_pad
 - tests/cupy_tests/sorting_tests/test_search.py:23 TestSearch.test_argmax_nan
 - tests/cupy_tests/sorting_tests/test_search.py:65 TestSearch.test_argmax_zero_size
 - tests/cupy_tests/sorting_tests/test_search.py:89 TestSearch.test_argmin_nan
 - tests/cupy_tests/sorting_tests/test_search.py:137 TestSearch.test_argmin_zero_size
 - tests/cupy_tests/sorting_tests/test_search.py:327 TestNanArgMin.test_nanargmin_zero_size
 - tests/cupy_tests/sorting_tests/test_search.py:417 TestNanArgMax.test_nanargmax_zero_size
```

cc @leofang and @anaruse as fellow CUB contributors here

ref: #2579 which should help avoid similar issues in the future

### PR DESCRIPTION
**Pull request by leofang**
***UPDATE:*** closes #2634.

cc: @grlee77 @anaruse @kmaehashi

### CODE REVIEW

**Comment by leofang** [comment]
@grlee77, if you have time, could you confirm that this PR resolves all of the bugs you found? Thanks!

**Comment by leofang** [comment]
Note: as a bug fix that involves minimal code changes (at the Cython level), this PR meets the original intention for supporting C-contiguous arrays. However, with proper reduction axes (or `axis=None`) F-contiguous arrays can also use CUB. I will address this in the next PR.

**Comment by grlee77** [comment]
I can confirm the c-contiguity fix works. I haven't tested the others yet

**Comment by grlee77** [comment]
I can confirm that all of the previously failing cases from #2634 pass with these changes. Thanks for the quick fix @leofang!

**Comment by grlee77** [comment]
Not related to the test failures, but I think there is still a "bug" in terms of not using cub for some compatible axis combinations in `_routines_statistics.pyx`. This one is just a performance loss for cases where the user has specified the axis

specifically the two places with:
```Python
if axis is None and cub.can_use_device_reduce(
```
should just be
```Python
if cub.can_use_device_reduce(
```

`can_use_device_reduce` will check the axis via `_cub_device_reduce_axis_compatible`.

Probably worth just fixing that here as well

**Comment by leofang** [comment]
Good catch, @grlee77! That was a residual from the segmented reduce experiment. I just stole your commit and corrected it 🤣

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Comment by take-cheeze** [comment]
Jenkins, test this please!

**Comment by leofang** [comment]
Thank you @grlee77 for finding those bugs and testing this fix and @take-cheeze for review!

**Comment by leofang** [comment]
@take-cheeze I suppose this PR can be tagged with [v7.0.0](https://github.com/cupy/cupy/milestone/62)?

**Comment by take-cheeze** [comment]
@leofang Thank you for noticing. Should be added now

**Pull request merged**
