### PR TITLE
[backport] Use `_csr_row_index` for CSR matrix major-axis slicing with step

### PR DESCRIPTION
**Pull request by toslunar**
Backport of #3852

### CODE REVIEW

**Comment by toslunar** [comment]
[automatic post] Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
