### PR TITLE
Fix multi thread  bug in memory pool

### PR DESCRIPTION
**Pull request by okuta**

### CODE REVIEW

**Comment by sonots** [comment]
LGTM

**Comment by kmaehashi** [comment]
Is this case (``IndexError``) really possible, or just a defensive programming?  I tried to reproduce this issue but I couldn't.

As far as I know, there are no chance of `self._free[size]` being changed between `if free:` and `free.pop()`, as the thread calling `malloc` should have a GIL.

**Comment by okuta** [comment]
Thank you for your report of experiment result.

It is defensive programming.

CPython has a instruction counter for multi-thread.
I think that `if free` consume very few time. In other words, this python thread has a very low possibility of contest switching. But, if two thread want to get same size memory, old code raises error very low probability.

**Comment by okuta** [comment]
Oh, I did not consider about Cython.
Cython do not release GIL between that two lines.
This fixing is redundant...

Is this opinion correct? @kmaehashi

**Comment by kmaehashi** [comment]
@okuta Yes, I think so.

**Comment by okuta** [comment]
OK.
I will send revert PR.

**Pull request merged**
