### PR TITLE
Fix stream capture in ROCm

### LINKED ISSUE #6295: Stream capture error in ROCm tests
https://jenkins.preferred.jp/job/chainer/job/cupy_master/TEST=rocm-4-0,label=mnj-mi50/1919/console

```
 E   RuntimeError: streamIsCapturing is supported since CUDA 10.1+
```

### PR DESCRIPTION
**Pull request by emcastillo**
The checks where called unconditionally and caused version checks to blow up

Closes #6295

### CODE REVIEW

**Comment by emcastillo** [comment]
run jenkins please

**Review by leofang — APPROVED** [review]
Thanks, Emilio!

**Review by kmaehashi — APPROVED** [review]

**Comment by leofang** [comment]
With a few glimpses I can identify at least two classes of errors:
1. For some reason cuTENSOR 1.4.0 is installed in the `cuda115` CI, which has a potential bug (see [here](https://github.com/cupy/cupy/pull/6187#issuecomment-1004256532)).
2. For some reason CUDA 11.5.1 (instead of 11.5.0) is installed in the CI, which has a known bug in cuSPARSE (thus leading to some TestSpMM failures). This will be fixed in CUDA 11.6 (cc: @anaruse for confirmation). So please ping the CI to 11.5.0 for the time being.

**Comment by emcastillo** [comment]
are test failures related? or just some random cuda update trashed everything

**Comment by leofang** [comment]
No they are unrelated.

**Comment by kmaehashi** [comment]
#6303 should fix CUDA 11.5 CI errors.

**Pull request merged**
