### PR TITLE
use continuous copies for concatenate if arrays are not contiguous on axis

### PR DESCRIPTION
**Pull request by uchida**
For #419 

benchmark code:
```
from itertools import product

import cupy as xp
from cupy import cuda

cnt = 1000
xs = xp.random.rand(256, 256, 256)

for axis, order, transpose in product([0, -1], ['C', 'F'], [True, False]):
    arr = [x.copy() if order is 'C' else xp.asfortranarray(x.copy()) for x in xs]
    tup = [a.T if transpose else a for a in arr]
    stream = cuda.Stream.null
    start = stream.record()
    for _ in range(cnt):
        _ = xp.concatenate(tup, axis=axis)
    end = stream.record()
    end.synchronize()
    elapsed = xp.cuda.get_elapsed_time(start, end) / cnt
    print("axis: {}, order: {}, T: {}, elapsed: {}".format(axis, order, transpose, elapsed))
```

This pull request:
```
axis: 0, order: C, T: True, elapsed: 7.17641357421875
axis: 0, order: C, T: False, elapsed: 2.462125732421875
axis: 0, order: F, T: True, elapsed: 2.475766845703125
axis: 0, order: F, T: False, elapsed: 6.72791455078125
axis: -1, order: C, T: True, elapsed: 4.633283203125
axis: -1, order: C, T: False, elapsed: 6.23294873046875
axis: -1, order: F, T: True, elapsed: 6.19220849609375
axis: -1, order: F, T: False, elapsed: 4.65268212890625
```

master
```
axis: 0, order: C, T: True, elapsed: 7.17486572265625
axis: 0, order: C, T: False, elapsed: 6.489275390625
axis: 0, order: F, T: True, elapsed: 6.13665966796875
axis: 0, order: F, T: False, elapsed: 6.7003427734375
axis: -1, order: C, T: True, elapsed: 12.597591796875
axis: -1, order: C, T: False, elapsed: 6.2214814453125
axis: -1, order: F, T: True, elapsed: 6.1746484375
axis: -1, order: F, T: False, elapsed: 12.63175390625
```

### CODE REVIEW

**Comment by okuta** [comment]
How about concatenating many array case?
Please check this PR chainer/chainer#2251.

**Comment by uchida** [comment]
Thank you for your comment.
 
As you mentioned, performance on large number of small arrays are slow in this implementation.
 
With some measurement, I confirmed cupy_copy with skip are faster than `cupy_concatenate` in the following cases:
 
1. average array size (`arr.size * arr.itemsize / len(arr)`) larger than ~500kB, It seems due to utilization on DtoD memcpy bandwidth
2. number of arrays (`len(arr)`), is less than ~100 and this seems independent to average array size. If number of arrays becomes larger, `cupy_concatenate` becomes faster than `len(arr)` times `cudaMemcpyAsync` API call overheads (several microseconds for single call)
 
I'll add the threshould above.

**Comment by okuta** [comment]
Thank you for your investigation. I wait your fixing,

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
I tried to test.
```python
from itertools import product

import chainer  # import for using memory pool
import cupy as xp
from cupy import cuda

cnt = 1000
xs = xp.random.rand(128, 128, 128)  # reduce array size

for axis, order, transpose in product([0, -1], ['C', 'F'], [True, False]):
    arr = [x.copy() if order is 'C' else xp.asfortranarray(x.copy()) for x in xs]
    tup = [a.T if transpose else a for a in arr]
    stream = cuda.Stream.null
    start = stream.record()
    for _ in range(cnt):
        _ = xp.concatenate(tup, axis=axis)
    end = stream.record()
    end.synchronize()
    elapsed = xp.cuda.get_elapsed_time(start, end) / cnt
    print("axis: {}, order: {}, T: {}, elapsed: {}".format(axis, order, transpose, elapsed))
```
I got following result.
before
```
axis: 0, order: C, T: True, elapsed: 0.795731994629
axis: 0, order: C, T: False, elapsed: 0.671243774414
axis: 0, order: F, T: True, elapsed: 0.673157775879
axis: 0, order: F, T: False, elapsed: 0.763187927246
axis: -1, order: C, T: True, elapsed: 1.03001135254
axis: -1, order: C, T: False, elapsed: 0.477306152344
axis: -1, order: F, T: True, elapsed: 0.476845672607
axis: -1, order: F, T: False, elapsed: 1.03566345215
```

after
```
axis: 0, order: C, T: True, elapsed: 0.778117431641
axis: 0, order: C, T: False, elapsed: 1.42882861328
axis: 0, order: F, T: True, elapsed: 1.52895715332
axis: 0, order: F, T: False, elapsed: 0.772997558594
axis: -1, order: C, T: True, elapsed: 2.57352539062
axis: -1, order: C, T: False, elapsed: 0.482660644531
axis: -1, order: F, T: True, elapsed: 0.482091644287
axis: -1, order: F, T: False, elapsed: 2.56440478516
```

I use GeForce GTX TITAN X(maxwell) and Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz .

Cloud you test one more?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!
Jenkins test is passed. I will try fine tuning later.

**Pull request merged**
