### PR TITLE
Implemented gradient function

### PR DESCRIPTION
**Pull request by TudorAndrei**
I have encountered some issues with the .ndim, when using it from the numpy lib. And cupy does not have .ndim. Looking forward to constructive feedback.

This pr should fix the #1270  issue

### CODE REVIEW

**Comment by asi1024** [comment]
Thank you for the PR! How about using `ElementwiseKernel` for the performance?

**Comment by leofang** [comment]
Note that `cupy.ndim` is being added in #3060.

**Comment by TudorAndrei** [comment]
@asi1024 I will work implementing the ElementwiseKernel,

in the meantime i have an issue with
`$ test ! -s check_autopep8

The command "test ! -s check_autopep8" exited with 1.`

How should I go about fixing this, both flake8 and autopep8 have been used on my code

**Comment by asi1024** [comment]
@TudorAndrei Any updates?

**Comment by TudorAndrei** [comment]
I haven't been able to work on it. I will resume shortly.

**Comment by asi1024** [comment]
Closing the PR as it has been WIP for a long time.
Please feel free to reopen if you want to continue.

**Comment by kunguz** [comment]
Any chance we can get gradient support to Cupy?

**Comment by asi1024** [comment]
The original issue: https://github.com/cupy/cupy/issues/1270

**Pull request closed without merging**
