### PR TITLE
Add sici and shichi to special for sine and cosine integrals

### PR DESCRIPTION
**Pull request by steppi**
This PR adds the functions `sici` and `shichi` to `cupyx.scipy.special` for evaluating *sine and cosine integrals* and *hyperbolic sine and cosine integrals* respectively. We added CUDA support for these functions to SciPy in https://github.com/scipy/scipy/pull/21210. 

Notice that  `cupy/_core/include/cupy/special` has been renamed to `cupy/_core/include/cupy/xsf`. We've made this change internally in SciPy too https://github.com/scipy/scipy/pull/21297, and are preparing to split this out into a separate library which SciPy and CuPy can both include as a submodule. I've updated the headers to the latest ones that are being used in SciPy.

### CODE REVIEW

**Comment by asi1024** [comment]
@steppi Thank you for your pull request submission! Could you please inform us about your schedule for the release of the header library submodule?

**Comment by steppi** [comment]
@asi1024, I've added macros for some `__host__ __device__` annotations which were missing. This should take care of the test failures. I'd like to see a first xsf release by late October, and am hoping to start the process soon.

**Comment by asi1024** [comment]
The static-checks failure seems unrelated to this PR.

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
@steppi LGTM! Thanks!

**Comment by steppi** [comment]
@asi1024, I've created an RFC here, https://github.com/scipy/xsf/issues/1, about the plan to create the header library submodule for special functions, if you're interested.

**Pull request merged**
