### PR TITLE
Fix imag for 0-size array

### LINKED ISSUE #2885: Complex imag causes error for 0-size array
`ndarray.imag` causes `AssertionError` if the array is 0-sized.

Version: current master (2aec8a78761cdcc88541bf1f5e40e17840d3eb84)
### Code:
```py
>>> import cupy
>>> a = cupy.zeros((0,), dtype='complex64')
>>> a.imag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1095, in cupy.core.core.ndarray.imag.__get__
    return _math._ndarray_imag_getter(self)
  File "cupy/core/_routines_math.pyx", line 52, in cupy.core._routines_math._ndarray_imag_getter
    memptr=self.data + self.dtype.itemsize // 2,
  File "cupy/cuda/memory.pyx", line 320, in cupy.cuda.memory.MemoryPointer.__add__
    assert self.ptr != 0 or offset == 0
AssertionError
>
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes #2885

### CODE REVIEW

**Comment by niboshi** [comment]
If #2870 is merged earlier, its TODO can be addressed.

**Comment by niboshi** [comment]
>If #2870 is merged earlier, its TODO can be addressed.

Done. PTAL

**Comment by niboshi** [comment]
Your intention is to make the resulting array alway a view of the original array, right?
Fixed as you suggestion, thanks!

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
