### PR TITLE
Fix errors on 0-sized inputs

### LINKED ISSUE #1455: `cumsum` and `cumprod` along 0-length axis
```
>>> cupy.cumprod(cupy.ones((0, 3)))
array([], dtype=float64)
>>> cupy.cumprod(cupy.ones((0, 3)), axis=1)
array([], shape=(0, 3), dtype=float64)
>>> cupy.cumprod(cupy.ones((0, 3)), axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/math/sumprod.py", line 190, in cumprod
    return _cum_core(a, axis, dtype, out, _cumprod_kern, _cumprod_batch_kern)
  File "/home/kataoka/cupy/cupy/math/sumprod.py", line 98, in _cum_core
    return _proc_as_batch(batch_kern, out, axis=axis)
  File "/home/kataoka/cupy/cupy/math/sumprod.py", line 66, in _proc_as_batch
    r = t.reshape(x.shape[axis], -1)
  File "cupy/core/core.pyx", line 523, in cupy.core.core.ndarray.reshape
  File "cupy/core/core.pyx", line 496, in cupy.core.core.ndarray._reshape
  File "cupy/core/internal.pyx", line 139, in cupy.core.internal.infer_unknown_dimension
ZeroDivisionError: integer division or modulo by zero
```

### LINKED ISSUE #1458: `cupy.split` sometimes fails with a 0-sized input array
```
>>> cupy.split(cupy.ones((3, 0)), [1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/manipulation/split.py", line 78, in split
    return array_split(ary, indices_or_sections, axis)
  File "/home/kataoka/cupy/cupy/manipulation/split.py", line 16, in array_split
    return core.array_split(ary, indices_or_sections, axis)
  File "cupy/core/core.pyx", line 2338, in cupy.core.core.array_split
    v.data = ary.data + prev * stride
  File "cupy/cuda/memory.pyx", line 243, in cupy.cuda.memory.MemoryPointer.__add__
    assert self.ptr > 0 or offset == 0
AssertionError
```

### PR DESCRIPTION
**Pull request by toslunar**
This PR make the following functions support 0-sized input arrays.
- `cupy.cumsum`, `cupy.cumprod` (fix #1455)
- `cupy.split`, `cupy.array_split` (fix #1458)

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
Test result.
```
=================================== FAILURES ===================================
____________________ TestSplit.test_array_split_empty_array ____________________
cupy/testing/helper.py:120: in test_func
    self.assertEqual(cupy_result.shape, numpy_result.shape)
E   AssertionError: Tuples differ: (5, 0) != (0,)
E   
E   First differing element 0:
E   5
E   0
E   
E   First tuple contains 1 additional elements.
E   First extra element 1:
E   0
E   
E   - (5, 0)
E   + (0,)
```

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
