### PR TITLE
Support all advanced indexing

### PR DESCRIPTION
**Pull request by toslunar**
In `__getitem__`, `__setitem__`, and scatter ops, allow mask index to be combined with other masks or arrays.

### CODE REVIEW

**Comment by toslunar** [comment]
Shape of masks should be checked.  For example, `cupy.arange(12).reshape(3, 4)[[1, 0], [True, True]]` should raise `IndexError`.
```
>>> numpy.arange(12).reshape(3, 4)[[1, 0], [True, True]]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 2
```

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Updated the branch because it seems CI config has been updated.

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
