### PR TITLE
Update install.py for downloading and installing libcusparselt 0.6.1

### PR DESCRIPTION
**Pull request by gdaisukesuzuki**
Regarding issue #6757, I tried editing install.py to make it compatible with cusparselt. At this point, it is only grammatically correct, and I haven't tested it on all patterns, so I leave it up to you to decide whether to merge it or not.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks @gdaisukesuzuki! CuPy is moving to use PyPI-hosted wheels instead of installing shared libraries on our own (#8013, #6999). As for cuSPARSELt, it looks like only a stub package ( https://pypi.org/project/nvidia-cusparselt-cu12) is available. @leofang, are there any plans to have cuSPARSELt wheels on PyPI?

**Comment by leofang** [comment]
We can't upload it to PyPI yet because of the size limit (https://github.com/pypi/support/issues/3904). I can check with @ethanhs next week and see if we can use pypi.nvidia.com as a temporary solution. Will get back once we discuss.

**Comment by leofang** [comment]
Sorry for my late response. I did discuss with the cuSPARSELt team and they have reasons to not publish to pypi.nvidia.com. Fortunately this is moot now that the size-bump request was granted. @ethanhs told me he should be able to get the wheels pushed to PyPI in a few days. Will keep this thread updated.

**Comment by leofang** [comment]
Update: We've released cuSPARSELt v0.6.2 wheels on PyPI (https://pypi.org/project/nvidia-cusparselt-cu12/), would you be able to give it a try @gdaisukesuzuki?

**Comment by kmaehashi** [comment]
As discussed above, we are moving away from our own installer, so let me close this PR. I've made an issue to track the feature: #8604. Thanks again @gdaisukesuzuki for the contribution!

**Pull request closed without merging**
