### PR TITLE
Test FutureWarning

### PR DESCRIPTION
**Pull request by toslunar**
chainer/chainer#5949

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Requires #4245.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
There's a failing test. `cupyx.scipy.sparse.linalg.gmres` calls `numpy.linalg.lstsq` without `rcond`.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Pull request merged**
