### PR TITLE
Change check condition of `accept_error`

### PR DESCRIPTION
**Pull request by asi1024**
Another solution for #2377.
Related to #2376, #2379.

Currently, `accept_error` requires the type of `cupy_error` to be a sub-type that of `numpy_error`. This behavior is inconvenient for us when the target NumPy's function raises an error of NumPy's private exception class.
This PR relaxes this check condition of `accept_error`.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
@toslunar PTAL.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
