### PR TITLE
[backport] Fix `put` when using scalars

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3328

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Sorry, can you fix the travis error? 
```
./tests/cupy_tests/indexing_tests/test_insert.py:91:17: F821 undefined name 'cupy'
./tests/cupy_tests/indexing_tests/test_insert.py:100:17: F821 undefined name 'cupy'
```

**Comment by takagi** [comment]
Yes, I've fixed it!

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Error is in docs

```
****************************************************************
13:24:23 File "../../cupy/padding/pad.py", line ?, in default
13:24:23 Failed example:
13:24:23     cupy.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4))
13:24:23 Exception raised:
13:24:23     Traceback (most recent call last):
13:24:23       File "/usr/lib/python3.5/doctest.py", line 1321, in __run
13:24:23         compileflags, 1), test.globs)
13:24:23       File "<doctest default[0]>", line 1, in <module>
13:24:23         cupy.pad(a, (2, 3), 'linear_ramp', end_values=(5, -4))
13:24:23       File "/work/cupy/cupy/padding/pad.py", line 698, in pad
13:24:23         ramp_pair = _get_linear_ramps(roi, axis, width_pair, value_pair)
13:24:23       File "/work/cupy/cupy/padding/pad.py", line 134, in _get_linear_ramps
13:24:23         "padding with 'linear_ramp' currently requires numpy >= 1.16")
13:24:23     NotImplementedError: padding with 'linear_ramp' currently requires numpy >= 1.16
```

**Comment by grlee77** [comment]
```
13:24:23     NotImplementedError: padding with 'linear_ramp' currently requires numpy >= 1.16
```

Not sure why that error is just now showing up in this unrelated PR. 

In master, numpy is no longer needed for the `linear_ramp` mode. To make this also true for 7.x would require backporting #2461 and #3101.

**Comment by emcastillo** [comment]
We fixed the requirements to install new numyp versions for doc generation 😂

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
