### PR TITLE
Add remaining greyscale morphology operations to `cupyx.scipy.ndimage`

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds the four remaining greyscale morphology functions: `morphological_gradient`, `morphological_laplace`, `white_tophat`, `black_tophat`. In combination with gh-3907, this completes CuPy's coverage of `scipy.ndimage.morphology` module with the exception of `distance_transform_*`.

The implementations here are simple as they just rely on the existing `grey_erosion` and `grey_dilation` functions.

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Check Jenkins error please 😇

**Comment by grlee77** [comment]
> Check Jenkins error please innocent

There is a single parameterized case failing for a binary erosion/dilation test case unrelated to this PR. Oddly enough, we did see one failure case ([although a different one](https://jenkins.preferred.jp/job/chainer/job/cupy_pr/2096/)) there was well when @jakirkham first ran the tests in #3907, but it was not reproducible and went away when the CI was re-run.

**Comment by jakirkham** [comment]
Sure let's try again. Though the fact that there is reoccurring sporadic test failure is a bit worrying.

Jenkins, test this please.

**Comment by grlee77** [comment]
> Sure let's try again. Though the fact that there is a reoccurring sporadic test failure is a bit worrying.

Agreed, but it is going to be hard to be difficult to diagnose if we can't reproduce it! (I have never seen it occur locally)

**Comment by jakirkham** [comment]
Should we file an issue to track it?

**Pull request merged**
