### PR TITLE
JIT: Avoid calling default constructor if possible

### PR DESCRIPTION
**Pull request by asi1024**
Rel https://github.com/cupy/cupy/issues/5280#issuecomment-1087142600.

Combines variable declaration and initialization if the variable is first used at the top level.

cc: @leofang

### CODE REVIEW

**Comment by leofang** [comment]
Thanks for coming up the solution in such a short period @asi1024! I am sure this nice improvement would also help when we support Python classes 🙂 Will help review later tonight.

**Review by leofang — APPROVED** [review]
LGTM! I guess we don't need tests as #6620 would not work without this PR, but if there is a way to test this it'd be nice to have.

**Comment by emcastillo** [comment]
Right now, I think we don't have constructors in the JIT that would use a default constructor, so the only thing I can think of for testing this is to parse the generated cuda code. Once #6620 is in, we will have the testing for free so I wouldn't care too much.

**Comment by asi1024** [comment]
@emcastillo All tests have passed!

**Review by emcastillo — APPROVED** [review]
LGTM!

**Pull request merged**
