### PR TITLE
`scipy.special.{btdtr,btdtri}` are deprecated since SciPy 1.12

### PR DESCRIPTION
**Pull request by asi1024**
Part of https://github.com/cupy/cupy/issues/8046.
https://scipy.github.io/devdocs/reference/generated/scipy.special.btdtr.html

### CODE REVIEW

**Comment by kmaehashi** [comment]
Let's use `/test mini,head` to ensure the CI pass in main branch as well!

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
This needs manual backport.

**Pull request merged**
