### PR TITLE
Add decorator to parameterize xp

### PR DESCRIPTION
**Pull request by toslunar**
From the discussion in #2871.

### CODE REVIEW

**Comment by niboshi** [comment]
How about `for_numpy_cupy`? I think "run" is not suitable for a test.

**Comment by toslunar** [comment]
I agree that `run` does not suit here.  Thanks.

**Comment by toslunar** [comment]
This PR is blocking #2982.  I made the decorator private in order to discuss its name later.

**Comment by niboshi** [comment]
@toslunar #2982 could proceed without depending on this PR.

**Comment by niboshi** [comment]
For now, we decided to use `for` loop for this parameterization. #3099

**Pull request closed without merging**
