### PR TITLE
Use https in supported websites

### PR DESCRIPTION
**Pull request by vilyaair**
Some websites now support https, and hence use it.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thank you!
Refs #4315

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
@vilyaair  Could you please revert the modifications under `cupy/core/include/cupy/complex` directory, because they came from [thrust](https://github.com/thrust/thrust/tree/master/thrust/detail/complex)?

**Comment by vilyaair** [comment]
Certainly, I have reverted.

**Comment by kmaehashi** [comment]
Thank you!
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
