### PR TITLE
Add NCCL to library installer

### PR DESCRIPTION
**Pull request by kmaehashi**
Depends on ~https://github.com/cupy/cupy/pull/4912~ (merged) and #4852

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
#4912 merged, ready for review.
/test

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Rebased!

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Windows test passed, Jenkins failure is a known flaky one.

**Comment by asi1024** [comment]
LGTM!

**Review by asi1024 — APPROVED** [review]

**Pull request merged**
