### PR TITLE
Move to PyTest

### PR DESCRIPTION
**Pull request by niboshi**
This is CuPy's counterpart of https://github.com/chainer/chainer/pull/3324
Needs https://github.com/chainer/chainer-test/pull/338

### CODE REVIEW

**Comment by unnonouno** [comment]
Do we need to add dependency to pytest in setup.py?

**Comment by niboshi** [comment]
I removed reuirements of both nose (from `setup.py`) and pytest (from `testing` package).
See also: https://github.com/chainer/chainer/pull/3604

**Comment by niboshi** [comment]
I put no-compat because those users who are using `testing.attr` (and not having pytest in their environment) will start getting an error.

**Comment by kmaehashi** [comment]
LGTM!

**Comment by kmaehashi** [comment]
I'll port https://github.com/chainer/chainer/pull/3624 to cupy later.

**Comment by kmaehashi** [comment]
> I'll port chainer/chainer#3624 to cupy later.

https://github.com/cupy/cupy/pull/662

**Pull request merged**
