### PR TITLE
Refactor sparse indexing tests

### PR DESCRIPTION
**Pull request by asi1024**
Blocked by #3944.

### CODE REVIEW

**Comment by emcastillo** [comment]
seems we need to rebase :(

**Comment by asi1024** [comment]
Rebased.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
