### PR TITLE
[backport] ROCm: Fix `getDeviceProperties` for HIP

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #4108

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
` cupy_backends/cuda/api/runtime.pxd:417:9: Compile-time name 'use_hip' not defined`

**Comment by leofang** [comment]
> cupy_backends/cuda/api/runtime.pxd:417:9: Compile-time name 'use_hip' not defined

Ah, yes, `use_hip` was passed to Cython starting #3896, but it's not backported. I added a quick fix to your branch @emcastillo.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
