### PR TITLE
[backport] Use larger type to represent index range in `cupy.take`

### PR DESCRIPTION
**Pull request by emcastillo**
Backport of #3118

### CODE REVIEW

**Comment by emcastillo** [comment]
[automatic post] Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
