### PR TITLE
Deprecations for v9

### LINKED ISSUE #4300: [RFC] Deprecation Plans for v9
In CuPy v9, we are going to drop support for the following:

* Python 3.5
* NumPy 1.16
    * c.f. NEP29: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table
* SciPy 1.3
* CUDA 9.0
    * CUDA 9.1 is already dropped in v8, so v9 will only support CUDA 9.2+

As for cuDNN and NCCL, we will only support the latest versions depending on the CUDA version:

* cuDNN: v9 supports v7.6.5 (for CUDA 9.2/10.x) & v8+ (for CUDA 10.1+)
* NCCL: v9 supports: v2.4.8 (CUDA 9.2 only), v2.6.4 (CUDA 10.0 only), v2.7.8+ (CUDA 10.1+)

See the following docs for the versions currently supported in v8 branch:
https://docs.cupy.dev/en/stable/install.html

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #4300.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by toslunar — COMMENTED** [review]
- The changes LGTM.  I've not yet checked the completeness.
- cuDNN version: Fix the CI configuration, first.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by toslunar — APPROVED** [review]

**Pull request merged**
