### PR TITLE
Remove experimental warning of `cupy.fuse`

### PR DESCRIPTION
**Pull request by asi1024**
~Merge #1789 first.~

### CODE REVIEW

**Comment by kmaehashi** [comment]
Do you mean `cupy.fuse` has stable interface now?

**Comment by niboshi** [comment]
We have agreed on removing the experimental warning.

**Comment by kmaehashi** [comment]
I discussed with @asi1024.  He is planning a big change, so let's wait until that change is introduced.

**Comment by okuta** [comment]
@asi1024 Can I merge this PR?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
