### PR TITLE
Fix FFT tests for NumPy 2.0

### PR DESCRIPTION
**Pull request by asi1024**
Fix tests for NumPy 2.0 API changes:

- Fix tests for fp32 inputs
- Deprecations for n-D transforms with None values in arguments

https://numpy.org/devdocs/release/2.0.0-notes.html

### CODE REVIEW

**Comment by asi1024** [comment]
https://ci.preferred.jp/cupy.linux.cuda-head/171940/

**Comment by asi1024** [comment]
note: The CI matrix in https://github.com/cupy/cupy/pull/8565 needs to be redesigned to enable testing for FFTs with various CUDA versions.

**Comment by asi1024** [comment]
https://ci.preferred.jp/cupy.linux.cuda-head/171941/

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
