### PR TITLE
Improved pow test

### PR DESCRIPTION
**Pull request by unnonouno**
I improved unit test for `__pow__` to cover all error cases, and found a bug.

### CODE REVIEW

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by takagi** [comment]
jenkins test this please

**Comment by takagi** [comment]
jenkins test this please

**Comment by takagi** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by takagi** [comment]
LGTM! CI failed but it's not due to this PR (because of an unstable test for a Chainer function).

**Pull request merged**
