### PR TITLE
Remove unnecessary imports in `cupy._sorting`

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR removes unnecessary imports from `cupy._sorting` submodule.

### CODE REVIEW

**Comment by kmaehashi** [comment]
These must be fixed?

```
_misc/memory_ranges.py:from cupy._sorting import search
manipulation/basic.py:from cupy._sorting import search
```

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
I suppose we should leave the lines as they are, but you mean?

**Comment by kmaehashi** [comment]
Ah, ok I misunderstood that `from cupy._sorting import search` won't work after this fix. Locally confirmed it's still working. LGTM!

**Pull request merged**
