### PR TITLE
Add `cupy.shares_memory`

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by asi1024** [comment]
Maybe we can use `searchsorted` for the performance.

**Comment by takagi** [comment]
Would you add it to the reference `misc.rst`?

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
Interesting solution, LGTM!

**Comment by leofang** [comment]
> Interesting solution

This is a very interesting approach indeed. Out of curiosity I dug into NumPy's implementation, and found it is a non-trivial problem: https://github.com/numpy/numpy/blob/master/numpy/core/src/common/mem_overlap.c

**Comment by asi1024** [comment]
My solution is simpler, but NumPy's solution seems to work with better memory/time complexity.

**Pull request merged**
