### PR TITLE
Avoid using _ufunc_wrapper and _reduction_wrapper

### PR DESCRIPTION
**Pull request by asi1024**
`_ufunc_wrapper` and `_reduction_wrapper` cause some problems (e.g. generate bad hyperlinks in documents), so made not allowed to use them.

### CODE REVIEW

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
