### PR TITLE
Update spec of `linspace` to NumPy 1.20

### PR DESCRIPTION
**Pull request by toslunar**
Follow numpy/numpy#16841.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
This PR was backported manually. https://github.com/cupy/cupy/pull/4625

**Pull request merged**
