### PR TITLE
Fix/skip some tests for HIP

### PR DESCRIPTION
**Pull request by leofang**
Among other minor changes, all sparse matrix tests (found via `find ./tests/ -name '*sparse*'`) are dibbled for HIP.

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
#4598 is in, retry...

Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@emcastillo This is ready.

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Test failure is weird...
```
tests.cupy_tests.manipulation_tests.test_basic.TestBasic.test_copyto_multigpu
```
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/3005/TEST=cupy-py3-cub,label=mn1-p100/testReport/junit/tests.cupy_tests.manipulation_tests.test_basic/TestBasic/test_copyto_multigpu/

Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please.

The test is flaky

**Pull request merged**
