### PR TITLE
Fix array() for readability

### PR DESCRIPTION
**Pull request by niboshi**
Reduces unnecessary indentation by early returns.

### CODE REVIEW

**Comment by niboshi** [comment]
This PR is blocking #2956.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
Would you rebase this on the current master as we need #3469 to pass CI to follow the latest SciPy release?

**Comment by kmaehashi** [comment]
pfnCI, test this please.
(no rebase necessary, tests runs against merged codebase (master + PR branch head) automatically)

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
