### PR TITLE
Add `cupy.interp`

### PR DESCRIPTION
**Pull request by leofang**
This PR implements `cupy.interp`. It uses `cupy.searchsorted` to determine the nearest interpolation point, and invokes an `ElementwiseKernel` to do the actual hard work. For compatibility the `ElementwiseKernel` loosely follows [NumPy's C implementation](https://github.com/numpy/numpy/blob/92bf2f6d81252f97a7acc69fcc016636b29d1277/numpy/core/src/multiarray/compiled_base.c#L592-L628), which may not be optimal because
- we need an extra conditional branch to determine whether we're sitting on the rightmost boundary, which in the worst case might cause read congestion (all threads reading the same value)
- we need a bunch of `isnan` checks, which can be annoying

Also, note that for mismatched (but legal) input dtypes, to save memory and avoid launching the type conversion kernel the dtypes are normalized on the fly.

Any comments or suggestions are welcome! Though for moderate array sizes the speed up is already quite good, see below:

<details><summary>Benchmark (click)</summary>
<p>

Done on GTX 2080 Ti + CUDA 10.2:
size | x dtype | y dtype | NumPy | CuPy (this PR) | speedup
-----|---------|---------|-------|----------------|--------
(10, 100) | float32 | float32 | 0.0057 ms | 0.0371 ms | 0.2x
(10, 100) | float32 | float64 | 0.0054 ms | 0.0366 ms | 0.1x
(10, 100) | float32 | complex64 | 0.0056 ms | 0.0372 ms | 0.2x
(10, 100) | float32 | complex128 | 0.0053 ms | 0.0369 ms | 0.1x
(10, 100) | float64 | float32 | 0.0051 ms | 0.0371 ms | 0.1x
(10, 100) | float64 | float64 | 0.0044 ms | 0.0367 ms | 0.1x
(10, 100) | float64 | complex64 | 0.0053 ms | 0.0373 ms | 0.1x
(10, 100) | float64 | complex128 | 0.0044 ms | 0.0365 ms | 0.1x
(100, 10) | float32 | float32 | 0.0060 ms | 0.0374 ms | 0.2x
(100, 10) | float32 | float64 | 0.0057 ms | 0.0375 ms | 0.2x
(100, 10) | float32 | complex64 | 0.0062 ms | 0.0369 ms | 0.2x
(100, 10) | float32 | complex128 | 0.0060 ms | 0.0371 ms | 0.2x
(100, 10) | float64 | float32 | 0.0054 ms | 0.0372 ms | 0.1x
(100, 10) | float64 | float64 | 0.0050 ms | 0.0375 ms | 0.1x
(100, 10) | float64 | complex64 | 0.0056 ms | 0.0369 ms | 0.2x
(100, 10) | float64 | complex128 | 0.0053 ms | 0.0370 ms | 0.1x
(100, 1000) | float32 | float32 | 0.0071 ms | 0.0380 ms | 0.2x
(100, 1000) | float32 | float64 | 0.0065 ms | 0.0368 ms | 0.2x
(100, 1000) | float32 | complex64 | 0.0074 ms | 0.0370 ms | 0.2x
(100, 1000) | float32 | complex128 | 0.0066 ms | 0.0370 ms | 0.2x
(100, 1000) | float64 | float32 | 0.0062 ms | 0.0381 ms | 0.2x
(100, 1000) | float64 | float64 | 0.0055 ms | 0.0375 ms | 0.1x
(100, 1000) | float64 | complex64 | 0.0067 ms | 0.0371 ms | 0.2x
(100, 1000) | float64 | complex128 | 0.0057 ms | 0.0372 ms | 0.2x
(1000, 100) | float32 | float32 | 0.0120 ms | 0.0386 ms | 0.3x
(1000, 100) | float32 | float64 | 0.0117 ms | 0.0387 ms | 0.3x
(1000, 100) | float32 | complex64 | 0.0135 ms | 0.0388 ms | 0.3x
(1000, 100) | float32 | complex128 | 0.0127 ms | 0.0380 ms | 0.3x
(1000, 100) | float64 | float32 | 0.0111 ms | 0.0383 ms | 0.3x
(1000, 100) | float64 | float64 | 0.0108 ms | 0.0383 ms | 0.3x
(1000, 100) | float64 | complex64 | 0.0123 ms | 0.0377 ms | 0.3x
(1000, 100) | float64 | complex128 | 0.0119 ms | 0.0379 ms | 0.3x
(1000, 10000) | float32 | float32 | 0.0319 ms | 0.0381 ms | 0.8x
(1000, 10000) | float32 | float64 | 0.0303 ms | 0.0383 ms | 0.8x
(1000, 10000) | float32 | complex64 | 0.0356 ms | 0.0380 ms | 0.9x
(1000, 10000) | float32 | complex128 | 0.0303 ms | 0.0381 ms | 0.8x
(1000, 10000) | float64 | float32 | 0.0294 ms | 0.0384 ms | 0.8x
(1000, 10000) | float64 | float64 | 0.0263 ms | 0.0386 ms | 0.7x
(1000, 10000) | float64 | complex64 | 0.0325 ms | 0.0380 ms | 0.9x
(1000, 10000) | float64 | complex128 | 0.0277 ms | 0.0386 ms | 0.7x
(10000, 1000) | float32 | float32 | 0.0697 ms | 0.0386 ms | 1.8x
(10000, 1000) | float32 | float64 | 0.0690 ms | 0.0387 ms | 1.8x
(10000, 1000) | float32 | complex64 | 0.0785 ms | 0.0394 ms | 2.0x
(10000, 1000) | float32 | complex128 | 0.0779 ms | 0.0394 ms | 2.0x
(10000, 1000) | float64 | float32 | 0.0666 ms | 0.0391 ms | 1.7x
(10000, 1000) | float64 | float64 | 0.0657 ms | 0.0383 ms | 1.7x
(10000, 1000) | float64 | complex64 | 0.0756 ms | 0.0393 ms | 1.9x
(10000, 1000) | float64 | complex128 | 0.0770 ms | 0.0390 ms | 2.0x
(10000, 100000) | float32 | float32 | 0.3989 ms | 0.0390 ms | 10.2x
(10000, 100000) | float32 | float64 | 0.3514 ms | 0.0384 ms | 9.1x
(10000, 100000) | float32 | complex64 | 0.4665 ms | 0.0396 ms | 11.8x
(10000, 100000) | float32 | complex128 | 0.3754 ms | 0.0395 ms | 9.5x
(10000, 100000) | float64 | float32 | 0.3474 ms | 0.0385 ms | 9.0x
(10000, 100000) | float64 | float64 | 0.3053 ms | 0.0382 ms | 8.0x
(10000, 100000) | float64 | complex64 | 0.4157 ms | 0.0395 ms | 10.5x
(10000, 100000) | float64 | complex128 | 0.3275 ms | 0.0392 ms | 8.3x
(100000, 10000) | float32 | float32 | 0.6795 ms | 0.0458 ms | 14.8x
(100000, 10000) | float32 | float64 | 0.6764 ms | 0.0451 ms | 15.0x
(100000, 10000) | float32 | complex64 | 0.7755 ms | 0.0591 ms | 13.1x
(100000, 10000) | float32 | complex128 | 0.7779 ms | 0.0583 ms | 13.3x
(100000, 10000) | float64 | float32 | 0.6289 ms | 0.0494 ms | 12.7x
(100000, 10000) | float64 | float64 | 0.6257 ms | 0.0486 ms | 12.9x
(100000, 10000) | float64 | complex64 | 0.7231 ms | 0.0627 ms | 11.5x
(100000, 10000) | float64 | complex128 | 0.7185 ms | 0.0614 ms | 11.7x
(100000, 1000000) | float32 | float32 | 4.5879 ms | 0.0622 ms | 73.8x
(100000, 1000000) | float32 | float64 | 3.8118 ms | 0.0650 ms | 58.7x
(100000, 1000000) | float32 | complex64 | 6.3037 ms | 0.0739 ms | 85.3x
(100000, 1000000) | float32 | complex128 | 4.7555 ms | 0.0748 ms | 63.6x
(100000, 1000000) | float64 | float32 | 3.9323 ms | 0.0799 ms | 49.2x
(100000, 1000000) | float64 | float64 | 3.2287 ms | 0.0820 ms | 39.4x
(100000, 1000000) | float64 | complex64 | 5.5096 ms | 0.0881 ms | 62.6x
(100000, 1000000) | float64 | complex128 | 3.9876 ms | 0.0903 ms | 44.2x
(1000000, 100000) | float32 | float32 | 6.8527 ms | 0.2047 ms | 33.5x
(1000000, 100000) | float32 | float64 | 6.8052 ms | 0.1993 ms | 34.1x
(1000000, 100000) | float32 | complex64 | 7.9367 ms | 0.3360 ms | 23.6x
(1000000, 100000) | float32 | complex128 | 7.8251 ms | 0.3222 ms | 24.3x
(1000000, 100000) | float64 | float32 | 6.2335 ms | 0.2507 ms | 24.9x
(1000000, 100000) | float64 | float64 | 6.1803 ms | 0.2437 ms | 25.4x
(1000000, 100000) | float64 | complex64 | 7.2581 ms | 0.3809 ms | 19.1x
(1000000, 100000) | float64 | complex128 | 7.1415 ms | 0.3663 ms | 19.5x
(1000000, 10000000) | float32 | float32 | 81.5438 ms | 0.3426 ms | 238.0x
(1000000, 10000000) | float32 | float64 | 66.8403 ms | 0.3695 ms | 180.9x
(1000000, 10000000) | float32 | complex64 | 103.9323 ms | 0.4119 ms | 252.3x
(1000000, 10000000) | float32 | complex128 | 74.6144 ms | 0.4170 ms | 178.9x
(1000000, 10000000) | float64 | float32 | 64.3082 ms | 0.4704 ms | 136.7x
(1000000, 10000000) | float64 | float64 | 50.2305 ms | 0.4957 ms | 101.3x
(1000000, 10000000) | float64 | complex64 | 86.8917 ms | 0.5145 ms | 168.9x
(1000000, 10000000) | float64 | complex128 | 58.3287 ms | 0.5446 ms | 107.1x
(10000000, 1000000) | float32 | float32 | 88.8248 ms | 1.8745 ms | 47.4x
(10000000, 1000000) | float32 | float64 | 88.0177 ms | 1.7210 ms | 51.1x
(10000000, 1000000) | float32 | complex64 | 108.2574 ms | 2.8832 ms | 37.5x
(10000000, 1000000) | float32 | complex128 | 106.5075 ms | 2.7291 ms | 39.0x
(10000000, 1000000) | float64 | float32 | 71.9153 ms | 2.2539 ms | 31.9x
(10000000, 1000000) | float64 | float64 | 71.0611 ms | 2.2748 ms | 31.2x
(10000000, 1000000) | float64 | complex64 | 90.6869 ms | 3.0176 ms | 30.1x
(10000000, 1000000) | float64 | complex128 | 88.9123 ms | 3.1559 ms | 28.2x

</p>
</details>

<details><summary>Script (click)</summary>
<p>

```python
import numpy as np
import cupy as cp
from cupyx.time import repeat


# (x.size, fx.size)
sizes = ((10, 100),           (100, 10),
         (100, 1000),         (1000, 100),
         (1000, 10000),       (10000, 1000),
         (10000, 100000),     (100000, 10000),
         (100000, 1000000),   (1000000, 100000),
         (1000000, 10000000), (10000000, 1000000),)

dtypes = 'fdFD'

print(f"size | x dtype | y dtype | NumPy | CuPy (this PR) | speedup")
print(f"-----|---------|---------|-------|----------------|--------")
for s in sizes:
    for x_t in dtypes:
        if x_t in 'FD':
            continue
        for y_t in dtypes:
            x = cp.random.random(s[0]).astype(x_t)
            x.sort()
            fx = cp.random.random(s[1]).astype(x_t)
            fx.sort()
            fy = cp.random.random(fx.size).astype(y_t)
            result = repeat(cp.interp, (x, fx, fy), n_repeat=100, name='interp (GPU)')
            gpu_avg_time = result.gpu_times.mean() * 1E+3  # ms

            x = cp.asnumpy(x)
            fx = cp.asnumpy(fx)
            fy = cp.asnumpy(fy)
            result = repeat(np.interp, (x, fx, fy), n_repeat=100, name='interp (CPU)')
            cpu_avg_time = result.gpu_times.mean() * 1E+3  # ms

            speedup = cpu_avg_time / gpu_avg_time
            print(f"{s} | {np.dtype(x_t)} | {np.dtype(y_t)} | {cpu_avg_time:.4f} ms | {gpu_avg_time:.4f} ms | {speedup:0.1f}x")
```

</p>
</details>

### CODE REVIEW

**Comment by leofang** [comment]
@takagi I updated the PR description, PTAL.

cc: @oshaughn (I've hopefully taken care of all corner cases since our last email exchange)

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
The test failure seems to be due to the behavior of the older NumPy (1.16) being buggy, see numpy/numpy#12989. I'll add a `test_require` to ensure `numpy>=1.17` is used.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
LGTM!

**Comment by leofang** [comment]
Thanks @takagi!

**Pull request merged**
