### PR TITLE
Drop support for CUDA 10.1 or earlier

### LINKED ISSUE #5717: [RFC] Drop CUDA 10.0/10.1 support in v10
We are currently thinking of dropping support for CUDA 10.0 / 10.1 in CuPy v10, which is planned to be released in November. Feel free to leave a comment if you have any concerns or feedback.

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #5717.

Blocked by https://github.com/chainer/chainer-test/pull/687 (merged)

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Added CUDA 10.2 variant: https://ci.preferred.jp/cupy.win.cuda102/79404/
Please ignore `pfn-public-ci/cupy.experimental.win.cuda100` test failure.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
CUDA 10.2 for Windows test: https://ci.preferred.jp/cupy.win.cuda102/79678/

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
ah, automerge wont work lol

**Comment by emcastillo** [comment]
Blocked by #5801 ?

**Comment by kmaehashi** [comment]
I think it's ok to proceed to merge, I'll rerun failing test after all PRs are merged.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
