### PR TITLE
add `cupy.random.negative_binomial`

### PR DESCRIPTION
**Pull request by YoshikawaMasashi**
Jenkins, test this please.

### CODE REVIEW

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
#1418 is merged.

**Comment by YoshikawaMasashi** [comment]
I mistaked...

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by YoshikawaMasashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure (`tests.chainer_tests.functions_tests.math_tests.test_batch_l2_norm_squared.TestBatchL2NormSquared_param_0.test_forward_gpu`) is irrelevant to the PR.

**Pull request merged**
