### PR TITLE
[backport] Test cuTENSOR v1.0.0

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #2727

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
