### PR TITLE
ENH: cupyx/interpolate: port interp1d from scipy

### PR DESCRIPTION
**Pull request by ev-br**
Port `interp1d` routine from `scipy.interpolate`.
The routine itself is not very interesting: for `nearest`-like modes it delegates to `cupy.searchsorted`; for `cubic`-like modes it delegates to `make_interp_spline`. And it adds heaps and heaps of overhead on top.
It's public in SciPy though, and is used under the hood by `griddata`. So it's easier to port it and be done with it.

cross-ref https://github.com/cupy/cupy/issues/7186

### CODE REVIEW

**Comment by ev-br** [comment]
CI failures were due to `RUN pip install -U 'numpy==1.22.*' 'scipy==1.7.*'` and the failing test was new in SciPy 1.10. The last commit adds an appropriate `@with_requires` skip.

**Comment by ev-br** [comment]
Grrrr. More test failures on scipy < 1.10, skipped in the last commit. Sorry for the back-and-forth.

**Review by takagi — APPROVED** [review]
LGTM! Waiting CI finishes.

**Comment by takagi** [comment]
Thanks, @ev-br!

**Comment by ev-br** [comment]
Thank you for the review @takagi !

**Pull request merged**
