### PR TITLE
Fix CUDA 7.5 nvcc compilation error in string.h

### PR DESCRIPTION
**Pull request by gwtnb**
https://github.com/BVLC/caffe/issues/4046

### CODE REVIEW

**Comment by beam2d** [comment]
Could you write down into the script briefly the reason why this line is needed?

**Comment by mitmul** [comment]
How about adding this comment right above the inserted line?

```
# When the gcc version is new, memcpy cannot be found in string.h
# This is a workaround for Ubuntu 16.04 environment with CUDA 7.5
```

**Comment by beam2d** [comment]
Then why does the issue resolved by adding `_FORCE_INLINES` macro?

**Comment by mitmul** [comment]
> A known problem with cuda 7.5 on Ubuntu 16.4 is that gcc5.3 does not automatically deal with memcpy as it did in the past. Some people pointed out that the string.h header files are different, that is no longer true. The string.h file is correct _if_ -D_FORCE_INLINES is passed to nvcc.
https://groups.google.com/forum/#!topic/theano-users/3ihQYiTRG4E

> Work around a glibc bug
http://www.deeplearning.net/software/theano/install_ubuntu.html

**Comment by beam2d** [comment]
It looks better to add a link to that discussion.

**Comment by mitmul** [comment]
Fixed the comment to make it more detailed and added links to some discussions.

**Comment by beam2d** [comment]
Thank you!

**Pull request merged**
