### PR TITLE
[backport] Add different dtype input test in histogram

### PR DESCRIPTION
**Pull request by takagi**
Backport of #3618

### CODE REVIEW

**Comment by takagi** [comment]
[automatic post] Jenkins, test this please.

**Comment by asi1024** [comment]
@takagi Why is this PR labeled "bug"? This PR looks to fix a test code.

**Comment by takagi** [comment]
"bug" label was initially put by @kmaehashi and I overlooked to update it properly. Yes, you make sense. Maybe the bug fix part was separated into another PR from #3618.

**Comment by takagi** [comment]
We may close this backport?

**Comment by asi1024** [comment]
OK. Let's close this PR.

**Pull request closed without merging**
