### PR TITLE
Remove LLVM_PATH note on document

### PR DESCRIPTION
**Pull request by takagi**
Follows up #5933.

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]
LGTM!

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
pfnCI, run Jenkins please.

**Comment by kmaehashi** [comment]
Confirmed RTD rendered as expected, merging.
https://cupy--6093.org.readthedocs.build/en/6093/install.html#using-cupy-on-amd-gpu-experimental

**Pull request merged**
