### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/cupy/issues/). This PR fixes a few of them.

#### Summary of changes
- ~Removed length check in favour of truthiness of the object~
- ~Removed unnecessary use of comprehension~
- Removed unnecessary comprehension
- Merged `isinstance` calls
- Added .deepsource.toml

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks, but the fix conflicts with our coding rule tests. Could you check the `pretest` results?

**Comment by withshubh** [comment]
> Thanks, but the fix conflicts with our coding rule tests. Could you check the `pretest` results?

Fixed! @kmaehashi :sparkling_heart:

**Review by toslunar — CHANGES_REQUESTED** [review]
> * Removed length check in favour of truthiness of the object

NumPy sometimes ignores this rule because of the difference between sequences and object arrays.

```
>>> bool([False])
True
>>> bool(np.array([False]))
False
```

> * Removed unnecessary use of comprehension

A list comprehension is usually faster than a generator expression.

> * Removed unnecessary comprehension

:+1:

> * Merged `isinstance` calls

:+1:

> * Added .deepsource.toml

It's not necessary in this PR.  Maybe the file would be added when a CuPy CI starts to check DeepSource.

**Comment by withshubh** [comment]
Hey @toslunar 

I have reverted the fixes:

- Removed length check in favour of truthiness of the object
- Removed unnecessary use of comprehension

and deleted the `.deepsource.toml` file.

Also, I would really appreciate If you could drop any suggestion on what we can do better to onboard you (or CuPy) on DeepSource in the future. :)

**Comment by withshubh** [comment]
Hey @kmaehashi :wave: 
Please review :sparkling_heart:

**Comment by kmaehashi** [comment]
Thanks! The changes look good to me.
We're about to code freeze & cut a release so let me merge the PR next week.

Btw I've tried DeepSource in my private fork of CuPy. Autofix feature looks great although we can't introduce it immediately due to conflict with the existing coding rules.
https://deepsource.io/gh/kmaehashi/cupy/run/f2fcc168-bab7-4b23-801c-b0bff03dad33/python
I think it would also be nice if DeepSource can propose a fix using GitHub's ` ```suggestion ` syntax to diff in pull-requests.

**Comment by withshubh** [comment]
> Thanks! The changes look good to me.
> We're about to code freeze & cut a release so let me merge the PR next week.

Sounds Good! :sparkles: 

> Btw I've tried DeepSource in my private fork of CuPy. Autofix feature looks great although we can't introduce it immediately due to conflict with the existing coding rules.

No worries. 

> [deepsource.io/gh/kmaehashi/cupy/run/f2fcc168-bab7-4b23-801c-b0bff03dad33/python](https://deepsource.io/gh/kmaehashi/cupy/run/f2fcc168-bab7-4b23-801c-b0bff03dad33/python)
> I think it would also be nice if DeepSource can propose a fix using GitHub's `` ```suggestion `` syntax to diff in pull-requests.

Thank you for your suggestion! :sparkling_heart: I reported this to our engineering team and They'll release a fix for this soon. :sparkles:

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by withshubh** [comment]
@kmaehashi 
Can I submit a new PR with `.deepsource.toml` configuration once this PR is merged?

**Comment by kmaehashi** [comment]
@withshubh I'm afraid we can't integrate DeepSource for now, as it's misleading for contributors to display conflicting suggestions (our coding rules tested in `pretest` and DeepSource) in pull-requests.

**Pull request merged**
