### PR TITLE
Simplify fp16 code in carray.cuh

### PR DESCRIPTION
**Pull request by okuta**
CuPy will use `__half_raw` and `half` in CUDA9 mainly.
But, if we use `half` directly, compiler outputs lots of errors. Thus, I use `float16` class.

### CODE REVIEW

**Comment by niboshi** [comment]
I don't fully understand the background, but could you answer some questions?

* What's the difference between `__half_raw` and `half`?
* Why did you stop using `static_cast`s?

**Comment by okuta** [comment]
> What's the difference between `__half_raw` and `half`?

`__half_raw` has a public member variable.
`half` has a private member variable.


> Why did you stop using static_casts?

I think using constructor is simpler.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Comment by niboshi** [comment]
@okuta Do you think it should be backported?

**Comment by okuta** [comment]
hmm, Both is OK.

**Comment by niboshi** [comment]
OK, I leave it for now.

**Pull request merged**
