### PR TITLE
Fix integer GEMM

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of #3994. ~~Blocked by #4217.~~

This PR fixes two things:
1. For ROCm/HIP, there is a bunch of errors in `test_product.py` (see https://github.com/cupy/cupy/issues/4484#issuecomment-751204258) due to ~~the different handlings in out-of-bound access between CUDA and HIP. A check is added on HIP.~~ a strange behavior in HIP (likely the same cause as in #4504. Fixed by syncing the block only on HIP.
2. The kernel allocates shared memory statically, not dynamically, so there's no reason to pass `shared_mem` when launching the kernel.

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
> there is a bunch of errors in `test_product.py` (see [#4484 (comment)](https://github.com/cupy/cupy/issues/4484#issuecomment-751204258)) due to the different handlings in out-of-bound access between CUDA and HIP. 

Frankly I don't understand why this isn't an issue on CUDA. @emcastillo any insight? 🙂

**Comment by leofang** [comment]
I looked at the PTX code in CUDA but it wasn't obvious to me if there is any special guard: https://godbolt.org/z/ad8Pje

**Comment by emcastillo** [comment]
Actually I have no idea ...

**Comment by leofang** [comment]
> Actually I have no idea ...

Haha no worries. I will write to a MAGMA developer that I know and see what he know about.

**Comment by leofang** [comment]
btw it's best to merge this PR after #4217 is in.

**Comment by leofang** [comment]
> I will write to a MAGMA developer that I know and see what he know about. But this PR should be ready to go.

The discussion is in MAGMA's mailing list: https://groups.google.com/a/icl.utk.edu/g/magma-user/c/igc66uduTfI.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I wonder if this will fix https://github.com/cupy/cupy/issues/4387

**Comment by leofang** [comment]
Just checked, unfortunately it's not fixed 😅 I checked the grid and block sizes and everything looked fine to me. Not sure why the driver complained about invalid arguments...

**Comment by emcastillo** [comment]
Hey, is this ready for review? :)

**Comment by leofang** [comment]
> Hey, is this ready for review? :)

@emcastillo I think so 🙂

**Comment by leofang** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
