### PR TITLE
Improve `_comparison_generator`

### PR DESCRIPTION
**Pull request by toslunar**
- Fix `scipy.linalg` table
  - Fix caption
  - Exclude `numpy.linalg` reexports
- Add `scipy.sparse.linalg` table
- Use ~`:func:`~ `:obj:` and `:meth:`

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
> Use :func: and :meth:

As far as I tested `:obj:` is needed to link to numpy ufuncs (which is not function nor method from Python perspective).

**Comment by kmaehashi** [comment]
> Shall I make scipy optional? (See #1478)

I think docs build should not to depend on environment (ie, docs build should require scipy).

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
