### PR TITLE
Remove Chainer related docs

### LINKED ISSUE #3607: Remove docs mentioning Chainer
* docs/source/tutorial/basic.rst
* Remove intersphinx config for chainer

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #3607

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
I guess it's a sad moment to say goodbye...Salute, Chainer!

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
