### PR TITLE
Refactor `cupyx.scipy.sparse.linalg.eigsh`

### PR DESCRIPTION
**Pull request by takagi**
Follows up #4214.

This PR refactors `cupyx.scipy.sparse.linalg.eigsh`. The new one should implement exactly the same algorithm except that `u` is once allocated and overwritten.

- [x] performance comparison

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by anaruse** [comment]
I shortened the lifespan of the spmv-related resources intentionally because longer lifespan sometimes resulted in unexpected illegal memory access when the matrix size was large. Please be aware of that.
However, `cupy.linalg.eigh` (using cuSolver) was used in `_eigsh_solve_ritz` at that time and it might be related to the illegal memory access. The current implementation does not use `cupy.linalg.eigh`, so it may not be a problem.

**Comment by takagi** [comment]
Thanks for your explanation! Yes, I read the comment you left.

I want to try to reuse the spmv-related resources this time as I have the impression that the way `u` is used in the original code is a bit tangled. Sometimes assigning another instance, sometimes overwriting its content, and sometimes copying the instance it is assigned to.

My guess is that, at some point you implemented the code, `u` was assigned to another instance from the previous update but the memory pool happened to return the same memory block, eventually making the code work. When the memory pool returned the different memory block in case a large matrix was supplied, illegal memory access occurred.

In this PR, `u` is once allocated and overwritten repeatedly so I suppose the problem has gone if my guess is right.

Do you remember the condition you got the error, for example, the matrix size? I want to try to reproduce it, if possible.

**Comment by anaruse** [comment]
I sometimes observed the error when I used the following script, so please use it.
https://github.com/cupy/cupy/pull/4214#issuecomment-718795577

**Comment by takagi** [comment]
Thanks!

**Comment by takagi** [comment]
The error you saw was something similar to this? (The line `CUBLASError` was raised might be different because of asynchronous operation)

```
Traceback (most recent call last):
  File "../work/4275/test.py", line 66, in <module>
    times = run(a, k)
  File "../work/4275/test.py", line 49, in run
    n_repeat=n_repeat, n_warmup=n_warmup)
  File "cupy/cupyx/time.py", line 79, in repeat
    func, args, kwargs, n_repeat, name, n_warmup, max_duration, devices)
  File "cupy/cupyx/time.py", line 97, in _repeat
    func(*args, **kwargs)
  File "cupy/cupyx/scipy/sparse/linalg/_eigen.py", line 108, in eigsh
    u = lanczos.update(k+1, ncv)
  File "cupy/cupyx/scipy/sparse/linalg/_eigen.py", line 181, in update
    return self._update_fast(i_start, i_end)
  File "cupy/cupyx/scipy/sparse/linalg/_eigen.py", line 203, in _update_fast
    self._norm(i)
  File "cupy/cupyx/scipy/sparse/linalg/_eigen.py", line 273, in _norm
    self.beta.data.ptr + i * self.beta.itemsize)
  File "cupy_backends/cuda/libs/cublas.pyx", line 664, in cupy_backends.cuda.libs.cublas.dnrm2
    cpdef dnrm2(intptr_t handle, int n, size_t x, int incx, size_t result):
  File "cupy_backends/cuda/libs/cublas.pyx", line 669, in cupy_backends.cuda.libs.cublas.dnrm2
    check_status(status)
  File "cupy_backends/cuda/libs/cublas.pyx", line 391, in cupy_backends.cuda.libs.cublas.check_status
    raise CUBLASError(status)
cupy_backends.cuda.libs.cublas.CUBLASError: CUBLAS_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 253, in cupy_backends.cuda.api.driver.moduleUnload
    check_status(status)
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
    raise CUDADriverError(status)
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
...
```

**Comment by anaruse** [comment]
It was not `CUBLASError` that I saw, but it is similar to the error I saw at that time.

**Comment by takagi** [comment]
Hmm, okay. A weird situation I got is that `A` is modified by `sum_duplicates()` in `@` operator call, and `A`'s descriptor needed to be created again. (The way `u` is used I mentioned above is not related. I'm wrong, sorry.)

**Comment by takagi** [comment]
I reverted 3547c845f6725bd98a11e5458571e9fc46c42aeb and just removed explicit `del` statements as the spmv resources are surely released when each update finishes as 60b4ac2efd1c2dc36779f19cbce5311110e4c3cf. Does it makes sense to you @anaruse ?

**Comment by takagi** [comment]
I will confirm that it has no performance degradation compared to the original one after my development environment under maintenance is back this Tuesday.

**Comment by anaruse** [comment]
> I reverted 3547c84 and just removed explicit del statements as the spmv resources are surely released when each update finishes as 60b4ac2. Does it makes sense to you @anaruse ?

That is perfectly fine.

**Comment by takagi** [comment]
The following is the performance comparison between the base branch and this PR, which I suppose has no significant performance degradation.

**base branch(f266b53)**

size | nnz | nnz per row | k | scipy.eigsh | cupyx.eigsh
-----|-----|-------------|---|-------------|-------------
5000 | 261383 | 52.3 | 3 | 0.093 | 0.038
5000 | 261383 | 52.3 | 6 | 0.122 | 0.040
5000 | 261383 | 52.3 | 12 | 0.195 | 0.080
5000 | 482392 | 96.5 | 3 | 0.201 | 0.032
5000 | 482392 | 96.5 | 6 | 0.198 | 0.053
5000 | 482392 | 96.5 | 12 | 0.316 | 0.085
5000 | 974852 | 195.0 | 3 | 0.321 | 0.036
5000 | 974852 | 195.0 | 6 | 0.371 | 0.054
5000 | 974852 | 195.0 | 12 | 0.564 | 0.093
10000 | 483126 | 48.3 | 3 | 0.145 | 0.030
10000 | 483126 | 48.3 | 6 | 0.208 | 0.046
10000 | 483126 | 48.3 | 12 | 0.316 | 0.071
10000 | 981948 | 98.2 | 3 | 0.345 | 0.032
10000 | 981948 | 98.2 | 6 | 0.412 | 0.050
10000 | 981948 | 98.2 | 12 | 0.631 | 0.094
10000 | 1967188 | 196.7 | 3 | 0.514 | 0.034
10000 | 1967188 | 196.7 | 6 | 0.729 | 0.065
10000 | 1967188 | 196.7 | 12 | 0.944 | 0.079
20000 | 976390 | 48.8 | 3 | 0.250 | 0.030
20000 | 976390 | 48.8 | 6 | 0.373 | 0.057
20000 | 976390 | 48.8 | 12 | 0.569 | 0.095
20000 | 1924285 | 96.2 | 3 | 0.764 | 0.051
20000 | 1924285 | 96.2 | 6 | 0.822 | 0.076
20000 | 1924285 | 96.2 | 12 | 1.073 | 0.096
20000 | 3822232 | 191.1 | 3 | 1.595 | 0.072
20000 | 3822232 | 191.1 | 6 | 1.656 | 0.087
20000 | 3822232 | 191.1 | 12 | 2.155 | 0.129

**this PR**

size | nnz | nnz per row | k | scipy.eigsh | cupyx.eigsh
-----|-----|-------------|---|-------------|-------------
5000 | 261383 | 52.3 | 3 | 0.084 | 0.039
5000 | 261383 | 52.3 | 6 | 0.126 | 0.043
5000 | 261383 | 52.3 | 12 | 0.201 | 0.081
5000 | 482392 | 96.5 | 3 | 0.201 | 0.035
5000 | 482392 | 96.5 | 6 | 0.199 | 0.049
5000 | 482392 | 96.5 | 12 | 0.314 | 0.085
5000 | 974852 | 195.0 | 3 | 0.318 | 0.032
5000 | 974852 | 195.0 | 6 | 0.379 | 0.055
5000 | 974852 | 195.0 | 12 | 0.561 | 0.091
10000 | 483126 | 48.3 | 3 | 0.146 | 0.028
10000 | 483126 | 48.3 | 6 | 0.215 | 0.042
10000 | 483126 | 48.3 | 12 | 0.319 | 0.067
10000 | 981948 | 98.2 | 3 | 0.341 | 0.032
10000 | 981948 | 98.2 | 6 | 0.411 | 0.049
10000 | 981948 | 98.2 | 12 | 0.613 | 0.091
10000 | 1967188 | 196.7 | 3 | 0.524 | 0.033
10000 | 1967188 | 196.7 | 6 | 0.726 | 0.060
10000 | 1967188 | 196.7 | 12 | 0.952 | 0.077
20000 | 976390 | 48.8 | 3 | 0.261 | 0.028
20000 | 976390 | 48.8 | 6 | 0.342 | 0.058
20000 | 976390 | 48.8 | 12 | 0.577 | 0.095
20000 | 1924285 | 96.2 | 3 | 0.753 | 0.049
20000 | 1924285 | 96.2 | 6 | 0.814 | 0.077
20000 | 1924285 | 96.2 | 12 | 1.113 | 0.099
20000 | 3822232 | 191.1 | 3 | 1.440 | 0.070
20000 | 3822232 | 191.1 | 6 | 1.606 | 0.084
20000 | 3822232 | 191.1 | 12 | 2.127 | 0.129

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
pfnCI, test this please.

**Pull request merged**
