### PR TITLE
[backport] Avoid hacking: Use the same test settings as Chainer

### PR DESCRIPTION
**Pull request by toslunar**
Backport of #1477

### CODE REVIEW

**Comment by toslunar** [comment]
[automatic post] Jenkins, test this please.

**Comment by toslunar** [comment]
It'll need some effort to fix codes.  I'd like to close this PR.
c.f. #1352 was not backported.

**Comment by toslunar** [comment]
It'll need some effort to fix codes. I'd like to close this PR.
cf. #1352 was not backported.

**Comment by okuta** [comment]
Please check test result.

**Comment by toslunar** [comment]
OK.  Fixed.
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
