### PR TITLE
ENH: Remove `NINF`, `PINF`, `Inf`,... usages

### PR DESCRIPTION
**Pull request by mtsokol**
Hi!
Due to NumPy's main namespace being changed in https://github.com/numpy/numpy/pull/24357, here I update warning imports. Here I delete aliases that were decided to be removed.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Hi @mtsokol, thanks for the PR! As CuPy v13 currently targets NumPy 1.25 API set as the baseline, I'd like to have keep these aliases for now. Maybe like this?

```py
# APIs to be removed in NumPy 2.0.
# Remove these when bumping the baseline API to NumPy 2.0.
# https://github.com/cupy/cupy/pull/7800
PINF = Inf = Infinity = infty = numpy.inf  # NOQA
NINF = - numpy.inf  # NOQA
NAN = NaN = numpy.nan  # NOQA
PZERO = 0.0  # NOQA
NZERO = -0.0  # NOQA
```

c.f. https://github.com/cupy/cupy/issues/7796#issuecomment-1670625628

**Comment by mtsokol** [comment]
> Hi @mtsokol, thanks for the PR! As CuPy v13 currently targets NumPy 1.25 API set as the baseline, I'd like to have keep these aliases for now. Maybe like this?
> 
> ```python
> # APIs to be removed in NumPy 2.0.
> # Remove these when bumping the baseline API to NumPy 2.0.
> # https://github.com/cupy/cupy/pull/7800
> PINF = Inf = Infinity = infty = numpy.inf  # NOQA
> NINF = - numpy.inf  # NOQA
> NAN = NaN = numpy.nan  # NOQA
> PZERO = 0.0  # NOQA
> NZERO = -0.0  # NOQA
> ```
> 
> c.f. [#7796 (comment)](https://github.com/cupy/cupy/issues/7796#issuecomment-1670625628)

Hi @kmaehashi, sure! This is also the same approach that I was asked to push in Jax: https://github.com/google/jax/pull/17041/files. I will update the PR.

**Comment by mtsokol** [comment]
@kmaehashi I updated PR and it's ready from my side.

**Comment by kmaehashi** [comment]
Thanks, LGTM!

/test mini

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
