### PR TITLE
Rename submodules under `cupyx.scipy.sparse`

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR renames submodules under `cupyx.scipy.sparse` to indicate that they are CuPy's private submodules and not intended to be used by users.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
@takagi Could you check Jenkins failures?

**Comment by takagi** [comment]
I've resolved the conflicts!

**Comment by takagi** [comment]
I'll fix the CI failure.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
