### PR TITLE
Fix redeclaration of sparse warning classes

### PR DESCRIPTION
**Pull request by kmaehashi**
I overlooked this during #4213 review :bow:

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
🙇

**Review by toslunar — APPROVED** [review]
I forgot to update #4213 after #4356 is merged.  Thanks for fixing the conflict.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Pull request merged**
