### PR TITLE
[backport] Eliminate read past end of array in percentile_weightnening

### PR DESCRIPTION
**Pull request by wphicks**
Bring changes from PR 4453 into v8 to eliminate read past end of array in percentile calculations

### CODE REVIEW

**Comment by wphicks** [comment]
Given that many consumers of cupy are currently on version 8 and that this issue has caused some difficult-to-mitigate bugs in (e.g.) Rapids, it would be helpful to have the fix from #4453 backported to version 8. Is this something that would be possible to get included in a patch release?

**Comment by toslunar** [comment]
backport of #4453

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by jakirkham** [comment]
Thanks everyone! 😀

**Pull request merged**
