### PR TITLE
Make nvrtc `getPTX` use `bytes` instead of `unicode`

### PR DESCRIPTION
**Pull request by emcastillo**
This is the first step to add support for hiprtc.

In some environments, hiprtc byte encoding when returning the compiled binary is not utf-8, so we can't rely on it.

This PR just deals with the intermediate code by keeping it as bytes. Thus making it encoding agnostic.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Could you rebase?

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@kmaehashi @emcastillo PTAL

**Comment by kmaehashi** [comment]
LGTM!

**Comment by leofang** [comment]
Thanks @emcastillo @kmaehashi!

**Pull request merged**
