### PR TITLE
delete from os import path

### LINKED ISSUE #3885: Eliminate `from os import path` from `cupy_setup_build.py`
Let's use `os.path` instead.

### PR DESCRIPTION
**Pull request by Yutaro-Sanada**
fixes #3885
 
- change ```from os import path``` to ```os.path```

### CODE REVIEW

**Comment by emcastillo** [comment]
Thank you!
Instead of using the archaic `os.path`, how about moving to `pathlib`?
Some places in the code base are already using it :)

**Comment by kmaehashi** [comment]
I think `distutils` does not expect path-like objects for the most part, so if we use `pathlib` in these scripts we'll need to do cast everywhere. I think this PR resolves the original issue #3885 and it's fine to merge as-is 😃

**Comment by emcastillo** [comment]
Good catch! thanks!

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
