### PR TITLE
Import numpy complex dtypes into cupy namespace.

### PR DESCRIPTION
**Pull request by ericmjl**
@kmaehashi please let me know what else needs to be done. (1st PR into cupy, still getting familiar with codebase.)

Addresses #905.

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by ericmjl** [comment]
@okuta just out of curiosity, where is jenkins running? (sorry if this question sounds a bit too basic, I'm asking both out of curiosity and out of ignorance.)

**Comment by kmaehashi** [comment]
Hi, thanks for the PR!
Jenkins is running in our internal network now. We're planning to publicize it in near future.

**Comment by okuta** [comment]
> jenkins, test this please.
This is keyword to launch internal Jenkins test.

LGTM!

**Pull request merged**
