### PR TITLE
Reorganize build scripts, part 2: separate modules

### PR DESCRIPTION
**Pull request by kmaehashi**
context: #5722, #5730

Please review commit by commit.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
CI error for pfnci-rocm

```
File "/tmp/flexci/run-00161320/tmp/pip-wrvbfxsp-build/install/cupy_builder/cupy_setup_build.py", line 587, in cythonize |  
-- | --
00:09:09.114941 STDOUT 2287] | compiler_directives=directives, **cythonize_options) |  
00:09:09.114947 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 1102, in cythonize |  
00:09:09.115055 STDOUT 2287] | cythonize_one(*args) |  
00:09:09.115058 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Build/Dependencies.py", line 1208, in cythonize_one |  
00:09:09.115063 STDOUT 2287] | result = compile_single(pyx_file, options, full_module_name=full_module_name) |  
00:09:09.115163 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Main.py", line 727, in compile_single |  
00:09:09.115166 STDOUT 2287] | return run_pipeline(source, options, full_module_name) |  
00:09:09.115172 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Main.py", line 515, in run_pipeline |  
00:09:09.115251 STDOUT 2287] | err, enddata = Pipeline.run_pipeline(pipeline, source) |  
00:09:09.115259 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline |  
00:09:09.115264 STDOUT 2287] | data = run(phase, data) |  
00:09:09.115319 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Pipeline.py", line 335, in run |  
00:09:09.115322 STDOUT 2287] | return phase(data) |  
00:09:09.115328 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage |  
00:09:09.115400 STDOUT 2287] | module_node.process_implementation(options, result) |  
00:09:09.115403 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation |  
00:09:09.115408 STDOUT 2287] | self.generate_c_code(env, options, result) |  
00:09:09.115455 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/ModuleNode.py", line 359, in generate_c_code |  
00:09:09.115457 STDOUT 2287] | self.generate_module_preamble(env, options, modules, result.embedded_metadata, h_code) |  
00:09:09.115461 STDOUT 2287] | File "/usr/local/lib/python3.7/dist-packages/Cython/Compiler/ModuleNode.py", line 634, in generate_module_preamble |  
00:09:09.115496 STDOUT 2287] | code.putln(json.dumps(metadata, indent=4, sort_keys=True)) |  
00:09:09.115498 STDOUT 2287] | File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps |  
00:09:09.115501 STDOUT 2287] | **kw).encode(obj) |  
00:09:09.115527 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 201, in encode |  
00:09:09.115529 STDOUT 2287] | chunks = list(chunks) |  
00:09:09.115537 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode |  
00:09:09.115667 STDOUT 2287] | yield from _iterencode_dict(o, _current_indent_level) |  
00:09:09.449872 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict |  
00:09:09.449969 STDOUT 2287] | yield from chunks |  
00:09:09.449971 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict |  
00:09:09.449975 STDOUT 2287] | yield from chunks |  
00:09:09.450009 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list |  
00:09:09.450010 STDOUT 2287] | yield from chunks |  
00:09:09.450013 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list |  
00:09:09.450037 STDOUT 2287] | yield from chunks |  
00:09:09.450038 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode |  
00:09:09.450041 STDOUT 2287] | o = _default(o) |  
00:09:09.450084 STDOUT 2287] | File "/usr/lib/python3.7/json/encoder.py", line 179, in default |  
00:09:09.450089 STDOUT 2287] | raise TypeError(f'Object of type {o.__class__.__name__} ' |  
00:09:09.450097 STDOUT 2287] | TypeError: Object of type function is not JSON serializable |  
00:09:09.450171 STDOUT 2287] | Running setup.py install for cupy: finished with status 'error'

```

**Comment by kmaehashi** [comment]
FlexCI passed!
pfnCI, run Jenkins please.

**Review by emcastillo — APPROVED** [review]
LGTM! much cleaner now :)

**Pull request merged**
