### PR TITLE
Update CUDA 11.0 FP16 header to production release version (11.0.2)

### PR DESCRIPTION
**Pull request by kmaehashi**
Headers imported in #3405 was CUDA version 11.0.1 (RC).
Update to the latest ones.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Oops, I'm sorry I mistakenly self-merged...
I believe this is harmless but please check :bow: @emcastillo @asi1024

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I think it should be fine

**Comment by asi1024** [comment]
Before the backport, #3405 should be backported.

**Pull request merged**
