### PR TITLE
Fix `nonzero` for 0d inputs

### LINKED ISSUE #4165: `nonzero` is wrong for nonzero 0d-array
```
>>> import numpy, cupy
>>> for xp in [numpy, cupy]: print(xp.__name__, xp.__version__, xp.array(3, 'i').nonzero())
...
<stdin>:1: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
numpy 1.19.2 (array([0]),)
<stdin>:1: DeprecationWarning: calling nonzero on 0d arrays is deprecated
cupy 8.0.0rc1 (array([], dtype=int64),)
```

https://github.com/cupy/cupy/blob/a8dfcd66d89c8e66a60e4b7272f95a15c26fc907/cupy/core/_routines_indexing.pyx#L58-L61

### PR DESCRIPTION
**Pull request by toslunar**
Fix #4165.

Merge #4167 first.

### CODE REVIEW

**Comment by asi1024** [comment]
Merged #4167.

**Comment by toslunar** [comment]
Updated.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
LGTM!

**Pull request merged**
