### PR TITLE
Use single quote

### PR DESCRIPTION
**Pull request by asi1024**
Rel. #700.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by asi1024** [comment]
This PR has a conflict with #2033, and I want to merge it firstly.

**Comment by okuta** [comment]
How about making PR excluding #2033?

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
