### PR TITLE
Test cuTENSOR v1.0.0

### PR DESCRIPTION
**Pull request by kmaehashi**
Merge after #2709 (merged)

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Rebased to the latest master.

**Comment by niboshi** [comment]
Jenkins, test this please

`/test` does not trigger jenkins.

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM

**Pull request merged**
