### PR TITLE
Fix usage check of TensorCore

### LINKED ISSUE #2153: Tensor Core is not used on the Turing GPU
The compute capability is 7.5 on the Turing GPU.
However, in the following Tensordot and Convolution code, the compute capability only supports 7.0.
So it seems that Tensor Core is not used on Turing GPU.

* Tensordot

https://github.com/cupy/cupy/blob/ba75ec09e33bd1b2aad4c564ed78389ceb09e0d2/cupy/core/core.pyx#L2288-L2290

* Convolution

https://github.com/cupy/cupy/blob/690997a6159ee84c0f6b41ae6c79d7974e358912/cupy/cudnn.pyx#L1198-L1201

### PR DESCRIPTION
**Pull request by okuta**
Fix #2153

### CODE REVIEW

**Comment by asi1024** [comment]
Could you resolve conflict?

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failure seems unrelated to this PR.

**Comment by niboshi** [comment]
Being reverted because enabling Tensor Core caused test errors in some other places.

Revert PRs
* master: #2197 
* v6: #2198

**Pull request merged**
