### PR TITLE
Rename submodule under `cupy.fft` package

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR renames `cupy.fft.fft` submodule to `cupy.fft._fft` to indicate that it is CuPy's private submodule and not intended to be used by users.

### CODE REVIEW

**Comment by leofang** [comment]
Need to merge with master 🙂 btw this PR blocks #3896.

**Comment by takagi** [comment]
Merged with master!

**Comment by leofang** [comment]
Thanks! There seems to be a few flake8 errors 🙂

**Comment by asi1024** [comment]
@takagi Could you check Travis failure?

**Comment by takagi** [comment]
`cupy.fft.config` should be a public submodule? Numpy does not have its counterpart, butv it is used by users to control the behavior of `cupy.fft` features.

**Comment by asi1024** [comment]
@takagi Yes, it is a public submodule. There is a helper function documented in https://docs.cupy.dev/en/latest/reference/generated/cupy.fft.config.set_cufft_gpus.html.

**Comment by leofang** [comment]
Yeah, and there's also an `enable_nd_planning` flag.

**Comment by leofang** [comment]
I also plan to expose a few cache-related APIs to the confit module in #3730.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
I'll fix the CI failure.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
@takagi Could you resolve conflicts?

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
