### PR TITLE
Use `size_t nbytes` in `__cuda_array_interface__`

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @kkraus14 @shwina @leofang

**Comment by leofang** [comment]
> We're actively hitting this issue in a cuDF example and this fix looks good to me

Interesting. Do you have a pointer to the issue?

**Comment by kkraus14** [comment]
> Interesting. Do you have a pointer to the issue?

Yep, you can see the test failure here: https://gpuci.gpuopenanalytics.com/job/docker/job/tests/job/docker-test-notebooks/CUDA_VERSION=10.0,LINUX_VERSION=ubuntu16.04,PYTHON_VERSION=3.6/lastCompletedBuild/testReport/(root)/cudf/notebooks_numba_cuDF_integration/

**Comment by jakirkham** [comment]
@kmaehashi, would it be possible for someone to look at this? It's causing us a bit of pain atm. Am planning to include it as a patch in the conda-forge packages, but would like to make sure this seems reasonable first. So a quick review should be sufficient for us near term 🙂

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by jakirkham** [comment]
Thanks for the review @emcastillo! 😄

<hr>

> Sounds like we should add a similar test to cupy!

Agreed, @leofang. Where would you suggest we add it? 🙂

**Comment by jakirkham** [comment]
Submitted a backport to `v6` with PR ( https://github.com/cupy/cupy/pull/3014 ).

**Comment by leofang** [comment]
> > Sounds like we should add a similar test to cupy!
> 
> Agreed, @leofang. Where would you suggest we add it? 🙂

See #3297.

**Pull request merged**
