### PR TITLE
Document `cupyx.time.repeat`

### PR DESCRIPTION
**Pull request by leofang**
Address https://github.com/cupy/cupy/issues/4902#issuecomment-801662941. I think it's better to get this API documented sooner while we plan to expand on the tutorial. It is a very handy API that we keep referring users in the issue tracker to use, so I say we just get it on the docs to have something to refer to. As such, we should backport this PR to v9.

### CODE REVIEW

**Comment by takagi** [comment]
Thanks! It was originally introduced as experimental but is pretty helpful and now often used.

**Comment by leofang** [comment]
Right, so I do put a warning saying it is still experimental. But we should get it documented anyway, like a few other experimental APIs 🙂

**Comment by UmashankarTriforce** [comment]
Thank you for this addition! The timing is impeccable :D 
I was just looking for a documentation source on `cupyx.time.repeat` to understand the function better!

**Comment by leofang** [comment]
Jenkins, test this please

**Review by asi1024 — APPROVED** [review]

**Comment by asi1024** [comment]
LGTM! Thanks!

**Comment by leofang** [comment]
Thanks!

**Pull request merged**
