### PR TITLE
[backport] Update installation guide for conda-forge

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #3052

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by jakirkham** [comment]
Thanks for doing this 😄

cc @leofang

**Comment by leofang** [comment]
Ah, we missed the v7.3.0 release! The tag should be v7.4.0, then.

**Comment by jakirkham** [comment]
Nah that was us. We only caught this after 7.3.0 shipped. It’s all good though 🙂

**Comment by leofang** [comment]
No worries. Thanks, @emcastillo! btw, for this PR the milestone should be v7.4.0 😄

**Comment by kmaehashi** [comment]
Fixed the milestone

**Pull request merged**
