### PR TITLE
Clean up `cupy_backends`

### PR DESCRIPTION
**Pull request by leofang**
Follow up of #3616. 

***UPDATE***: See https://github.com/cupy/cupy/pull/4088#issuecomment-745784398. Ignore the original PR description below.

----

~~This PR is to ensure compliance of the proposed directory structure (https://github.com/cupy/cupy/pull/3616#issuecomment-699662624), which was not fully honored. Specifically, instead of doing an import like this~~
```python
from cupy_backends.cuda.api import runtime
```
~~we now do~~
```python
from cupy_backends.api import runtime  # "cuda" is gone
```
~~making it neutral of the backend provider~~

### CODE REVIEW

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
> The motivation for `cupy_backends` was to allow different backends to be added. So it makes sense that there is an actual `cuda` directory with all the cuda code. If someone wants, he/she could write an additional backend for example opencl in `cupy_backends/opencl` Although now the dependence with CUDA APIs is extreme in all the cupy codebase, we believe that we need to have this logical separation between backends.

I agree that the name `cuda` should appear somewhere, so if you take a look at the directory structure there is one:
```
cupy_backends/
    |__ api/  (only contains actual Cython implementations)
    |   |__ driver.pxd   (include ../cupy_backend.h)
    |   |__ driver.pyd   (include ../cupy_backend.h)
    |   |__ runtime.pxd  (include ../cupy_backend_runtime.h)
    |   |__ runtime.pyx  (include ../cupy_backend_runtime.h)
    |
    |__ libs/  (only contains actual Cython implementations)
    |   |__ cublas.pxd  (include ../cupy_cublas.h)
    |   |__ cublas.pyx  (include ../cupy_cublas.h)
    |   |__ ...
    |
    |__ cuda/  (only contains headers)
    |   |__ cupy_cuda.h
    |   |__ cupy_cuda_runtime.h
    |   |__ cupy_cuda_cublas.h
    |   |__ ...
    |
    |__ hip/  (only contains headers)
    |   |__ cupy_hip.h
    |   |__ cupy_hip_runtime.h
    |   |__ cupy_hip_hipblas.h
    |   |__ ...
    |
    |__ stub/  (only contains headers for RTD)
    |   |__ cupy_cuda.h
    |   |__ cupy_cuda_runtime.h
    |   |__ cupy_cuda_cublas.h
    |   |__ ...
    |
    |   (the rest are headers included by Cython implementations)
    |__ cupy_backend.h          (include cuda/cupy_cuda.h or hip/cupy_hip.h)
    |__ cupy_backend_runtime.h  (include cuda/cupy_cuda_runtime.h or hip/cupy_hip_runtime.h)
    |__ cupy_cublas.h           (include cuda/cupy_cuda_cublas.h or hip/cupy_hip_hipblas.h)
    |__ ...   
```
All of the backends exist in the form of header stubs (currently `cupy_backends/cuda`, `cupy_backends/hip`, and `cupy_backends/stub` for RTD). IMHO all new backends (say OpenCL) should provide the stubs wrapping the actually C/C++ api so that the Cython codes, such as `cupy_backends.api.getDevice`, can continue to work without any change. Like you pointed out, currently the CUDA api is baked deeply in the codebase, and I see no way for any potentially new backend to join the game, except if they follow the same set of api conventions through adding header stubs. I can't emphasize enough how painful it would be if we also had to support e.g. `cupy_backends.opencl.api.getDevice` in the codebase. It'd be a nightmare and against the intention of separating out `cupy_backends` in the first place.

**Comment by leofang** [comment]
Would it be acceptable if I restore the `cupy_backends.cuda.*` namespace but keep the stubs refactored?

**Comment by emcastillo** [comment]
```
Would it be acceptable if I restore the cupy_backends.cuda.* namespace but keep the stubs refactored?
```

I think this seems promising. Sorry for the delay.

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
I backed up the original branch here for later reference: https://github.com/leofang/cupy/tree/backup_fix_backend, still work in progress...

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
OK, @emcastillo I guess this is ready. So the directory structure roughly follows what was done earlier, but without removing the `cupy_backends.cuda` namespace. Specifically,
- Headers for CUDA/HIP/RTD are fully separated; for CUDA capabilities not available in HIP/RTD, the latter two share the same header to avoid code dup
- The master headers (those in `cupy_backends/`) have generic filenames (decoupled from the actual libraries) 
- Only the master headers are directly imported in the codebase

Below is the updated directory hierarchy:
```
cupy_backends/
    |__ cuda/  (contains CUDA headers in ./ and Cython codes in ./api/ and ./libs/) 
    |    |__ api/  (only contains actual Cython implementations)
    |    |   |__ driver.pxd   (include ../../cupy_backend.h)
    |    |   |__ driver.pyd   (include ../../cupy_backend.h)
    |    |   |__ runtime.pxd  (include ../../cupy_backend_runtime.h)
    |    |   |__ runtime.pyx  (include ../../cupy_backend_runtime.h)
    |    |
    |    |__ libs/  (only contains actual Cython implementations)
    |    |   |__ cublas.pxd  (include ../../cupy_cublas.h)
    |    |   |__ cublas.pyx  (include ../../cupy_cublas.h)
    |    |   |__ ...
    |    |
    |    |__ cupy_cuda.h
    |    |__ cupy_cuda_runtime.h
    |    |__ cupy_cuda_cublas.h
    |    |__ ...
    |
    |__ hip/  (only contains headers in ./)
    |    |__ cupy_hip.h
    |    |__ cupy_hip_runtime.h
    |    |__ cupy_hip_hipblas.h
    |    |__ ...
    |
    |__ stub/  (only contains headers for RTD)
    |    |__ cupy_cuda.h
    |    |__ cupy_cuda_runtime.h
    |    |__ cupy_cuda_cublas.h
    |    |__ ...
    |
    |   (the rest are headers included by Cython implementations)
    |__ cupy_backend.h          (include cuda/cupy_cuda.h, hip/cupy_hip.h, or stub/cupy_cuda.h)
    |__ cupy_backend_runtime.h  (include cuda/cupy_cuda_runtime.h, hip/cupy_hip_runtime.h, or stub/cupy_cuda_runtime.h)
    |__ cupy_blas.h           (include cuda/cupy_cuda_cublas.h, hip/cupy_hip_hipblas.h, or stub/cupy_cublas.h)
    |__ ... 
```

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Thanks, @emcastillo!

**Pull request merged**
