### PR TITLE
Support ROCm 5.0

### PR DESCRIPTION
**Pull request by takagi**
Merge #6472 first.

### CODE REVIEW

**Comment by kmaehashi** [comment]
> Looks `hipGetDeviceCount` returns `hipErrorInvalidDevice`, making rocm-build pretest fail.

I think it's ok to by rewriting `raise` with `warnings.warn(f'Failed to detect number of GPUs: {e}')` here. Both CUDA/ROCm may fail with errors different than `ErrorNoDevice` here.
https://github.com/cupy/cupy/blob/0c459bee6d9090fbb6c67b507b46c058fe59df99/cupyx/_runtime.py#L278

**Comment by takagi** [comment]
Sure!

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

**Comment by kmaehashi** [comment]
Can you exclude the docs part from this PR? I think it will take some time to fully support ROCm 5.0 so I'd like to merge this one first without declaring official support.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
I've fixed to use ROCm 5.0.0 as 5.0.1 image is not available yet.

**Pull request merged**
