### PR TITLE
Avoid importing NumPy docstring

### PR DESCRIPTION
**Pull request by niboshi**
**(I have changed the main objective of this PR)**

Curerntly NumPy alias functions use NumPy docstring in documentation.
That incurs warnings because intersphinx environment is different between CuPy and NumPy.
This PR avoids this problem. (Rel. #442)

**(original motivation)**
[source] links for NumPy alias functions are not correctly shown.
#354 fixes the problem by hiding the links, but it might look strange for some users.
This PR is to enable the links anyway for such functions.

~(Currently only applied to `cupy.isscalar`. If this implementation is acceptable, I will apply to all such alias functions)~

### CODE REVIEW

**Comment by niboshi** [comment]
I found this PR also fixes warning in `make html`:
`
/home/niboshi/anaconda/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py:docstring of cupy.isscalar:: WARNING: more than one target found for cross-reference u'any': cupy.any, cupy.ndarray.any
`

So this PR is needed before merging #442.

**Comment by niboshi** [comment]
Perhaps
```
def isscalar(num):
    return numpy.isscalar(num)
```
is enough? (no need of `@_numpy_alias`?)

**Comment by okuta** [comment]
Yes, we can define function.But, speed will down.

**Comment by okuta** [comment]
I think that `_numpy_alias` can be written as a test.
Because it has not changed the function.
Cloud you fix?

**Comment by niboshi** [comment]
OK, that makes sense.
Btw, performance should not degrade that much anyway (no more than a single function call).

**Comment by niboshi** [comment]
Updated.

**Comment by okuta** [comment]
Please check travis result.

**Comment by niboshi** [comment]
flake8 fixed.

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
In order to pass the tests, [chainer-test](https://github.com/chainer/chainer-test) needs a fix to test only `tests` directory.

**Comment by niboshi** [comment]
I separated tests as a new PR: #471

**Comment by okuta** [comment]
LGTM!I

**Comment by niboshi** [comment]
Can we backport this?
#442 (which is to be backported) needs this fix.

**Comment by okuta** [comment]
OK. Please.

**Comment by niboshi** [comment]
Could you do it, because this PR is originally created by me?

**Comment by okuta** [comment]
OK, I will

**Pull request merged**
