### PR TITLE
Eliminate RUNPATH to use correct cuDNN

### PR DESCRIPTION
**Pull request by gwtnb**
TODO: write description

### CODE REVIEW

**Comment by okuta** [comment]
@gwtnb Please check travis result.

**Comment by gwtnb** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
@gwtnb Is this still WIP PR?

**Comment by gwtnb** [comment]
Removed [WIP].

**Comment by okuta** [comment]
Thanks

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
