### PR TITLE
Add `cupyx.scipy.ndimage.sum_labels` to docs

### PR DESCRIPTION
**Pull request by kmaehashi**
Follow-up for #5200

### CODE REVIEW

**Review by takagi — APPROVED** [review]

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Ok to skip Jenkins as docs are rendered successfully.
https://cupy--5223.org.readthedocs.build/en/5223/reference/ndimage.html

**Comment by takagi** [comment]
Hmm... "Merge pull request" button is disabled and I can not merge this without passing Jenkins. Does this depends on privilege? Anyway, let me trigger the CI again.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
> Hmm... "Merge pull request" button is disabled and I can not merge this without passing Jenkins. Does this depends on privilege?

Ah, yes, skipping `Required` tests are only for admins :bow:

**Pull request merged**
