### PR TITLE
Matrix power

### LINKED ISSUE #1358: matrix power is missing from cupy.linalg.
There is a corresponding `numpy.linalg.matrix_power` in NumPy. Is there a reason why this has not made it into CuPy?

If it helps, I am willing to take a shot at this one, though I might need a bit of hand-holding as I've not much experience with Cython code.

### PR DESCRIPTION
**Pull request by ericmjl**
Submitting matrix power, closes #1358

- Implementation works. (See below)
- Test not written, would like guidance.

Code showing that implementation works.

```python
In [4]: import cupy as cp
   ...: from product import matrix_power  # initialized IPython session inside cupy/linalg
   ...: import numpy as np
   ...: import numpy.linalg as LA
   ...:
   ...: acp = cp.arange(100).reshape(10,10)
   ...: anp = np.arange(100).reshape(10,10)
   ...:
   ...: print(LA.matrix_power(anp, 2))
   ...: print(matrix_power(acp, 2))
   ...:
   ...:
[[ 2850  2895  2940  2985  3030  3075  3120  3165  3210  3255]
 [ 7350  7495  7640  7785  7930  8075  8220  8365  8510  8655]
 [11850 12095 12340 12585 12830 13075 13320 13565 13810 14055]
 [16350 16695 17040 17385 17730 18075 18420 18765 19110 19455]
 [20850 21295 21740 22185 22630 23075 23520 23965 24410 24855]
 [25350 25895 26440 26985 27530 28075 28620 29165 29710 30255]
 [29850 30495 31140 31785 32430 33075 33720 34365 35010 35655]
 [34350 35095 35840 36585 37330 38075 38820 39565 40310 41055]
 [38850 39695 40540 41385 42230 43075 43920 44765 45610 46455]
 [43350 44295 45240 46185 47130 48075 49020 49965 50910 51855]]
[[ 2850  2895  2940  2985  3030  3075  3120  3165  3210  3255]
 [ 7350  7495  7640  7785  7930  8075  8220  8365  8510  8655]
 [11850 12095 12340 12585 12830 13075 13320 13565 13810 14055]
 [16350 16695 17040 17385 17730 18075 18420 18765 19110 19455]
 [20850 21295 21740 22185 22630 23075 23520 23965 24410 24855]
 [25350 25895 26440 26985 27530 28075 28620 29165 29710 30255]
 [29850 30495 31140 31785 32430 33075 33720 34365 35010 35655]
 [34350 35095 35840 36585 37330 38075 38820 39565 40310 41055]
 [38850 39695 40540 41385 42230 43075 43920 44765 45610 46455]
 [43350 44295 45240 46185 47130 48075 49020 49965 50910 51855]]
```

I would like some help with writing tests for this please. I'm not quite sure where to start; there seems to be a bit of testing mental overhead that I'm not familiar with. Would one of you be kind enough to guid me through please?

### CODE REVIEW

**Comment by asi1024** [comment]
Thanks for the PR!

Please add the unit test here: tests/cupy_tests/linalg_tests/test_product.py
The testing utilities are documented here: https://docs-cupy.chainer.org/en/latest/reference/testing.html

Thanks!

**Comment by ericmjl** [comment]
Added on test, and they pass!

```bash
$ pytest test_product.py
============================ test session starts ============================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/maer3/github/software/cupy, inifile: setup.cfg
plugins: hypothesis-3.38.5
collected 187 items

test_product.py ..................................................... [ 28%]
..................................................................... [ 65%]
.................................................................     [100%]

======================== 187 passed in 15.83 seconds ========================
```

**Comment by ericmjl** [comment]
Investigating why this one failed.

**Comment by ericmjl** [comment]
@asi1024 I believe the test passes! Please do let me know if you'd like me to elaborate on the test, by adding more complicated ones.

**Comment by asi1024** [comment]
Thanks!
Could you add some more tests, for instance the case for n >= 3, n = 0 or n < 0?

**Comment by asi1024** [comment]
@ericmjl Thanks!
Could you add some more tests, for instance the case for n >= 3, n = 0 or n < 0?

**Comment by ericmjl** [comment]
@asi1024 Done! Thank you for the reminder; through further testing, I discovered that this current `matrix_power` implementation can only accept float32 and float64 dtype arrays. I did not want to implicitly convert a user's array dtypes, therefore I documented this behaviour in the `matrix_power` docstring.

**Comment by ericmjl** [comment]
@asi1024 thank you for your help with this PR! 

(I don't know Japanese, so my best attempt at saying thank you in Japanese has to come from Google Translate: どうもありがとうございました！😸)

**Comment by asi1024** [comment]
The update of .gitignore is not related to this PR.  Could you please split into several PRs?

**Comment by ericmjl** [comment]
Ok!

**Comment by ericmjl** [comment]
All done!

**Comment by ericmjl** [comment]
Oh my, my git-fu is not good enough to handle this. Would you be kind enough to point out how I can make this happen? I'd like to learn along the way too.

**Comment by ericmjl** [comment]
If need be, I can redo this PR from scratch, not an issue.

**Comment by ericmjl** [comment]
ARRGGGHHH!!!! I think I will redo this PR from scratch. Many apologies, @asi1024 @kmaehashi.

**Comment by kmaehashi** [comment]
Could you try this?

```
git fetch https://github.com/cupy/cupy.git master:upstream-master
git checkout -b matrix_power-2 upstream-master
wget "https://patch-diff.githubusercontent.com/raw/cupy/cupy/pull/1363.diff"
patch -p1 < 1363.diff
# then, git add, commit & push
```

**Pull request closed without merging**
