### PR TITLE
Use cython.no_gc to avoid memory leak

### LINKED ISSUE #1461: Fix memory leak in Python 3.7
The tentative fix is made in #1457 for Python 3.7, but it leaks memory.

```py
import cupy
import gc

def func():
    try:
        a = cupy.ones((1000,1000)).reshape(1000,1000)
        raise RuntimeError
    except Exception as e:
        err = e


func()
print(cupy.get_default_memory_pool().used_bytes())
print(gc.collect())
print(cupy.get_default_memory_pool().used_bytes())
```

### PR DESCRIPTION
**Pull request by okuta**
Fix #1461. This PR uses [cython.no_gc](https://github.com/cython/cython/blob/master/docs/src/userguide/extension_types.rst#controlling-cyclic-garbage-collection-in-cpython).
rel #1457

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by kmaehashi** [comment]
@okuta As far as I understand,

* `no_gc_clear`: Cython skips `tp_clear` (i.e., for immutables)
* `no_gc`: Cython skips both `tp_traverse` and `tp_clear` (i.e., for container class only holding atomic types)

so we should use `no_gc_clear` instead to avoid leaking `device`?

**Comment by kmaehashi** [comment]
Refs #946

**Comment by okuta** [comment]
Yes, We can wait merging #946. But, This object has no cyclic reference.
Cython default is defensive because there are no information about cyclic reference.

**Comment by kmaehashi** [comment]
Ah, sorry I got wrong. LGTM.

**Pull request merged**
