### PR TITLE
[backport] Rename `cupy.core` submodule to `cupy._core`

### PR DESCRIPTION
**Pull request by asi1024**
Backport of #3820

### CODE REVIEW

**Comment by asi1024** [comment]
[automatic post] Jenkins, test this please.

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by takagi** [comment]
Passing pfn-public-ci/cupy.py3.amd is now required?

**Comment by kmaehashi** [comment]
> Passing pfn-public-ci/cupy.py3.amd is now required?

Please wait until https://github.com/cupy/cupy/pull/4976, https://github.com/cupy/cupy/pull/4982 and its backport got merged.

**Comment by takagi** [comment]
Okay, thanks!

**Comment by kmaehashi** [comment]
Dependent PRs are merged! Could you rebase? :pray:

**Comment by takagi** [comment]
Jenkins, test this please.

**Pull request merged**
