### PR TITLE
[backport] Update installation guide for cuTENSOR on Conda-Forge

### PR DESCRIPTION
**Pull request by kmaehashi**
Backport of #4614

### CODE REVIEW

**Comment by kmaehashi** [comment]
[automatic post] Jenkins, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI pass.

**Comment by leofang** [comment]
Looks like mergify does not like the Windows CI? 😂

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by takagi** [comment]
Merged!

**Pull request merged**
