### PR TITLE
Avoid creating empty numpy ndarray in `common_type`

### PR DESCRIPTION
**Pull request by asi1024**
Fixed to use `numpy.find_common_type`

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
The logic (return value and return type) is changed. Can you really do this sort of substitution?
```python
a = np.empty((), dtype='int64')
np.common_type(a)  # numpy.float64 which is a `numpy.dtype`
np.find_common_type([a.dtype], [])  # dtype('int64') which is a `type`
```

**Comment by asi1024** [comment]
@hvy PTAL.

**Comment by hvy** [comment]
It's not just the type but the dtypes also differ.

**Comment by hvy** [comment]
Are there alternatives or should we close this ticket?

**Comment by asi1024** [comment]
Currently, `testing.numpy_cupy_equals` does not support `accept_error`, so I added a new test for the exception.

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
Thanks for the fixed, LGTM!

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
CI failure in unrelated, LGTM!

**Pull request merged**
