### PR TITLE
Move `matmul` from `core.pyx` to `_routine_linalg.pyx`

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by emcastillo** [comment]
Seems that #3994 got merged first 😞
Can you rebase?

**Comment by asi1024** [comment]
Rebased.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
as the dependent PR was merged, let's not backport this

**Comment by asi1024** [comment]
#3994 is backported to v8, so we can backport this PR.

**Pull request merged**
