### PR TITLE
Remove fallback mode

### PR DESCRIPTION
**Pull request by asi1024**
Close https://github.com/cupy/cupy/issues/8497.
Removes `cupyx.fallback` in CuPy v14.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks! How about removing it in v14 as we don't see any negative responses in #8497?

**Comment by asi1024** [comment]
I agree. Fixed to remove all `cupyx.fallback` module.

**Comment by kmaehashi** [comment]
Looks good, thanks!

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
