### PR TITLE
[backport] Refactor array creation for RNN API

### PR DESCRIPTION
**Pull request by okuta**
Backport of #1842

### CODE REVIEW

**Comment by okuta** [comment]
[automatic post] Jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
@unnonouno Could you merge this?

**Comment by kmaehashi** [comment]
Closing as v5 branch has been freezed.

**Pull request closed without merging**
