### PR TITLE
Fix bug about empty coo_matrix

### PR DESCRIPTION
**Pull request by unnonouno**
I found a bug about coo_matrix. It does not work correctly when it is empty.
merge #316 first

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please

**Comment by okuta** [comment]
jenkins, test this please

**Comment by okuta** [comment]
jenkins, test this please again

**Comment by okuta** [comment]
jenkins, test this please again

**Comment by takagi** [comment]
LGTM! CI failed but it is because of an unstable deconvolution_2d test, which is to be fixed in https://github.com/chainer/chainer/pull/3107 .

**Pull request merged**
