### PR TITLE
Document more environment variables

### LINKED ISSUE #661: Some environment variables are undocumented
Currently some environment variables like `CUPY_SEED` are not documented.

### PR DESCRIPTION
**Pull request by leofang**
Closes #661. As per requested in https://github.com/cupy/cupy/issues/661#issuecomment-524750781. 

All of the env variables are searched via `grep --include=\*.{pyx,pxd,pxi,py} -R './' -e 'CUPY_'`. Except for `CUB_PATH` and `CUB_DISABLED` (to be discussed with CuPy core devs, see https://github.com/cupy/cupy/pull/2562#issuecomment-548390938), I hope I am not missing anything.

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
@emcastillo how about `CUB_PATH` and `CUB_DISABLED`? They are relevant to https://github.com/cupy/cupy/pull/2562#issuecomment-548390938. Did you guys happen to discuss it internally already?

**Comment by emcastillo** [comment]
Lets send a different PR once CUB is integrated in a stable way.

**Comment by leofang** [comment]
Sounds good. Thanks.

**Pull request merged**
