### PR TITLE
Support NumPy 1.24: `dtype` and `casting` keyword arguments for `hstack`, `vstack`, `stack`

### PR DESCRIPTION
**Pull request by tysonwu**
Following the items listed in #7250, adding `dtype` and `casting` keyword arguments for `hstack`, `vstack`, `stack`.

The addition of these kwargs should not make CuPy incompatible with NumPy versions before 1.24, as the under-the-hood `concatenate` supports these two kwargs since NumPy 1.20.

### CODE REVIEW

**Comment by takagi** [comment]
Thanks for your work! Your implementation looks fine. Although the `stack` family just wraps `concatenate`, we'd like to have tests for the new arguments. Can I ask you to make it have such tests? You can find the current tests here:
https://github.com/cupy/cupy/blob/main/tests/cupy_tests/manipulation_tests/test_join.py

**Comment by tysonwu** [comment]
Thanks for the review. I have added the tests for dtype and casting options accordingly.

**Comment by takagi** [comment]
Let me merge this PR as the CI failures are not related here. Thanks, @tysonwu!

**Pull request merged**
