### PR TITLE
Implement RawKernel

### PR DESCRIPTION
**Pull request by kmaehashi**
~`SimpleKernel`~ `RawKernel` is intended to expose public API to bring in raw CUDA kernel code to CuPy world.
This is one of the frequently requested feature (#1258, #1242, etc.).

Currently it is just a thin wrapper around `cupy.core.compile_with_cache` with automatic per-device memoize. We'd like to discuss the design of SimpleKernel.

After that, I should:

- [x] write documentation
- [x] add tests

### CODE REVIEW

**Comment by kmaehashi** [comment]
One consideration is that this feature exposes another route to use Driver API without implicit CUDA context (ref #916). I think it can be ignored though.

```py
import cupy

kern = cupy.SimpleKernel(r'''
extern "C" __global__
void test() {
    printf("Hello world\n");
}
''', 'test')

cupy.cuda.Device(0).use()
kern((1,), (1,), ())
cupy.cuda.Stream.null.synchronize()

cupy.cuda.Device(1).use()
# cupy.cuda.runtime.memGetInfo()  # uncomment to avoid FAIL
kern((1,), (1,), ())  # FAIL
cupy.cuda.Stream.null.synchronize()
```

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    kern((1,), (1,), ())
  File "cupy/core/simple.pxi", line 23, in cupy.core.core.SimpleKernel.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/simple.pxi", line 29, in cupy.core.core._get_simple_kernel
  File "cupy/core/carray.pxi", line 146, in cupy.core.core.compile_with_cache
  File "/home/kenichi/Development/cupy/cupy/cuda/compiler.py", line 165, in compile_with_cache
    ls = function.LinkState()
  File "cupy/cuda/function.pyx", line 195, in cupy.cuda.function.LinkState.__init__
  File "cupy/cuda/driver.pyx", line 139, in cupy.cuda.driver.linkCreate
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_CONTEXT_IS_DESTROYED: context is destroyed
```

**Comment by okuta** [comment]
Please use `simple.pyx` instead of `simple.pxi`.

**Comment by kmaehashi** [comment]
I discussed offline with @okuta -san regarding other design considerations:

* Regarding the class name
    * I decided to rename it from `SimpleKernel` to `RawKernel`.
      We'll reserve the name `Simple` for future, e.g., with more high-level kernels like automatic Indexer support for array arguments.
* Regarding including CuPy-specific headers
    * As the primary target users of `RawKernel` is those who intend to bring-in raw CUDA source to CuPy, I decided not to include CuPy-specific headers to avoid unexpected conflict. Users can still (unofficially) import such headers by their own, though.

**Comment by kmaehashi** [comment]
This PR is ready for review.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
