### PR TITLE
Add `ptp` ndarray method and function

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds `ptp` (peak-to-peak). 

I have included a `dtype` argument to make it consistent with CuPy's min & max (which `ptp` calls internally), but this argument is not present in the NumPy API. If preferred it can be removed (I wasn't sure what the reasoning for its inclusion was).

Also, unlike `amin` or `amax`, `ptp` as implemented here does not currently support Fusion. I haven't looked at the Fusion code implementation, so am not sure how easy it might be to support? The current implementation calls both `_amin` and `_amax` ufuncs rather than implementing its own separate reduction kernel, so there was not a single kernel to point to as done in the `amin` function I looked at as a reference.

Finally, should we also check explicitly for `bool` dtype and raise a TypeError in that case to match NumPy's behavior?

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for the PR!
I think there's no point to have `dtype` argument. Could you remove it?
As for `bool`, it's `-=` that should raise an error. I think it's fine not to check it in `ptp`.

**Comment by grlee77** [comment]
I have now updated without the dtype argument

**Comment by niboshi** [comment]
Thanks. Jenkins, test this please

**Comment by grlee77** [comment]
Older NumPy apparently did not support `keepdims` or a tuple of axes. Please try again now.

**Comment by niboshi** [comment]
Thanks! Jenkins, test this please

**Comment by niboshi** [comment]
👍

**Pull request merged**
