### PR TITLE
Support Python 3.12, add Windows CI

### PR DESCRIPTION
**Pull request by kmaehashi**
Part of #7899

- Update Python versions used in Windows CI
- Add classifier
- Update docs

I'm now installing Python 3.12 to Windows CI image... ⏳ -> Done

### CODE REVIEW

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
FYI: SciPy issue found in this PR upstreamed as https://github.com/scipy/scipy/issues/19423

**Pull request merged**
