### PR TITLE
Rename submodules under `cupyx.linalg` package

### PR DESCRIPTION
**Pull request by takagi**
Rel #3420.

This PR renames the submodules under `cupyx.linalg` to indicate that they are CuPy's private submodules and not intended to be used by users.

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Could you resolve conflicts?

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
