### PR TITLE
[backport] improve error message when import failed

### PR DESCRIPTION
**Pull request by niboshi**
Backport of #970

### CODE REVIEW

**Comment by kmaehashi** [comment]
As we don't have wheels for v3, I think no backport is necessary.

**Comment by niboshi** [comment]
I thought the link to the installation guide may be beneficial.
How do you think?

**Comment by niboshi** [comment]
(I also think the page it points to should have been stable documentation.)

**Comment by kmaehashi** [comment]
> I thought the link to the installation guide may be beneficial.

OK, I agree with that.

> (I also think the page it points to should have been stable documentation.)

By the way, what should we do when we release new major version?
I want to avoid replacing `latest` to `stable` in all URLs in `v4` branch when we release v4 (i.e. create `v4` branch from `master`).
I guess it's better to always use `stable` even in master branch (as we can say that master branch is "under development of stable version").

**Comment by niboshi** [comment]
Yes, that's exactly what I was thinking.
But I want a consensus as a team.

**Comment by kmaehashi** [comment]
OK. I'll merge this for now.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
