### PR TITLE
Fix `ascontiguousarray` with 0-dim array input

### LINKED ISSUE #1246: cupy.ascontiguousarray behavior different from numpy
```py
>>> np.ascontiguousarray(np.array(3))
array([3])
>>> cp.ascontiguousarray(cp.array(3))
array(3)
```

### PR DESCRIPTION
**Pull request by okuta**
Fix #1246

### CODE REVIEW

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
```
% git grep asfortranarray cupy
cupy/__init__.py:from cupy.manipulation.kind import asfortranarray  # NOQA
cupy/core/__init__.py:from cupy.core.core import asfortranarray  # NOQA
cupy/core/core.pyx:                        a_gpu = asfortranarray(self)
cupy/core/core.pyx:                        a_gpu = asfortranarray(self)
cupy/core/core.pyx:            arr = numpy.asfortranarray(arr)
cupy/core/core.pyx:cpdef ndarray asfortranarray(ndarray a, dtype=None):
cupy/cusparse.py:    x = cupy.asfortranarray(x)
cupy/cusparse.py:    x = cupy.asfortranarray(x)
cupy/fft/fft.py:        a = cupy.asfortranarray(a)
cupy/linalg/solve.py:    a = cupy.asfortranarray(a)
cupy/linalg/solve.py:    b = cupy.asfortranarray(b)
cupy/manipulation/kind.py:def asfortranarray(a, dtype=None):
cupy/manipulation/kind.py:    .. seealso:: :func:`numpy.asfortranarray`
cupy/manipulation/kind.py:    return core.asfortranarray(a, dtype)
% git grep ascontiguousarray cupy
cupy/__init__.py:from cupy.creation.from_data import ascontiguousarray  # NOQA
cupy/core/__init__.py:from cupy.core.core import ascontiguousarray  # NOQA
cupy/core/core.pxd:cpdef ndarray ascontiguousarray(ndarray a, dtype=*)
cupy/core/core.pyx:                        a_gpu = ascontiguousarray(self)
cupy/core/core.pyx:                        a_gpu = ascontiguousarray(self)
cupy/core/core.pyx:            arr = numpy.ascontiguousarray(arr)
cupy/core/core.pyx:cpdef ndarray ascontiguousarray(ndarray a, dtype=None):
cupy/core/core.pyx:    a = ascontiguousarray(a, dtype)
cupy/core/core.pyx:    b = ascontiguousarray(b, dtype)
cupy/creation/from_data.py:def ascontiguousarray(a, dtype=None):
cupy/creation/from_data.py:    .. seealso:: :func:`numpy.ascontiguousarray`
cupy/creation/from_data.py:    return core.ascontiguousarray(a, dtype)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    ys = core.ascontiguousarray(ys)
cupy/cudnn.pyx:    dhy = core.ascontiguousarray(dhy)
cupy/cudnn.pyx:        dcy = core.ascontiguousarray(dcy)
cupy/cudnn.pyx:    dys = core.ascontiguousarray(dys)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:    ys = core.ascontiguousarray(ys)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    y = core.ascontiguousarray(y)
cupy/cudnn.pyx:    gy = core.ascontiguousarray(gy)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    y = core.ascontiguousarray(y)
cupy/cudnn.pyx:    gy = core.ascontiguousarray(gy)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:        cx = core.ascontiguousarray(cx)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    ys = core.ascontiguousarray(ys)
cupy/cudnn.pyx:    dhy = core.ascontiguousarray(dhy)
cupy/cudnn.pyx:        dcy = core.ascontiguousarray(dcy)
cupy/cudnn.pyx:    dys = core.ascontiguousarray(dys)
cupy/cudnn.pyx:    xs = core.ascontiguousarray(xs)
cupy/cudnn.pyx:    hx = core.ascontiguousarray(hx)
cupy/cudnn.pyx:    ys = core.ascontiguousarray(ys)
cupy/cudnn.pyx:    w = core.ascontiguousarray(w)
cupy/cudnn.pyx:        x = core.ascontiguousarray(x)
cupy/cudnn.pyx:        dy = core.ascontiguousarray(dy)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    W = core.ascontiguousarray(W)
cupy/cudnn.pyx:            b = _manipulation._reshape(core.ascontiguousarray(b), b_shape)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    gy = core.ascontiguousarray(gy)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    W = core.ascontiguousarray(W)
cupy/cudnn.pyx:            b = _manipulation._reshape(core.ascontiguousarray(b), b_shape)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    gy = core.ascontiguousarray(gy)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:            gamma = core.ascontiguousarray(gamma)
cupy/cudnn.pyx:            beta = core.ascontiguousarray(beta)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:            gamma = core.ascontiguousarray(gamma)
cupy/cudnn.pyx:            beta = core.ascontiguousarray(beta)
cupy/cudnn.pyx:    x = core.ascontiguousarray(x)
cupy/cudnn.pyx:    gy = core.ascontiguousarray(gy)
cupy/cudnn.pyx:            gamma = core.ascontiguousarray(gamma)
cupy/fft/fft.py:            a = cupy.ascontiguousarray(a)
cupy/fft/fft.py:        a = cupy.ascontiguousarray(a)
cupy/statistics/order.py:    return cupy.ascontiguousarray(ret)
```

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
Note:
For example, the PR keeps `cupy/linalg/solve.py` because the inputs are at least 1 dim.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
