### PR TITLE
Skip some failing tests for fp16 + CUDA 9.0

### LINKED ISSUE #4254: `ndarray.max()` does not call CUB in some conditions
As mentioned in #4232, a daily test fails where `ndarray.max()` does not call `cupy.core._routines_statistics.cub.device_segmented_reduce` for some reasons.

https://jenkins.preferred.jp/job/chainer/job/daily_master_cupy-shuffled/378/ID=20,label=mn1-p100/

The following shows the condition of the daily shuffle test.

```
11:22:17 + ./run_cupy_combination_test.py --id 20
11:22:17 --- Shuffle Parameters ---
11:22:17 cuda_libs: ('cuda90', 'cudnn73-cuda9', 'nccl2.4-cuda9', 'none')
11:22:17 scipy: None
11:22:17 base: ubuntu16_py35
11:22:17 numpy: 1.18
11:22:17 --- Configuration ---
11:22:17 nccl: nccl2.4-cuda9
11:22:17 cutensor: none
11:22:17 cudnn: cudnn73-cuda9
11:22:17 base: ubuntu16_py35
11:22:17 cuda: cuda90
11:22:17 requires: ['numpy<1.19']
11:23:55 sha256:28646ab8950d2c4793c87a7631006aa0a7c063fd6ba98cfeef674f1c0dff3798
```

### PR DESCRIPTION
**Pull request by leofang**
Close #4254. See the discussion there.

cc: @toslunar

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
I'll check if the combination test on #4254 passes on my local before merging this PR.

**Comment by takagi** [comment]
I've checked that this change works with the shuffle test condition, LGTM!

**Comment by leofang** [comment]
Awesome!!!

**Pull request merged**
