### PR TITLE
Add a warning for `sum_duplicates`

### PR DESCRIPTION
**Pull request by leofang**
Follow up of https://github.com/cupy/cupy/pull/3620#issuecomment-659935352. 

~~TODO: I wanna make sure only coo is impacted.~~

### CODE REVIEW

**Comment by leofang** [comment]
> TODO: I wanna make sure only coo is impacted.

I think it is. Because when constructing CSC/CSR, the indices are always sorted.

**Comment by leofang** [comment]
I added a test to ensure the sorting order is not changed again. (CuPy originally followed SciPy, @anaruse corrected it in #3129, I reverted it in #3509, and finally @anaruse caught it in #3620 😅)

**Comment by leofang** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Done, PTAL.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by leofang** [comment]
Thanks!

**Pull request merged**
