### PR TITLE
 Add dtype, fweights, aweights to cupy.cov

### LINKED ISSUE #6383: Support `dtype` argument in `cupy.corrcoef` and `cupy.cov`
### Description

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

https://docs.cupy.dev/en/stable/reference/generated/cupy.corrcoef.html

Seems args are different

### Additional Information

`dtype` argument added in NumPy version 1.20.

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #6383 

This is a revival of #6401, which applies the last comments that @emcastillo left.

### CODE REVIEW

**Comment by emcastillo** [comment]
Test failures seem to be real

**Comment by leofang** [comment]
Can we please not bump Jitify in this PR? Is it needed?

**Comment by emcastillo** [comment]
@andfoy sorry, could you take a look at the test failures?

https://ci.preferred.jp/cupy.linux.cuda102/106932/

let us know if you don't understand any of these :)

Thanks!

**Comment by andfoy** [comment]
The test failures are unrelated, as they are NCCL-related

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
