### PR TITLE
Skip test_pos_boolarray if numpy>=1.25

### PR DESCRIPTION
**Pull request by asi1024**
Close https://github.com/cupy/cupy/issues/7884.
Part of https://github.com/cupy/cupy/issues/7616.

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
71 Errors!

**Comment by leofang** [comment]
> 71 Errors!

What happened? lol

**Comment by emcastillo** [comment]
there were 117 previously! so the error amount is reduced now 😂

**Comment by leofang** [comment]
What's special about the "head" CI? I guess I missed something.

**Comment by asi1024** [comment]
@leofang head CI is a test with the latest supported versions of NumPy and SciPy.

https://ci.preferred.jp/cupy.linux.cuda-head/144947/#L155

We are currently working on support for NumPy 1.25, 1.26 and SciPy 1.11, and this PR has reduced the number of test failures of head CI!

**Pull request merged**
