### PR TITLE
Drop support for Python 3.6

### LINKED ISSUE #5699: [RFC] Drop Python 3.6 support in v10
We are now discussing to drop support for Python 3.6 in CuPy v10. Feel free to leave a comment here if you have any concerns.

Background:
* CUDA Python is unlikely to provide a wheel for Python 3.6, although it can be built from the source without any issue. CUDA Python currently requires [`-std=c++14`](https://github.com/NVIDIA/cuda-python/blob/427c597959e6fe1409195a30d42fc4a1886bc89a/setup.py#L38) so recent versions of gcc, which is not in RHEL/CentOS 7 by default, is needed. We want to avoid requiring CuPy wheel users to manually install non-default GCC.
* NumPy dropped Python 3.6 support in June 2020: https://numpy.org/neps/nep-0029-deprecation_policy.html
* Python 3.6 support become EOL in December 2021.

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #5699.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Review by asi1024 — APPROVED** [review]

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

Will trigger FlexCI after image rebuild: https://ci.preferred.jp/cupy.prep-linux/79597/

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

Will trigger FlexCI after image rebuild: https://ci.preferred.jp/cupy.prep-linux/79613/

**Comment by kmaehashi** [comment]
All tests passed except for `cupy-py36` (which is expected).
I'll exclude running `cupy-py36` for master branch after this PR got merged.

**Comment by asi1024** [comment]
All tests passed except for cupy-py36.

**Pull request merged**
