### PR TITLE
added cupy.searchsorted function

### PR DESCRIPTION
**Pull request by Onkar627**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Hi @Onkar627, please confirm that CuPy builds fine in your local machine before submitting a pull-request, as described in [`Steps to Contribute`](https://github.com/cupy/cupy/issues/6078),

**Comment by Onkar627** [comment]
> Hi @Onkar627, please confirm that CuPy builds fine in your local machine before submitting a pull-request, as described in [`Steps to Contribute`](https://github.com/cupy/cupy/issues/6078),

Yes sure @kmaehashi.Can you guide me on how to go through it, it would be a great help.:)

**Comment by emcastillo** [comment]
https://docs.cupy.dev/en/latest/install.html#installing-cupy-from-source

**Comment by emcastillo** [comment]
do not rename the core files, please

**Comment by Onkar627** [comment]
> do not rename the core files, please

Yes, sure.

**Comment by kmaehashi** [comment]
Please reopen when it becomes review ready.

**Pull request closed without merging**
