### PR TITLE
Fix overfow in `matmul` test

### LINKED ISSUE #2334: Overflow warning in CI
https://jenkins.preferred.jp/job/chainer/job/cupy_pr/210/TEST=cupy-py3,label=mn1-p100/console
```
15:02:17 tests/cupy_tests/math_tests/test_matmul.py::TestMatmulLarge_param_0::test_cupy_matmul
15:02:17   /work/cupy/tests/cupy_tests/math_tests/test_matmul.py:136: RuntimeWarning: overflow encountered in matmul
15:02:17     return xp.matmul(x1, x2)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_matmul.py::TestMatmulLarge_param_0::test_operator_matmul
15:02:17   /work/cupy/tests/cupy_tests/math_tests/test_matmul.py:123: RuntimeWarning: overflow encountered in matmul
15:02:17     return operator.matmul(x1, x2)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_misc.py::TestMisc::test_nan_to_num_inf
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/numeric.py:2510: RuntimeWarning: overflow encountered in absolute
15:02:17     return less_equal(abs(x-y), atol + rtol * abs(y))
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_misc.py::TestMisc::test_nan_to_num_inf_nan
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/numeric.py:2510: RuntimeWarning: overflow encountered in absolute
15:02:17     return less_equal(abs(x-y), atol + rtol * abs(y))
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_sumprod.py::TestSumprod::test_sum_all2
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
15:02:17     return umr_sum(a, axis, dtype, out, keepdims, initial)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_sumprod.py::TestSumprod::test_sum_all_transposed2
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
15:02:17     return umr_sum(a, axis, dtype, out, keepdims, initial)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_sumprod.py::TestSumprod::test_sum_axes2
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
15:02:17     return umr_sum(a, axis, dtype, out, keepdims, initial)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_sumprod.py::TestSumprod::test_sum_axes4
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
15:02:17     return umr_sum(a, axis, dtype, out, keepdims, initial)
15:02:17 
15:02:17 tests/cupy_tests/math_tests/test_sumprod.py::TestSumprod::test_sum_axis_transposed2
15:02:17   /opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
15:02:17     return umr_sum(a, axis, dtype, out, keepdims, initial)
```

### PR DESCRIPTION
**Pull request by niboshi**
Fixes  #2334

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
`Not equal to tolerance rtol=0.001, atol=0.001` :pensive:

**Comment by niboshi** [comment]
Hm, how can I fix this? 🤔
Adjusting tolerances?

**Comment by niboshi** [comment]
Fixed by using `shaped_random` instead of `shaped_arange`.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
/test
Testing again using the latest master.

cc/ @toslunar

**Pull request merged**
