### PR TITLE
ENH: cupyx/scipy/signal: add unique_roots, invres{z}, residue{z}

### PR DESCRIPTION
**Pull request by ev-br**
`scipy.signal` version uses `scipy.spatial.KDTree`; here we loop over the points manually instead. The inputs are most likely to be small, so there is not much need to seriously optimize performance. 

Also add 
- [x] unique_roots
- [x] invres
- [x] invresz
- [x] residue
- [x] residuez

cross-ref https://github.com/cupy/cupy/issues/7403

### CODE REVIEW

**Comment by ev-br** [comment]
Apparently, pytest requires test file names to be unique across the project, and `cupyx_tests/scipy_tests/signal_tests/test_polyutils.py` was clashing with `tests/cupy_tests/polynomial_tests/test_polyutils.py`. So renamed the former into `test_polyutils_.py` and rebased on main.

**Comment by takagi** [comment]
Seems that we've got to have `__init__.py` in the same directory with `cupyx_tests/scipy_tests/signal_tests/test_polyutils.py` to make pytest recognize it as part of a package.
https://docs.pytest.org/en/latest/explanation/pythonpath.html

I understand renaming works, but would like to prefer `test_polyutils.py`. Would you make it as such?

**Comment by ev-br** [comment]
OK, done.

**Review by takagi — APPROVED** [review]
LGTM! CI failures are not related and is to be handled elsewhere.

**Comment by takagi** [comment]
Thanks, @ev-br!

**Pull request merged**
