### PR TITLE
Add repr of parameterized test and stop adding error message

### LINKED ISSUE #3915: `cupy.testing.parameterze` does not work when Exception requiring arguments more than one
Currently `cupy.testing.parameterze` assumes that exceptions are always constructible with one string argument, but this is not always true (e.g., `scipy.sparse.linalg.ArpackNoConvergence`).

- Fix the `cupy.testing.parameterze` to work with exceptions whose constructor require more than one argument, OR
- Rewrite it as a wrapper for `pytest.mark.parameterize`

cc/ @asi1024 @toslunar

### PR DESCRIPTION
**Pull request by toslunar**
chainer/chainer#3661 started editing exceptions of test failures because PyTest does not print str(self), while Nosetests does. However, it should have been utilized that PyTest shows repr of local variables.

Fixes #3915.

<details><summary>before</summary>

```
__________________________ TestA_param_0_{x=1}.test_a __________________________

self = <cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>, args = ()
kwargs = {}, s = <_io.StringIO object at 0x7fdb15dc5ee0>, k = 'x', v = 1
err_class = <class 'AssertionError'>

    @functools.wraps(base_method)
    def new_method(self, *args, **kwargs):
        try:
>           return base_method(self, *args, **kwargs)

../cupy/testing/parameterized.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = <cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>.x

test_tmp.py:11: AssertionError

During handling of the above exception, another exception occurred:

self = <cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: Parameterized test failed.
E
E       Base test method: TestA.test_a
E       Test parameters:
E         x: 1

test_tmp.py:11: AssertionError
```
</details>
<details><summary>after</summary>

```
__________________________ TestA_param_0_{x=1}.test_a __________________________

self = <<cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>  parameter: {'x': 1}>

    def test_a(self):
        """This is test_a"""
>       assert self.x == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = <<cupy.testing._bundle.TestA_param_0_{x=1} testMethod=test_a>  parameter: {'x': 1}>.x

test_tmp.py:11: AssertionError
```
</details>

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
After this PR is merged, `method_generator` in the following line will be always an identity function. Let's make a code simplification in another PR.
https://github.com/cupy/cupy/blob/a95f3f0a98e6e04dc266992abd41f51862903e54/cupy/testing/_bundle.py#L31

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
