### PR TITLE
Scipy sparse requires numpy>=1.10

### PR DESCRIPTION
**Pull request by okuta**
Chainer test is failed on numpy==1.9 environment.

### CODE REVIEW

**Comment by kmaehashi** [comment]
I guess you are using NumPy 1.9.x + SciPy 0.18.x on Python 3.6.
`scipy-0.18.1-cp36-cp36m-manylinux1_x86_64.whl` is linked against NumPy API version 1.10, instead of 1.9, because NumPy 1.9 does not support Python 3.5+; in that case `import scipy.sparse` fails with strange error.

See also: https://github.com/chainer/chainer-test/pull/383

**Comment by okuta** [comment]
OK, I will fix this PR.

**Comment by kmaehashi** [comment]
Do you think we should take care of version matrix unsupported by NumPy/SciPy (e.g., NumPy 1.9.x on Python 3.6)? (If yes, I need to fix https://github.com/chainer/chainer-test/pull/383)

**Comment by unnonouno** [comment]
I don't think it is good idea to skip when `import` fails. In this situation the problem is in the environment that has inconsistent combination of numpy and scipy, not in the test code. For a developer who uses such a environment, the test itself is skipped by your fix and he/she doesn't notice the error.

**Comment by okuta** [comment]
This problem will be solved by fixing chainer-test.

**Pull request closed without merging**
