### PR TITLE
Add CubicHermiteSpline to cupyx.scipy.interpolate

### PR DESCRIPTION
**Pull request by andfoy**
See https://github.com/cupy/cupy/issues/7186

### CODE REVIEW

**Comment by andfoy** [comment]
@takagi, this one is ready for review! We need to merge this one first before merging the `pchip` and the `akima` ones, respectively

**Comment by takagi** [comment]
note: `CubicHermiteSpline` is derived from `PPoly`, so we may refer to it for its benchmark.
https://github.com/cupy/cupy/pull/7204#issuecomment-1352117803

**Comment by takagi** [comment]
Thanks! Just confirmation, `CubicHermiteSpline` finds its coefficients by means of the given `y` and `dydx` only?

**Review by takagi — APPROVED** [review]
LGTM!

**Comment by andfoy** [comment]
Yes, the coefficients are derived from `x`, `y` and `dydx` directly on the constructor

**Comment by takagi** [comment]
Let me merge this PR. The CI failures should be fixed by #7262.

**Comment by takagi** [comment]
Thanks, @andfoy!

**Pull request merged**
