### PR TITLE
Matrix power v2

### LINKED ISSUE #1358: matrix power is missing from cupy.linalg.
There is a corresponding `numpy.linalg.matrix_power` in NumPy. Is there a reason why this has not made it into CuPy?

If it helps, I am willing to take a shot at this one, though I might need a bit of hand-holding as I've not much experience with Cython code.

### PR DESCRIPTION
**Pull request by ericmjl**
Replaces/closes #1363 and closes #1358.

### CODE REVIEW

**Comment by ericmjl** [comment]
cc @asi1024 and @kmaehashi. My apologies I could not figure out how to do the git rebase properly. This version has a much, much cleaner git history.

**Comment by kmaehashi** [comment]
Thanks!
Jenkins, test this please.

**Comment by ericmjl** [comment]
Looks like a random failure on Python 3.4?

**Comment by ericmjl** [comment]
Hmmm... coveralls failed here. Is there anything I can do about this?

**Comment by ericmjl** [comment]
Oh my, I did something wrong again with my commit history...

**Pull request closed without merging**
