### PR TITLE
Document `CFunctionAllocator` and `ManagedMemory`

### PR DESCRIPTION
**Pull request by leofang**
I think it'd be good to expand the memory management documentation, but before that let's make them appear in the index first.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Do you come up with any usecase for `CFunctionAllocator`? It was originally implemented for ChainerX but I guess no one is using it now.

**Comment by leofang** [comment]
For now it's mostly for completeness:
allocate memory | from CuPy via C | from CuPy via Python | from external via C | from external via Python
---|---|---|---|---
method | N/A (see #3212) | `cupy.cuda.alloc` | `cupy.cuda.CFunctionAllocator` | `cupy.cuda.PythonFunctionAllocator`

In the near future there might be C libraries wanting to share the same memory pool with CuPy (ex: nvJPEG2000, in which there is a [device allocator interface](https://docs.nvidia.com/cuda/nvjpeg2000/userguide.html#device-allocator-interface)). If "from CuPy via C" is not available, at least they can do it in the reverse direction using `CFunctionAllocator`.

**Comment by kmaehashi** [comment]
Thanks for the clarification!

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
