### PR TITLE
Add `cached_code` to `ElementwiseKernel` and `ReductionKernel`

### LINKED ISSUE #1243: Provide method to return CUDA source from user-defined kernels
Sometimes I want to see CUDA source generated by user-defined kernels.
It should help users to understand how to write custom kernels, especially when `preamble`, `loop_prep`, etc. is involved.

### PR DESCRIPTION
**Pull request by emcastillo**
Closes  #1243 #6969

### CODE REVIEW

**Comment by asi1024** [comment]
@emcastillo Could you compare the performance of ReductionKernel? I am concerned about the performance degradation because `_AbstractReductionKernel.get_function` is called from `ReductionKernel.__call__`.

**Comment by emcastillo** [comment]
This PR
```
my_sum              :    CPU:    28.064 us   +/-  0.883 (min:    26.911 / max:    89.833) us     GPU-0:    31.977 us   +/-  1.104 (min:    30.432 / max:    94.144) us
my_sum              :    CPU:    27.991 us   +/-  0.560 (min:    27.049 / max:    46.671) us     GPU-0:    31.917 us   +/-  0.620 (min:    30.528 / max:    50.432) us
my_sum              :    CPU:    28.068 us   +/-  9.715 (min:    26.982 / max:   990.307) us     GPU-0:    32.006 us   +/- 10.194 (min:    30.560 / max:  1042.304) us
my_sum              :    CPU:    28.003 us   +/-  1.085 (min:    27.097 / max:   103.036) us     GPU-0:    31.937 us   +/-  1.135 (min:    30.464 / max:   109.504) us
my_sum              :    CPU:    27.921 us   +/-  0.846 (min:    26.997 / max:    91.190) us     GPU-0:    31.879 us   +/-  2.450 (min:    30.304 / max:   269.216) us
my_sum              :    CPU:    27.995 us   +/-  2.673 (min:    27.020 / max:   290.384) us     GPU-0:    31.924 us   +/-  2.748 (min:    30.464 / max:   296.256) us
my_sum              :    CPU:    28.009 us   +/-  0.553 (min:    26.990 / max:    46.157) us     GPU-0:    31.935 us   +/-  0.740 (min:    30.464 / max:    55.136) us
my_sum              :    CPU:    28.196 us   +/- 13.168 (min:    27.157 / max:  1339.834) us     GPU-0:    32.118 us   +/- 13.563 (min:    30.528 / max:  1383.072) us
my_sum              :    CPU:    28.028 us   +/-  0.623 (min:    26.958 / max:    52.523) us     GPU-0:    31.947 us   +/-  0.784 (min:    30.592 / max:    56.288) us
my_sum              :    CPU:    27.997 us   +/-  0.533 (min:    27.062 / max:    41.054) us     GPU-0:    31.904 us   +/-  0.608 (min:    30.528 / max:    48.416) us
```


master
```
my_sum              :    CPU:    27.873 us   +/-  0.606 (min:    26.928 / max:    42.119) us     GPU-0:    31.548 us   +/-  0.680 (min:    30.304 / max:    45.952) us
my_sum              :    CPU:    28.043 us   +/-  1.394 (min:    26.964 / max:   154.396) us     GPU-0:    31.694 us   +/-  1.640 (min:    30.464 / max:   168.512) us
my_sum              :    CPU:    28.288 us   +/- 10.145 (min:    27.243 / max:  1038.527) us     GPU-0:    32.121 us   +/- 10.306 (min:    30.592 / max:  1058.048) us
my_sum              :    CPU:    27.559 us   +/-  0.919 (min:    26.685 / max:    97.817) us     GPU-0:    31.242 us   +/-  0.974 (min:    29.856 / max:   102.336) us
my_sum              :    CPU:    28.400 us   +/-  0.857 (min:    27.320 / max:    89.374) us     GPU-0:    32.286 us   +/-  0.917 (min:    30.784 / max:    95.520) us
my_sum              :    CPU:    29.086 us   +/-  1.818 (min:    27.888 / max:    55.312) us     GPU-0:    32.798 us   +/-  2.049 (min:    31.264 / max:    60.928) us
my_sum              :    CPU:    35.949 us   +/-  2.296 (min:    34.992 / max:   111.447) us     GPU-0:    40.823 us   +/-  2.612 (min:    39.296 / max:   126.880) us
my_sum              :    CPU:    28.312 us   +/- 10.788 (min:    27.211 / max:  1104.957) us     GPU-0:    31.933 us   +/- 11.027 (min:    30.432 / max:  1130.464) us
```

Seems like CPU time remains more or less the same

**Review by asi1024 — APPROVED** [review]

**Comment by emcastillo** [comment]
@asi1024 I think CI errors are unrelated

**Pull request merged**
