### PR TITLE
Revert memory back to reference

### PR DESCRIPTION
**Pull request by emcastillo**
We discussed that the memory explanation should be in reference instead of tutorial.

### CODE REVIEW

**Comment by leofang** [comment]
I moved it to tutorial in #4537 because it was harder to find when it was in reference (ex: https://github.com/cupy/cupy/issues/4080, #4821). Also, the presentation there is more like a tutorial than a pure API reference to me. Perhaps we could at least add a link to this page somewhere, say in the landing page ("Overview"), so that it's easier for new comers to know it exists?

**Comment by kmaehashi** [comment]
I asked @emcastillo to move it back to the reference 😃 

> Also, the presentation style there is more like a tutorial than a pure API reference to me. Perhaps we could at least add a link to this page somewhere, say in the landing page ("Overview"), so that it's easier for new comers to know it exists?

I talked with @emcastillo and agreed on this point. Let's add a simple description and a link to memory management page in the "Basics of CuPy" page.

Maybe in future, it's better to add a new top-level section like "Using CuPy", which includes topics like memory pools, interoperability, how to profile, etc.

**Comment by emcastillo** [comment]
Pushed a link from the tutorial to the reference.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Comment by leofang** [comment]
Thanks guys!

**Pull request merged**
