### PR TITLE
[v9] Fix broken build on CUDA 9.2

### PR DESCRIPTION
**Pull request by kmaehashi**
`type` member has been added in CUDA 10.0. Have to use `memoryType` for CUDA 9.2 (or earlier or HIP).

Follow-up: #5571

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by toslunar — APPROVED** [review]
LGTM

**Review by emcastillo — APPROVED** [review]

**Comment by leofang** [comment]
Thanks for catching it @kmaehashi. I forgot we still support CUDA 9.2 in v9...

**Pull request merged**
