### PR TITLE
Refactor `fft_tests`: unittest -> pytest

### PR DESCRIPTION
**Pull request by toslunar**
Apply #4192.

### CODE REVIEW

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
The CI failure seems to have the following problems:
- `testing.with_requires` does not work well?
- `testing.helper._fail_test_with_unexpected_errors` still assumes `testcase` derives from `unittest.TestCase`

**Comment by toslunar** [comment]
I'm sorry.  #4304 seems to fix the issue, but I forgot to add "This PR requires #4304" here, too.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
#4304 is merged.

**Comment by takagi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
LGTM! Waiting for CI pass.

**Pull request merged**
