### PR TITLE
Fix#8133, Update cutensor.pyx

### PR DESCRIPTION
**Pull request by jemiryguo**
Remove the contiguous check in cutensor/contraction to enable the contaction performing on in-contiguous arrays.

### CODE REVIEW

**Comment by leofang** [comment]
Thanks, @jemiryguo, could you check the pre-test failures? You can run
```
pre-commit run -a --show-diff-on-failure
```
locally and fix the formatting issue following the hints.

**Comment by leofang** [comment]
Other than formatting, I think the fix is on the right track. Once the formatting is fixed, I'll check with CI.

**Comment by kmaehashi** [comment]
@leofang Could you review this one if possible, Leo?

**Comment by leofang** [comment]
@asi1024 AFAICT the to-remove contiguity check was added in https://github.com/cupy/cupy/pull/3374, any chance you still remember the reason? 🙂 cuTENSOR was designed to handle strided tensor operations, so checking contiguity shouldn't be necessary with hindsight.

**Review by leofang — APPROVED** [review]

**Comment by asi1024** [comment]
@leofang I added a check for contiguity because the test for non-contiguous input raised illegal memory access. If the test for non-contiguous input passes now, we can remove the check.

**Comment by leofang** [comment]
Got it, seems like it's safe to remove now. Anything else that needs to be addressed before merging, @asi1024? Like adding extra tests etc?

**Comment by asi1024** [comment]
Yes, could you add a contiguity parameter to `TestCuTensorContraction` in `tests/cupyx_tests/test_cutensor.py`?

**Comment by wxj6000** [comment]
@leofang Could alignment_req check be removed too? 
 https://github.com/cupy/cupy/blob/f5d8ed48487f1ce6f31e524d5361bf6f47a4a2e4/cupyx/cutensor.pyx#L247

**Comment by leofang** [comment]
Please keep the alignment requirement for now. There are some subtitles regarding it. For views, if the view does not offset from the original pointer address, the alignment shouldn't be an issue.

**Comment by wxj6000** [comment]
> Please keep the alignment requirement for now. There are some subtitles regarding it. For views, if the view does not offset from the original pointer address, the alignment shouldn't be an issue.

Yes, there are some issues when the view offset from the original address. Just out of curiosity, 

And the contiguous check also appears in reduction, elementwise_binary, and elementwise_trinary. Not sure if it is safe to remove them too.

**Comment by jemiryguo** [comment]
I will give another PR after i finishing all related changs

**Comment by jemiryguo** [comment]
> Please keep the alignment requirement for now. There are some subtitles regarding it. For views, if the view does not offset from the original pointer address, the alignment shouldn't be an issue.

I think we can add a func like this:
```py
cpdef int cal_align_req(_ndarray_base a, _ndarray_base b, _ndarray_base c):
    """Calculate the required alignment to support incontiguous input/output.

    Args:
        a (cupy.ndarray): tensor involved in contraction.
        b (cupy.ndarray): tensor involved in contraction.
        c (cupy.ndarray): tensor involved in contraction.

    Returns:
        (int): required alignment.
    """
    cdef int pa = a.data.ptr
    cdef int pb = b.data.ptr
    cdef int pc = c.data.ptr

    cdef int alignment_req = 255
    cdef int i

    for i in range(5):
        if (pa & alignment_req) + (pb & alignment_req) + (pc & alignment_req) == 0:
            return alignment_req+1
        alignment_req >>= 1
    return 16
    ```

and calculate the required aligned before creating the descriptor:
```
    alignment_req = cal_align_req(A, B, C)
    desc_A = create_tensor_descriptor(A, alignment_req)
    desc_B = create_tensor_descriptor(B, alignment_req)
    desc_C = create_tensor_descriptor(C, alignment_req)
```

This will only effect the alignment for contraction, thus no worry about  "some subtitles regarding it".

**Pull request closed without merging**
