### PR TITLE
Add `cupy.util.PerformanceWarning`

### PR DESCRIPTION
**Pull request by kmaehashi**
I want to introduce this warnings class to make the meaning of the warning clear for users.

### CODE REVIEW

**Comment by okuta** [comment]
I agree this PR. Cloud you continue your work?

**Comment by kmaehashi** [comment]
This PR is ready for review.

Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
