### PR TITLE
Align vector access with #3020 #3022

### PR DESCRIPTION
**Pull request by emcastillo**
As per the discussion in #3225 

Can be closed if not necessary

### CODE REVIEW

**Comment by takagi** [comment]
LGTM except the conflicting. Can I fix it as it's so trivial?

**Comment by emcastillo** [comment]
This fix is only valid as long as we are sure that the buffer is not empty.

.data() in an empty vector is not  defined 😭

**Comment by takagi** [comment]
I've rebased it on the current master and made a change that explicitly checks empty sizes. I think it makes sense here. Would you take a look?

**Comment by emcastillo** [comment]
LGTM

**Comment by leofang** [comment]
Tests weren't run...?

**Comment by emcastillo** [comment]
😂　thanks @leofang !

**Pull request merged**
