### PR TITLE
[backport] Update `__cuda_array_interface__` to protocol version 2 + Add backward compatibility test

### LINKED ISSUE #2521: Write unit tests for older protocols of __cuda_array_interface__
#2491 has updated the supported protocol version to 2, and it's tested.

CuPy should also ensure protocol 0 and 1 are accepted.

### PR DESCRIPTION
**Pull request by leofang**
This PR does two things:
1. backport #2491 (by applying the patch from there)
2. add backward compatibility test for older protocols, resolve #2521 

The compatibility test should be ported to v7 once this PR is merged.

### CODE REVIEW

**Comment by niboshi** [comment]
Could you send test additions to master branch first?

**Comment by leofang** [comment]
> Could you send test additions to master branch first?

So you suggest to add tests to master first, and then let the bot kick off automatic backport PRs?

Anyway, I think I messed up my local environment. Will work on it tomorrow morning.

**Comment by niboshi** [comment]
Yes, that's what I mean. (It's actually a script, not a bot)
Thank you so much!

**Comment by leofang** [comment]
> (It's actually a script, not a bot)

Is it open source on GitHub? I'd love to learn how you do that.

btw, should I close this PR and let your script do the job once #2536 is merged?

**Comment by niboshi** [comment]
https://github.com/chainer/backport

This is the script.
It won't be that simple in this case though, because we have to backport 2 PRs (#2491 and #2536).

**Comment by niboshi** [comment]
>btw, should I close this PR and let your script do the job once #2536 is merged?

I believe so.

**Comment by leofang** [comment]
> https://github.com/chainer/backport
> This is the script.

Thanks!

**Pull request closed without merging**
