### PR TITLE
Support CUDA 11.6

### PR DESCRIPTION
**Pull request by takagi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Could you add `config.pbtxt` in this PR so that the configuration can be tested?

Let's merge this one first, then test and merge #6346 and #6347.

**Comment by kmaehashi** [comment]
Triggered:
https://ci.preferred.jp/cupy.linux.cuda116/91911/
https://ci.preferred.jp/cupy.linux.cuda116.multi/91912/
(These are expected to fail as #6346 and #6347 are not in)

**Comment by kmaehashi** [comment]
Testing:
* https://ci.preferred.jp/cupy.linux.cuda116/92216/
* https://ci.preferred.jp/cupy.linux.cuda116.multi/92217/

**Comment by kmaehashi** [comment]
Testing:
* https://ci.preferred.jp/cupy.linux.cuda116/92224/
* https://ci.preferred.jp/cupy.linux.cuda116.multi/92225/

**Comment by kmaehashi** [comment]
Could you exclude `README.md` and `docs/source/install.rst` from this PR? As it may take some time to add CUDA 11.6 CI, I'd like to merge this one without an explicit support announcement for now.

**Comment by takagi** [comment]
Sure!

**Comment by takagi** [comment]
I've removed the change there. PTAL!

**Review by kmaehashi — CHANGES_REQUESTED** [review]

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
