### PR TITLE
Remove cuDNN overhead

### PR DESCRIPTION
**Pull request by okuta**
~~Please merge #482 before this PR.~~
Please merge ~~chainer/chainer#3364~~ and ~~chainer/chainer#3781~~ first.

### CODE REVIEW

**Comment by niboshi** [comment]
#482 has been merged.

**Comment by niboshi** [comment]
Please rebase.

Also, I got this error in my environment:

```
>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/work/w/repos/chainer/chainer/__init__.py", line 16, in <module>
    from chainer import functions  # NOQA
  File "/data/work/w/repos/chainer/chainer/functions/__init__.py", line 13, in <module>
    from chainer.functions.activation.log_softmax import log_softmax  # NOQA
  File "/data/work/w/repos/chainer/chainer/functions/activation/log_softmax.py", line 11, in <module>
    libcudnn = cudnn.cudnn
AttributeError: module 'cupy.cudnn' has no attribute 'cudnn'
```

(No problem when importing `cupy` directly).

**Comment by okuta** [comment]
Thanks for your reporting.
Please merge chainer/chainer#3364 first.

**Comment by niboshi** [comment]
OK.

**Comment by niboshi** [comment]
chainer/chainer#3364 merged.

**Comment by okuta** [comment]
Thanks!

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by niboshi** [comment]
Please fix jenkins test.
Also, I think you need to skip zero handles before calling `cudnn.destroy`.

**Comment by okuta** [comment]
All descriptor are initialized before try scope. So, we do not need zero checking.
I fixed test.

**Comment by niboshi** [comment]
I meant this line:
https://github.com/cupy/cupy/pull/512/files#diff-da3b471a8f2bebf46bb07243ffb2caedR42
`_handle` is now `vector` and contains `0`s.

**Comment by okuta** [comment]
thanks, i will fix

**Comment by okuta** [comment]
Pealse merge chainer/chainer#3781

**Comment by niboshi** [comment]
#3781 has been merged.

**Comment by okuta** [comment]
I fixed

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
