### PR TITLE
Support CUDA 12.1

### PR DESCRIPTION
**Pull request by kmaehashi**
Depends on ~#7472~ (merged)

Ref #7441, #7378, #7471

CI for CUDA 12.1:
* https://ci.preferred.jp/cupy.linux.cuda121/126591/
* https://ci.preferred.jp/cupy.linux.cuda121.multi/126592/
* https://ci.preferred.jp/cupy.win.cuda121/126632/

### CODE REVIEW

**Comment by takagi** [comment]
Made a fix https://github.com/cupy/cupy/pull/7473/commits/87a2d3b5103efd90cee1069641eb727a223e4287 and kicked cupy.win.cuda121 CI again.

**Comment by kmaehashi** [comment]
Thanks! CUDA 12.1 test passed, and failures are unrelated to this PR.

**Review by takagi — APPROVED** [review]
LGTM!

**Pull request merged**
